Repository bevyengine/bevy, pull requests merged in 2020-09, with the labels that each got.

#324 iOS: use shaderc-rs for glsl to spirv compilation
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/shader/shader.rs
Labels: ci / build system, rendering, third party / dependencies

#408 Quick fix for #405
  crates/bevy_app/src/task_pool_options.rs
Labels: bug

#386 Remove child from parent when it is despawned
  crates/bevy_transform/src/hierarchy/hierarchy.rs
Labels: bug, ecs

#363 Feature to disable libloading (helpful for WASM support)
  Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/app_builder.rs
  crates/bevy_app/src/plugin.rs
  crates/bevy_core/Cargo.toml
  crates/bevy_type_registry/Cargo.toml
Labels: ci / build system, third party / dependencies

#332 Rename Assets::get_id_mut -> Assets::get_with_id_mut
  crates/bevy_asset/src/assets.rs
Labels: code-quality

#406 Allowing glTFs to be loaded that don't have uvs and normals
  crates/bevy_render/src/mesh/mesh.rs
Labels: assets, bug, rendering

#428 Add access to pressed/just_pressed/just_released to Input<T>
  crates/bevy_input/src/input.rs
Labels: enhancement, input

#433 Speed up fast compiles config
  .cargo/config_fast_builds
Labels: enhancement, performance

#443 Create CHANGELOG.md and add all unreleased changes since `0.1.3`
  CHANGELOG.md
Labels: documentation, enhancement

#439 Replace some println spam in a test with an assertion
  crates/bevy_tasks/src/task_pool.rs
Labels: code-quality, enhancement

#437 Reworked parallel executor to not block
  crates/bevy_app/src/task_pool_options.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/schedule/parallel_executor.rs
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/src/countdown_event.rs
  crates/bevy_tasks/src/lib.rs
Labels: ecs, enhancement

#417 Optimize transform systems to only run on change
  crates/bevy_ecs/src/lib.rs
  crates/bevy_transform/src/local_transform_systems.rs
  crates/bevy_transform/src/transform_systems.rs
Labels: enhancement, performance

#270 Add derives to mouse structs
  crates/bevy_input/src/mouse.rs
Labels: code-quality, input

#339 SceneSpawner: add unload() and unload_sync()
  crates/bevy_scene/src/scene_spawner.rs
Labels: ecs, enhancement

#451 Update docs for Updated, Changed and Mutated
  crates/bevy_ecs/hecs/src/query.rs
Labels: documentation, ecs

#430 Resize mode for sprite
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/render/sprite.vert
  crates/bevy_sprite/src/sprite.rs
  examples/game/breakout.rs
Labels: enhancement, rendering

#292 Parallel queries
  Cargo.toml
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_tasks/benches/iter.rs
  crates/bevy_tasks/src/iter/adapters.rs
  crates/bevy_tasks/src/iter/mod.rs
  crates/bevy_tasks/src/lib.rs
  examples/ecs/parallel_query.rs
Labels: ecs, enhancement

#145 custom rodio source for audio
  .gitignore
  crates/bevy_audio/src/audio_output.rs
  crates/bevy_audio/src/audio_source.rs
  crates/bevy_audio/src/lib.rs
Labels: audio, enhancement

#465 Add parallel_query to the examples readme
  examples/README.md
Labels: documentation, examples

#463 Add pkg-config as a Ubuntu 20.04 dependency.
  docs/linux_dependencies.md
Labels: documentation, third party / dependencies

#452 Update multitask dependency to async-executor
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/src/countdown_event.rs
  crates/bevy_tasks/src/task.rs
  crates/bevy_tasks/src/task_pool.rs
Labels: ci / build system, enhancement

#470 update dependencies
  benches/Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_asset/Cargo.toml
  crates/bevy_audio/Cargo.toml
  crates/bevy_core/Cargo.toml
  crates/bevy_derive/Cargo.toml
  crates/bevy_diagnostic/Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/hecs/macros/Cargo.toml
  crates/bevy_gltf/Cargo.toml
  crates/bevy_input/Cargo.toml
  crates/bevy_math/Cargo.toml
  crates/bevy_pbr/Cargo.toml
  crates/bevy_property/Cargo.toml
  crates/bevy_property/bevy_property_derive/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_scene/Cargo.toml
  crates/bevy_sprite/Cargo.toml
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/README.md
  crates/bevy_tasks/src/task.rs
  crates/bevy_tasks/src/task_pool.rs
  crates/bevy_text/Cargo.toml
  crates/bevy_transform/Cargo.toml
  crates/bevy_type_registry/Cargo.toml
  crates/bevy_ui/Cargo.toml
  crates/bevy_utils/Cargo.toml
  crates/bevy_wgpu/Cargo.toml
  crates/bevy_wgpu/src/lib.rs
  crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
  crates/bevy_window/Cargo.toml
  crates/bevy_winit/Cargo.toml
Labels: third party / dependencies

#444 Init App.schedule systems when running the app
  crates/bevy_app/src/schedule_runner.rs
  examples/app/headless.rs
Labels: bug, ecs

#388 Resource change tracking
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/resource/resource_query.rs
  crates/bevy_ecs/src/resource/resources.rs
  crates/bevy_ecs/src/schedule/parallel_executor.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/into_system.rs
  crates/bevy_render/src/draw.rs
Labels: ecs, enhancement

#474 Adds profiling for non-thread-local-systems
  crates/bevy_ecs/src/schedule/parallel_executor.rs
Labels: ecs, enhancement, performance

#471 Fix cargo run command for running examples
  examples/README.md
Labels: bug, documentation, examples

#458 Fix handling of nested generics in PropertyTypeRegistration
  crates/bevy_property/src/type_registry.rs
Labels: crash

#473 render: Export entity module outside of prelude
  crates/bevy_render/src/lib.rs
Labels: code-quality

#484 update async-executor
  crates/bevy_tasks/Cargo.toml
  examples/shader/shader_custom_material.rs
  examples/shader/shader_defs.rs
Labels: ci / build system, enhancement, third party / dependencies

#486 Fix missing asset info path for synchronous loading
  crates/bevy_asset/src/asset_server.rs
Labels: assets, bug

#491 Provide shell.nix for easier compiling with nix-shell
  docs/linux_dependencies.md
Labels: ci / build system, enhancement, platform linux

#485 Make "render" feature optional
  Cargo.toml
  src/add_default_plugins.rs
  src/lib.rs
  src/prelude.rs
Labels: ci / build system, enhancement, rendering

#497 Update changelog
  CHANGELOG.md
Labels: documentation

#496 Implement single threaded task scheduler for WebAssembly
  Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_tasks/src/lib.rs
  crates/bevy_tasks/src/single_threaded_task_pool.rs
  crates/bevy_window/Cargo.toml
  examples/README.md
  examples/wasm/.gitignore
  examples/wasm/favicon.ico
  examples/wasm/headless_wasm.rs
  examples/wasm/hello_wasm.rs
  examples/wasm/index.html
Labels: enhancement, platform web

#495 fix font atlas overflow
  crates/bevy_text/src/font_atlas.rs
  crates/bevy_text/src/font_atlas_set.rs
  examples/ui/font_atlas_debug.rs
Labels: assets, bug, crash, rendering, ui

#502 Update headless example / add feature docs
  docs/cargo_features.md
  examples/app/headless.rs
Labels: bug, documentation, examples

#503 Implement WASM support for bevy_winit
  Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_core/Cargo.toml
  crates/bevy_core/src/time/time.rs
  crates/bevy_diagnostic/Cargo.toml
  crates/bevy_diagnostic/src/system_profiler.rs
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/wasm/winit_wasm.rs
Labels: enhancement, platform web, windowing

#504 ecs: use generational entity ids and other optimizations
  assets/scenes/load_scene_example.scn
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/hecs/benches/bench.rs
  crates/bevy_ecs/hecs/examples/format.rs
  crates/bevy_ecs/hecs/src/archetype.rs
  crates/bevy_ecs/hecs/src/borrow.rs
  crates/bevy_ecs/hecs/src/entities.rs
  crates/bevy_ecs/hecs/src/lib.rs
  crates/bevy_ecs/hecs/src/query.rs
  crates/bevy_ecs/hecs/src/query_one.rs
  crates/bevy_ecs/hecs/src/serde.rs
  crates/bevy_ecs/hecs/src/world.rs
  crates/bevy_ecs/hecs/tests/tests.rs
  crates/bevy_ecs/src/resource/resource_query.rs
  crates/bevy_ecs/src/resource/resources.rs
  crates/bevy_ecs/src/schedule/parallel_executor.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/commands.rs
  crates/bevy_ecs/src/system/into_system.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/world/world_builder.rs
  crates/bevy_property/src/impl_property/impl_property_bevy_ecs.rs
  crates/bevy_render/src/draw.rs
  crates/bevy_render/src/render_graph/nodes/pass_node.rs
  crates/bevy_scene/src/scene.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_scene/src/serde.rs
  crates/bevy_transform/src/components/parent.rs
  crates/bevy_transform/src/hierarchy/child_builder.rs
  crates/bevy_transform/src/hierarchy/hierarchy.rs
  crates/bevy_transform/src/hierarchy/hierarchy_maintenance_system.rs
  crates/bevy_transform/src/hierarchy/world_child_builder.rs
  crates/bevy_transform/src/transform_propagate_system.rs
  examples/scene/scene.rs
Labels: ecs, enhancement, performance

#505 Add AppBuilder::add_startup_stage_[before/after]
  crates/bevy_app/src/app_builder.rs
Labels: code-quality, enhancement

#280 Added gamepad support using Gilrs
  .github/workflows/ci.yml
  Cargo.toml
  crates/bevy_gilrs/Cargo.toml
  crates/bevy_gilrs/src/converter.rs
  crates/bevy_gilrs/src/gilrs_system.rs
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_input/src/axis.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input/src/input.rs
  crates/bevy_input/src/lib.rs
  examples/input/gamepad_input.rs
  src/add_default_plugins.rs
Labels: enhancement, input

#506 Create winit canvas under WebAssembly
  Cargo.toml
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/winit_windows.rs
  examples/README.md
  examples/wasm/index.html
  examples/wasm/winit_wasm.rs
Labels: enhancement, platform web, windowing

#490 Do not assume font handle is present in assets.
  crates/bevy_text/src/font_atlas_set.rs
  crates/bevy_ui/src/widget/text.rs
Labels: assets, crash

#526 Update async-executor to 1.3.0 (urgent)
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/src/task_pool.rs
Labels: third party / dependencies

#538 Add `libudev-dev` to Ubuntu dependencies
  docs/linux_dependencies.md
Labels: ci / build system, documentation, enhancement

#535 use FnOnce in Commands and ChildBuilder where possible
  crates/bevy_ecs/src/system/commands.rs
  crates/bevy_transform/src/hierarchy/child_builder.rs
  crates/bevy_transform/src/hierarchy/world_child_builder.rs
Labels: code-quality, ecs, enhancement

#528 Add systemd-devel for Fedora Linux dependencies
  docs/linux_dependencies.md
Labels: documentation, platform linux, third party / dependencies

#522 Merge some imports in bevy_winit/src/lib.rs
  crates/bevy_winit/src/lib.rs
Labels: code-quality

#515 Option to give existing canvas element as winit window
  crates/bevy_window/Cargo.toml
  crates/bevy_window/src/window.rs
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/winit_windows.rs
Labels: enhancement, platform web, windowing

#552 Suggest -Zrun-dsymutil-no for macOS fast compiles
  .cargo/config_fast_builds
  CHANGELOG.md
Labels: ci / build system, platform macos

#568 Index buffer specialization
  crates/bevy_gltf/src/loader.rs
  crates/bevy_render/src/draw.rs
  crates/bevy_render/src/mesh/mesh.rs
  crates/bevy_render/src/pipeline/pipeline_compiler.rs
  crates/bevy_render/src/pipeline/render_pipelines.rs
  crates/bevy_render/src/pipeline/state_descriptors.rs
Labels: enhancement, rendering

#569 Downstream memory leak fix in `Archetype::grow()` from `hecs`
  crates/bevy_ecs/hecs/src/archetype.rs
Labels: bug, ecs

#559 WASM asset loading
  Cargo.toml
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/asset_server.rs
  crates/bevy_asset/src/load_request/mod.rs
  crates/bevy_asset/src/load_request/platform_default.rs
  crates/bevy_asset/src/load_request/platform_wasm.rs
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/src/single_threaded_task_pool.rs
  examples/wasm/assets_wasm.rs
Labels: assets, enhancement, platform web

#591 Use instant::Instant with wasm-bindgen feature
  crates/bevy_app/Cargo.toml
  crates/bevy_core/Cargo.toml
  crates/bevy_diagnostic/Cargo.toml
Labels: ci / build system, platform web
