Repository bevyengine/bevy, pull requests merged in 2020-10, with the labels that each got.

#610 Fix ScheduleRunnerPlugin
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/schedule_runner.rs
Labels: crash, ecs

#583 Add `#[cfg_attr(feature = "serialize", derive(serde::Serialize, serde::Deserialize))]` to gamepad types.
  crates/bevy_input/src/gamepad.rs
Labels: code-quality

#595 Expose current_entity in ChildBuilder
  crates/bevy_transform/src/hierarchy/child_builder.rs
Labels: ecs, enhancement

#580 Add AppBuilder::asset_loader_from_instance
  Cargo.toml
  assets/data/test_data.data1
  assets/data/test_data.data2
  crates/bevy_asset/src/assets.rs
  examples/asset/custom_asset_loading.rs
Labels: assets, enhancement

#565 Add hierarchy example
  Cargo.toml
  examples/ecs/hierarchy.rs
Labels: ecs, enhancement, examples

#544 Added bevy_dynload to replace the dynamic_plugin feature
  Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/app_builder.rs
  crates/bevy_app/src/plugin.rs
  crates/bevy_core/Cargo.toml
  crates/bevy_dynamic_plugin/Cargo.toml
  crates/bevy_dynamic_plugin/src/lib.rs
  crates/bevy_dynamic_plugin/src/loader.rs
  crates/bevy_type_registry/Cargo.toml
  src/lib.rs
  src/prelude.rs
  tools/publish.sh
Labels: ci / build system, code-quality

#618 Fix FloatOrd hash being different for different NaN values
  crates/bevy_core/src/float_ord.rs
Labels: code-quality

#543 Fix Added behaviour with QueryOne get
  crates/bevy_ecs/hecs/src/query_one.rs
  crates/bevy_ecs/hecs/tests/tests.rs
Labels: bug, ecs

#488 Update camera_system to fix issue with late camera addition.
  crates/bevy_render/src/camera/camera.rs
Labels: bug, rendering

#627 Exposing winit decorations
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: enhancement, windowing

#612 ui/text example: Use a unit component to identify the target Text
  examples/ui/text.rs
Labels: examples, ui

#645 Add Void Linux to linux dependencies file
  docs/linux_dependencies.md
Labels: documentation, platform linux, third party / dependencies

#616 sRGB awareness for Color
  CHANGELOG.md
  crates/bevy_render/src/color.rs
  crates/bevy_render/src/colorspace.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_text/src/font.rs
  crates/bevy_wgpu/src/wgpu_type_converter.rs
Labels: enhancement, rendering

#646 Remove outdated ecs docs
  crates/bevy_ecs/hecs/README.md
Labels: documentation

#656 fix new clippy error
  crates/bevy_app/src/event.rs
Labels: code-quality

#653 Upgrade to gilrs 0.8.0 to gain dpad support on macos
  crates/bevy_gilrs/Cargo.toml
Labels: dependencies, enhancement, input, platform macos

#670 Update color.rs
  crates/bevy_render/src/color.rs
Labels: rendering

#669 add more methods to Assets for clearing and allocation reduction
  crates/bevy_asset/src/assets.rs
Labels: assets, code-quality, enhancement, performance

#664 Register `IndexFormat` as a property
  crates/bevy_render/src/lib.rs
Labels: rendering

#671 add thread local resources
  crates/bevy_app/src/app_builder.rs
  crates/bevy_ecs/hecs/src/borrow.rs
  crates/bevy_ecs/hecs/src/lib.rs
  crates/bevy_ecs/src/resource/resources.rs
  crates/bevy_gilrs/src/gilrs_system.rs
  crates/bevy_gilrs/src/lib.rs
Labels: ecs, enhancement

#661 add version of the ecs's `write_world` method that takes a pre-boxed …
  crates/bevy_ecs/src/system/commands.rs
Labels: ecs

#678 added frame count to FrameTimeDiagnosticsPlugin
  crates/bevy_diagnostic/src/frame_time_diagnostics_plugin.rs
Labels: enhancement, performance

#460 Add a way to specify padding/ margins between sprites in a TextureAtlas.
  crates/bevy_sprite/src/texture_atlas.rs
  examples/2d/sprite_sheet.rs
Labels: assets, enhancement

#644 can change window settings at runtime
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/render_graph/nodes/window_swapchain_node.rs
  crates/bevy_render/src/render_graph/nodes/window_texture_node.rs
  crates/bevy_ui/src/flex/mod.rs
  crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
  crates/bevy_wgpu/src/wgpu_renderer.rs
  crates/bevy_wgpu/src/wgpu_type_converter.rs
  crates/bevy_window/src/window.rs
  crates/bevy_window/src/windows.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/ecs/parallel_query.rs
  examples/window/window_settings.rs
Labels: enhancement, windowing

#683 Support to get gamepad button/trigger values using Axis<GamepadButton>
  crates/bevy_gilrs/src/gilrs_system.rs
  crates/bevy_input/src/lib.rs
  examples/input/gamepad_input.rs
Labels: enhancement, input

#674 Expose a pointer of EventLoopProxy to process custom messages
  crates/bevy_winit/src/lib.rs
Labels: ecs, enhancement, windowing

#660 Adjust how `ArchetypeAccess` tracks mutable & immutable deps
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system.rs
Labels: ecs

#551 Add issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: enhancement

#689 do not depend on spirv on wasm target
  CHANGELOG.md
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/shader/mod.rs
  crates/bevy_render/src/shader/shader.rs
  crates/bevy_render/src/shader/shader_reflect.rs
  crates/bevy_render/src/shader/shader_reflect_wasm.rs
Labels: platform web, rendering

#675 Add default for texture format
  crates/bevy_pbr/src/render_graph/forward_pipeline/mod.rs
  crates/bevy_render/src/pipeline/pipeline.rs
  crates/bevy_render/src/render_graph/base.rs
  crates/bevy_render/src/texture/texture_dimension.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_wgpu/src/wgpu_type_converter.rs
  examples/window/multiple_windows.rs
Labels: rendering

#679 Added basic mouse capture API
  Cargo.toml
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/window/window_settings.rs
Labels: enhancement, examples, input, windowing

#696 Touch support implementation
  CHANGELOG.md
  Cargo.toml
  crates/bevy_input/src/lib.rs
  crates/bevy_input/src/touch.rs
  crates/bevy_winit/src/converters.rs
  crates/bevy_winit/src/lib.rs
  examples/input/touch_input.rs
  examples/input/touch_input_highlevel.rs
Labels: enhancement, input

#690 Runners explicitly call App.initialize()
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_winit/src/lib.rs
Labels: code-quality

#596 Moving transform data out of Mat4
  crates/bevy_pbr/src/light.rs
  crates/bevy_render/src/camera/visible_entities.rs
  crates/bevy_render/src/render_graph/nodes/camera_node.rs
  crates/bevy_render/src/renderer/render_resource/render_resource.rs
  crates/bevy_transform/src/components/global_transform.rs
  crates/bevy_transform/src/components/transform.rs
  crates/bevy_transform/src/transform_propagate_system.rs
  crates/bevy_ui/src/flex/mod.rs
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/update.rs
  crates/bevy_ui/src/widget/text.rs
  examples/2d/sprite_sheet.rs
  examples/2d/texture_atlas.rs
  examples/3d/3d_scene.rs
  examples/3d/load_model.rs
  examples/3d/msaa.rs
  examples/3d/parenting.rs
  examples/3d/spawner.rs
  examples/3d/texture.rs
  examples/3d/z_sort_debug.rs
  examples/asset/asset_loading.rs
  examples/asset/hot_asset_reloading.rs
  examples/ecs/hierarchy.rs
  examples/ecs/parallel_query.rs
  examples/game/breakout.rs
  examples/shader/shader_custom_material.rs
  examples/shader/shader_defs.rs
  examples/window/multiple_windows.rs
Labels: enhancement

#688 two-way conversions between `Color`-`Vec4` and `Color`-`[f32; 4]`
  crates/bevy_render/src/color.rs
Labels: code-quality

#397 Low power default option [#366]
  crates/bevy_wgpu/src/lib.rs
  crates/bevy_wgpu/src/wgpu_renderer.rs
Labels: ci / build system, rendering, third party / dependencies

#700 Separate gamepad state code from gamepad event code and other customizations
  Cargo.toml
  crates/bevy_gilrs/src/gilrs_system.rs
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_input/src/axis.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input/src/lib.rs
  examples/input/gamepad_input.rs
  examples/input/gamepad_input_event.rs
Labels: code-quality, input

#706 Documenting small things here and there..
  CHANGELOG.md
  README.md
  crates/bevy_app/src/app_builder.rs
  crates/bevy_asset/src/loader.rs
  crates/bevy_core/src/time/timer.rs
  docs/cargo_features.md
  docs/debugging.md
  docs/linux_dependencies.md
  docs/profiling.md
  src/lib.rs
Labels: documentation

#716 port upstream hecs performance improvements
  crates/bevy_ecs/hecs/src/archetype.rs
  crates/bevy_ecs/hecs/src/query.rs
  crates/bevy_ecs/hecs/src/query_one.rs
  crates/bevy_ecs/src/system/query.rs
Labels: ecs, performance

#736 Run app.initialize in the run_once runner
  crates/bevy_app/src/app.rs
Labels: bug, core

#728 Optimize returns in file_asset_io.rs and entities.rs
  crates/bevy_asset/src/io/file_asset_io.rs
  crates/bevy_ecs/hecs/src/entities.rs
Labels: code-quality

#723 Add support for android file system
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/io/android_asset_io.rs
  crates/bevy_asset/src/io/file_asset_io.rs
  crates/bevy_asset/src/io/mod.rs
  crates/bevy_asset/src/lib.rs
Labels: assets, platform android

#727 Add WSL 2 instructions to linux_dependencies.md
  docs/linux_dependencies.md
Labels: documentation, third party / dependencies

#744 app: PluginGroups and DefaultPlugins
  Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/app_builder.rs
  crates/bevy_app/src/lib.rs
  crates/bevy_app/src/plugin_group.rs
  examples/app/plugin_group.rs
  src/add_default_plugins.rs
  src/default_plugins.rs
  src/lib.rs
  src/prelude.rs
Labels: ecs, enhancement

#713 Hierarchy
  crates/bevy_transform/src/components/parent.rs
  crates/bevy_transform/src/hierarchy/child_builder.rs
  crates/bevy_transform/src/hierarchy/hierarchy_maintenance_system.rs
  crates/bevy_transform/src/hierarchy/world_child_builder.rs
Labels: ecs, enhancement

#730 Fix bug of connection event of gamepad at startup
  crates/bevy_gilrs/src/gilrs_system.rs
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input/src/lib.rs
  examples/input/gamepad_input.rs
Labels: input

#747 Add SamplerDescriptor to Texture (#399)
  crates/bevy_gltf/src/loader.rs
  crates/bevy_render/src/texture/sampler_descriptor.rs
  crates/bevy_render/src/texture/texture.rs
Labels: assets, rendering

#748 Improve `bevy` crate's docs
  src/lib.rs
Labels: documentation

#741 ecs: ergonomic query.iter(), remove locks, add QuerySets
  crates/bevy_core/src/label.rs
  crates/bevy_core/src/time/timer.rs
  crates/bevy_ecs/hecs/macros/src/lib.rs
  crates/bevy_ecs/hecs/src/access.rs
  crates/bevy_ecs/hecs/src/archetype.rs
  crates/bevy_ecs/hecs/src/lib.rs
  crates/bevy_ecs/hecs/src/query.rs
  crates/bevy_ecs/hecs/src/query_one.rs
  crates/bevy_ecs/hecs/src/world.rs
  crates/bevy_ecs/hecs/tests/tests.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/resource/resource_query.rs
  crates/bevy_ecs/src/schedule/parallel_executor.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/commands.rs
  crates/bevy_ecs/src/system/into_system.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/query/mod.rs
  crates/bevy_ecs/src/system/query/query_set.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_pbr/src/render_graph/lights_node.rs
  crates/bevy_render/src/camera/active_cameras.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/visible_entities.rs
  crates/bevy_render/src/draw.rs
  crates/bevy_render/src/mesh/mesh.rs
  crates/bevy_render/src/pipeline/render_pipelines.rs
  crates/bevy_render/src/render_graph/nodes/pass_node.rs
  crates/bevy_render/src/render_graph/nodes/render_resources_node.rs
  crates/bevy_render/src/shader/shader_defs.rs
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_transform/src/hierarchy/hierarchy.rs
  crates/bevy_transform/src/hierarchy/hierarchy_maintenance_system.rs
  crates/bevy_transform/src/transform_propagate_system.rs
  crates/bevy_ui/src/flex/mod.rs
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/update.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_ui/src/widget/text.rs
  examples/2d/sprite_sheet.rs
  examples/3d/parenting.rs
  examples/3d/spawner.rs
  examples/3d/z_sort_debug.rs
  examples/ecs/ecs_guide.rs
  examples/ecs/hierarchy.rs
  examples/ecs/parallel_query.rs
  examples/game/breakout.rs
  examples/scene/scene.rs
  examples/ui/button.rs
  examples/ui/font_atlas_debug.rs
  examples/ui/text.rs
Labels: code-quality, ecs, performance

#749 Remove unsound cast in thread local resources
  crates/bevy_ecs/src/resource/resources.rs
Labels: ecs

#745 Insert custom local system resources
  crates/bevy_ecs/src/resource/resource_query.rs
Labels: ecs, enhancement

#725 fix wavy text
  crates/bevy_text/src/draw.rs
Labels: bug, ui

#599 Mesh overhaul with custom vertex attributes #592
  CHANGELOG.md
  crates/bevy_derive/src/as_vertex_buffer_descriptor.rs
  crates/bevy_derive/src/lib.rs
  crates/bevy_gltf/src/loader.rs
  crates/bevy_render/src/draw.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/mesh/mesh.rs
  crates/bevy_render/src/mesh/mod.rs
  crates/bevy_render/src/mesh/vertex.rs
  crates/bevy_render/src/pipeline/pipeline.rs
  crates/bevy_render/src/pipeline/pipeline_compiler.rs
  crates/bevy_render/src/pipeline/pipeline_layout.rs
  crates/bevy_render/src/pipeline/render_pipelines.rs
  crates/bevy_render/src/pipeline/vertex_buffer_descriptor.rs
  crates/bevy_render/src/pipeline/vertex_format.rs
  crates/bevy_render/src/renderer/headless_render_resource_context.rs
  crates/bevy_render/src/renderer/render_resource/render_resource_bindings.rs
  crates/bevy_render/src/renderer/render_resource_context.rs
  crates/bevy_render/src/shader/shader_reflect.rs
  crates/bevy_render/src/texture/texture.rs
  crates/bevy_text/src/draw.rs
  crates/bevy_ui/src/widget/text.rs
  crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
  crates/bevy_wgpu/src/wgpu_resources.rs
  crates/bevy_wgpu/src/wgpu_type_converter.rs
Labels: enhancement, rendering

#755 Update and fix changelog
  CHANGELOG.md
Labels: documentation

#754 Make event example use a local resource
  examples/ecs/event.rs
Labels: code-quality, documentation, examples

#539 An initial xcode setup for using xcode
  .github/workflows/ios.yml
  Cargo.toml
  README.md
  crates/bevy_render/Cargo.toml
  examples/README.md
  examples/ios/.gitignore
  examples/ios/Cargo.toml
  examples/ios/Makefile
  examples/ios/bevy_ios_example.xcodeproj/.gitignore
  examples/ios/bevy_ios_example.xcodeproj/project.pbxproj
  examples/ios/build_rust_deps.sh
  examples/ios/ios-src/Info.plist
  examples/ios/ios-src/bindings.h
  examples/ios/ios-src/main.m
  examples/ios/src/lib.rs
Labels: ci / build system, enhancement, platform ios
