Repository bevyengine/bevy, pull requests merged in 2020-11, with the labels that each got.

#759 Make the startup system in the ecs_guide example non-thread local
  examples/ecs/ecs_guide.rs
Labels: examples

#763 impl ReadOnlyFetch for Or, FetchOr, and FetchMutated
  crates/bevy_ecs/hecs/src/query.rs
  crates/bevy_ecs/src/system/into_system.rs
Labels: ecs

#768 fix mesh allocation bug and public mesh api improvements
  crates/bevy_gltf/src/loader.rs
  crates/bevy_render/src/mesh/mesh.rs
  crates/bevy_render/src/pipeline/pipeline_compiler.rs
  crates/bevy_render/src/pipeline/render_pipelines.rs
  crates/bevy_text/src/draw.rs
  crates/bevy_ui/src/widget/text.rs
  examples/asset/asset_loading.rs
Labels: bug, code-quality, rendering

#757 Example for custom mesh attributes
  CHANGELOG.md
  Cargo.toml
  examples/shader/mesh_custom_attribute.rs
Labels: documentation, examples

#740 Use embedded glslang for runtime glsl-to-spirv
  Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/shader/shader.rs
  examples/android/bevy_android.rs
Labels: platform android, rendering

#771 Add more notes about `bevy`'s modules
  src/lib.rs
Labels: documentation

#769 Move ElementState to top-level of bevy_input.
  crates/bevy_input/src/keyboard.rs
  crates/bevy_input/src/lib.rs
  crates/bevy_input/src/mouse.rs
  crates/bevy_input/src/system.rs
  crates/bevy_winit/src/converters.rs
Labels: enhancement, input

#767 Convenient way to add minimal plugins for a headless server
  crates/bevy_app/src/schedule_runner.rs
  examples/2d/sprite.rs
  examples/2d/sprite_sheet.rs
  examples/2d/texture_atlas.rs
  examples/3d/3d_scene.rs
  examples/3d/load_gltf.rs
  examples/3d/msaa.rs
  examples/3d/parenting.rs
  examples/3d/spawner.rs
  examples/3d/texture.rs
  examples/3d/z_sort_debug.rs
  examples/app/empty_defaults.rs
  examples/app/headless.rs
  examples/app/plugin.rs
  examples/app/plugin_group.rs
  examples/app/return_after_run.rs
  examples/app/thread_pool_resources.rs
  examples/asset/asset_loading.rs
  examples/asset/custom_asset.rs
  examples/asset/hot_asset_reloading.rs
  examples/audio/audio.rs
  examples/diagnostics/custom_diagnostic.rs
  examples/diagnostics/print_diagnostics.rs
  examples/ecs/ecs_guide.rs
  examples/ecs/event.rs
  examples/ecs/hierarchy.rs
  examples/ecs/parallel_query.rs
  examples/game/breakout.rs
  examples/input/gamepad_input.rs
  examples/input/gamepad_input_events.rs
  examples/input/keyboard_input.rs
  examples/input/keyboard_input_events.rs
  examples/input/mouse_input.rs
  examples/input/mouse_input_events.rs
  examples/input/touch_input.rs
  examples/input/touch_input_events.rs
  examples/ios/src/lib.rs
  examples/scene/properties.rs
  examples/scene/scene.rs
  examples/shader/mesh_custom_attribute.rs
  examples/shader/shader_custom_material.rs
  examples/shader/shader_defs.rs
  examples/ui/button.rs
  examples/ui/font_atlas_debug.rs
  examples/ui/text.rs
  examples/ui/ui.rs
  examples/wasm/assets_wasm.rs
  examples/wasm/headless_wasm.rs
  examples/wasm/winit_wasm.rs
  examples/window/clear_color.rs
  examples/window/multiple_windows.rs
  examples/window/window_settings.rs
  src/default_plugins.rs
  src/prelude.rs
Labels: core, enhancement

#778 Fix initial Android support
  .github/workflows/ci.yml
  Cargo.toml
  crates/bevy_audio/Cargo.toml
  crates/bevy_input/src/lib.rs
  crates/bevy_input/src/touch.rs
  crates/bevy_ui/src/focus.rs
  crates/bevy_winit/src/converters.rs
  crates/bevy_winit/src/lib.rs
  examples/README.md
Labels: bug, platform android

#780 Remove two unused deps
  crates/bevy_app/Cargo.toml
  crates/bevy_ecs/hecs/Cargo.toml
Labels: dependencies

#785 fix unsafe Query function names
  crates/bevy_ecs/src/system/query/mod.rs
Labels: ecs

#404 Add mutated state when inserting an already existing component
  crates/bevy_ecs/hecs/src/archetype.rs
  crates/bevy_ecs/hecs/src/query.rs
  crates/bevy_ecs/hecs/src/world.rs
  crates/bevy_ecs/src/resource/resources.rs
Labels: bug, ecs, enhancement

#761 Port hecs derive macro improvements
  crates/bevy_ecs/hecs/macros/src/lib.rs
  crates/bevy_ecs/hecs/src/archetype.rs
  crates/bevy_ecs/hecs/tests/tests.rs
Labels: ecs, enhancement

#801 add example that represents contributors as bevy icons
  Cargo.toml
  examples/2d/contributors.rs
Labels: examples

#772 [gltf] Support camera and fix hierarchy
  crates/bevy_gltf/src/loader.rs
Labels: assets, enhancement

#806 Fixed several typos.
  crates/bevy_property/src/property_serde.rs
  crates/bevy_scene/src/serde.rs
  docs/cargo_features.md
Labels: code-quality

#794 upgrade glam and hexasphere
  crates/bevy_math/Cargo.toml
  crates/bevy_render/Cargo.toml
Labels: dependencies

#805 Add received character
  Cargo.toml
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/src/lib.rs
  examples/input/char_input_events.rs
Labels: enhancement, input

#799 Add basic example of a custom update loop
  Cargo.toml
  examples/app/custom_loop.rs
Labels: enhancement, examples

#815 Added RenderPass::set_scissor_rect
  crates/bevy_render/src/pass/render_pass.rs
  crates/bevy_wgpu/src/wgpu_render_pass.rs
Labels: enhancement, rendering

#827 Bump changelog version
  CHANGELOG.md
Labels: documentation

#831 Add readme key back to Cargo.toml
  Cargo.toml
Labels: code-quality

#691 delegate layout reflection to RenderResourceContext
  crates/bevy_pbr/src/entity.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/pipeline/pipeline.rs
  crates/bevy_render/src/pipeline/pipeline_compiler.rs
  crates/bevy_render/src/pipeline/render_pipelines.rs
  crates/bevy_render/src/renderer/render_resource/render_resource_bindings.rs
  crates/bevy_render/src/renderer/render_resource_context.rs
  crates/bevy_sprite/src/entity.rs
  crates/bevy_ui/src/entity.rs
  examples/shader/mesh_custom_attribute.rs
  examples/shader/shader_custom_material.rs
  examples/shader/shader_defs.rs
Labels: platform web, rendering

#829 Reduce the API surface of `bevy_ecs::Query`
  crates/bevy_ecs/src/system/query/mod.rs
  crates/bevy_ecs/src/system/query/query_set.rs
Labels: ecs, enhancement

#822 Explain default behavior of AssetServer in the asset_loading example
  examples/asset/asset_loading.rs
Labels: assets, documentation

#821 Update FileAssetIo NotFound error to include full path
  crates/bevy_asset/src/io/file_asset_io.rs
Labels: assets, enhancement

#790 Ahash constructor extensions and HashMap / HashSet
  crates/bevy_input/src/axis.rs
  crates/bevy_utils/src/lib.rs
Labels: code-quality

#830 Simple window modifications: added .resolution() accessor and more #[inline]
  crates/bevy_window/src/window.rs
Labels: enhancement, windowing

#789 Add tracing spans to schedules, stages, systems
  Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/schedule/parallel_executor.rs
  crates/bevy_internal/Cargo.toml
  examples/README.md
  examples/app/tracing.rs
Labels: enhancement, performance

#834 Query Filters
  crates/bevy_ecs/hecs/macros/src/lib.rs
  crates/bevy_ecs/hecs/src/access.rs
  crates/bevy_ecs/hecs/src/filter.rs
  crates/bevy_ecs/hecs/src/lib.rs
  crates/bevy_ecs/hecs/src/query.rs
  crates/bevy_ecs/hecs/src/world.rs
  crates/bevy_ecs/hecs/tests/tests.rs
  crates/bevy_ecs/src/system/into_system.rs
  crates/bevy_ecs/src/system/query/mod.rs
  crates/bevy_ecs/src/system/query/query_set.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/visible_entities.rs
  crates/bevy_transform/src/hierarchy/hierarchy_maintenance_system.rs
  crates/bevy_transform/src/transform_propagate_system.rs
  crates/bevy_ui/src/flex/mod.rs
  crates/bevy_ui/src/update.rs
  crates/bevy_ui/src/widget/text.rs
  examples/ecs/hierarchy.rs
  examples/scene/scene.rs
  examples/ui/button.rs
Labels: ecs, enhancement

#842 bevy_render: delegate buffer aligning to RenderResourceContext
  crates/bevy_render/src/render_graph/nodes/render_resources_node.rs
  crates/bevy_render/src/render_graph/nodes/texture_copy_node.rs
  crates/bevy_render/src/renderer/headless_render_resource_context.rs
  crates/bevy_render/src/renderer/render_resource/shared_buffers.rs
  crates/bevy_render/src/renderer/render_resource_context.rs
  crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
Labels: rendering

#845 android example polish
  Cargo.toml
  assets/android-res/mipmap-mdpi/ic_launcher.png
  examples/android/android.rs
Labels: examples, platform android

#844 Add entries, ToC, and releases note on examples
  examples/README.md
Labels: documentation, examples

#847 cross-platform main function
  Cargo.toml
  crates/bevy_derive/src/bevy_main.rs
  crates/bevy_derive/src/lib.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/lib.rs
  crates/bevy_internal/src/prelude.rs
  examples/android/android.rs
  examples/ios/src/lib.rs
Labels: enhancement, platform android, platform ios

#765 Refactor: use glyph_brush_layout and add text alignment support
  Cargo.toml
  crates/bevy_text/Cargo.toml
  crates/bevy_text/src/draw.rs
  crates/bevy_text/src/error.rs
  crates/bevy_text/src/font.rs
  crates/bevy_text/src/font_atlas.rs
  crates/bevy_text/src/font_atlas_set.rs
  crates/bevy_text/src/glyph_brush.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_ui/src/widget/text.rs
  examples/2d/contributors.rs
  examples/game/breakout.rs
  examples/scene/scene.rs
  examples/ui/button.rs
  examples/ui/font_atlas_debug.rs
  examples/ui/text.rs
  examples/ui/text_debug.rs
  examples/ui/ui.rs
Labels: code-quality, enhancement, rendering

#849 Clean up now-unused files due to changes in the transform system
  crates/bevy_transform/examples/hierarchy.rs
  crates/bevy_transform/examples/types_of_transforms.rs
  crates/bevy_transform/src/transform_system_bundle.rs
Labels: code-quality

#820 Make Timer.tick return &Self
  crates/bevy_core/src/time/timer.rs
  crates/bevy_diagnostic/src/print_diagnostics_plugin.rs
  examples/app/plugin.rs
  examples/ecs/event.rs
  examples/ui/font_atlas_debug.rs
Labels: code-quality, core

#273 add bevymark benchmark example
  Cargo.toml
  examples/tools/bevymark.rs
Labels: examples, performance, rendering

#851 More query filter usage
  crates/bevy_transform/src/hierarchy/hierarchy_maintenance_system.rs
  crates/bevy_ui/src/update.rs
  crates/bevy_ui/src/widget/image.rs
  examples/2d/contributors.rs
  examples/3d/parenting.rs
  examples/3d/z_sort_debug.rs
  examples/ecs/hierarchy.rs
  examples/ui/button.rs
  examples/ui/text.rs
Labels: code-quality

#854 Refresh the examples readme
  examples/README.md
Labels: documentation, examples

#856 Grammar correction
  README.md
  docs/debugging.md
  docs/linux_dependencies.md
Labels: documentation

#852 Controllable ambient light color
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/render_graph/forward_pipeline/forward.frag
  crates/bevy_pbr/src/render_graph/lights_node.rs
Labels: enhancement, rendering

#843 wasm32: non-spirv shader specialization
  crates/bevy_render/src/pipeline/pipeline_compiler.rs
  crates/bevy_render/src/renderer/headless_render_resource_context.rs
  crates/bevy_render/src/renderer/render_resource_context.rs
  crates/bevy_render/src/shader/mod.rs
  crates/bevy_render/src/shader/shader.rs
  crates/bevy_render/src/shader/shader_reflect_wasm.rs
  crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
Labels: platform web, rendering

#866 Remove redundant `.into` for mesh set_attributes with impl
  crates/bevy_render/src/mesh/mesh.rs
Labels: code-quality

#864 Prevent conflicting system resource parameters
  crates/bevy_ecs/src/system/into_system.rs
  crates/bevy_ecs/src/system/system_param.rs
Labels: ecs

#859 Add all basic color constants
  crates/bevy_render/src/color.rs
Labels: core, enhancement

#719 fallback to remove components one by one when failing to remove a bundle
  crates/bevy_ecs/hecs/src/world.rs
  crates/bevy_ecs/src/system/commands.rs
Labels: ecs, enhancement

#857 Fixed property typos, KeyCode typo.
  crates/bevy_input/src/keyboard.rs
  crates/bevy_property/src/type_registry.rs
  crates/bevy_type_registry/src/type_registry.rs
  crates/bevy_wgpu/src/wgpu_renderer.rs
  crates/bevy_winit/src/converters.rs
Labels: code-quality

#879 Misc cleanups
  crates/bevy_audio/src/audio_source.rs
  crates/bevy_gltf/src/loader.rs
  crates/bevy_math/src/geometry.rs
  crates/bevy_render/src/camera/visible_entities.rs
  crates/bevy_render/src/color.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/mesh/mesh.rs
  crates/bevy_render/src/render_graph/nodes/texture_copy_node.rs
  crates/bevy_render/src/texture/hdr_texture_loader.rs
  crates/bevy_render/src/texture/image_texture_loader.rs
  crates/bevy_render/src/texture/texture.rs
  crates/bevy_render/src/texture/texture_descriptor.rs
  crates/bevy_scene/src/scene_loader.rs
  crates/bevy_sprite/src/collide_aabb.rs
  crates/bevy_sprite/src/dynamic_texture_atlas_builder.rs
  crates/bevy_sprite/src/rect.rs
  crates/bevy_sprite/src/texture_atlas.rs
  crates/bevy_sprite/src/texture_atlas_builder.rs
  crates/bevy_text/src/font_loader.rs
  crates/bevy_ui/src/flex/mod.rs
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/update.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_winit/src/lib.rs
  examples/2d/contributors.rs
  examples/ecs/parallel_query.rs
  examples/game/breakout.rs
  examples/tools/bevymark.rs
  examples/wasm/assets_wasm.rs
Labels: code-quality

#878 ecs: replace "bool" component states with bitflags
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/core/archetype.rs
  crates/bevy_ecs/src/core/borrow.rs
  crates/bevy_ecs/src/core/filter.rs
  crates/bevy_ecs/src/core/mod.rs
  crates/bevy_ecs/src/core/query.rs
  crates/bevy_ecs/src/core/world.rs
Labels: ecs

#874 Replace Bytes with Byteable for TextureAtlasSprite
  crates/bevy_sprite/src/texture_atlas.rs
Labels: rendering

#877 Switch to default PartialEq implementation for RenderResourceBinding
  crates/bevy_render/src/renderer/render_resource/bind_group.rs
  crates/bevy_render/src/renderer/render_resource/render_resource_bindings.rs
Labels: rendering

#906 fix deprecation error in image_texture_loader (and CI error)
  .github/workflows/ci.yml
  crates/bevy_render/src/texture/image_texture_loader.rs
Labels: ci / build system

#887 Tweaks to TextureAtlasBuilder.finish()
  crates/bevy_sprite/src/texture_atlas_builder.rs
Labels: enhancement, rendering

#883 Add rectangular cuboid shape
  crates/bevy_render/src/mesh/mesh.rs
  crates/bevy_render/src/mesh/mod.rs
  crates/bevy_render/src/mesh/shape.rs
  examples/3d/3d_scene.rs
  examples/3d/msaa.rs
  examples/3d/parenting.rs
  examples/3d/z_sort_debug.rs
  examples/android/android.rs
  examples/ios/src/lib.rs
  examples/shader/mesh_custom_attribute.rs
  examples/shader/shader_custom_material.rs
  examples/shader/shader_defs.rs
Labels: enhancement, rendering

#895 use wasm-friendly instant::Instant everywhere
  Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_core/Cargo.toml
  crates/bevy_core/src/time/time.rs
  crates/bevy_core/src/time/timer.rs
  crates/bevy_diagnostic/Cargo.toml
  crates/bevy_diagnostic/src/diagnostic.rs
  crates/bevy_diagnostic/src/print_diagnostics_plugin.rs
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/examples/busy_behavior.rs
  crates/bevy_tasks/examples/idle_behavior.rs
  crates/bevy_tasks/src/countdown_event.rs
  crates/bevy_utils/Cargo.toml
  crates/bevy_utils/src/lib.rs
  examples/app/headless.rs
  examples/app/plugin.rs
  examples/ecs/ecs_guide.rs
  examples/scene/scene.rs
  examples/wasm/headless_wasm.rs
Labels: ci / build system, enhancement

#893 do not spend time drawing text with is_visible = false
  crates/bevy_ui/src/widget/text.rs
Labels: performance, ui

#903 Extend the Texture asset type to support 3D data
  Cargo.toml
  assets/textures/array_texture.png
  crates/bevy_gltf/src/loader.rs
  crates/bevy_render/src/render_graph/nodes/texture_copy_node.rs
  crates/bevy_render/src/texture/hdr_texture_loader.rs
  crates/bevy_render/src/texture/image_texture_loader.rs
  crates/bevy_render/src/texture/texture.rs
  crates/bevy_render/src/texture/texture_descriptor.rs
  crates/bevy_render/src/texture/texture_dimension.rs
  crates/bevy_sprite/src/dynamic_texture_atlas_builder.rs
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_sprite/src/texture_atlas_builder.rs
  crates/bevy_text/src/font.rs
  crates/bevy_text/src/font_atlas.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
  examples/shader/array_texture.rs
Labels: enhancement, rendering

#904 Fix duplicated chilren in Scene spawn
  crates/bevy_transform/src/components/children.rs
  crates/bevy_transform/src/components/parent.rs
  crates/bevy_transform/src/hierarchy/child_builder.rs
  crates/bevy_transform/src/hierarchy/hierarchy.rs
  crates/bevy_transform/src/hierarchy/hierarchy_maintenance_system.rs
  crates/bevy_transform/src/hierarchy/world_child_builder.rs
  crates/bevy_transform/src/lib.rs
  examples/ecs/hierarchy.rs
Labels: bug, ecs, performance

#909 avoid exclusive lock during `update_asset_storage`
  crates/bevy_asset/src/asset_server.rs
Labels: assets, performance

#923 Improve Timer ergonomics
  crates/bevy_core/src/time/timer.rs
Labels: core, enhancement

#905 Fix ui depth system
  crates/bevy_transform/src/hierarchy/hierarchy.rs
  crates/bevy_ui/src/update.rs
Labels: ui

#908 Allow despawning of hierarchies in threadlocal systems
  crates/bevy_transform/src/hierarchy/hierarchy.rs
Labels: ecs, enhancement

#920 wgpu: use mailbox instead of fifo for vsync
  crates/bevy_wgpu/src/wgpu_type_converter.rs
Labels: rendering

#917 Add set_cursor_position method to Window
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/lib.rs
Labels: enhancement, windowing

#916 Create winit windows before app.initialize()
  crates/bevy_winit/src/lib.rs
Labels: bug, windowing

#907 Remove Changed from parent update system
  crates/bevy_transform/src/hierarchy/hierarchy_maintenance_system.rs
Labels: ecs

#892 Fix a deadlock that can occur when using scope() on ComputeTaskPool from within a system
  crates/bevy_tasks/src/task_pool.rs
Labels: bug, core

#914 Allow timers to be paused
  crates/bevy_core/src/lib.rs
  crates/bevy_core/src/time/timer.rs
  crates/bevy_diagnostic/src/print_diagnostics_plugin.rs
  examples/2d/contributors.rs
  examples/2d/sprite_sheet.rs
  examples/app/plugin.rs
  examples/ecs/event.rs
  examples/ui/font_atlas_debug.rs
Labels: core, enhancement

#938 Removed redundant v_Normal in shader
  crates/bevy_pbr/src/render_graph/forward_pipeline/forward.vert
Labels: code-quality, rendering

#934 Refactor Time API and internals
  CHANGELOG.md
  crates/bevy_core/src/time/time.rs
  crates/bevy_diagnostic/src/frame_time_diagnostics_plugin.rs
  crates/bevy_diagnostic/src/print_diagnostics_plugin.rs
  examples/2d/contributors.rs
  examples/2d/sprite_sheet.rs
  examples/3d/parenting.rs
  examples/3d/spawner.rs
  examples/3d/z_sort_debug.rs
  examples/app/plugin.rs
  examples/ecs/event.rs
  examples/ecs/hierarchy.rs
  examples/ecs/timers.rs
  examples/game/breakout.rs
  examples/tools/bevymark.rs
  examples/ui/font_atlas_debug.rs
  examples/wasm/winit_wasm.rs
  examples/window/window_settings.rs
Labels: code-quality, core

#936 store PipelineSpecialization.dynamic_bindings in HashSet
  crates/bevy_render/src/pipeline/pipeline_compiler.rs
  crates/bevy_render/src/pipeline/render_pipelines.rs
Labels: bug, rendering

#955 Run parent-update and transform-propagation during the "post-startup" stage (instead of "startup")
  CHANGELOG.md
  crates/bevy_transform/src/lib.rs
Labels: ecs

#946 Additional vertex attribute value types
  crates/bevy_render/src/mesh/mesh.rs
Labels: enhancement, rendering

#945 Add removal_detection example
  CHANGELOG.md
  Cargo.toml
  examples/ecs/removal_detection.rs
Labels: ecs, examples

#948 Fix `RenderResources` index slicing
  crates/bevy_derive/src/render_resources.rs
Labels: code-quality, rendering
