Repository bevyengine/bevy, pull requests merged in 2020-12, with the labels that each got.

#952 Align bevy_input::Touch API with other similar APIs
  crates/bevy_input/src/touch.rs
  crates/bevy_ui/src/focus.rs
  examples/input/touch_input.rs
Labels: code-quality, input

#947 switch winit size to logical to be dpi independent
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/converters.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: enhancement, windowing

#953 Test more areas of the codebase
  crates/bevy_input/src/input.rs
  crates/bevy_input/src/touch.rs
  crates/bevy_math/src/face_toward.rs
Labels: code-quality

#954 Rename reflect 'hash' method to 'reflect_hash'
  crates/bevy_reflect/README.md
  crates/bevy_reflect/bevy_reflect_derive/src/lib.rs
  crates/bevy_reflect/src/impls/smallvec.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/list.rs
  crates/bevy_reflect/src/map.rs
  crates/bevy_reflect/src/reflect.rs
  crates/bevy_reflect/src/struct_trait.rs
  crates/bevy_reflect/src/tuple_struct.rs
  examples/reflection/reflection.rs
Labels: code-quality

#958 Renderer Optimization Round 1
  crates/bevy_ecs/src/core/world_builder.rs
  crates/bevy_render/src/mesh/mesh.rs
  crates/bevy_render/src/render_graph/nodes/pass_node.rs
  crates/bevy_render/src/render_graph/nodes/render_resources_node.rs
  crates/bevy_render/src/renderer/headless_render_resource_context.rs
  crates/bevy_render/src/renderer/render_resource/render_resource_bindings.rs
  crates/bevy_render/src/renderer/render_resource_context.rs
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_transform/src/hierarchy/world_child_builder.rs
  crates/bevy_transform/src/transform_propagate_system.rs
  crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
  crates/bevy_wgpu/src/wgpu_render_pass.rs
  crates/bevy_wgpu/src/wgpu_renderer.rs
  crates/bevy_wgpu/src/wgpu_resources.rs
Labels: enhancement, rendering

#973 hidpi swap chains
  crates/bevy_render/src/render_graph/nodes/window_texture_node.rs
  crates/bevy_wgpu/src/wgpu_type_converter.rs
  crates/bevy_window/src/window.rs
Labels: enhancement, rendering

#972 Optimize Text rendering / SharedBuffers
  crates/bevy_render/src/draw.rs
  crates/bevy_render/src/render_graph/nodes/shared_buffers_node.rs
  crates/bevy_render/src/renderer/render_resource/shared_buffers.rs
  crates/bevy_text/src/draw.rs
  crates/bevy_wgpu/src/lib.rs
Labels: enhancement, rendering

#984 fix changed meshes
  crates/bevy_render/src/mesh/mesh.rs
Labels: bug

#985 Add Archetype TypeInfo::type_name accessor
  crates/bevy_ecs/src/core/archetype.rs
Labels: ecs, enhancement

#983 Update examples readme
  examples/README.md
Labels: documentation, examples

#979 Tracing chrome span names
  crates/bevy_log/Cargo.toml
  crates/bevy_log/src/lib.rs
Labels: core, enhancement

#978 Debug text example: render fps and frame time
  examples/ui/text_debug.rs
Labels: examples

#976 Document part of bevy_ecs::Commands
  crates/bevy_ecs/src/core/bundle.rs
  crates/bevy_ecs/src/core/world.rs
  crates/bevy_ecs/src/system/commands.rs
Labels: documentation

#969 Change`TextureAtlasBuilder` into expected Builder conventions
  crates/bevy_sprite/src/texture_atlas_builder.rs
  examples/2d/texture_atlas.rs
Labels: code-quality, documentation

#940 Store mouse cursor position in Window
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/lib.rs
Labels: enhancement, windowing

#987 Optimize Asset Gpu Data Transfer
  crates/bevy_render/src/draw.rs
  crates/bevy_render/src/pipeline/render_pipelines.rs
  crates/bevy_render/src/render_graph/nodes/render_resources_node.rs
  crates/bevy_render/src/renderer/render_resource/render_resource_bindings.rs
  crates/bevy_text/src/draw.rs
  crates/bevy_ui/src/widget/text.rs
Labels: assets, performance, rendering

#988 fix scene loading
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/handle.rs
  crates/bevy_audio/src/audio.rs
  crates/bevy_core/src/label.rs
  crates/bevy_pbr/src/entity.rs
  crates/bevy_pbr/src/render_graph/forward_pipeline/mod.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/projection.rs
  crates/bevy_render/src/camera/visible_entities.rs
  crates/bevy_render/src/draw.rs
  crates/bevy_render/src/pipeline/render_pipelines.rs
  crates/bevy_render/src/render_graph/base.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_sprite/src/entity.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_text/src/draw.rs
  crates/bevy_transform/src/components/children.rs
  crates/bevy_transform/src/components/global_transform.rs
  crates/bevy_transform/src/components/parent.rs
  crates/bevy_ui/src/entity.rs
  crates/bevy_ui/src/render/mod.rs
Labels: assets, bug

#1001 fix example bindings
  examples/shader/array_texture.rs
  examples/shader/shader_custom_material.rs
  examples/shader/shader_defs.rs
Labels: bug, rendering

#1000 account for "still loading" textures in RenderResourceNodes
  crates/bevy_render/src/render_graph/nodes/render_resources_node.rs
Labels: bug, rendering

#1004 Allow windows to be maximized.
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/lib.rs
Labels: enhancement, windowing

#937 Live reloading of shaders
  Cargo.toml
  assets/shaders/hot.frag
  assets/shaders/hot.vert
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/pipeline/pipeline_compiler.rs
  crates/bevy_render/src/renderer/headless_render_resource_context.rs
  crates/bevy_render/src/renderer/render_resource_context.rs
  crates/bevy_render/src/shader/shader.rs
  crates/bevy_render/src/shader/shader_reflect.rs
  crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
  examples/shader/hot_shader_reloading.rs
Labels: assets, enhancement, rendering

#950 Add documentation for bevy::ecs::Query::removed
  crates/bevy_ecs/src/system/query/mod.rs
Labels: documentation, ecs

#956 Added FocusedWindow event and raw winit WindowEvents
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/src/lib.rs
Labels: enhancement, windowing

#997 attempt to deal with rounding issue when creating the swap chain
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/projection.rs
  crates/bevy_render/src/render_graph/nodes/window_texture_node.rs
  crates/bevy_ui/src/flex/mod.rs
  crates/bevy_wgpu/src/wgpu_type_converter.rs
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/2d/contributors.rs
  examples/ecs/parallel_query.rs
Labels: bug, rendering

#1016 Ensure a GLTF Default material is loaded
  crates/bevy_gltf/src/loader.rs
Labels: bug, rendering

#1023 scene: only update components for entities in scene
  crates/bevy_reflect/src/impls/bevy_ecs.rs
Labels: crash, ecs

#1026 can spawn a scene from a ChildBuilder, or directly set its parent when spawning it
  crates/bevy_scene/Cargo.toml
  crates/bevy_scene/src/command.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_transform/src/hierarchy/child_builder.rs
Labels: ecs, enhancement

#1027 Use shaderc for aarch64-apple-darwin.
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/shader/shader.rs
Labels: enhancement, platform macos, rendering

#1034 Break out Visible component from Draw
  CHANGELOG.md
  crates/bevy_pbr/src/entity.rs
  crates/bevy_render/src/camera/visible_entities.rs
  crates/bevy_render/src/draw.rs
  crates/bevy_render/src/entity.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/pipeline/render_pipelines.rs
  crates/bevy_render/src/render_graph/nodes/pass_node.rs
  crates/bevy_render/src/render_graph/nodes/render_resources_node.rs
  crates/bevy_sprite/src/entity.rs
  crates/bevy_ui/src/entity.rs
  crates/bevy_ui/src/widget/text.rs
  examples/3d/texture.rs
  examples/tools/bevymark.rs
  examples/ui/ui.rs
Labels: bug, rendering

#1035 fixes a panic
  crates/bevy_render/src/shader/shader_defs.rs
Labels: crash, rendering

#1038 add ability to load `.dds`, `.tga`, and `.jpeg` texture formats
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/texture/image_texture_loader.rs
Labels: enhancement, rendering

#1021 Schedule v2
  Cargo.toml
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/app_builder.rs
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_app/src/stage.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_core/src/lib.rs
  crates/bevy_core/src/time/fixed_timestep.rs
  crates/bevy_core/src/time/mod.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/stage.rs
  crates/bevy_ecs/src/schedule/stage_executor.rs
  crates/bevy_ecs/src/schedule/state.rs
  crates/bevy_ecs/src/system/into_system.rs
  crates/bevy_ecs/src/system/into_thread_local.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_chaining.rs
  crates/bevy_input/src/lib.rs
  crates/bevy_pbr/src/render_graph/lights_node.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_graph/graph.rs
  crates/bevy_render/src/render_graph/node.rs
  crates/bevy_render/src/render_graph/nodes/camera_node.rs
  crates/bevy_render/src/render_graph/nodes/render_resources_node.rs
  crates/bevy_render/src/render_graph/system.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_transform/src/hierarchy/hierarchy_maintenance_system.rs
  crates/bevy_transform/src/transform_propagate_system.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/update.rs
  crates/bevy_winit/src/lib.rs
  examples/2d/texture_atlas.rs
  examples/app/custom_loop.rs
  examples/ecs/ecs_guide.rs
  examples/ecs/fixed_timestep.rs
  examples/ecs/state.rs
Labels: ecs, enhancement

#1043 Add support for Apple Silicon by upgrading winit.
  CHANGELOG.md
  crates/bevy_input/src/mouse.rs
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/lib.rs
Labels: dependencies, windowing

#1033 update `Window`'s `width` & `height` methods to return `f32`
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_ui/src/flex/mod.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/2d/contributors.rs
  examples/ecs/parallel_query.rs
  examples/tools/bevymark.rs
  examples/wasm/winit_wasm.rs
  examples/window/multiple_windows.rs
  examples/window/window_settings.rs
Labels: enhancement, windowing

#1059 Improve usability of StateStage and cut down on "magic"
  crates/bevy_app/src/app_builder.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/stage.rs
  crates/bevy_ecs/src/schedule/state.rs
  crates/bevy_ecs/src/system/into_system.rs
  examples/2d/texture_atlas.rs
  examples/ecs/state.rs
Labels: ecs, enhancement

#1066 suppress wgpu warnings by default
  crates/bevy_log/src/lib.rs
Labels: enhancement

#1065 Update dependencies for Enable Fast Compiles
  docs/linux_dependencies.md
Labels: ci / build system, documentation

#1061 run stretch's layout on physical coordinates to fix pixel alignment
  crates/bevy_ui/src/flex/convert.rs
  crates/bevy_ui/src/flex/mod.rs
Labels: bug, ui

#1037 add ability to provide custom a `AssetIo` implementation
  Cargo.toml
  crates/bevy_asset/src/asset_server.rs
  crates/bevy_asset/src/lib.rs
  examples/asset/custom_asset_io.rs
Labels: assets, enhancement

#1082 Fix example return_after_run
  crates/bevy_log/src/lib.rs
  crates/bevy_winit/src/lib.rs
  examples/app/return_after_run.rs
Labels: core, crash, windowing

#1071 set is_transparent to true by default for UI bundles
  crates/bevy_ui/src/entity.rs
  examples/asset/custom_asset_io.rs
  examples/tools/bevymark.rs
  examples/ui/ui.rs
Labels: enhancement, rendering

#1088 fix multiple windows example
  examples/window/multiple_windows.rs
Labels: bug, rendering

#1091 add with_enter_stage (and other variants)
  crates/bevy_ecs/src/schedule/state.rs
Labels: ecs

#1092 update changelog
  CHANGELOG.md
Labels: documentation

#1042 Allow wgpu backend to be configured from the environment
  crates/bevy_wgpu/src/lib.rs
  crates/bevy_wgpu/src/wgpu_renderer.rs
Labels: enhancement, rendering

#1121 Fix lock order to remove the chance of deadlock
  crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
Labels: rendering

#1064 Prevent double panic in the Drop of TaksPoolInner
  crates/bevy_tasks/src/task_pool.rs
Labels: ci / build system, core, crash

#1133 make wgpu options public
  crates/bevy_wgpu/src/lib.rs
Labels: rendering

#1070 do not check for focus until cursor position has been set
  crates/bevy_ui/src/focus.rs
Labels: bug, ui

#1081 Add bmp as a supported texture format
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/texture/image_texture_loader.rs
Labels: assets, enhancement

#1089 Modify Derive to allow unit structs for RenderResources.
  crates/bevy_derive/src/render_resources.rs
  examples/shader/mesh_custom_attribute.rs
Labels: enhancement, rendering

#1104 bevy_render: load .spv assets
  crates/bevy_render/src/pipeline/pipeline_compiler.rs
  crates/bevy_render/src/shader/shader.rs
Labels: rendering

#1063 Add an alternative winit runner that can be started when not on the main thread
  crates/bevy_winit/src/lib.rs
Labels: enhancement, windowing

#1085 updates on diagnostics (log + new diagnostics)
  Cargo.toml
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/diagnostic/asset_count_diagnostics_plugin.rs
  crates/bevy_asset/src/diagnostic/mod.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_diagnostic/Cargo.toml
  crates/bevy_diagnostic/src/diagnostic.rs
  crates/bevy_diagnostic/src/entity_count_diagnostics_plugin.rs
  crates/bevy_diagnostic/src/lib.rs
  crates/bevy_diagnostic/src/log_diagnostics_plugin.rs
  crates/bevy_ecs/src/core/entities.rs
  crates/bevy_ecs/src/core/world.rs
  examples/3d/spawner.rs
  examples/README.md
  examples/app/plugin_group.rs
  examples/diagnostics/custom_diagnostic.rs
  examples/diagnostics/log_diagnostics.rs
Labels: core, enhancement

#1111 Update fedora version from 32 to 33 in docs
  docs/linux_dependencies.md
Labels: platform linux

#1122 Render text in 2D scenes
  Cargo.toml
  crates/bevy_render/src/render_graph/base.rs
  crates/bevy_render/src/render_graph/nodes/pass_node.rs
  crates/bevy_text/Cargo.toml
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/text.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/entity.rs
  crates/bevy_ui/src/flex/mod.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/node.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_ui/src/widget/text.rs
  examples/2d/text2d.rs
  examples/ui/text.rs
Labels: enhancement, rendering

#1072 Add option to ignore events when receving unknown WindowId
  crates/bevy_winit/src/lib.rs
Labels: crash, windowing

#1152 Test entity labels, fixed corner cases, changed interface
  crates/bevy_core/src/label.rs
  crates/bevy_core/src/lib.rs
Labels: bug, ecs

#1131 Added use_dpi setting to WindowDescriptor
  Cargo.toml
  crates/bevy_ui/src/flex/mod.rs
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/window/scale_factor_override.rs
  examples/window/window_settings.rs
Labels: enhancement, rendering

#1154 Implement Copy for ElementState
  crates/bevy_input/src/lib.rs
Labels: code-quality, input

#1155 enable change detection for labels
  crates/bevy_core/src/label.rs
  crates/bevy_core/src/lib.rs
Labels: core, enhancement

#1156 let user disable feature png when using only other format
  crates/bevy_render/src/texture/mod.rs
Labels: bug, rendering

#1132 Text render resolution
  crates/bevy_math/src/geometry.rs
  crates/bevy_text/src/draw.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/widget/text.rs
Labels: rendering

#1109 Alternative name component used for faster comparisons
  crates/bevy_core/Cargo.toml
  crates/bevy_core/src/lib.rs
  crates/bevy_core/src/name.rs
Labels: ecs

#1020 make more information available from loaded GLTF model
  crates/bevy_asset/src/loader.rs
  crates/bevy_gltf/Cargo.toml
  crates/bevy_gltf/src/lib.rs
  crates/bevy_gltf/src/loader.rs
  examples/3d/load_gltf.rs
  examples/asset/hot_asset_reloading.rs
  examples/window/multiple_windows.rs
Labels: assets, enhancement

#1055 Fix potential bug when using multiple lights.
  crates/bevy_pbr/src/render_graph/forward_pipeline/forward.frag
Labels: bug, rendering
