Repository bevyengine/bevy, pull requests merged in 2020-08, with the labels that each got.

#109 Added missing gpu message instead of panicking on 'None'.
  crates/bevy_wgpu/src/wgpu_renderer.rs
Labels: enhancement, rendering

#132 Cleaned up breakout example collision code, altered setup so ball doesn't clip through walls as often
  examples/game/breakout.rs
Labels: examples

#144 Fix comment in keyboard_input_event example
  examples/input/keyboard_input_events.rs
Labels: documentation, examples

#161 Creates linux_dependencies.md
  docs/linux_dependencies.md
Labels: ci / build system, documentation

#153 ecs: remove unused Entities::current
  crates/bevy_ecs/hecs/src/entities.rs
Labels: ecs, enhancement

#146 Add support for embedded buffers in GLTF loader
  crates/bevy_gltf/Cargo.toml
  crates/bevy_gltf/src/loader.rs
Labels: assets, enhancement

#149 Add resizable flag and windowmode option to window creation
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/window/multiple_windows.rs
  examples/window/window_settings.rs
Labels: enhancement, windowing

#172 Added Mut to ECS prelude
  crates/bevy_ecs/src/lib.rs
Labels: enhancement

#173 Added BindingShaderStage in order to pass the correct shader stage to wgpu.
  crates/bevy_render/src/pipeline/binding.rs
  crates/bevy_render/src/render_graph/nodes/pass_node.rs
  crates/bevy_render/src/renderer/render_resource/render_resource_bindings.rs
  crates/bevy_render/src/shader/shader_reflect.rs
  crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
Labels: enhancement, rendering

#154 Add Icospheres mesh generation
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/mesh/mesh.rs
  examples/3d/3d_scene.rs
Labels: enhancement

#181 Add info message in UI for scene example
  examples/scene/scene.rs
Labels: enhancement, examples

#188 Add possibility to control num_threads and stack_size of global thread pool
  Cargo.toml
  crates/bevy_ecs/src/schedule/parallel_executor.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  examples/app/thread_pool_resources.rs
Labels: enhancement, performance

#150 Use Rust bundled lld for msvc target
  .cargo/config_fast_builds
Labels: ci / build system, platform windows

#196 Added 2 more draw.is_visible checks to render crate
  crates/bevy_render/src/pipeline/render_pipelines.rs
  crates/bevy_render/src/render_graph/nodes/render_resources_node.rs
Labels: enhancement, rendering

#204 profiling: fix build
  crates/bevy_diagnostic/Cargo.toml
  crates/bevy_diagnostic/src/lib.rs
  crates/bevy_diagnostic/src/system_profiler.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/profiler.rs
Labels: bug, ci / build system

#211 Add Draw command to RenderCommand
  crates/bevy_render/src/draw.rs
  crates/bevy_render/src/render_graph/nodes/pass_node.rs
Labels: enhancement, rendering

#203 Replace vector of UniformProperty with a single UniformProperty
  crates/bevy_render/src/pipeline/binding.rs
  crates/bevy_render/src/render_graph/nodes/pass_node.rs
  crates/bevy_render/src/renderer/render_resource/render_resource_bindings.rs
  crates/bevy_render/src/shader/shader_reflect.rs
  crates/bevy_wgpu/src/wgpu_type_converter.rs
Labels: enhancement, rendering

#189 Reflect shader stage for bind groups.
  crates/bevy_render/src/pipeline/pipeline_layout.rs
  crates/bevy_render/src/shader/shader_reflect.rs
Labels: enhancement, rendering

#245 Simplify GLTF loader code
  crates/bevy_gltf/src/loader.rs
Labels: assets, code-quality

#230 Fix #187 . Multiple return instead of continue inside for loops.
  crates/bevy_render/src/render_graph/nodes/render_resources_node.rs
Labels: bug, rendering

#263 Updating README.md with subreddit info and link to Code of Conduct
  README.md
Labels: documentation

#222 Basic mouse scroll-wheel event
  crates/bevy_input/src/lib.rs
  crates/bevy_input/src/mouse.rs
  crates/bevy_winit/src/lib.rs
  examples/input/mouse_input_events.rs
Labels: enhancement, input

#225 README.md link points to the correct example
  examples/README.md
Labels: documentation

#243 Allow calling winit with the 'run_return' variant of the run function
  Cargo.toml
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/winit_config.rs
  examples/app/return_after_run.rs
Labels: ecs, enhancement, third party / dependencies, windowing

#275 Add Arch / Manjaro dependencies
  docs/linux_dependencies.md
Labels: documentation, third party / dependencies

#311 Fix unresolved import in window settings example
  examples/window/window_settings.rs
Labels: bug, examples

#314 Update zld path to use alias (mac fast compile config)
  .cargo/config_fast_builds
Labels: ci / build system, platform macos

#249 add an option about display server protocol, and create document `docs/cargo_features.md`
  Cargo.toml
  README.md
  crates/bevy_winit/Cargo.toml
  docs/cargo_features.md
  examples/README.md
Labels: third party / dependencies, windowing

#183 Support multiline Texts
  crates/bevy_text/src/draw.rs
Labels: enhancement, ui

#304 Fix default UI node size
  crates/bevy_ui/src/node.rs
Labels: bug, ui

#347 Add .vscode to gitignore file
  .gitignore
Labels: ci / build system

#331 Add Solus dependency install instructions
  docs/linux_dependencies.md
Labels: ci / build system, documentation, third party / dependencies

#271 Add support for binary glTF (.glb)
  assets/models/monkey/Monkey.glb
  crates/bevy_gltf/src/loader.rs
  examples/3d/load_model.rs
Labels: assets, enhancement

#349 Set CI to run on master commits
  .github/workflows/ci.yml
Labels: ci / build system, enhancement

#345 Check asset-path existence. Previously App just crashed if not
  crates/bevy_asset/src/load_request.rs
Labels: assets, crash

#381 Add Color::rgb_u8 and Color::rgba_u8
  crates/bevy_render/src/color.rs
Labels: code-quality, rendering

#379 Update icosphere dependency and add a limit to subdivisions.
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/mesh/mesh.rs
Labels: rendering

#290 add documentation for NixOS dependencies
  docs/linux_dependencies.md
Labels: ci / build system, documentation

#376 Fix deadlock in hot asset reloading (#375)
  crates/bevy_asset/src/asset_server.rs
Labels: assets, bug

#383 Fix archetypes_generation being incorrectly updated for systems
  crates/bevy_ecs/src/schedule/parallel_executor.rs
Labels: bug, ecs

#396 add bevy_render::pass::ClearColor to prelude
  crates/bevy_render/src/lib.rs
Labels: code-quality, rendering

#394 Fix hot asset reloading on Windows
  crates/bevy_asset/src/asset_server.rs
Labels: assets, bug, platform windows

#362 Add Color::hex fn
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/color.rs
Labels: code-quality, enhancement, rendering

#393 Bump entities to u128 to avoid collisions (#117)
  crates/bevy_ecs/hecs/src/archetype.rs
  crates/bevy_ecs/hecs/src/entities.rs
  crates/bevy_ecs/hecs/src/query.rs
  crates/bevy_ecs/hecs/src/serde.rs
  crates/bevy_ecs/src/resource/resources.rs
  crates/bevy_property/src/impl_property/impl_property_bevy_ecs.rs
  crates/bevy_scene/src/scene.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_scene/src/serde.rs
  crates/bevy_transform/src/components/parent.rs
Labels: ecs
