Repository bevyengine/bevy, pull requests merged in 2021-01, with the labels that each got.

#1177 Derive Clone for SpriteSheetBundle and SpriteBundle
  crates/bevy_sprite/src/entity.rs
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_sprite/src/texture_atlas.rs
Labels: code-quality, rendering

#1058 let user run a function on a scene entities
  Cargo.toml
  crates/bevy_scene/src/scene_spawner.rs
  examples/3d/update_gltf_scene.rs
  examples/README.md
Labels: ecs, enhancement, examples

#1096 Add basic file drag and drop support
  Cargo.toml
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/src/lib.rs
  examples/README.md
  examples/app/drag_and_drop.rs
Labels: enhancement, windowing

#1171 Text2d render quality
  crates/bevy_sprite/src/render/sprite_sheet.vert
  crates/bevy_text/Cargo.toml
  crates/bevy_text/src/glyph_brush.rs
  crates/bevy_text/src/text2d.rs
Labels: enhancement, rendering

#1180 remove panics when mixing UI and non UI entities in hierarchy
  crates/bevy_ui/Cargo.toml
  crates/bevy_ui/src/flex/mod.rs
Labels: crash, ui

#1182 bevy_reflect incorrectly looks for bevy in dev-deps
  crates/bevy_reflect/bevy_reflect_derive/src/modules.rs
Labels: bug, core

#1204 fix example update_gltf_scene: add label to load asset
  examples/3d/update_gltf_scene.rs
Labels: bug, examples

#1119 ECS: Use fxhash in TypeIdMap.
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/core/archetype.rs
Labels: ecs

#1114 Update rand requirement from 0.7 to 0.8
  Cargo.toml
  crates/bevy_asset/Cargo.toml
  crates/bevy_ecs/Cargo.toml
  examples/2d/contributors.rs
  examples/3d/spawner.rs
Labels: dependencies, third party / dependencies

#1249 Update glam to 0.12.0
  crates/bevy_math/Cargo.toml
  crates/bevy_reflect/Cargo.toml
Labels: core, third party / dependencies

#1216 Support for !Send tasks
  crates/bevy_tasks/src/single_threaded_task_pool.rs
  crates/bevy_tasks/src/task_pool.rs
Labels: core, enhancement

#1244 Make EventReader a SystemParam
  crates/bevy_app/src/event.rs
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input/src/keyboard.rs
  crates/bevy_input/src/mouse.rs
  crates/bevy_input/src/system.rs
  crates/bevy_input/src/touch.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/mesh/mesh.rs
  crates/bevy_render/src/render_graph/nodes/render_resources_node.rs
  crates/bevy_render/src/render_graph/nodes/texture_copy_node.rs
  crates/bevy_render/src/render_graph/nodes/window_swapchain_node.rs
  crates/bevy_render/src/render_graph/nodes/window_texture_node.rs
  crates/bevy_render/src/shader/shader.rs
  crates/bevy_render/src/texture/texture.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_ui/src/flex/mod.rs
  crates/bevy_wgpu/src/wgpu_renderer.rs
  crates/bevy_window/src/system.rs
  crates/bevy_winit/src/lib.rs
  examples/app/drag_and_drop.rs
  examples/ecs/event.rs
  examples/input/char_input_events.rs
  examples/input/gamepad_input.rs
  examples/input/gamepad_input_events.rs
  examples/input/keyboard_input_events.rs
  examples/input/mouse_input_events.rs
  examples/input/touch_input_events.rs
  examples/wasm/winit_wasm.rs
Labels: ecs, enhancement

#1245 Rich text
  crates/bevy_text/src/draw.rs
  crates/bevy_text/src/glyph_brush.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_text/src/text.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/widget/text.rs
  examples/2d/contributors.rs
  examples/2d/text2d.rs
  examples/ecs/state.rs
  examples/game/alien_cake_addict.rs
  examples/game/breakout.rs
  examples/scene/scene.rs
  examples/tools/bevymark.rs
  examples/ui/button.rs
  examples/ui/font_atlas_debug.rs
  examples/ui/text.rs
  examples/ui/text_debug.rs
  examples/ui/ui.rs
  examples/window/scale_factor_override.rs
Labels: enhancement, ui

#400 OrthographicProjection scaling mode + camera bundle refactoring
  crates/bevy_render/src/camera/projection.rs
  crates/bevy_render/src/entity.rs
  crates/bevy_ui/src/entity.rs
  examples/2d/contributors.rs
  examples/2d/sprite.rs
  examples/2d/sprite_sheet.rs
  examples/2d/text2d.rs
  examples/2d/texture_atlas.rs
  examples/3d/3d_scene.rs
  examples/3d/load_gltf.rs
  examples/3d/msaa.rs
  examples/3d/parenting.rs
  examples/3d/spawner.rs
  examples/3d/texture.rs
  examples/3d/update_gltf_scene.rs
  examples/3d/z_sort_debug.rs
  examples/android/android.rs
  examples/asset/asset_loading.rs
  examples/asset/custom_asset_io.rs
  examples/asset/hot_asset_reloading.rs
  examples/ecs/hierarchy.rs
  examples/ecs/parallel_query.rs
  examples/ecs/removal_detection.rs
  examples/ecs/state.rs
  examples/game/alien_cake_addict.rs
  examples/game/breakout.rs
  examples/ios/src/lib.rs
  examples/scene/scene.rs
  examples/shader/array_texture.rs
  examples/shader/hot_shader_reloading.rs
  examples/shader/mesh_custom_attribute.rs
  examples/shader/shader_custom_material.rs
  examples/shader/shader_defs.rs
  examples/tools/bevymark.rs
  examples/ui/button.rs
  examples/ui/font_atlas_debug.rs
  examples/ui/text.rs
  examples/ui/text_debug.rs
  examples/ui/ui.rs
  examples/window/multiple_windows.rs
  examples/window/scale_factor_override.rs
Labels: enhancement, rendering

#1192 examples: add rng coloring to bevymark birds
  examples/tools/bevymark.rs
Labels: enhancement, examples
