Repository bevyengine/bevy, pull requests merged in 2021-02, with the labels that each got.

#542 Update to wgpu-rs 0.7
  crates/bevy_pbr/src/render_graph/forward_pipeline/mod.rs
  crates/bevy_render/src/draw.rs
  crates/bevy_render/src/mesh/mesh.rs
  crates/bevy_render/src/pass/render_pass.rs
  crates/bevy_render/src/pipeline/binding.rs
  crates/bevy_render/src/pipeline/pipeline.rs
  crates/bevy_render/src/pipeline/pipeline_compiler.rs
  crates/bevy_render/src/pipeline/pipeline_layout.rs
  crates/bevy_render/src/pipeline/state_descriptors.rs
  crates/bevy_render/src/pipeline/vertex_buffer_descriptor.rs
  crates/bevy_render/src/render_graph/nodes/pass_node.rs
  crates/bevy_render/src/renderer/render_resource/render_resource_bindings.rs
  crates/bevy_render/src/shader/mod.rs
  crates/bevy_render/src/shader/shader_reflect.rs
  crates/bevy_render/src/texture/sampler_descriptor.rs
  crates/bevy_render/src/texture/texture_descriptor.rs
  crates/bevy_render/src/texture/texture_dimension.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_text/src/draw.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/widget/text.rs
  crates/bevy_wgpu/Cargo.toml
  crates/bevy_wgpu/src/renderer/wgpu_render_context.rs
  crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs
  crates/bevy_wgpu/src/wgpu_render_pass.rs
  crates/bevy_wgpu/src/wgpu_renderer.rs
  crates/bevy_wgpu/src/wgpu_type_converter.rs
  examples/2d/texture_atlas.rs
Labels: ci / build system, rendering, third party / dependencies

#1250 Plugin guidelines
  README.md
  docs/cargo_features.md
  docs/plugins_guidelines.md
  examples/README.md
Labels: documentation, third party / dependencies

#1144 System sets and parallel executor v2
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/app_builder.rs
  crates/bevy_audio/src/audio_output.rs
  crates/bevy_audio/src/lib.rs
  crates/bevy_core/src/label.rs
  crates/bevy_core/src/time/fixed_timestep.rs
  crates/bevy_diagnostic/src/entity_count_diagnostics_plugin.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/benches/system_stage.rs
  crates/bevy_ecs/src/core/access.rs
  crates/bevy_ecs/src/core/mod.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/resource/resource_query.rs
  crates/bevy_ecs/src/resource/resources.rs
  crates/bevy_ecs/src/schedule/executor.rs
  crates/bevy_ecs/src/schedule/executor_parallel.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/stage.rs
  crates/bevy_ecs/src/schedule/stage_executor.rs
  crates/bevy_ecs/src/schedule/state.rs
  crates/bevy_ecs/src/schedule/system_container.rs
  crates/bevy_ecs/src/schedule/system_descriptor.rs
  crates/bevy_ecs/src/schedule/system_set.rs
  crates/bevy_ecs/src/system/exclusive_system.rs
  crates/bevy_ecs/src/system/into_system.rs
  crates/bevy_ecs/src/system/into_thread_local.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_chaining.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_gilrs/src/gilrs_system.rs
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_log/src/lib.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_graph/graph.rs
  crates/bevy_render/src/render_graph/system.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_text/src/draw.rs
  crates/bevy_transform/src/hierarchy/hierarchy_maintenance_system.rs
  crates/bevy_transform/src/transform_propagate_system.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/update.rs
  crates/bevy_wgpu/src/lib.rs
  crates/bevy_winit/src/lib.rs
  examples/scene/scene.rs
Labels: ecs, enhancement

#1456 add labels and ordering for transform propagation and parent update systems in POST_UPDATE stage
  crates/bevy_transform/src/lib.rs
Labels: bug, ecs, high-impact, ready for cart

#1469 Explicit execution order ambiguities API
  crates/bevy_ecs/src/schedule/stage.rs
  crates/bevy_ecs/src/schedule/system_container.rs
  crates/bevy_ecs/src/schedule/system_descriptor.rs
  crates/bevy_transform/src/lib.rs
Labels: core, ecs, ready for cart, usability

#1473 Non-string labels (#1423 continued)
  crates/bevy_app/src/app_builder.rs
  crates/bevy_app/src/lib.rs
  crates/bevy_app/src/stage.rs
  crates/bevy_app/src/startup_stage.rs
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_audio/src/lib.rs
  crates/bevy_core/src/lib.rs
  crates/bevy_diagnostic/src/log_diagnostics_plugin.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/label.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/stage.rs
  crates/bevy_ecs/src/schedule/system_container.rs
  crates/bevy_ecs/src/schedule/system_descriptor.rs
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_input/src/lib.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_graph/graph.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_transform/src/lib.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_wgpu/src/lib.rs
  examples/2d/texture_atlas.rs
  examples/ecs/ecs_guide.rs
  examples/ecs/fixed_timestep.rs
  examples/ecs/removal_detection.rs
  examples/ecs/state.rs
  examples/game/alien_cake_addict.rs
  examples/input/gamepad_input.rs
  examples/shader/shader_defs.rs
  examples/window/multiple_windows.rs
Labels: core, ecs, high-impact, ready for cart

#1453 Extend AppBuilder api with `add_system_set` and similar methods
  crates/bevy_app/src/app_builder.rs
  crates/bevy_ecs/src/schedule/mod.rs
Labels: ecs, ready for cart, usability

#1479 Fix deprecation warning when running cargo fmt
  rustfmt.toml
Labels: code-quality, ready for cart

#1482 Bors
  .github/bors.toml
  .github/workflows/ci.yml
  .github/workflows/rebase.yml
Labels: ci / build system, meta
