Repository bevyengine/bevy, pull requests merged in 2023-11, with the labels that each got.

#10311 Added 'clear_children' and 'replace_children' methods to BuildWorldChildren to be consistent with BuildChildren.
  crates/bevy_hierarchy/src/child_builder.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Hierarchy

#10330 double sided normals: fix apply_normal_mapping calls
  assets/shaders/array_texture.wgsl
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#10345 don't Implement `Display` for `Val`
  crates/bevy_ui/src/geometry.rs
Labels: A-UI, C-Code-Quality, S-Ready-For-Final-Review

#10196 Combine visibility queries in check_visibility_system
  crates/bevy_render/src/view/visibility/mod.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#10341 Make VERTEX_COLORS usable in prepass shader, if available
  crates/bevy_pbr/src/prepass/mod.rs
Labels: C-Bug, A-Rendering

#10223 allow DeferredPrepass to work without other prepass markers
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/mod.rs
Labels: A-Rendering, C-Crash, S-Ready-For-Final-Review

#9610 UI batching Fix
  crates/bevy_ui/src/render/mod.rs
Labels: C-Bug, A-Rendering, C-Performance, A-UI, P-High

#10346 Increase default normal bias to avoid common artifacts
  crates/bevy_pbr/src/light.rs
Labels: C-Bug, A-Rendering, C-Breaking-Change

#9226 Make `DirectionalLight` `Cascades` computation generic over `CameraProjection`
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_render/src/camera/projection.rs
Labels: C-Bug, A-Rendering, C-Crash, C-Breaking-Change

#10352 Corrected incorrect doc comment on read_asset_bytes
  crates/bevy_asset/src/loader.rs
Labels: C-Docs, A-Assets, S-Ready-For-Final-Review

#10356 Allow AccessKit to react to WindowEvents before they reach the engine
  crates/bevy_winit/src/lib.rs
Labels: C-Bug, O-Linux, O-MacOS, C-Accessibility, S-Ready-For-Final-Review

#10358 Fix typo in window.rs
  crates/bevy_window/src/window.rs
Labels: C-Docs, A-Windowing, S-Ready-For-Final-Review

#9506 Add UI Materials
  Cargo.toml
  assets/shaders/circle_shader.wgsl
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_material.wgsl
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_vertex_output.wgsl
  crates/bevy_ui/src/ui_material.rs
  examples/README.md
  examples/ui/ui_material.rs
Labels: C-Enhancement, A-Rendering, A-UI, S-Ready-For-Final-Review

#10312 support file operations in single threaded context
  crates/bevy_asset/src/io/file/file_asset.rs
  crates/bevy_asset/src/io/file/mod.rs
  crates/bevy_asset/src/io/file/sync_file_asset.rs
Labels: A-Assets, C-Usability

#10360 Fix gizmo crash when prepass enabled
  crates/bevy_gizmos/src/pipeline_3d.rs
Labels: C-Bug, A-Rendering

#10366 Fix example showcase
  .gitignore
  example_showcase_config.ron
  tools/example-showcase/extra-window-resized-events.patch
Labels: A-Build-System, C-Examples, S-Ready-For-Final-Review

#10365 gate depth reads on !WEBGL2
  crates/bevy_pbr/src/render/pbr_transmission.wgsl
Labels: C-Bug, A-Rendering

#10369 Add "update screenshots" to release checklist
  docs/release_checklist.md
Labels: A-Meta

#10376 docs: use `read` instead of deprecated `iter`
  crates/bevy_time/src/time.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Time

#10421 ui material: fix right border width
  crates/bevy_ui/src/render/ui_material_pipeline.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#10415 Use `EntityHashMap` for `EntityMapper`
  crates/bevy_ecs/src/entity/map_entities.rs
  crates/bevy_ecs/src/reflect/map_entities.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/scene.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_scene/src/serde.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review, C-Breaking-Change

#10424 Add PartialEq to Anchor
  crates/bevy_sprite/src/sprite.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#10434 UI Materials: ignore entities with a `BackgroundColor` component
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
Labels: C-Bug, A-UI

#10423 Fix bevy_pbr shader function name
  crates/bevy_pbr/src/prepass/prepass.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#10394 Implement Clone for VisibilityBundle and SpatialBundle
  crates/bevy_render/src/spatial_bundle.rs
  crates/bevy_render/src/view/visibility/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#10445 Fix intra-doc link warnings
  examples/2d/mesh2d.rs
  examples/2d/mesh2d_manual.rs
  examples/2d/mesh2d_vertex_color_texture.rs
  examples/animation/morph_targets.rs
  examples/app/headless.rs
  examples/ecs/one_shot_systems.rs
  examples/ui/ui_scaling.rs
Labels: C-Docs, C-Examples, S-Ready-For-Final-Review

#10378 Allow registering boxed systems
  crates/bevy_ecs/src/system/system_registry.rs
Labels: A-ECS, S-Ready-For-Final-Review

#10446 Remove unnecessary if statement in scheduler
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: C-Bug, A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#10461 Reexport `wgpu::Maintain`
  crates/bevy_render/src/render_resource/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#10452 Don't `.unwrap()` in `AssetPath::try_parse`
  crates/bevy_asset/src/path.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#10475 Remove a ptr-to-int cast in `CommandQueue::apply`
  crates/bevy_ecs/src/system/commands/command_queue.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Pointers

#10474 Use a consistent scale factor and resolution in stress tests
  examples/stress_tests/many_animated_sprites.rs
  examples/stress_tests/many_buttons.rs
  examples/stress_tests/many_foxes.rs
  examples/stress_tests/many_gizmos.rs
  examples/stress_tests/many_glyphs.rs
  examples/stress_tests/many_lights.rs
  examples/stress_tests/many_sprites.rs
  examples/stress_tests/text_pipeline.rs
Labels: A-Rendering, C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#10494 feat: `Debug` implemented for `AssetMode`
  crates/bevy_asset/src/lib.rs
Labels: C-Enhancement, A-Assets, S-Ready-For-Final-Review

#10483 `#[derive(Reflect)]` on `GizmoConfig`
  crates/bevy_gizmos/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection, A-Gizmos

#10502 Fix shader import hot reloading on windows
  crates/bevy_render/src/render_resource/shader.rs
Labels: C-Bug, A-Rendering, A-Assets

#10516 Remove rogue : from embedded_asset! docs
  crates/bevy_asset/src/io/embedded/mod.rs
Labels: C-Docs, A-Assets, S-Ready-For-Final-Review

#10486 Register `WireframeColor`
  crates/bevy_pbr/src/wireframe.rs
Labels: C-Usability, A-Reflection, A-Gizmos

#10523 use `tree` syntax to explain bevy_rock file structure
  crates/bevy_asset/src/io/embedded/mod.rs
Labels: C-Docs, A-Assets, S-Ready-For-Final-Review

#10448 Rename `Time::<Fixed>::overstep_percentage()` and `Time::<Fixed>::overstep_percentage_f64()`
  crates/bevy_time/src/fixed.rs
Labels: C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, A-Time

#10337 Fix minor issues with custom_asset example
  examples/asset/custom_asset.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#10493 Make AssetLoader/Saver Error type bounds compatible with anyhow::Error
  crates/bevy_asset/src/loader.rs
  crates/bevy_asset/src/processor/process.rs
  crates/bevy_asset/src/saver.rs
Labels: A-Assets, S-Ready-For-Final-Review, C-Regression

#10540 Fix animations resetting after repeat count
  crates/bevy_animation/src/lib.rs
Labels: C-Bug, C-Regression, A-Animation

#10519 Optimize `Entity::eq`
  benches/Cargo.toml
  benches/benches/bevy_utils/entity_hash.rs
  crates/bevy_ecs/src/entity/mod.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review

#10543 Ignore inactive cameras
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_ui/src/render/mod.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#10542 Add shader_material_2d example
  Cargo.toml
  assets/shaders/custom_material_2d.wgsl
  examples/README.md
  examples/shader/shader_material_2d.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#10514 Fix untyped labeled asset loading
  crates/bevy_asset/src/server/info.rs
  crates/bevy_asset/src/server/mod.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#10555 More inactive camera checks
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/render/light.rs
Labels: A-Rendering, C-Performance, C-Code-Quality, S-Ready-For-Final-Review

#10544 check for all-features with cargo-deny
  deny.toml
Labels: C-Bug, A-Build-System, C-Dependencies, S-Ready-For-Final-Review

#10408 Fix float precision issue in the gizmo shader
  crates/bevy_gizmos/src/lines.wgsl
Labels: C-Bug, S-Ready-For-Final-Review, C-Regression, A-Gizmos

#10560 Fix post processing example to only run effect on camera with settings component
  examples/shader/post_processing.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#10556 Make sure added image assets are checked in camera_system
  crates/bevy_render/src/camera/camera.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#10548 Ensure ExtendedMaterial works with reflection (to enable bevy_egui_inspector integration)
  crates/bevy_pbr/src/extended_material.rs
  examples/shader/extended_material.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#10380 Add 'World::run_system_with_input' function + allow `World::run_system` to get system output
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/system_registry.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review, D-Complex

#10562 Add Debug, PartialEq and Eq derives to bevy_animation.
  crates/bevy_animation/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Animation

#10517 Make FakeTask public on singlethreaded context
  crates/bevy_tasks/src/lib.rs
  crates/bevy_tasks/src/single_threaded_task_pool.rs
Labels: C-Usability, A-Tasks

#10534 Make ButtonSettings.is_pressed/released public
  crates/bevy_input/src/gamepad.rs
Labels: A-Input, C-Usability, S-Ready-For-Final-Review

#10529 Re-export `ron` in `bevy_scene`
  crates/bevy_asset/src/lib.rs
  crates/bevy_scene/Cargo.toml
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_scene/src/scene_loader.rs
  crates/bevy_scene/src/serde.rs
  examples/asset/custom_asset.rs
  examples/asset/processing/asset_processing.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Scenes

#10321 Explicit color conversion methods
  crates/bevy_gltf/src/loader.rs
  crates/bevy_render/src/color/mod.rs
  examples/ui/ui_material.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#10466 Define a basic set of Primitives
  crates/bevy_math/src/lib.rs
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_math/src/primitives/mod.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math

#10526 Add `load_untyped` to LoadContext
  crates/bevy_asset/src/loader.rs
Labels: A-Assets, C-Usability

#10574 fix example custom_asset_reader on wasm
  examples/asset/custom_asset_reader.rs
Labels: C-Examples, A-Assets, O-Web

#10577 support required features in wasm examples showcase
  Cargo.toml
  tools/build-wasm-example/src/main.rs
  tools/example-showcase/src/main.rs
Labels: C-Examples, O-Web

#10551 Update `Event` send methods to return `EventId`
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_gilrs/src/gilrs_system.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_winit/src/lib.rs
  examples/games/game_menu.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#10450 `ReadAssetBytesError::Io` exposes failing path
  crates/bevy_asset/src/loader.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review, C-Breaking-Change

#10564 Document how to configure FixedUpdate
  crates/bevy_app/src/main_schedule.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Time

#10563 Some docs for IntoSystemSet
  crates/bevy_ecs/src/schedule/config.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#10565 Added Method to Allow Pipelined Asset Loading
  Cargo.toml
  assets/data/compressed_image.png.gz
  crates/bevy_asset/src/loader.rs
  examples/README.md
  examples/asset/asset_decompression.rs
Labels: C-Enhancement, A-Assets, S-Ready-For-Final-Review

#10578 Add missing asset load error logs for load_folder and load_untyped
  crates/bevy_asset/src/server/mod.rs
Labels: C-Bug, A-Assets

#10591 Fix panic when using image in UiMaterial
  crates/bevy_ui/src/render/ui_material_pipeline.rs
Labels: C-Bug, C-Crash, A-UI

#10389 Revert `App::run()` behavior/Remove `winit` specific code from `bevy_app`
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_winit/src/lib.rs
Labels: C-Bug, A-Windowing, P-High, A-App

#10608 Add `VolumeLevel::ZERO`
  crates/bevy_audio/src/audio.rs
Labels: A-Audio, C-Usability, S-Ready-For-Final-Review

#10596 Link to `In` in `pipe` documentation
  crates/bevy_ecs/src/system/mod.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#10580 Add and impl Primitives
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math

#10589 Fix wasm builds with file_watcher enabled
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/io/mod.rs
Labels: A-Assets, O-Web, C-Compile-Failure

#10614 Do not panic when failing to create assets folder (#10613)
  crates/bevy_asset/src/io/file/mod.rs
Labels: C-Bug, A-Assets

#10601 examples showcase: use patches instead of sed for wasm hacks
  tools/example-showcase/asset-source-website.patch
  tools/example-showcase/src/main.rs
  tools/example-showcase/window-settings-wasm.patch
Labels: C-Examples, O-Web

#10453 Add discard_overstep function to Time<Fixed>
  crates/bevy_time/src/fixed.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Time

#10619 Use handles for queued scenes in SceneSpawner
  crates/bevy_scene/src/scene_spawner.rs
Labels: A-Assets, S-Ready-For-Final-Review

#10609 add regression test for #10385/#10389
  crates/bevy_app/src/app.rs
Labels: S-Ready-For-Final-Review, C-Testing, A-App

#10558 Optimise `Entity` with repr align & manual `PartialOrd`/`Ord`
  crates/bevy_ecs/src/entity/mod.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review, C-Breaking-Change, D-Complex

#10611 Re-export wgpu BufferAsyncError
  crates/bevy_render/src/render_resource/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#10592 Add `Transform::is_finite`
  crates/bevy_transform/src/components/transform.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Transform

#10585 Fix file_watcher feature hanging indefinitely
  crates/bevy_asset/src/lib.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#10620 Add winding order for `Triangle2d`
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/mod.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math

#10631 Move Circle Gizmos to Their Own File
  crates/bevy_gizmos/src/arrows.rs
  crates/bevy_gizmos/src/circles.rs
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_gizmos/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change, A-Gizmos

#10547 Improve shader_material example
  assets/shaders/custom_material.frag
  assets/shaders/custom_material.wgsl
  examples/shader/shader_material.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#10663 Fix Line for tracy version
  docs/profiling.md
Labels: C-Docs, S-Ready-For-Final-Review, A-Diagnostics

#10594 Standardize toml format with taplo
  .github/workflows/ci.yml
  CONTRIBUTING.md
  crates/bevy_animation/Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_audio/Cargo.toml
  crates/bevy_core/Cargo.toml
  crates/bevy_core_pipeline/Cargo.toml
  crates/bevy_diagnostic/Cargo.toml
  crates/bevy_gltf/Cargo.toml
  crates/bevy_hierarchy/Cargo.toml
  crates/bevy_input/Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_log/Cargo.toml
  crates/bevy_macros_compile_fail_tests/Cargo.toml
  crates/bevy_mikktspace/Cargo.toml
  crates/bevy_pbr/Cargo.toml
  crates/bevy_reflect/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_scene/Cargo.toml
  crates/bevy_sprite/Cargo.toml
  crates/bevy_text/Cargo.toml
  crates/bevy_time/Cargo.toml
  crates/bevy_transform/Cargo.toml
  crates/bevy_ui/Cargo.toml
  crates/bevy_window/Cargo.toml
  crates/bevy_winit/Cargo.toml
  deny.toml
  docs/profiling.md
  tools/build-templated-pages/Cargo.toml
Labels: A-Build-System, C-Code-Quality, A-Meta, S-Ready-For-Final-Review

#10410 derive asset for enums
  crates/bevy_asset/macros/src/lib.rs
  crates/bevy_asset/src/lib.rs
Labels: C-Enhancement, A-Assets, S-Ready-For-Final-Review

#10561 Allow #[derive(Bundle)] on tuple structs (take 3)
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_macro_utils/src/shape.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#10598 bevy_hierarchy: add some docs
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_hierarchy/src/components/children.rs
  crates/bevy_hierarchy/src/components/parent.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Hierarchy

#10628 Ensure consistency between Un/Typed `AssetId` and `Handle`
  crates/bevy_asset/src/handle.rs
  crates/bevy_asset/src/id.rs
Labels: C-Bug, A-Assets, C-Code-Quality, S-Ready-For-Final-Review

#10638 Fix load scene example to use proper serialization format for rotation field
  assets/scenes/load_scene_example.scn.ron
Labels: C-Bug, C-Examples, S-Ready-For-Final-Review, A-Scenes

#10640 Add doc_markdown clippy linting config to cargo workspace
  Cargo.toml
  tools/ci/src/main.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#10650 Add an `Entry` api to `EntityWorldMut`.
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Complex

#10651 Make impl block for RemovedSystem generic
  crates/bevy_ecs/src/system/system_registry.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#10643 Use minor and major radii for `Torus` primitive shape
  crates/bevy_math/src/primitives/dim3.rs
Labels: C-Docs, C-Usability, S-Ready-For-Final-Review, A-Math

#10646 Enable `clippy::undocumented_unsafe_blocks` warning across the workspace
  Cargo.toml
  crates/bevy_animation/src/lib.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_mikktspace/src/lib.rs
  crates/bevy_ptr/src/lib.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_resource/resource_macros.rs
  crates/bevy_render/src/view/window/mod.rs
  crates/bevy_tasks/src/task_pool.rs
  crates/bevy_transform/src/lib.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_utils/src/lib.rs
  crates/bevy_window/src/raw_handle.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#10670 Re-export `futures_lite` in `bevy_tasks`
  crates/bevy_tasks/src/lib.rs
  examples/async_tasks/async_compute.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Tasks

#10400 Append commands
  crates/bevy_ecs/src/system/commands/command_queue.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  examples/async_tasks/async_compute.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#10698 Fix Asset Loading Bug
  crates/bevy_asset/src/id.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#10370 Bumps async crates requirements to latest major version
  crates/bevy_asset/Cargo.toml
Labels: C-Dependencies, S-Ready-For-Final-Review

#10454 Make clipped areas of UI nodes non-interactive
  crates/bevy_ui/src/focus.rs
  examples/ui/overflow.rs
Labels: C-Bug, A-UI, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#10660 move gizmo arcs to their own file
  crates/bevy_gizmos/src/arcs.rs
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_gizmos/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change, A-Gizmos

#10674 Non uniform transmission samples
  crates/bevy_pbr/src/render/pbr_transmission.wgsl
Labels: A-Rendering, C-Crash, S-Ready-For-Final-Review, O-WebGPU

#10682 Rustdoc example for Ref
  crates/bevy_ecs/src/change_detection.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#10691 Link to `Main` schedule docs from other schedules
  crates/bevy_app/src/main_schedule.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#10681 Warn that Added/Changed filters do not see deferred changes
  crates/bevy_ecs/src/query/filter.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#10705 Fix issue with `Option` serialization
  crates/bevy_reflect/Cargo.toml
  crates/bevy_reflect/src/serde/ser.rs
Labels: C-Bug, A-Reflection

#10712 Explain how `AmbientLight` is inserted and configured
  crates/bevy_pbr/src/light.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#10675 bump bevy_tasks futures-lite to 2.0.1
  Cargo.toml
  crates/bevy_asset/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_tasks/Cargo.toml
Labels: C-Dependencies, S-Ready-For-Final-Review, A-Tasks

#10693 delete methods deprecated in 0.12
  crates/bevy_app/src/app.rs
  crates/bevy_asset/src/path.rs
  crates/bevy_ecs/README.md
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/reflect/entity_commands.rs
  crates/bevy_ecs/src/removal_detection.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_reflect/src/reflect.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#10723 Remove trailing whitespace
  crates/bevy_asset/Cargo.toml
  crates/bevy_render/Cargo.toml
Labels: A-Build-System, S-Ready-For-Final-Review

#10721 Make bevy_app and reflect opt-out for bevy_hierarchy.
  crates/bevy_hierarchy/Cargo.toml
  crates/bevy_hierarchy/src/components/children.rs
  crates/bevy_hierarchy/src/components/parent.rs
  crates/bevy_hierarchy/src/lib.rs
  crates/bevy_hierarchy/src/valid_parent_check_plugin.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Hierarchy

#10722 Add wgpu_pass method to TrackedRenderPass
  crates/bevy_render/src/render_phase/draw_state.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#10730 Fix typo in resolve_outlines_system
  crates/bevy_ui/src/layout/mod.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#10683 Add a `depth_bias` to `Material2d`
  crates/bevy_sprite/src/mesh2d/material.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#10714 Some explanations for Window component
  crates/bevy_window/src/window.rs
Labels: C-Docs, A-Windowing, S-Ready-For-Final-Review

#10719 Fix non-functional nondeterministic_system_order example
  examples/ecs/nondeterministic_system_order.rs
Labels: A-ECS, C-Examples, S-Ready-For-Final-Review

#10496 bevy_utils: Export `generate_composite_uuid` utility function
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/type_uuid.rs
  crates/bevy_utils/src/lib.rs
  crates/bevy_utils/src/uuid.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Utils

#10741 don't run update before window creation in winit
  crates/bevy_winit/src/lib.rs
Labels: C-Bug, A-Windowing

#10733 Use as_image_copy where possible
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
Labels: A-Rendering, C-Code-Quality

#10734 impl From<Color> for ClearColorConfig
  crates/bevy_core_pipeline/src/clear_color.rs
  examples/3d/render_to_texture.rs
  examples/shader/post_processing.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#10735 add new event `WindowOccluded` from winit
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/src/lib.rs
Labels: A-Windowing, C-Dependencies

#10077 Wait until `FixedUpdate` can see events before dropping them
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_time/src/lib.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, A-Time

#10748 Copy over docs for `Condition` trait from PR #10718
  crates/bevy_ecs/src/schedule/condition.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#10758 Ran `cargo fmt` on `benches` crate
  benches/benches/bevy_utils/entity_hash.rs
Labels: C-Code-Quality

#10623 AssetMetaMode
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/server/mod.rs
Labels: C-Bug, A-Assets

#10746 Implement `Drop` for `CommandQueue`
  crates/bevy_ecs/src/system/commands/command_queue.rs
Labels: C-Bug, A-ECS, C-Performance, S-Ready-For-Final-Review

#10745 Fix GLTF scene dependencies and make full scene renders predictable
  crates/bevy_asset/src/loader.rs
  crates/bevy_asset/src/server/info.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_gltf/src/loader.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#10627 fix `insert_reflect` panic caused by `clone_value`
  crates/bevy_ecs/src/reflect/entity_commands.rs
Labels: C-Bug, A-Reflection

#9918 Split WorldQuery into WorldQueryData and WorldQueryFilter
  crates/bevy_core/src/name.rs
  crates/bevy_ecs/macros/src/fetch.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/macros/src/world_query.rs
  crates/bevy_ecs/macros/src/world_query_data.rs
  crates/bevy_ecs/macros/src/world_query_filter.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/query/world_query.rs
  crates/bevy_ecs/src/system/exclusive_system_param.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_iter_combinations_mut_iterator_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_iter_many_mut_iterator_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/system_param_derive_readonly.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/world_query_derive.rs
  crates/bevy_ecs_compile_fail_tests/tests/ui/world_query_derive.stderr
  crates/bevy_hierarchy/src/query_extension.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/extract_component.rs
  crates/bevy_render/src/extract_instances.rs
  crates/bevy_render/src/render_graph/node.rs
  crates/bevy_render/src/render_phase/draw.rs
  crates/bevy_ui/src/focus.rs
  examples/ecs/custom_query_param.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, D-Complex

#10224 Bind group layout entries
  crates/bevy_core_pipeline/src/blit/mod.rs
  crates/bevy_core_pipeline/src/bloom/downsampling_pipeline.rs
  crates/bevy_core_pipeline/src/bloom/upsampling_pipeline.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_core_pipeline/src/deferred/copy_lighting_id.rs
  crates/bevy_core_pipeline/src/fxaa/mod.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/environment_map/mod.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass_bindings.rs
  crates/bevy_pbr/src/render/mesh_bindings.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/render_resource/bind_group_layout_entries.rs
  crates/bevy_render/src/render_resource/gpu_array_buffer.rs
  crates/bevy_render/src/render_resource/mod.rs
  crates/bevy_render/src/renderer/render_device.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/pipeline.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  examples/shader/compute_shader_game_of_life.rs
  examples/shader/post_processing.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#10672 Move remaining clippy lint definitions to Cargo.toml
  Cargo.toml
  tools/ci/src/main.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#10684 Add `clippy::manual_let_else` at warn level to lints
  Cargo.toml
  crates/bevy_asset/src/reflect.rs
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_core_pipeline/src/core_2d/main_pass_2d_node.rs
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/fxaa/mod.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/node.rs
  crates/bevy_core_pipeline/src/upscaling/node.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_reflect/bevy_reflect_derive/src/type_uuid.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/render/mod.rs
  examples/shader/shader_instancing.rs
  examples/stress_tests/many_lights.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#10739 Provide GlobalsUniform in UiMaterial shaders
  crates/bevy_ui/src/render/ui_material.wgsl
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/ui_material.rs
Labels: A-Rendering, A-UI, C-Usability, S-Ready-For-Final-Review

#10485 Swap material and mesh bind groups
  assets/shaders/array_texture.wgsl
  assets/shaders/circle_shader.wgsl
  assets/shaders/cubemap_unlit.wgsl
  assets/shaders/custom_material.frag
  assets/shaders/custom_material.vert
  assets/shaders/custom_material.wgsl
  assets/shaders/custom_material_screenspace_texture.wgsl
  assets/shaders/custom_vertex_attribute.wgsl
  assets/shaders/extended_material.wgsl
  assets/shaders/fallback_image_test.wgsl
  assets/shaders/line_material.wgsl
  assets/shaders/shader_defs.wgsl
  assets/shaders/show_prepass.wgsl
  assets/shaders/texture_binding_array.wgsl
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass_bindings.wgsl
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_bindings.wgsl
  crates/bevy_pbr/src/render/morph.wgsl
  crates/bevy_pbr/src/render/pbr_bindings.wgsl
  crates/bevy_pbr/src/render/skinning.wgsl
  crates/bevy_pbr/src/render/wireframe.wgsl
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_sprite/src/mesh2d/color_material.wgsl
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh2d_bindings.wgsl
  examples/2d/mesh2d_manual.rs
  examples/shader/shader_instancing.rs
  examples/shader/texture_binding_array.rs
Labels: A-Rendering, C-Performance, C-Breaking-Change

#10484 Reflect and register audio-related types
  crates/bevy_audio/src/audio.rs
  crates/bevy_audio/src/lib.rs
Labels: A-Audio, C-Usability, S-Ready-For-Final-Review, A-Reflection

#10780 Mention DynamicSceneBuilder in doc comment
  crates/bevy_scene/src/dynamic_scene.rs
Labels: C-Docs, A-Scenes

#10771 Remove pointless trait implementation exports in `bevy_reflect`
  crates/bevy_reflect/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Reflection

#10787 Print precise and correct watch warnings (and only when necessary)
  crates/bevy_asset/src/io/embedded/mod.rs
  crates/bevy_asset/src/io/source.rs
Labels: C-Bug, A-Assets

#10791 Fix nested generics in Reflect derive
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
  crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/nested.pass.rs
Labels: C-Bug, A-Reflection

#10624 Make IntoSystemConfigs::into_configs public API (visible in docs)
  crates/bevy_ecs/src/schedule/config.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#10801 try_insert Aabbs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_sprite/src/lib.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#10788 Fix prepass binding issues causing crashes when not all prepass bindings are used
  crates/bevy_pbr/src/prepass/prepass_bindings.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#10785 Allow removing and reloading assets with live handles
  crates/bevy_asset/src/assets.rs
Labels: C-Bug, A-Assets

#10804 Add GltfLoaderSettings
  crates/bevy_gltf/src/loader.rs
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#10441 Mention DynamicSceneBuilder in scene example
  examples/scene/scene.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Scenes
