Repository bevyengine/bevy, pull requests merged in 2023-06, with the labels that each got.

#8732 Use ViewNode for TAA
  crates/bevy_core_pipeline/src/taa/mod.rs
Labels: A-Rendering, C-Code-Quality

#8728 update bitflags to 2.3
  crates/bevy_core_pipeline/Cargo.toml
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/texture/image.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_sprite/Cargo.toml
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  tools/build-templated-pages/Cargo.toml
  tools/build-templated-pages/src/main.rs
  tools/ci/Cargo.toml
  tools/ci/src/main.rs
Labels: C-Dependencies, S-Ready-For-Final-Review

#8723 bevy_reflect: Allow construction of MapIter outside of the bevy_reflect crate.
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/map.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Reflection

#8734 Update cargo deny configuration
  crates/bevy_diagnostic/Cargo.toml
  deny.toml
Labels: A-Build-System, C-Dependencies, S-Ready-For-Final-Review

#8738 Resolve clippy issues for rust 1.70.0
  crates/bevy_ecs/macros/src/fetch.rs
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_to_readonly.stderr
  crates/bevy_render/src/render_resource/pipeline_cache.rs
Labels: A-Build-System, C-Code-Quality

#8739 remove some use of once_cell that can be replace with new std
  Cargo.toml
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/src/usages.rs
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/lib.rs
Labels: C-Dependencies

#8691 Add get_at_mut to bevy_reflect::Map trait
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/map.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Reflection

#8726 Rename apply_system_buffers to apply_deferred
  Cargo.toml
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_transform/src/commands.rs
  examples/README.md
  examples/ecs/apply_deferred.rs
  examples/ecs/removal_detection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#8743 Fix all_tuples + added docs.
  crates/bevy_utils/macros/src/lib.rs
Labels: C-Bug, C-Docs, A-ECS, C-Code-Quality

#8736 Update B0003 error docs to stageless
  errors/B0003.md
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#8753 Change Camera3dBundle::tonemapping to Default
  crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#8677 Allow systems using Diagnostics to run in parallel
  crates/bevy_asset/src/diagnostic/asset_count_diagnostics_plugin.rs
  crates/bevy_diagnostic/src/diagnostic.rs
  crates/bevy_diagnostic/src/entity_count_diagnostics_plugin.rs
  crates/bevy_diagnostic/src/frame_time_diagnostics_plugin.rs
  crates/bevy_diagnostic/src/lib.rs
  crates/bevy_diagnostic/src/log_diagnostics_plugin.rs
  crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs
  examples/diagnostics/custom_diagnostic.rs
  examples/stress_tests/bevymark.rs
  examples/stress_tests/many_gizmos.rs
  examples/ui/text.rs
  examples/ui/text_debug.rs
Labels: C-Enhancement, C-Performance, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, A-Diagnostics

#8740 correctly setup everything in the default run_once runner
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/app.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-App

#8752 Mention that default spawned primary window is spawned with `PrimaryWindow` marker component
  crates/bevy_window/src/lib.rs
Labels: C-Docs, A-Windowing, S-Ready-For-Final-Review

#8593 Support to set window theme and expose system window theme changed event
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/converters.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/window/window_settings.rs
Labels: C-Enhancement, A-Windowing, S-Ready-For-Final-Review

#8761 bevy_reflect: Disambiguate type bounds in where clauses.
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
  crates/bevy_reflect/src/lib.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Reflection

#7086 Require `#[derive(Event)]` on all Events
  benches/benches/bevy_ecs/events/iter.rs
  benches/benches/bevy_ecs/events/send.rs
  crates/bevy_a11y/src/lib.rs
  crates/bevy_app/src/app.rs
  crates/bevy_asset/src/assets.rs
  crates/bevy_ecs/README.md
  crates/bevy_ecs/examples/events.rs
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/removal_detection.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_hierarchy/src/events.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input/src/keyboard.rs
  crates/bevy_input/src/mouse.rs
  crates/bevy_input/src/touch.rs
  crates/bevy_window/src/event.rs
  crates/bevy_winit/src/accessibility.rs
  examples/async_tasks/external_source_external_thread.rs
  examples/ecs/event.rs
  examples/games/breakout.rs
  examples/ui/size_constraints.rs
  tests/how_to_test_systems.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, S-Controversial

#8764 Reflect now requires DynamicTypePath. Remove Reflect::get_type_path()
  crates/bevy_reflect/bevy_reflect_derive/src/impls/enums.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/tuple_structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/values.rs
  crates/bevy_reflect/src/array.rs
  crates/bevy_reflect/src/enums/dynamic_enum.rs
  crates/bevy_reflect/src/impls/smallvec.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/list.rs
  crates/bevy_reflect/src/map.rs
  crates/bevy_reflect/src/reflect.rs
  crates/bevy_reflect/src/struct_trait.rs
  crates/bevy_reflect/src/tuple.rs
  crates/bevy_reflect/src/tuple_struct.rs
  crates/bevy_reflect/src/type_info.rs
  crates/bevy_reflect/src/type_path.rs
  crates/bevy_reflect/src/utility.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Reflection

#8760 skip check change tick for apply_deferred systems
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, A-Diagnostics

#8791 Touchpad magnify and rotate events
  crates/bevy_input/src/lib.rs
  crates/bevy_input/src/touchpad.rs
  crates/bevy_winit/src/lib.rs
  examples/input/mouse_input_events.rs
Labels: C-Enhancement, A-Windowing, O-MacOS, S-Ready-For-Final-Review

#8771 bevy_reflect: implement Reflect for SmolStr
  crates/bevy_reflect/Cargo.toml
  crates/bevy_reflect/src/impls/smol_str.rs
  crates/bevy_reflect/src/lib.rs
Labels: A-Windowing, C-Usability, S-Ready-For-Final-Review, A-Reflection

#8796 Fix errors in the doc comment for `UiSurface::upsert_node`.
  crates/bevy_ui/src/layout/mod.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#8795 Perform `relative_cursor_position` calculation vectorwise in `ui_focus_system`
  crates/bevy_ui/src/focus.rs
Labels: A-UI, C-Code-Quality, S-Ready-For-Final-Review

#8801 Implement Reflect on NoFrustumCulling
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/visibility/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, A-Reflection

#8802 Disable camera on window close
  crates/bevy_render/src/camera/camera_driver_node.rs
Labels: A-Rendering, A-Windowing, C-Usability

#8804 Remove `Component` derive for AlphaMode
  crates/bevy_pbr/src/alpha.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#8731 Document every public item in `bevy_ecs`
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/reflect.rs
  crates/bevy_ecs/src/removal_detection.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/graph_utils.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/schedule/state.rs
  crates/bevy_ecs/src/storage/sparse_set.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/commands/parallel_scope.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/exclusive_system_param.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/error.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/spawn_batch.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_ecs/src/world/world_cell.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#8797 Add `new` and `map` methods to `Ref`
  crates/bevy_ecs/src/change_detection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#8807 Register a few missed reflect components
  crates/bevy_core_pipeline/src/fxaa/mod.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/render/fog.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_window/src/lib.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Reflection

#8772 Add iter_many_manual QueryState method
  crates/bevy_ecs/src/query/state.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#8817 Allow unsized types as mapped value in `Ref::map`
  crates/bevy_ecs/src/change_detection.rs
Labels: C-Bug, A-ECS, C-Usability, S-Ready-For-Final-Review

#8803 Add last_changed_tick and added_tick to ComponentTicks
  crates/bevy_ecs/src/component.rs
Labels: C-Enhancement, A-ECS

#8814 Rename Command's "write" method to "apply"
  benches/benches/bevy_ecs/world/commands.rs
  crates/bevy_ecs/src/system/commands/command_queue.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_hierarchy/src/hierarchy.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_transform/src/commands.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#7984 Add integer equivalents for `Rect`
  crates/bevy_math/src/lib.rs
  crates/bevy_math/src/rects/irect.rs
  crates/bevy_math/src/rects/mod.rs
  crates/bevy_math/src/rects/rect.rs
  crates/bevy_math/src/rects/urect.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math

#8830 Remove stray boilerplate line in `bevy_dynamic_plugin/Cargo.toml`
  crates/bevy_dynamic_plugin/Cargo.toml
Labels: C-Code-Quality, S-Ready-For-Final-Review

#8408 Make setup of Opaque3dPrepass and AlphaMask3dPrepass phase items consistent with others
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_pbr/src/prepass/mod.rs
Labels: C-Bug, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#8744 Rename `Plane` struct to `HalfSpace`
  crates/bevy_pbr/src/light.rs
  crates/bevy_render/src/primitives/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#8747 Fix documentation of `SubApp` `extract`
  crates/bevy_app/src/app.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#8819 Initialize `DiagnosticStore` on `register_diagnostic` if it does not exist
  crates/bevy_diagnostic/src/diagnostic.rs
Labels: C-Bug, C-Examples, S-Ready-For-Final-Review, A-Diagnostics

#8826 Implement `Clone` for `CombinatorSystem`
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#8832 Require read-only queries in `QueryState::par_iter`
  crates/bevy_ecs/src/query/state.rs
Labels: C-Bug, A-ECS, P-High, C-Breaking-Change, C-Unsoundness

#8427 Instanced line rendering for gizmos based on `bevy_polyline`
  crates/bevy_gizmos/Cargo.toml
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gizmos/src/lines.wgsl
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_internal/Cargo.toml
  examples/2d/2d_gizmos.rs
  examples/3d/3d_gizmos.rs
  examples/stress_tests/many_gizmos.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#8818 Add get_ref to EntityRef
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review

#8837 Rename a leftover usage of a renamed function `read_change_tick`
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: C-Docs, A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#7795 Ui Node Borders
  Cargo.toml
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/ui_node.rs
  examples/README.md
  examples/ui/borders.rs
  examples/ui/button.rs
  examples/ui/ui.rs
  examples/ui/viewport_debug.rs
Labels: C-Enhancement, A-UI, S-Ready-For-Final-Review

#8792 Rename keys like `LAlt` to `AltLeft`
  crates/bevy_input/src/keyboard.rs
  crates/bevy_winit/src/converters.rs
  examples/3d/fog.rs
  examples/3d/shadow_biases.rs
  examples/3d/skybox.rs
  examples/input/keyboard_modifiers.rs
  examples/tools/scene_viewer/camera_controller_plugin.rs
Labels: A-Input, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#8833 Migrate the rest of the engine to `UnsafeWorldCell`
  benches/benches/bevy_ecs/world/world_get.rs
  crates/bevy_ecs/macros/src/fetch.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#8845 Simplify the `ComponentIdFor` type
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/removal_detection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#8848 Make `QueryParIter::for_each_unchecked` private
  crates/bevy_ecs/src/query/par_iter.rs
Labels: A-ECS, S-Ready-For-Final-Review, C-Breaking-Change, C-Unsoundness

#8849 Add a method to run read-only systems using `&World`
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/system/system.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review

#8852 Add window entity to mouse and keyboard events
  crates/bevy_input/src/keyboard.rs
  crates/bevy_input/src/mouse.rs
  crates/bevy_winit/src/converters.rs
  crates/bevy_winit/src/lib.rs
Labels: A-Input, C-Usability, S-Ready-For-Final-Review

#8881 doc: update a reference from add_system to add_systems
  crates/bevy_ecs/src/system/system.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#7402 Screen Space Ambient Occlusion (SSAO) MVP
  Cargo.toml
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.wgsl
  crates/bevy_pbr/src/render/pbr.wgsl
  crates/bevy_pbr/src/render/pbr_ambient.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/utils.wgsl
  crates/bevy_pbr/src/ssao/gtao.wgsl
  crates/bevy_pbr/src/ssao/gtao_utils.wgsl
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_pbr/src/ssao/preprocess_depth.wgsl
  crates/bevy_pbr/src/ssao/spatial_denoise.wgsl
  crates/bevy_render/src/view/mod.rs
  examples/3d/ssao.rs
  examples/README.md
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, D-Complex

#8834 Split the bevy_ecs reflect.rs module
  crates/bevy_ecs/src/reflect.rs
  crates/bevy_ecs/src/reflect/component.rs
  crates/bevy_ecs/src/reflect/map_entities.rs
  crates/bevy_ecs/src/reflect/mod.rs
  crates/bevy_ecs/src/reflect/resource.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, A-Reflection

#8889 Small doc fix
  examples/ecs/apply_deferred.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#8042 Add `RenderTarget::TextureView`
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/manual_texture_view.rs
  crates/bevy_render/src/camera/mod.rs
  crates/bevy_render/src/view/mod.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, O-XR, C-Breaking-Change

#8844 Added Has<T> WorldQuery type
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/mod.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review

#8866 Add `UiRect::px()` and `UiRect::percent()` utils
  crates/bevy_ui/src/geometry.rs
  crates/bevy_ui/src/ui_node.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#8687 Make function pointers of ecs Reflect* public
  crates/bevy_ecs/src/reflect/component.rs
  crates/bevy_ecs/src/reflect/resource.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review, A-Reflection

#8891 Do not require mut on ParsedPath::element_mut
  crates/bevy_reflect/src/path.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Reflection

#8776 Add FromReflect where Reflect is used
  crates/bevy_asset/src/handle.rs
  crates/bevy_asset/src/path.rs
  crates/bevy_core/src/name.rs
  crates/bevy_core_pipeline/src/bloom/settings.rs
  crates/bevy_core_pipeline/src/clear_color.rs
  crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
  crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_gltf/src/lib.rs
  crates/bevy_hierarchy/src/components/children.rs
  crates/bevy_hierarchy/src/components/parent.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input/src/input.rs
  crates/bevy_input/src/keyboard.rs
  crates/bevy_input/src/lib.rs
  crates/bevy_input/src/mouse.rs
  crates/bevy_input/src/touch.rs
  crates/bevy_pbr/src/alpha.rs
  crates/bevy_pbr/src/bundle.rs
  crates/bevy_pbr/src/fog.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/projection.rs
  crates/bevy_render/src/mesh/mesh/skinning.rs
  crates/bevy_render/src/primitives/mod.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_transform/src/components/global_transform.rs
  crates/bevy_transform/src/components/transform.rs
  crates/bevy_ui/src/measurement.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/text.rs
  crates/bevy_window/src/cursor.rs
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/window.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#8822 UI texture atlas support
  Cargo.toml
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/image.rs
  examples/README.md
  examples/ui/ui_texture_atlas.rs
Labels: C-Enhancement, A-Rendering, A-UI, S-Ready-For-Final-Review

#8843 Deprecate type aliases for `WorldQuery::Fetch`
  crates/bevy_ecs/src/query/fetch.rs
Labels: A-ECS, C-Breaking-Change

#8893 Add missing inline documentation for android code
  crates/bevy_asset/src/io/android_asset_io.rs
  crates/bevy_winit/src/lib.rs
Labels: C-Docs, O-Android

#6974 Expand `FallbackImage` to include a `GpuImage` for each possible `TextureViewDimension`
  Cargo.toml
  assets/shaders/fallback_image_test.wgsl
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/src/texture/fallback_image.rs
  examples/shader/fallback_image.rs
  examples/shader/texture_binding_array.rs
Labels: C-Bug, A-Rendering, C-Usability

#8871 Add get_unclamped to Axis
  crates/bevy_input/src/axis.rs
Labels: A-Input, C-Usability, S-Ready-For-Final-Review

#7629 UI Display and Visibility Example
  Cargo.toml
  examples/README.md
  examples/ui/display_and_visibility.rs
Labels: C-Examples, A-UI, S-Ready-For-Final-Review

#8886 log to stderr instead of stdout
  crates/bevy_log/src/lib.rs
Labels: C-Bug, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, A-Diagnostics

#8903 Fix windows not being centered properly when system interface is scaled
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review

#8885 Providing a better example for Mesh-building in docs.
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#8890 fix normal prepass
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/pbr.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#8905 Reflect UUID
  crates/bevy_reflect/src/impls/uuid.rs
  crates/bevy_reflect/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#8907 Remove "bevy_text" feature attributes on imports used by non-text systems
  crates/bevy_ui/src/render/mod.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#8877 Cascaded shadow maps: Fix prepass ortho depth clamping
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass.wgsl
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
Labels: C-Bug, A-Rendering

#8793 Improved UI render batching
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/pipeline.rs
  crates/bevy_ui/src/render/ui.wgsl
Labels: A-Rendering, C-Performance, A-UI

#8868 Fix AsBindGroup derive, texture attribute, visibility flag parsing
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/src/render_resource/bind_group.rs
Labels: C-Bug, A-Rendering

#8858 Update and improve Window Documentation
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_window/src/cursor.rs
  crates/bevy_window/src/window.rs
Labels: C-Docs, A-Windowing, S-Ready-For-Final-Review

#8920 Add missing dependencies to `bevy_text` feature
  Cargo.toml
Labels: A-UI, S-Ready-For-Final-Review

#8910 Fix gizmos in WebGPU
  crates/bevy_gizmos/src/lib.rs
Labels: C-Bug, A-Rendering, O-Web, S-Ready-For-Final-Review

#8158 Add morph targets
  CREDITS.md
  Cargo.toml
  assets/models/animated/MorphStressTest.gltf
  crates/bevy_animation/Cargo.toml
  crates/bevy_animation/src/lib.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_gltf/Cargo.toml
  crates/bevy_gltf/src/loader.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass.wgsl
  crates/bevy_pbr/src/prepass/prepass_bindings.wgsl
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh.wgsl
  crates/bevy_pbr/src/render/mesh_bindings.rs
  crates/bevy_pbr/src/render/mesh_bindings.wgsl
  crates/bevy_pbr/src/render/mesh_types.wgsl
  crates/bevy_pbr/src/render/mod.rs
  crates/bevy_pbr/src/render/morph.rs
  crates/bevy_pbr/src/render/morph.wgsl
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/mesh/mod.rs
  crates/bevy_render/src/mesh/morph.rs
  examples/README.md
  examples/animation/morph_targets.rs
  examples/tools/scene_viewer/animation_plugin.rs
  examples/tools/scene_viewer/main.rs
  examples/tools/scene_viewer/morph_viewer_plugin.rs
  examples/tools/scene_viewer/scene_viewer_plugin.rs
Labels: C-Enhancement, A-Rendering, A-Animation

#7614 Bias texture mipmaps
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_pbr/src/render/pbr.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/view.wgsl
Labels: C-Enhancement, A-Rendering

#6960 Implement WorldQuery for EntityRef
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/query.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#8928 Change `despawn_descendants` to return `&mut Self`
  crates/bevy_hierarchy/src/hierarchy.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Hierarchy

#8545 Apply scale factor to `ImageMeasure` sizes
  crates/bevy_ui/src/widget/image.rs
Labels: C-Bug, A-Rendering, A-UI, S-Ready-For-Final-Review

#8939 Fix any_component_removed
  crates/bevy_ecs/src/schedule/condition.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#8909 Add example to demonstrate manual generation and UV mapping of 3D mesh (generate_custom_mesh) solve #4922
  Cargo.toml
  examples/3d/generate_custom_mesh.rs
  examples/README.md
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#8940 fix example grid
  examples/ui/grid.rs
Labels: C-Examples, A-UI, S-Ready-For-Final-Review

#8933 Fix WebGPU error in "ui_pipeline" by adding a flat interpolate attribute
  crates/bevy_ui/src/render/ui.wgsl
Labels: C-Bug, A-Rendering, A-UI, O-Web, S-Ready-For-Final-Review

#8947 `NoWrap` `Text` feature
  crates/bevy_text/src/text.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/measurement.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/widget/text.rs
  examples/ui/text_wrap_debug.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#8960 Use AHash to get color from entity in bevy_gizmos
  crates/bevy_gizmos/src/lib.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Gizmos

#8951 Add/fix `track_caller` attribute on panicking entity accessor methods
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#8454 blend_modes example: fix label position
  examples/3d/blend_modes.rs
Labels: C-Examples

#7112 Don't ignore additional entries in `UntypedReflectDeserializerVisitor`
  crates/bevy_reflect/src/serde/de.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Reflection, C-Breaking-Change

#8957 reflect: avoid deadlock in `GenericTypeCell`
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/utility.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Reflection

#8968 Fix fallback_image example
  assets/shaders/fallback_image_test.wgsl
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#8970 Remove unnecessary required feature metadata for tonemapping example
  Cargo.toml
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#8977 Refs #8975 -- Add return to RenderDevice::poll()
  crates/bevy_render/src/renderer/render_device.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#8990 Fix typo in Archetypes documentation
  crates/bevy_ecs/src/archetype.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#8982 Relax `FnMut` to `FnOnce` in `app::edit_schedule`
  crates/bevy_app/src/app.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, A-App

#8978 fix prepass normal_mapping
  assets/shaders/array_texture.wgsl
  crates/bevy_pbr/src/render/pbr.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
Labels: C-Bug, A-Rendering

#8952 Add option to disable gizmo rendering for specific cameras
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_render/src/camera/camera.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, A-Gizmos

#8961 Relaxed runner type from `Fn` to `FnOnce`
  crates/bevy_app/src/app.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-App

#8987 Provide access to world storages via `UnsafeWorldCell`
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: C-Enhancement, A-ECS

#8508 Fix WebGL mode for Adreno GPUs
  crates/bevy_pbr/src/render/light.rs
Labels: C-Bug, A-Rendering, C-Crash, O-Web, O-Android, S-Controversial

#8993 Fix CAS shader with explicit FullscreenVertexOutput import
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/robust_contrast_adaptive_sharpening.wgsl
Labels: C-Bug, A-Rendering

#8999 Simplify setup_scene_once_loaded in animated_fox
  examples/animation/animated_fox.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review, A-Animation
