Repository bevyengine/bevy, pull requests merged in 2023-03, with the labels that each got.

#7945 Fix broken code behind wasm feature flag in blend_modes example
  examples/3d/blend_modes.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#7953 Upgrade Taffy to 0.3.4
  crates/bevy_ui/Cargo.toml
Labels: C-Bug, A-UI

#7947 remove bors and small CI improvements
  .github/bors.toml
  .github/workflows/ci.yml
  .github/workflows/dependencies.yml
  .github/workflows/validation-jobs.yml
  CONTRIBUTING.md
  docs/the_bevy_organization.md
Labels: A-Build-System, S-Ready-For-Final-Review

#7934 Clarify breaking release frequency
  README.md
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review, S-Controversial

#7962 Update contributing guide to refer to roles instead of people
  CONTRIBUTING.md
Labels: C-Docs, A-Meta

#7980 Small Fix: Add an escape character to avoid blockquote
  crates/bevy_core_pipeline/src/bloom/settings.rs
Labels: C-Bug, C-Docs

#7983 Small fix: Change ">" to "Greater than"
  crates/bevy_core_pipeline/src/bloom/settings.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#7988 Move cursor position to internal state
  crates/bevy_window/src/window.rs
Labels: A-Windowing, C-Usability, S-Ready-For-Final-Review

#7966 Set cursor hittest during window creation
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review

#7964 Make `WorldQuery` meta types unnameable
  crates/bevy_ecs/macros/src/fetch.rs
  crates/bevy_ecs/src/query/fetch.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#7931 Add a public constructor for `Mut<T>`
  crates/bevy_ecs/src/change_detection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#7770 Document bevy_ecs::storage
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/storage/blob_vec.rs
  crates/bevy_ecs/src/storage/mod.rs
  crates/bevy_ecs/src/storage/resource.rs
  crates/bevy_ecs/src/storage/sparse_set.rs
  crates/bevy_ecs/src/storage/table.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#7997 Fix typo in utility.rs
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Reflection

#7930 Add methods for calculating the size and postion of UI nodes
  crates/bevy_ui/src/ui_node.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#8002 Update trybuild tests for Rust 1.68
  crates/bevy_ecs_compile_fail_tests/tests/ui/world_query_derive.stderr
  crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/generics.fail.stderr
Labels: A-Build-System, P-High, S-Ready-For-Final-Review

#7905 Increase type safety and clarity for change detection
  crates/bevy_ecs/macros/src/fetch.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/removal_detection.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/storage/resource.rs
  crates/bevy_ecs/src/storage/sparse_set.rs
  crates/bevy_ecs/src/storage/table.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/identifier.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/spawn_batch.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_render/src/extract_param.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#7911 Initialize empty schedules when calling `.in_schedule` if they do not already exist
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/config.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#7902 Remove ChangeTrackers
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
Labels: A-ECS, S-Ready-For-Final-Review

#7936 Add OnTransition schedule that is ran between OnExit and OnEnter
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/state.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#8019 Fix the `Text2d` text anchor's incorrect horizontal alignment
  crates/bevy_text/src/text2d.rs
  examples/2d/text2d.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#8024 Process 1 in Chrome tracing starts expanded
  docs/profiling.md
Labels: C-Docs, S-Ready-For-Final-Review, C-Testing

#8041 Color::Lcha constructors
  crates/bevy_render/src/color/mod.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#7950 don't panic on unknown ambiguity
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: A-ECS, C-Crash, S-Ready-For-Final-Review

#7485 Remove `Val::Undefined`
  crates/bevy_ui/src/flex/convert.rs
  crates/bevy_ui/src/geometry.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/text.rs
  examples/2d/bloom_2d.rs
  examples/3d/atmospheric_fog.rs
  examples/3d/blend_modes.rs
  examples/3d/bloom_3d.rs
  examples/3d/fog.rs
  examples/3d/pbr.rs
  examples/3d/tonemapping.rs
  examples/games/alien_cake_addict.rs
  examples/games/breakout.rs
  examples/games/game_menu.rs
  examples/input/text_input.rs
  examples/mobile/src/lib.rs
  examples/shader/shader_prepass.rs
  examples/stress_tests/bevymark.rs
  examples/stress_tests/many_buttons.rs
  examples/ui/font_atlas_debug.rs
  examples/ui/text.rs
  examples/ui/text_debug.rs
  examples/ui/ui.rs
  examples/ui/ui_scaling.rs
  examples/ui/window_fallthrough.rs
  examples/ui/z_index.rs
  examples/window/low_power.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#7407 Construct Box<dyn Reflect> from world for ReflectComponent
  crates/bevy_ecs/src/reflect.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection, A-Scenes, C-Breaking-Change

#7996 do not set hit test unconditionally on window creation
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Bug, A-Windowing, O-Web, O-Android, O-iOS, S-Ready-For-Final-Review

#8035 Tests for Run Conditions
  crates/bevy_ecs/src/schedule/condition.rs
Labels: C-Docs, A-ECS, C-Examples, S-Ready-For-Final-Review

#8066 Move docs for `!Sync` resources onto the correct trait
  crates/bevy_ecs/src/system/system_param.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#8068 Make BundleInfo's fields not pub(crate)
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Unsoundness

#8070 Added Globals struct to prepass shader
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass_bindings.wgsl
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, C-Breaking-Change

#8076 change breakout to use FixedTime::period
  examples/games/breakout.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review, A-Time

#8029 Pass query change ticks to `QueryParIter` instead of always using change ticks from `World`.
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#7819 Perform text scaling calculations per text, not per glyph
  Cargo.toml
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/render/mod.rs
  examples/README.md
  examples/stress_tests/many_glyphs.rs
Labels: A-Rendering, C-Performance, A-UI, S-Ready-For-Final-Review

#7855 Add depending bevy features for higher level one
  Cargo.toml
Labels: A-Rendering, A-Assets, C-Usability, A-Meta, S-Ready-For-Final-Review

#8088 fix: register Cascade in the TypeRegistry
  crates/bevy_pbr/src/lib.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, A-Reflection, A-Scenes

#8093 Fix blend_modes example UI positioning
  examples/3d/blend_modes.rs
Labels: C-Examples, A-UI, S-Ready-For-Final-Review

#8069 Fix scrolling in UI example
  examples/ui/ui.rs
Labels: C-Bug, C-Examples, A-UI, S-Ready-For-Final-Review

#7817 Fix look_to resulting in NaN rotations
  crates/bevy_transform/src/components/transform.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Transform

#6909 Add low level post process example using a custom render pass
  Cargo.toml
  assets/shaders/post_process_pass.wgsl
  examples/README.md
  examples/shader/post_process_pass.rs
Labels: A-Rendering, C-Examples

#8094 Improve UI stack docs and other small tweaks
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/stack.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#8045 Doc and test `get_many(_mut)` ordering
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/query.rs
Labels: C-Docs, A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#8108 Remove redundant bounds check in `Entities::get`
  crates/bevy_ecs/src/entity/mod.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review

#8103 Fix `Plugin::build` detection
  crates/bevy_app/src/app.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-App

#8028 Add World::try_run_schedule
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/schedule/state.rs
  crates/bevy_ecs/src/world/error.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#7809 Skip the UV calculations for untextured UI nodes
  crates/bevy_ui/src/render/mod.rs
Labels: C-Performance, A-UI, S-Ready-For-Final-Review

#8105 change not implemation to custom system struct
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/system/function_system.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#8121 Derive Copy and Clone for Collision
  crates/bevy_sprite/src/collide_aabb.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#8116 Allow `many_buttons` to be run without text
  examples/stress_tests/many_buttons.rs
Labels: C-Examples, C-Performance, A-UI, S-Ready-For-Final-Review

#8122 Left-handed y-up cubemap coordinates
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/shadows.wgsl
Labels: C-Enhancement, A-Rendering

#7772 Allow SPIR-V shaders to process when shader defs are present
  crates/bevy_render/src/render_resource/shader.rs
Labels: C-Bug, A-Rendering

#8127 improve comments in example
  examples/2d/texture_atlas.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#8065 add position to scene errors
  crates/bevy_scene/src/scene_loader.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Scenes

#6529 Immediate Mode Line/Gizmo Drawing
  Cargo.toml
  crates/bevy_gizmos/Cargo.toml
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gizmos/src/lines.wgsl
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_internal/src/lib.rs
  crates/bevy_internal/src/prelude.rs
  docs/cargo_features.md
  examples/2d/2d_gizmos.rs
  examples/3d/3d_gizmos.rs
  examples/README.md
  examples/stress_tests/many_gizmos.rs
  tools/publish.sh
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, C-Testing, S-Controversial

#6846 (De) serialize resources in scenes
  assets/scenes/load_scene_example.scn.ron
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/dynamic_scene_builder.rs
  crates/bevy_scene/src/scene.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_scene/src/serde.rs
  examples/scene/scene.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Scenes, S-Controversial

#8134 Improve the 'Val` doc comments
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#7204 bevy_ecs: add untyped methods for inserting components and bundles
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Reflection, D-Complex, S-Controversial

#8151 Fix crash when enabling HDR on 2d cameras
  crates/bevy_gizmos/src/pipeline_2d.rs
Labels: C-Bug, A-Rendering, C-Crash

#8115 Add documentation comments to `bevy_winit`
  crates/bevy_winit/src/accessibility.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/winit_config.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Docs, A-Windowing

#8109 Make render graph slots optional for most cases
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/core_2d/main_pass_2d_node.rs
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/main_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/fxaa/mod.rs
  crates/bevy_core_pipeline/src/fxaa/node.rs
  crates/bevy_core_pipeline/src/msaa_writeback.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_core_pipeline/src/tonemapping/node.rs
  crates/bevy_core_pipeline/src/upscaling/node.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_render/src/camera/camera_driver_node.rs
  crates/bevy_render/src/render_graph/context.rs
  crates/bevy_render/src/render_graph/node.rs
  crates/bevy_render/src/renderer/graph_runner.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/render_pass.rs
  examples/shader/post_process_pass.rs
Labels: C-Enhancement, A-Rendering, C-Breaking-Change

#8053 Reduce branching when inserting components
  crates/bevy_ecs/src/bundle.rs
Labels: A-ECS, C-Performance

#7943 Rename `text_layout` example to `flex_layout`
  Cargo.toml
  examples/README.md
  examples/ui/flex_layout.rs
Labels: C-Examples, A-UI, S-Ready-For-Final-Review

#8154 Check for conflicting accesses in `assert_is_system`
  crates/bevy_ecs/src/system/mod.rs
Labels: A-ECS, C-Testing, C-Breaking-Change

#8012 Fix name conflicts caused by the `SystemParam` and `WorldQuery` macros
  crates/bevy_ecs/macros/src/fetch.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_macro_utils/Cargo.toml
  crates/bevy_macro_utils/src/lib.rs
Labels: C-Bug, A-ECS, C-Usability, S-Ready-For-Final-Review

#8164 Fix documentation on RegularPolygon
  crates/bevy_render/src/mesh/shape/regular_polygon.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#8212 `Or<T>` should be a new type of `PhantomData<T>`
  crates/bevy_ecs/src/query/filter.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#8225 Make bevy_winit/trace optional in trace feature
  crates/bevy_internal/Cargo.toml
Labels: C-Dependencies, S-Ready-For-Final-Review

#8207 Add ReflectComponent registration for Sprite
  crates/bevy_sprite/src/sprite.rs
Labels: C-Usability, A-Reflection, A-Scenes

#7977 Dither fix
  crates/bevy_pbr/src/render/pbr.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
Labels: A-Rendering, C-Code-Quality

#8014 bevy_reflect: Fix trailing comma breaking derives
  crates/bevy_reflect/bevy_reflect_derive/src/from_reflect.rs
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
  crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/bounds.pass.rs
Labels: C-Bug, A-Reflection

#7993 Register missing types in bevy_window
  crates/bevy_core/src/lib.rs
  crates/bevy_window/src/lib.rs
Labels: A-Windowing, C-Usability, A-Reflection, S-Controversial

#8156 docs: update docs and comments that still refer to stages
  crates/bevy_ecs/examples/resources.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_transform/src/commands.rs
  crates/bevy_transform/src/components/global_transform.rs
  crates/bevy_transform/src/lib.rs
  crates/bevy_winit/src/lib.rs
  examples/shader/post_process_pass.rs
Labels: C-Bug, C-Docs, S-Ready-For-Final-Review

#7951 Bugfix: Scene reload fix (nonbreaking)
  crates/bevy_ecs/src/reflect.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/scene.rs
Labels: C-Bug, A-Scenes, S-Controversial

#7291 Temporal Antialiasing (TAA)
  Cargo.toml
  assets/shaders/show_prepass.wgsl
  crates/bevy_core_pipeline/Cargo.toml
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/core_3d/main_pass_3d_node.rs
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_core_pipeline/src/taa/taa.wgsl
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass.wgsl
  crates/bevy_pbr/src/prepass/prepass_bindings.wgsl
  crates/bevy_pbr/src/prepass/prepass_utils.wgsl
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_types.wgsl
  crates/bevy_pbr/src/render/mesh_view_bindings.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/view.wgsl
  examples/3d/anti_aliasing.rs
  examples/3d/fxaa.rs
  examples/3d/msaa.rs
  examples/README.md
  examples/shader/shader_prepass.rs
Labels: C-Enhancement, A-Rendering, D-Complex

#8090 Split opaque and transparent phases
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transparent_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/msaa_writeback.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_ui/src/render/mod.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#8220 Added `WebP` image format support
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/texture/image_texture_loader.rs
  docs/cargo_features.md
Labels: C-Enhancement, A-Rendering, A-Assets, S-Ready-For-Final-Review

#8232 Re-export glam_assert feature
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_math/Cargo.toml
  docs/cargo_features.md
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math

#8147 Improve UI `update_clipping_system` comments
  crates/bevy_ui/src/update.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#8186 Document `bevy_gizmos`
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_internal/src/lib.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Gizmos

#8216 daily job running mobile example on real devices
  .github/start-mobile-example/.gitignore
  .github/start-mobile-example/mobile.conf.js
  .github/start-mobile-example/package-lock.json
  .github/start-mobile-example/package.json
  .github/start-mobile-example/specs/screenshot.js
  .github/workflows/daily.yml
  README.md
  examples/mobile/Makefile
  examples/mobile/bevy_mobile_example.xcodeproj/project.pbxproj
  examples/mobile/src/lib.rs
Labels: A-Build-System, O-Android, O-iOS, S-Ready-For-Final-Review, S-Controversial

#8223 Fix segfault with 2d gizmos
  crates/bevy_gizmos/src/lines.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#8231 Use the prepass normal texture in main pass when possible
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/pbr.wgsl
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#8249 Make standard commands more ergonomic (in niche cases)
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review

#8261 Format SystemState doc example code
  crates/bevy_ecs/src/system/function_system.rs
Labels: C-Docs, A-ECS

#8247 Simplify `Clone` for `ThinSlicePtr`
  crates/bevy_ptr/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Pointers

#8269 Remove base set error variants of `ScheduleBuildError`
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/state.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#8270 Use actual tests for `SystemParam` regression tests
  crates/bevy_ecs/src/system/system_param.rs
Labels: A-ECS, S-Ready-For-Final-Review, C-Testing

#8265 Remove `#[system_param(ignore)]` and `#[world_query(ignore)]`
  crates/bevy_ecs/macros/src/fetch.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/system/system_param.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#8251 Basic event benchmarks
  benches/benches/bevy_ecs/benches.rs
  benches/benches/bevy_ecs/events/iter.rs
  benches/benches/bevy_ecs/events/mod.rs
  benches/benches/bevy_ecs/events/send.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review, A-Diagnostics

#8049 Fix CubicCurve::iter_samples iteration count
  crates/bevy_math/src/cubic_splines.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Math

#8277 Fix inaccurate documentation on `QueryState::for_each_unchecked
  crates/bevy_ecs/src/query/state.rs
Labels: C-Docs, A-ECS

#8274 Replace some unsafe system executor code with safe code
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_utils/src/syncunsafecell.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change
