Repository bevyengine/bevy, pull requests merged in 2023-09, with the labels that each got.

#9497 Split `ComputedVisibility` into two components to allow for accurate change detection and speed up visibility propagation
  crates/bevy_hierarchy/src/valid_parent_check_plugin.rs
  crates/bevy_pbr/src/bundle.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/morph.rs
  crates/bevy_render/src/extract_component.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/spatial_bundle.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_scene/src/bundle.rs
  crates/bevy_sprite/src/bundle.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/render/mod.rs
  errors/B0004.md
  examples/2d/mesh2d_manual.rs
  examples/stress_tests/many_cubes.rs
Labels: C-Bug, A-Rendering, C-Performance, C-Breaking-Change

#9596 Enhance many_cubes stress test use cases
  Cargo.toml
  examples/stress_tests/many_cubes.rs
Labels: A-Rendering, C-Code-Quality, A-Diagnostics

#9597 Use instancing for sprites
  crates/bevy_pbr/src/render/mesh_functions.wgsl
  crates/bevy_pbr/src/render/mesh_types.wgsl
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/maths.wgsl
  crates/bevy_render/src/render_resource/buffer_vec.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_sprite/src/render/sprite.wgsl
Labels: A-Rendering, C-Performance

#9672 Fix some nightly warnings
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/spawn_batch.rs
  crates/bevy_reflect/src/path/parse.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#9665 Fix running examples on linux in CI
  .github/workflows/validation-jobs.yml
Labels: A-Build-System, P-High, S-Ready-For-Final-Review

#9666 Use default resolution for viewport_debug example
  examples/ui/viewport_debug.rs
Labels: C-Examples, S-Ready-For-Final-Review

#9674 Enhance bevymark
  examples/stress_tests/bevymark.rs
  examples/stress_tests/many_cubes.rs
Labels: A-Rendering, C-Examples, C-Performance, S-Ready-For-Final-Review

#9677 bevy_ui: reflect missing types
  crates/bevy_ui/src/lib.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, A-Reflection

#9669 Remove redundant math in tonemapping.
  crates/bevy_core_pipeline/src/tonemapping/tonemapping_shared.wgsl
Labels: A-Rendering, C-Performance, C-Code-Quality, S-Ready-For-Final-Review

#9463 Fix unsoundness in `QueryState::is_empty`
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Unsoundness

#9673 Improve `SpatialBundle` docs
  crates/bevy_render/src/spatial_bundle.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#9679 Add `DiagnosticsStore::iter_mut`
  crates/bevy_diagnostic/src/diagnostic.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Editor, A-Diagnostics

#9662 Fix check that cursor position is within window bounds
  crates/bevy_window/src/window.rs
Labels: C-Bug, A-Input, A-Windowing, S-Ready-For-Final-Review

#9659 Add panicking helpers for getting components from `Query`
  crates/bevy_ecs/src/system/query.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#9565 Cache depth texture based on usage
  crates/bevy_core_pipeline/src/core_3d/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#9697 Fix doc link in transparent_window example
  examples/window/transparent_window.rs
Labels: C-Docs, C-Examples, A-Windowing

#9247 Replace `IntoSystemSetConfig` with `IntoSystemSetConfigs`
  crates/bevy_app/src/app.rs
  crates/bevy_audio/src/lib.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_transform/src/lib.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9705 derive Clone/Copy/Debug trio for shape::Cylinder
  crates/bevy_render/src/mesh/shape/cylinder.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, A-Math

#9704 Refer to "macOS", not "macOS X".
  crates/bevy_window/src/window.rs
Labels: C-Docs, S-Ready-For-Final-Review

#9699 warn and min for different vertex count
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: A-Rendering, C-Crash, S-Ready-For-Final-Review

#9611 default 16bit rgb/rgba textures to unorm instead of uint
  crates/bevy_render/src/texture/dds.rs
  crates/bevy_render/src/texture/image_texture_conversion.rs
Labels: C-Bug, A-Rendering, C-Crash, S-Ready-For-Final-Review

#9716 create imported asset directory if needed
  crates/bevy_asset/src/processor/log.rs
Labels: C-Bug, A-Assets

#9494 TextureAtlasBuilder padding
  crates/bevy_sprite/src/texture_atlas_builder.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#9712 `many_buttons` enhancements
  examples/stress_tests/many_buttons.rs
Labels: A-Rendering, C-Examples, C-Performance, A-UI, S-Ready-For-Final-Review

#9720 Remove useless single tuples and trailing commas
  benches/benches/bevy_ecs/change_detection.rs
  benches/benches/bevy_ecs/events/mod.rs
  benches/benches/bevy_ecs/world/world_get.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_reflect/src/serde/de.rs
  crates/bevy_render/src/color/mod.rs
  crates/bevy_scene/src/serde.rs
  crates/bevy_time/src/time.rs
  crates/bevy_ui/src/layout/convert.rs
  examples/3d/atmospheric_fog.rs
  examples/ecs/component_change_detection.rs
  examples/stress_tests/many_animated_sprites.rs
  examples/stress_tests/many_lights.rs
  examples/stress_tests/many_sprites.rs
  examples/ui/display_and_visibility.rs
  examples/ui/ui_texture_atlas.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#9724 Fix some warnings
  crates/bevy_asset/src/lib.rs
  crates/bevy_pbr/src/light.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#9729 Copy on Write AssetPaths
  crates/bevy_asset/src/io/processor_gated.rs
  crates/bevy_asset/src/loader.rs
  crates/bevy_asset/src/path.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/saver.rs
  crates/bevy_asset/src/server/info.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_utils/src/cow_arc.rs
  crates/bevy_utils/src/lib.rs
  examples/shader/texture_binding_array.rs
  examples/tools/scene_viewer/main.rs
Labels: A-Assets, C-Performance, S-Ready-For-Final-Review, C-Breaking-Change

#9737 Increase iteration count for asset tests
  crates/bevy_asset/src/lib.rs
Labels: A-Build-System, A-Assets, S-Ready-For-Final-Review, C-Testing

#7179 Add example for `Camera::viewport_to_world`
  Cargo.toml
  examples/2d/2d_viewport_to_world.rs
  examples/3d/3d_viewport_to_world.rs
  examples/README.md
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#8856 `impl From<String>` and `From<&str>` for `TextSection`
  crates/bevy_text/src/text.rs
  crates/bevy_ui/src/node_bundles.rs
  examples/ui/text.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#9686 Moved `get_component(_unchecked_mut)` from `Query` to `QueryState`
  crates/bevy_ecs/src/query/error.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/query.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9692 Wait before making window visible
  examples/window/window_settings.rs
Labels: C-Examples, A-Windowing, S-Ready-For-Final-Review

#9733 Remove z-axis scaling in `extract_text2d_sprite`
  crates/bevy_text/src/text2d.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#9734 Fix wireframe for skinned/morphed meshes
  crates/bevy_pbr/src/render/wireframe.wgsl
  crates/bevy_pbr/src/wireframe.rs
Labels: C-Bug, A-Rendering, C-Crash, S-Ready-For-Final-Review

#9739 Fix doc comments for align items
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#9742 Implement `Reflect` for `State<S>` and `NextState<S>`
  crates/bevy_ecs/src/schedule/state.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Reflection

#9743 Fix comment in scene example `FromResources`
  examples/scene/scene.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Reflection

#9744 Fix naming on "tick" Column and ComponentSparseSet methods
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/storage/resource.rs
  crates/bevy_ecs/src/storage/sparse_set.rs
  crates/bevy_ecs/src/storage/table.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#9749 Clarify a comment in Option WorldQuery impl
  crates/bevy_ecs/src/query/fetch.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#9779 Implement `Reflect` for `Mesh`
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/mesh/mod.rs
Labels: C-Enhancement, A-Rendering, A-Assets, S-Ready-For-Final-Review, A-Reflection

#9781 Add tests to `bevy_ui::Layout`
  crates/bevy_ui/src/layout/mod.rs
Labels: A-UI, C-Code-Quality, S-Ready-For-Final-Review

#9756 Asset v2: Asset path serialization fix
  crates/bevy_asset/src/handle.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/path.rs
Labels: C-Bug, A-Assets

#9767 don't ignore some EventKind::Modify
  crates/bevy_asset/src/io/file/file_watcher.rs
Labels: C-Bug, A-Assets

#9752 Manual "Reflect Value" AssetPath impl to fix dynamic linking
  crates/bevy_asset/src/path.rs
  crates/bevy_utils/src/cow_arc.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#9795 examples: Remove unused doc comments.
  examples/ui/grid.rs
Labels: C-Examples, A-UI, C-Code-Quality, S-Ready-For-Final-Review

#9785 Add missing `bevy_text` feature attribute to `TextBundle` from impl
  crates/bevy_ui/src/node_bundles.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#9769 Fix animate_scale scaling z value in text2d example
  examples/2d/text2d.rs
Labels: C-Examples

#9801 Return a boolean from `set_if_neq`
  crates/bevy_ecs/src/change_detection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9794 doc: Remove reference to `clippy::manual-strip`.
  docs/linters.md
Labels: C-Docs, A-Build-System, S-Ready-For-Final-Review

#9807 Remove TypeRegistry re-export rename
  crates/bevy_internal/src/lib.rs
Labels: A-Reflection, C-Breaking-Change

#9778 Rename RemovedComponents::iter/iter_with_id to read/read_with_id
  crates/bevy_ecs/src/removal_detection.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_transform/src/systems.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_winit/src/system.rs
  examples/ecs/removal_detection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9818 Move `Val` into `geometry`
  crates/bevy_ui/src/geometry.rs
  crates/bevy_ui/src/ui_node.rs
Labels: A-UI, C-Code-Quality, S-Ready-For-Final-Review

#9820 Derive Serialize and Deserialize for UiRect
  crates/bevy_ui/src/geometry.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#9823 fix deprecation warning in bench
  benches/benches/bevy_ecs/events/iter.rs
Labels: S-Ready-For-Final-Review

#8862 generate indices for Mikktspace
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#9833 Remove some old references to CoreSet
  crates/bevy_ecs/src/world/mod.rs
  examples/ecs/apply_deferred.rs
  examples/ecs/removal_detection.rs
  examples/stress_tests/transform_hierarchy.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#9829 don't enable filesystem_watcher when building for WebGPU
  tools/build-wasm-example/src/main.rs
Labels: C-Examples, S-Ready-For-Final-Review, O-WebGPU

#9753 `ContentSize` replacement fix
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_ui/src/widget/text.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#9748 Provide getters for fields of ReflectFromPtr
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_reflect/src/type_registry.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection, C-Breaking-Change

#8859 invert face culling for negatively scaled gltf nodes
  crates/bevy_gltf/src/loader.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#9814 Round up for the batch size to improve par_iter performance
  crates/bevy_ecs/src/query/par_iter.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review, A-Tasks

#9840 Improve doc formatting.
  crates/bevy_core_pipeline/src/fxaa/mod.rs
  crates/bevy_diagnostic/src/diagnostic.rs
  crates/bevy_ecs/src/reflect/entity_commands.rs
  crates/bevy_ecs/src/storage/mod.rs
  crates/bevy_ecs/src/storage/sparse_set.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_input/src/axis.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/extract_param.rs
  crates/bevy_tasks/src/task.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_utils/src/label.rs
Labels: C-Docs, S-Ready-For-Final-Review

#9839 docs: Improve some `ComponentId` doc cross-linking.
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#9784 Round UI coordinates after scaling
  crates/bevy_ui/src/layout/mod.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#9834 Fix the `clippy::explicit_iter_loop` lint
  crates/bevy_app/src/app.rs
  crates/bevy_asset/macros/src/lib.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/processor/process.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/enums.rs
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/src/render_graph/graph.rs
  crates/bevy_render/src/render_resource/shader.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_sprite/src/texture_atlas_builder.rs
  crates/bevy_ui/src/accessibility.rs
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/layout/debug.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/widget/text.rs
  crates/bevy_winit/src/accessibility.rs
  tools/ci/src/main.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#9845 Fix ambiguities in transform example
  examples/transforms/transform.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Transform

#9846 Use a seeded rng for custom_skinned_mesh example
  examples/animation/custom_skinned_mesh.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review, A-Animation, C-Testing

#9830 renderer init: create a detached task only on wasm, block otherwise
  crates/bevy_render/src/lib.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#9637 Have a separate implicit viewport node per root node + make viewport node `Display::Grid`
  crates/bevy_ui/src/layout/debug.rs
  crates/bevy_ui/src/layout/mod.rs
  examples/ecs/apply_deferred.rs
  examples/ecs/state.rs
  examples/games/game_menu.rs
  examples/stress_tests/many_buttons.rs
  examples/stress_tests/many_glyphs.rs
  examples/ui/borders.rs
  examples/ui/button.rs
  examples/ui/display_and_visibility.rs
  examples/ui/overflow.rs
  examples/ui/relative_cursor_position.rs
  examples/ui/size_constraints.rs
  examples/ui/text_wrap_debug.rs
  examples/ui/transparency_ui.rs
  examples/ui/ui.rs
  examples/ui/ui_texture_atlas.rs
  examples/ui/z_index.rs
  examples/window/scale_factor_override.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#8963 One Shot Systems
  Cargo.toml
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_registry.rs
  crates/bevy_utils/src/label.rs
  examples/README.md
  examples/ecs/one_shot_systems.rs
Labels: C-Enhancement, A-ECS, S-Controversial

#9851 Fix clippy lint in single_threaded_task_pool
  crates/bevy_tasks/src/single_threaded_task_pool.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Tasks

#9836 Add mutual exclusion safety info on filter_fetch
  crates/bevy_ecs/src/query/fetch.rs
Labels: C-Docs, A-ECS, C-Unsoundness

#9850 Cleanup `visibility` module
  crates/bevy_render/src/view/visibility/mod.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#9849 Use a single line for of large binding lists
  assets/shaders/array_texture.wgsl
  assets/shaders/cubemap_unlit.wgsl
  assets/shaders/custom_material.wgsl
  assets/shaders/custom_material_screenspace_texture.wgsl
  assets/shaders/custom_vertex_attribute.wgsl
  assets/shaders/fallback_image_test.wgsl
  assets/shaders/game_of_life.wgsl
  assets/shaders/line_material.wgsl
  assets/shaders/post_processing.wgsl
  assets/shaders/shader_defs.wgsl
  assets/shaders/show_prepass.wgsl
  assets/shaders/texture_binding_array.wgsl
  crates/bevy_core_pipeline/src/blit/blit.wgsl
  crates/bevy_core_pipeline/src/bloom/bloom.wgsl
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/robust_contrast_adaptive_sharpening.wgsl
  crates/bevy_core_pipeline/src/fxaa/fxaa.wgsl
  crates/bevy_core_pipeline/src/skybox/skybox.wgsl
  crates/bevy_core_pipeline/src/tonemapping/tonemapping.wgsl
  crates/bevy_core_pipeline/src/tonemapping/tonemapping_shared.wgsl
  crates/bevy_gizmos/src/lines.wgsl
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/prepass_bindings.wgsl
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_bindings.wgsl
  crates/bevy_pbr/src/render/mesh_view_bindings.wgsl
  crates/bevy_pbr/src/render/morph.wgsl
  crates/bevy_pbr/src/render/pbr_bindings.wgsl
  crates/bevy_pbr/src/render/skinning.wgsl
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_sprite/src/mesh2d/color_material.wgsl
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh2d_bindings.wgsl
  crates/bevy_sprite/src/mesh2d/mesh2d_view_bindings.wgsl
  crates/bevy_sprite/src/render/sprite.wgsl
  crates/bevy_ui/src/render/ui.wgsl
  examples/2d/mesh2d_manual.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#9861 Fix a typo in `DirectionalLightBundle`
  crates/bevy_pbr/src/bundle.rs
Labels: A-Rendering

#9842 Wslg docs
  docs/linux_dependencies.md
Labels: C-Docs, O-Linux, O-Windows, S-Ready-For-Final-Review

#9867 Handle empty morph weights when loading gltf
  crates/bevy_gltf/src/loader.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review, A-Animation

#9872 Only run some workflows on the bevy repo (not forks)
  .github/workflows/daily.yml
  .github/workflows/docs.yml
  .github/workflows/post-release.yml
  .github/workflows/release.yml
Labels: A-Build-System

#9878 Revert "Update defaults for OrthographicProjection (#9537)"
  crates/bevy_render/src/camera/projection.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, C-Breaking-Change

#9844 add try_insert to entity commands
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#9812 `#[derive(Clone)]` on `Component{Info,Descriptor}`
  crates/bevy_ecs/src/component.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Reflection

#9879 Rename `num_font_atlases` to `len`.
  crates/bevy_text/src/font_atlas_set.rs
  crates/bevy_text/src/glyph_brush.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9870 Refactor rendering systems to use `let-else`
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_sprite/src/mesh2d/material.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#9881 Remove dependecies from bevy_tasks' README
  crates/bevy_tasks/README.md
Labels: C-Docs, S-Ready-For-Final-Review, A-Tasks

#9882 Use radsort for Transparent2d PhaseItem sorting
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_sprite/Cargo.toml
  examples/stress_tests/bevymark.rs
Labels: A-Rendering, C-Performance

#9464 Improve codegen for world validation
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
Labels: A-ECS, C-Performance, C-Usability

#9685 Automatic batching/instancing of draw commands
  assets/shaders/custom_gltf_2d.wgsl
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_math/src/affine3.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/morph.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_render/src/render_resource/batched_uniform_buffer.rs
  crates/bevy_render/src/render_resource/gpu_array_buffer.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/mesh2d/mesh2d.wgsl
  crates/bevy_sprite/src/mesh2d/mesh2d_bindings.wgsl
  crates/bevy_sprite/src/mesh2d/mesh2d_functions.wgsl
  crates/bevy_sprite/src/mesh2d/mesh2d_types.wgsl
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/render_pass.rs
  crates/bevy_utils/Cargo.toml
  crates/bevy_utils/src/lib.rs
  examples/2d/mesh2d_manual.rs
  examples/shader/shader_instancing.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#9871 Add as_slice to parent
  crates/bevy_hierarchy/src/components/parent.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Hierarchy

#9684 don't create windows on winit StartCause::Init event
  crates/bevy_winit/src/lib.rs
Labels: A-Windowing, O-Android, S-Ready-For-Final-Review

#7728 Only run event systems if they have tangible work to do
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/examples/events.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/schedule/condition.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review, A-App, C-Breaking-Change

#9922 Fix typos.
  crates/bevy_ecs/src/reflect/component.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_render/src/render_asset.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_utils/src/label.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/lib.rs
Labels: C-Docs, S-Ready-For-Final-Review

#9899 Move skin code to a separate module
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_bindings.rs
  crates/bevy_pbr/src/render/mod.rs
  crates/bevy_pbr/src/render/morph.rs
  crates/bevy_pbr/src/render/skin.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, A-Animation, C-Breaking-Change

#9919 register `TextLayoutInfo` and `TextFlags` type.
  crates/bevy_text/src/font_atlas_set.rs
  crates/bevy_text/src/glyph_brush.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_ui/src/lib.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, A-Reflection

#9626 Allow using async_io::block_on in bevy_tasks
  Cargo.toml
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/src/lib.rs
  crates/bevy_tasks/src/task_pool.rs
  docs/cargo_features.md
  examples/async_tasks/async_compute.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Tasks

#9900 Add link to `Text2dBundle` in `TextBundle` docs.
  crates/bevy_ui/src/node_bundles.rs
Labels: C-Docs, S-Ready-For-Final-Review

#9925 Allow other plugins to create renderer resources
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/renderer/mod.rs
  crates/bevy_render/src/settings.rs
  examples/3d/wireframe.rs
  examples/app/no_renderer.rs
Labels: A-Rendering, O-XR

#9934 Fix some typos
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_reflect/src/type_registry.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_render/src/view/window/mod.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_utils/macros/src/lib.rs
  docs-template/EXAMPLE_README.md.tpl
  examples/3d/parallax_mapping.rs
  examples/README.md
  examples/ui/display_and_visibility.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#9935 Fix documentation for ui node Style
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#9927 Fix morph interpolation
  crates/bevy_animation/src/lib.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Animation

#9933 Fix the doc warning attribute and document remaining items for `bevy_window`
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_window/src/raw_handle.rs
Labels: C-Docs, A-Windowing, S-Ready-For-Final-Review

#9903 Use EntityHashMap<Entity, T> for render world entity storage for better performance
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/morph.rs
  crates/bevy_pbr/src/render/skin.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_utils/src/lib.rs
  examples/shader/shader_instancing.rs
  examples/stress_tests/bevymark.rs
  examples/stress_tests/many_cubes.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#9905 macOS Sonoma (14.0) / Xcode 15.0 — Compatibility Fixes + Docs
  crates/bevy_winit/src/lib.rs
Labels: C-Crash, O-MacOS, P-High

#9951 `text_wrap_debug` scale factor commandline args
  examples/ui/text_wrap_debug.rs
Labels: A-UI, S-Ready-For-Final-Review, C-Testing

#9936 run mobile tests on more devices / OS versions
  .github/workflows/daily.yml
Labels: A-Build-System, O-Android, O-iOS, S-Ready-For-Final-Review

#9923 Store both the rounded and unrounded node size in Node
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/text.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#9958 docs: Use intradoc links for method references.
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: C-Docs, A-ECS

#9961 Fix unused variable warning for simple AssetV2 derives
  crates/bevy_asset/macros/src/lib.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#9963 Add TypePath to the prelude
  crates/bevy_reflect/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#9965 Fix typos
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/system_registry.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_hierarchy/src/components/parent.rs
  crates/bevy_ui/src/ui_node.rs
  examples/input/gamepad_input_events.rs
Labels: C-Code-Quality

#9939 Clarify behaviour of `Timer::finished()` for repeating timers
  crates/bevy_time/src/timer.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Time

#9974 Remove monkey.gltf
  assets/models/monkey/Monkey.gltf
  assets/models/torus/torus.gltf
  examples/asset/asset_loading.rs
  examples/asset/hot_asset_reloading.rs
  examples/window/multiple_windows.rs
Labels: A-Assets, P-High, S-Ready-For-Final-Review

#9950 Cache parallel iteration spans
  crates/bevy_ecs/src/query/state.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review, A-Diagnostics

#9945 Remove States::variants and remove enum-only restriction its derive
  crates/bevy_ecs/macros/src/states.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/schedule/state.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change
