Repository bevyengine/bevy, pull requests merged in 2023-12, with the labels that each got.

#6773 Override QueryIter::fold to port Query::for_each perf gains to select Iterator combinators
  benches/benches/bevy_ecs/iteration/iter_frag_foreach.rs
  benches/benches/bevy_ecs/iteration/iter_frag_foreach_sparse.rs
  benches/benches/bevy_ecs/iteration/iter_frag_foreach_wide.rs
  benches/benches/bevy_ecs/iteration/iter_frag_foreach_wide_sparse.rs
  benches/benches/bevy_ecs/iteration/iter_simple_foreach.rs
  benches/benches/bevy_ecs/iteration/iter_simple_foreach_sparse_set.rs
  benches/benches/bevy_ecs/iteration/iter_simple_foreach_wide.rs
  benches/benches/bevy_ecs/iteration/iter_simple_foreach_wide_sparse_set.rs
  benches/benches/bevy_ecs/scheduling/running_systems.rs
  benches/benches/bevy_ecs/scheduling/schedule.rs
  benches/benches/bevy_ecs/world/world_get.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_lifetime_safety.rs
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_lifetime_safety.stderr
  examples/stress_tests/many_buttons.rs
Labels: A-ECS, C-Performance, C-Code-Quality, S-Ready-For-Final-Review, D-Complex

#10837 Clarifying Commands' purpose
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#10847 Substitute `get(0)` with `first()`
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/src/view/window/mod.rs
  examples/stress_tests/bevymark.rs
  examples/stress_tests/many_cubes.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#10841 Fix binding group in custom_material_2d.wgsl
  assets/shaders/custom_material_2d.wgsl
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#10848 Remove identity `map` calls
  crates/bevy_app/src/app.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#10770 Make ComponentId typed in Components
  crates/bevy_ecs/src/component.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#10808 Add helper macro's for logging only once
  crates/bevy_log/src/lib.rs
  crates/bevy_log/src/once.rs
  examples/app/logs.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Utils

#10836 Remove references to specific projects from the readme
  README.md
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review

#10811 Reduced `TableRow` `as` Casting
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/storage/resource.rs
  crates/bevy_ecs/src/storage/sparse_set.rs
  crates/bevy_ecs/src/storage/table.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#10857 Remove `From` implementations from the direction types
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#10854 Rename `TextAlignment` to `JustifyText`.
  crates/bevy_text/src/glyph_brush.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_text/src/text.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/widget/text.rs
  examples/2d/text2d.rs
  examples/3d/tonemapping.rs
  examples/async_tasks/external_source_external_thread.rs
  examples/mobile/src/lib.rs
  examples/stress_tests/many_glyphs.rs
  examples/stress_tests/text_pipeline.rs
  examples/time/virtual_time.rs
  examples/ui/display_and_visibility.rs
  examples/ui/size_constraints.rs
  examples/ui/text.rs
  examples/ui/text_debug.rs
  examples/ui/text_wrap_debug.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change, A-Text

#10879 Remove unnecessary ResMut in examples
  examples/2d/texture_atlas.rs
  examples/3d/generate_custom_mesh.rs
  examples/asset/custom_asset.rs
  examples/ui/ui_scaling.rs
Labels: A-ECS, C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#10884 Impl `TryFrom` vector for directions and add `InvalidDirectionError`
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_math/src/primitives/mod.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#10856 Split `Ray` into `Ray2d` and `Ray3d` and simplify plane construction
  crates/bevy_math/src/lib.rs
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_math/src/ray.rs
  crates/bevy_render/src/camera/camera.rs
  examples/3d/3d_viewport_to_world.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, A-Math, C-Breaking-Change

#10893 Add a couple assertions for system types
  crates/bevy_ecs/src/system/mod.rs
Labels: A-ECS, C-Testing

#10906 Deduplicate systems in bevy_audio
  crates/bevy_audio/src/lib.rs
Labels: A-Audio, C-Code-Quality

#10914 Renamed Accessibility plugin to AccessKitPlugin in bevy_winit
  crates/bevy_winit/src/accessibility.rs
  crates/bevy_winit/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#10918 Remove reference to default schedule
  crates/bevy_app/src/app.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#10910 Non-Intrusive refactor of `play_queued_audio_system()`
  crates/bevy_audio/src/audio_output.rs
Labels: A-Audio, C-Code-Quality, S-Ready-For-Final-Review

#10922 Clip outlines by the node's own clipping rect, not the parent's.
  crates/bevy_ui/src/render/mod.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#10911 Refactor function `update_accessibility_nodes`
  crates/bevy_winit/src/accessibility.rs
Labels: A-Windowing, C-Code-Quality, S-Ready-For-Final-Review

#10905 Normalize only nonzero normals for mikktspace normal maps
  crates/bevy_pbr/src/render/mesh_functions.wgsl
Labels: C-Enhancement, A-Rendering

#10943 Improve `EntityWorldMut.remove`, `retain` and `despawn` docs by linking to more detail
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#10889 Add a doc note about despawn footgun
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review, A-Hierarchy

#10740 Fix debug printing for dynamic types
  crates/bevy_reflect/src/array.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/struct_trait.rs
  crates/bevy_reflect/src/tuple_struct.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Reflection

#10742 light renderlayers
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh_view_types.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/view.wgsl
  crates/bevy_render/src/view/visibility/render_layers.rs
  examples/3d/render_to_texture.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#10764 Reorder fields in SystemSchedule
  crates/bevy_ecs/src/schedule/executor/mod.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#10920 Refactor `process_handle_drop_internal()` in bevy_asset
  crates/bevy_asset/src/server/info.rs
Labels: A-Assets, C-Code-Quality, S-Ready-For-Final-Review

#10927 Explain how RegularPolygon mesh is generated
  crates/bevy_render/src/mesh/shape/regular_polygon.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#10941 Fix soundness of `UnsafeWorldCell` usage example
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: C-Docs, A-ECS, C-Unsoundness

#10885 Actually check alignment in BlobVec test aligned_zst
  crates/bevy_ecs/src/storage/blob_vec.rs
Labels: A-ECS, C-Code-Quality, C-Unsoundness

#10962 Fix broken link between files
  .github/contributing/engine_style_guide.md
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review

#10782 Rename `Q` type parameter to `D` when referring to `WorldQueryData`
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/exclusive_system_param.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_hierarchy/src/query_extension.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#10970 docs: AnimationPlayer::play doesn't have transition_duration arg
  crates/bevy_animation/src/lib.rs
Labels: C-Docs, A-Audio, S-Ready-For-Final-Review

#10963 Remove unused import
  .github/start-wasm-example/tests/wasm_example.spec.ts
Labels: A-Build-System, C-Code-Quality, O-Web, S-Ready-For-Final-Review

#10961 Rename functions and variables to follow code style
  .github/start-wasm-example/tests/wasm_example.spec.ts
Labels: A-Build-System, C-Code-Quality, O-Web, S-Ready-For-Final-Review

#10967 Fix Mesh2d normals on webgl
  crates/bevy_sprite/src/mesh2d/mesh2d_functions.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, O-WebGL2

#10966 Remove unused variable
  .github/start-mobile-example/specs/screenshot.js
Labels: A-Build-System, C-Code-Quality, O-Android, O-iOS, S-Ready-For-Final-Review

#10964 Reorder impl to be the same as the trait
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#10965 Remove unused namespace declarations
  assets/branding/bevy_logo_dark.svg
  assets/branding/bevy_logo_light.svg
  assets/branding/bevy_logo_light_dark_and_dimmed.svg
  assets/branding/icon.svg
Labels: A-Meta, S-Ready-For-Final-Review

#10266 Update to wgpu 0.18
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/node.rs
  crates/bevy_core_pipeline/src/core_2d/main_pass_2d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transmissive_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transparent_pass_3d_node.rs
  crates/bevy_core_pipeline/src/deferred/copy_lighting_id.rs
  crates/bevy_core_pipeline/src/deferred/node.rs
  crates/bevy_core_pipeline/src/fxaa/node.rs
  crates/bevy_core_pipeline/src/msaa_writeback.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/node.rs
  crates/bevy_core_pipeline/src/upscaling/node.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/utils.wgsl
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/camera/camera_driver_node.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_resource/mod.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/renderer/mod.rs
  crates/bevy_render/src/settings.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_ui/src/render/render_pass.rs
  examples/shader/post_processing.rs
Labels: A-Rendering, C-Dependencies, S-Ready-For-Final-Review

#10969 Allow the editing of startup schedules
  crates/bevy_app/src/main_schedule.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#10977 Add First/Pre/Post/Last schedules to the Fixed timestep
  crates/bevy_app/src/lib.rs
  crates/bevy_app/src/main_schedule.rs
  crates/bevy_time/src/fixed.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_time/src/time.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Time

#10897 Change `Window` scale factor to f32 (adopted)
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/layout/convert.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_ui/src/widget/text.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/ui/text_wrap_debug.rs
  examples/ui/ui_scaling.rs
Labels: A-Windowing, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#10882 Add `Direction2d::from_xy` and `Direction3d::from_xyz`
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#9822 Auto insert sync points
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/graph_utils.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/view/visibility/mod.rs
Labels: C-Enhancement, A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, S-Controversial

#10980 Make SystemTime available in both native and wasm
  crates/bevy_utils/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Utils, A-Time

#10979 Fix typo in docs for `ViewVisibility`
  crates/bevy_render/src/view/visibility/mod.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#10937 Simplify lifetimes in `QueryState` methods
  crates/bevy_ecs/src/query/state.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#10947 Add docs to bevy_sprite a little
  crates/bevy_sprite/src/bundle.rs
  crates/bevy_sprite/src/collide_aabb.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_sprite/src/texture_atlas.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#10073 Update texture_atlas example with different padding and sampling
  examples/2d/texture_atlas.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#10818 Fix BindingType import warning
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#10991 Replace deprecated elements
  crates/bevy_render/src/color/colorspace.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#10990 Remove unnecessary parentheses
  crates/bevy_app/src/app.rs
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/storage/blob_vec.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/stack.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#10989 Add html tags required for accessibility
  examples/wasm/index.html
Labels: C-Examples, C-Accessibility, S-Ready-For-Final-Review

#10998 Add docs link to root `Cargo.toml`
  Cargo.toml
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review

#10999 Replace deprecated elements
  crates/bevy_core/src/task_pool_options.rs
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_text/src/glyph_brush.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#10988 Simplify equality assertions
  crates/bevy_derive/src/bevy_main.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_hierarchy/src/hierarchy.rs
  crates/bevy_input/src/touch.rs
  crates/bevy_ptr/src/lib.rs
  crates/bevy_render/src/render_graph/graph.rs
  crates/bevy_render/src/texture/image.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#10996 Add Solus package requrements to linux_dependencies.md
  docs/linux_dependencies.md
Labels: C-Docs, O-Linux, S-Ready-For-Final-Review

#10368 Introduce AspectRatio struct
  crates/bevy_core_pipeline/src/bloom/settings.rs
  crates/bevy_math/src/aspect_ratio.rs
  crates/bevy_math/src/lib.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_render/src/camera/projection.rs
  crates/bevy_render/src/texture/image.rs
Labels: C-Bug, A-Rendering, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, A-Math, C-Breaking-Change

#11003 Implement Std traits for `SceneInstanceReady`
  crates/bevy_scene/src/scene_spawner.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Scenes

#11010 Add method to check if all inputs are pressed
  crates/bevy_input/src/button_input.rs
Labels: A-Input, C-Usability, S-Ready-For-Final-Review

#11016 Update AABB when Sprite component changes in calculate_bounds_2d()
  crates/bevy_sprite/src/lib.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#11020 Some doc to bevy_diagnostic
  crates/bevy_diagnostic/src/entity_count_diagnostics_plugin.rs
  crates/bevy_diagnostic/src/frame_time_diagnostics_plugin.rs
  crates/bevy_diagnostic/src/log_diagnostics_plugin.rs
  crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Diagnostics

#11021 Rename some lifetimes (ResMut etc) for clarity
  crates/bevy_ecs/src/change_detection.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#11025 Add non-existent entity behavior to Has doc
  crates/bevy_ecs/src/query/fetch.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#11028 Fix typo in docs for Has
  crates/bevy_ecs/src/query/fetch.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#11024 OrthographicProjection.scaling_mode is not just for resize
  crates/bevy_render/src/camera/projection.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#11011 Reexport winit::platform::android::activity::* in bevy_winit
  crates/bevy_derive/src/bevy_main.rs
  crates/bevy_winit/src/lib.rs
Labels: A-Windowing, O-Android, C-Usability, S-Ready-For-Final-Review

#10336 Update base64 requirement from 0.13.0 to 0.21.5
  crates/bevy_gltf/Cargo.toml
  crates/bevy_gltf/src/loader.rs
Labels: C-Dependencies

#11054 Add SystemTime to bevy_utils
  crates/bevy_utils/src/lib.rs
Labels: C-Bug, A-Utils

#11043 Add insert_state to App.
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/schedule/state.rs
  examples/2d/texture_atlas.rs
  examples/ecs/generic_system.rs
  examples/ecs/state.rs
  examples/games/alien_cake_addict.rs
  examples/games/game_menu.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review, C-Breaking-Change

#11041 Derive `Debug` for `BloomCompositeMode`
  crates/bevy_core_pipeline/src/bloom/settings.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#11049 Explain Changed, Added are not archetype filters
  crates/bevy_ecs/src/query/filter.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#11053 fix base64 padding when loading a gltf file
  crates/bevy_gltf/src/loader.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#11057 Remove CanvasParentResizePlugin
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/web_resize.rs
  examples/window/window_settings.rs
  tools/example-showcase/window-settings-wasm.patch
Labels: C-Examples, A-Windowing, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#11060 add libxkbcommon-x11-0 to the default linux dependencies
  .github/workflows/validation-jobs.yml
  docs/linux_dependencies.md
Labels: A-Build-System, O-Linux, C-Dependencies, S-Ready-For-Final-Review

#11051 Document None conditions on compute_aabb
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#11058 fix patches for example showcase after winit update
  tools/example-showcase/extra-window-resized-events.patch
  tools/example-showcase/remove-desktop-app-mode.patch
Labels: A-Build-System, C-Examples, S-Ready-For-Final-Review

#11064 Add missing colon in `States` documentation
  crates/bevy_ecs/src/schedule/state.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#10942 Give UI nodes with `Display::None` an empty clipping rect
  crates/bevy_ui/src/update.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#11077 Replace calculation with function call
  crates/bevy_mikktspace/src/generated.rs
Labels: A-Rendering, C-Code-Quality

#11069 Register Camera types.
  crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#11071 Update sysinfo version to 0.30.0
  crates/bevy_diagnostic/Cargo.toml
  crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs
Labels: C-Dependencies, S-Ready-For-Final-Review

#11059 finish cleaning up dependency bans job
  .github/workflows/dependencies.yml
Labels: A-Build-System, C-Dependencies

#11006 Re-export smallvec crate from bevy_utils
  crates/bevy_hierarchy/Cargo.toml
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_hierarchy/src/components/children.rs
  crates/bevy_hierarchy/src/lib.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_reflect/Cargo.toml
  crates/bevy_reflect/src/impls/smallvec.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/type_uuid_impl.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/renderer/graph_runner.rs
  crates/bevy_ui/Cargo.toml
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_utils/Cargo.toml
  crates/bevy_utils/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Utils

#11075 Remove unnecessary parens
  crates/bevy_asset/src/io/source.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_audio/src/audio_output.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_gizmos/src/arcs.rs
  crates/bevy_gizmos/src/circles.rs
  crates/bevy_macro_utils/src/label.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_render/src/texture/image.rs
  crates/bevy_sprite/src/mesh2d/color_material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  examples/ecs/iter_combinations.rs
  examples/stress_tests/bevymark.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#11076 Reorder impl to be the same as the trait
  crates/bevy_asset/src/io/file/file_asset.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/loader.rs
  crates/bevy_asset/src/meta.rs
  crates/bevy_asset/src/path.rs
  crates/bevy_audio/src/audio_source.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_pbr/src/extended_material.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_reflect/src/array.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/map.rs
  crates/bevy_reflect/src/serde/de.rs
  crates/bevy_reflect/src/struct_trait.rs
  crates/bevy_reflect/src/tuple.rs
  crates/bevy_reflect/src/tuple_struct.rs
  crates/bevy_render/src/render_graph/app.rs
  crates/bevy_scene/src/serde.rs
  crates/bevy_transform/src/commands.rs
  crates/bevy_utils/src/lib.rs
  examples/2d/custom_gltf_vertex_attribute.rs
  examples/audio/decodable.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#11037 reflect: maximally relax `TypePath` bounds
  crates/bevy_reflect/bevy_reflect_derive/src/impls/enums.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/tuple_structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/typed.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/values.rs
  crates/bevy_reflect/bevy_reflect_derive/src/lib.rs
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#11063 Explain EventWriter limits concurrency
  crates/bevy_ecs/src/event.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#11065 Use `WindowBuilder::with_append()` to append canvas
  crates/bevy_winit/src/winit_windows.rs
Labels: A-Windowing, C-Dependencies, O-Web, C-Usability, S-Ready-For-Final-Review

#11084 Better doc for SystemName
  crates/bevy_ecs/src/system/system_param.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#8112 Add example for pixel-perfect grid snapping in 2D
  Cargo.toml
  assets/pixel/bevy_pixel_dark.png
  assets/pixel/bevy_pixel_light.png
  examples/2d/pixel_grid_snap.rs
  examples/2d/pixel_perfect.rs
  examples/README.md
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#11134 Misc cleanup
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_render/src/render_resource/mod.rs
Labels: A-Rendering, C-Code-Quality, C-Usability, S-Ready-For-Final-Review

#10325 Keep track of when a texture is first cleared
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
  crates/bevy_core_pipeline/src/core_2d/main_pass_2d_node.rs
  crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transmissive_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transparent_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/deferred/node.rs
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_core_pipeline/src/msaa_writeback.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/prepass/prepass_bindings.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/clear_color.rs
  crates/bevy_render/src/camera/mod.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/texture/mod.rs
  crates/bevy_render/src/texture/texture_attachment.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_ui/src/render/render_pass.rs
  examples/3d/render_to_texture.rs
  examples/3d/split_screen.rs
  examples/3d/two_passes.rs
  examples/shader/post_processing.rs
  tests/window/minimising.rs
  tests/window/resizing.rs
Labels: C-Enhancement, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#10755 support all types of animation interpolation from gltf
  crates/bevy_animation/src/lib.rs
  crates/bevy_gltf/src/loader.rs
  examples/animation/animated_transform.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Animation, C-Breaking-Change
