Repository bevyengine/bevy, pull requests merged in 2023-07, with the labels that each got.

#9003 Fix parallax mapping
  crates/bevy_pbr/src/render/pbr.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, C-Regression

#8926 Fix black spots appearing due to NANs when SSAO is enabled
  crates/bevy_pbr/src/prepass/prepass_utils.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#9013 Fix morph target prepass shader
  crates/bevy_pbr/src/prepass/prepass.wgsl
Labels: C-Bug, A-Rendering, C-Regression, A-Animation

#9032 Remove reference to base sets
  crates/bevy_ecs/src/schedule/graph_utils.rs
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: C-Bug, A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#9030 Use a consistent seed for AABB gizmo colors
  crates/bevy_gizmos/src/lib.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Gizmos

#8985 Fix bevy_ui compilation failure without bevy_text
  crates/bevy_ui/src/measurement.rs
  crates/bevy_ui/src/widget/image.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review, C-Compile-Failure

#9020 Derive Eq, PartialEq for Tick
  crates/bevy_ecs/src/component.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#9039 Remove unused dependency on once_cell in bevy_render
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/lib.rs
Labels: A-Rendering, C-Dependencies, C-Code-Quality

#8981 Remove unused shader define
  crates/bevy_gizmos/src/pipeline_3d.rs
Labels: A-Rendering, C-Code-Quality

#9023 Register bevy_animation::PlayingAnimation
  crates/bevy_animation/src/lib.rs
Labels: C-Enhancement, C-Code-Quality, S-Ready-For-Final-Review, A-Animation, A-Reflection

#9016 Expose `WindowDestroyed` events
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/src/lib.rs
Labels: A-Windowing, S-Ready-For-Final-Review

#9004 `many_buttons` with bordered buttons
  examples/stress_tests/many_buttons.rs
Labels: A-Rendering, C-Performance, A-UI

#9027 Rename Interaction::Clicked -> Interaction::Pressed (#8989)
  crates/bevy_ui/src/focus.rs
  examples/ecs/state.rs
  examples/games/game_menu.rs
  examples/mobile/src/lib.rs
  examples/ui/button.rs
  examples/ui/display_and_visibility.rs
  examples/ui/size_constraints.rs
Labels: A-Input, A-UI, S-Ready-For-Final-Review, C-Breaking-Change

#9024 Run `update_previous_view_projections` in `PreUpdate` schedule
  crates/bevy_pbr/src/prepass/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#8932 Reduce android example APK size
  examples/mobile/Cargo.toml
Labels: C-Examples, O-Android, S-Ready-For-Final-Review

#9053 Remove unnecessary `clone_weak`
  crates/bevy_ui/src/render/mod.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#8720 Divide by `UiScale` when converting UI coordinates from physical to logical
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/text.rs
  examples/ui/viewport_debug.rs
Labels: C-Bug, A-UI

#6793 bevy_scene: Add `SceneFilter`
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/dynamic_scene_builder.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_scene/src/scene_filter.rs
  crates/bevy_scene/src/serde.rs
  examples/scene/scene.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Scenes, C-Breaking-Change, S-Controversial

#8655 Bump `accesskit` and `accesskit_winit`.
  crates/bevy_a11y/Cargo.toml
  crates/bevy_winit/Cargo.toml
Labels: C-Dependencies, C-Accessibility

#8424 bevy_audio: ECS-based API redesign
  crates/bevy_audio/src/audio.rs
  crates/bevy_audio/src/audio_output.rs
  crates/bevy_audio/src/lib.rs
  crates/bevy_audio/src/sinks.rs
  examples/audio/audio.rs
  examples/audio/audio_control.rs
  examples/audio/decodable.rs
  examples/audio/spatial_audio_2d.rs
  examples/audio/spatial_audio_3d.rs
  examples/games/breakout.rs
  examples/mobile/src/lib.rs
Labels: A-Audio, C-Usability, C-Breaking-Change, S-Controversial

#9074 make accesskit_unix optional again
  crates/bevy_winit/Cargo.toml
Labels: O-Linux, C-Dependencies

#6690 Add optional single-threaded feature to bevy_ecs/bevy_tasks
  Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/src/lib.rs
  crates/bevy_tasks/src/single_threaded_task_pool.rs
  docs/cargo_features.md
Labels: C-Enhancement, A-ECS, C-Performance, A-Tasks

#9054 Fix not calling `App::finish` and `App::cleanup` in `ScheduleRunnerPlugin`
  crates/bevy_app/src/schedule_runner.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-App

#8931 Growing UI nodes Fix
  crates/bevy_ui/src/layout/mod.rs
Labels: C-Bug, A-UI

#9090 Fix typos throughout the project
  crates/bevy_app/src/main_schedule.rs
  crates/bevy_core_pipeline/src/bloom/settings.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/reflect/map_entities.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/storage/table.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_gizmos/src/lines.wgsl
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_pbr/src/render/morph.rs
  crates/bevy_pbr/src/render/morph.wgsl
  crates/bevy_pbr/src/render/pbr_lighting.wgsl
  crates/bevy_reflect/bevy_reflect_derive/src/container_attributes.rs
  crates/bevy_reflect/bevy_reflect_derive/src/derive_data.rs
  crates/bevy_reflect/bevy_reflect_derive/src/lib.rs
  crates/bevy_reflect/src/array.rs
  crates/bevy_reflect/src/from_reflect.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/list.rs
  crates/bevy_reflect/src/type_path.rs
  crates/bevy_reflect/src/utility.rs
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_transform/src/components/transform.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/stack.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/text.rs
  crates/bevy_utils/src/syncunsafecell.rs
  examples/shader/post_processing.rs
  examples/tools/scene_viewer/morph_viewer_plugin.rs
  examples/ui/display_and_visibility.rs
  examples/ui/size_constraints.rs
  examples/ui/ui.rs
  tools/build-wasm-example/src/main.rs
Labels: C-Docs, C-Code-Quality, S-Ready-For-Final-Review

#9081 Update `GlobalTransform` on insertion
  crates/bevy_transform/src/systems.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Transform

#9102 Fix typo in NamedTypePathDef
  crates/bevy_reflect/bevy_reflect_derive/src/lib.rs
  crates/bevy_reflect/bevy_reflect_derive/src/type_path.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection, C-Breaking-Change

#9103 Remove out-of-date paragraph in `Style::border`
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, A-Rendering, A-UI

#9105 doc(asset): fix asset trait example
  crates/bevy_asset/src/loader.rs
Labels: C-Docs, A-Assets, S-Ready-For-Final-Review

#9144 fix `clippy::default_constructed_unit_structs` and trybuild errors
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/handle.rs
  crates/bevy_core/src/lib.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/generics.fail.stderr
  crates/bevy_tasks/src/thread_executor.rs
Labels: C-Code-Quality

#9128 delete code deprecated in 0.11
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#9133 Fix for vertical text bounds and alignment
  crates/bevy_text/src/glyph_brush.rs
  crates/bevy_text/src/pipeline.rs
Labels: C-Bug, A-UI

#9120 Add `GltfLoader::new`.
  crates/bevy_gltf/src/loader.rs
Labels: A-Assets, C-Usability, C-Regression

#9068 Put `#[repr(transparent)]` attr to bevy_ptr types
  crates/bevy_ptr/src/lib.rs
Labels: S-Ready-For-Final-Review, C-Unsoundness, A-Pointers

#9093 Clarify that wgpu is based on the webGPU API
  README.md
Labels: C-Docs, A-Rendering, S-Controversial

#9159 Rename bevy_math::rects conversion methods
  crates/bevy_math/src/rects/rect.rs
  crates/bevy_math/src/rects/urect.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Math, C-Breaking-Change

#9162 Fix doc typo
  crates/bevy_render/src/mesh/morph.rs
Labels: C-Docs, A-Animation

#9129 Fix gizmo draw order in 2D
  crates/bevy_gizmos/src/pipeline_2d.rs
Labels: C-Bug, A-Rendering, A-Gizmos

#9085 Return URect instead of (UVec2, UVec2) in Camera::physical_viewport_rect
  crates/bevy_core_pipeline/src/bloom/settings.rs
  crates/bevy_math/src/lib.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_ui/src/render/mod.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#9132 impl `From<&AssetPath>` for `HandleId`
  crates/bevy_asset/src/handle.rs
Labels: A-Assets, C-Usability

#9186 fix module name for AssetPath shaders
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/render_resource/shader.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#9169 Fix UI corruption for AMD gpus with Vulkan
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/pipeline.rs
  crates/bevy_ui/src/render/render_pass.rs
Labels: C-Bug, A-Rendering, A-UI, S-Ready-For-Final-Review

#9204 Add the Has world query to bevy_ecs::prelude
  crates/bevy_ecs/src/lib.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#9207 Add some more helpful errors to BevyManifest when it doesn't find Cargo.toml
  crates/bevy_macro_utils/src/lib.rs
Labels: S-Ready-For-Final-Review

#9219 Fix path reference to contributors example
  examples/2d/text2d.rs
Labels: C-Docs, C-Examples, S-Ready-For-Final-Review

#9222 Register `AlphaMode` type
  crates/bevy_pbr/src/lib.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, A-Reflection

#9223 replace parens with square brackets when referencing _mut on `Query` docs #9200
  crates/bevy_ecs/src/system/query.rs
Labels: C-Docs, S-Ready-For-Final-Review

#8204 Add GpuArrayBuffer and BatchedUniformBuffer
  crates/bevy_render/src/gpu_component_array_buffer.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_resource/batched_uniform_buffer.rs
  crates/bevy_render/src/render_resource/buffer_vec.rs
  crates/bevy_render/src/render_resource/gpu_array_buffer.rs
  crates/bevy_render/src/render_resource/mod.rs
  crates/bevy_render/src/render_resource/storage_buffer.rs
  crates/bevy_render/src/render_resource/uniform_buffer.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#9230 Update `bevy_window::PresentMode` to mirror `wgpu::PresentMode`
  crates/bevy_render/src/view/window.rs
  crates/bevy_window/src/window.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9175 Replace AHash with a good sequence for entity AABB colors
  crates/bevy_gizmos/src/lib.rs
Labels: C-Enhancement, C-Usability, S-Ready-For-Final-Review, A-Gizmos

#9229 use AutoNoVsync in stress tests
  examples/stress_tests/many_glyphs.rs
  examples/stress_tests/text_pipeline.rs
Labels: C-Examples, S-Ready-For-Final-Review

#9166 gizmo plugin lag bugfix
  crates/bevy_gizmos/src/lib.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Gizmos

#9191 Add reflect impls to IRect and URect
  crates/bevy_math/src/rects/irect.rs
  crates/bevy_math/src/rects/urect.rs
  crates/bevy_reflect/src/impls/rect.rs
Labels: S-Ready-For-Final-Review, A-Reflection, A-Math

#9083 Add option to toggle window control buttons
  crates/bevy_window/src/lib.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/converters.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/window/window_settings.rs
Labels: C-Enhancement, A-Windowing, S-Ready-For-Final-Review, C-Breaking-Change

#9174 Add `track_caller` to `App::add_plugins`
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/plugin.rs
  crates/bevy_app/src/plugin_group.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-App

#9052 Stop using unwrap in the pipelined rendering thread
  crates/bevy_render/src/pipelined_rendering.rs
Labels: C-Bug, A-Rendering, C-Crash, S-Ready-For-Final-Review

#9194 add `MutUntyped::map_unchanged`
  crates/bevy_ecs/src/change_detection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Reflection, A-Pointers

#9158 Fix panic whilst loading UASTC encoded ktx2 textures
  crates/bevy_gltf/src/lib.rs
  crates/bevy_render/src/texture/image_texture_loader.rs
  crates/bevy_render/src/texture/mod.rs
Labels: A-Rendering, C-Crash, S-Ready-For-Final-Review

#8854 Simplify parallel iteration methods
  benches/benches/bevy_ecs/iteration/heavy_compute.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_transform/src/systems.rs
  examples/ecs/parallel_query.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, D-Complex

#9249 bevy_render: Remove direct dep on wgpu-hal.
  crates/bevy_render/Cargo.toml
Labels: S-Ready-For-Final-Review

#9099 UI extraction order fix
  crates/bevy_ui/src/render/mod.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#9259 Update text example using default font
  examples/ui/text.rs
Labels: C-Examples, A-UI, S-Ready-For-Final-Review

#9252 only check for bans if the dependency tree changed
  .github/workflows/dependencies.yml
Labels: A-Build-System

#9237 Revert "Fix UI corruption for AMD gpus with Vulkan (#9169)"
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/pipeline.rs
  crates/bevy_ui/src/render/render_pass.rs
Labels: A-Rendering, A-UI

#8246 Fix safety invariants for `WorldQuery::fetch` and simplify cloning
  crates/bevy_ecs/macros/src/fetch.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/iter.rs
Labels: A-ECS, C-Code-Quality, C-Breaking-Change, C-Unsoundness

#9276 Fixed typo in line 322
  examples/shader/post_processing.rs
Labels: C-Docs, S-Ready-For-Final-Review

#9301 Fixed: Default window is now "App" instead of "Bevy App"
  crates/bevy_window/src/window.rs
Labels: A-Windowing, C-Usability, S-Ready-For-Final-Review

#9295 bevy_ui: fix doc formatting for some Style fields
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#9288 Document `ClearColorConfig`
  crates/bevy_core_pipeline/src/clear_color.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#9225 Added Pitch as an alternative sound source
  Cargo.toml
  crates/bevy_audio/src/lib.rs
  crates/bevy_audio/src/pitch.rs
  examples/README.md
  examples/audio/pitch.rs
Labels: C-Enhancement, A-Audio, S-Ready-For-Final-Review

#9254 Use GpuArrayBuffer for MeshUniform
  assets/shaders/custom_vertex_attribute.wgsl
  assets/shaders/instancing.wgsl
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass.wgsl
  crates/bevy_pbr/src/prepass/prepass_bindings.wgsl
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh.wgsl
  crates/bevy_pbr/src/render/mesh_bindings.rs
  crates/bevy_pbr/src/render/mesh_bindings.wgsl
  crates/bevy_pbr/src/render/mesh_functions.wgsl
  crates/bevy_pbr/src/render/mesh_vertex_output.wgsl
  crates/bevy_pbr/src/render/pbr.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/wireframe.wgsl
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/gpu_component_array_buffer.rs
Labels: A-Rendering, C-Performance

#9290 Fix timers.rs documentation
  examples/ecs/timers.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Time

#9297 Update docs for scaling_mode field of Orthographic projection
  crates/bevy_render/src/camera/projection.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#9293 Derive debug for ManualEventIterator
  crates/bevy_ecs/src/event.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#9173 improve documentation relating to `WindowPlugin` and `Window`
  crates/bevy_window/src/lib.rs
  crates/bevy_window/src/window.rs
Labels: C-Docs, A-Windowing, S-Ready-For-Final-Review

#8887 Refactor `path` module of `bevy_reflect`
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/path/access.rs
  crates/bevy_reflect/src/path/mod.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Reflection, C-Breaking-Change

#9311 Fix shader_material_glsl example after #9254
  assets/shaders/custom_material.vert
  crates/bevy_pbr/src/render/mesh.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#9061 Improve `Mesh` documentation
  assets/docs/Mesh.png
  crates/bevy_asset/src/loader.rs
  crates/bevy_gltf/src/lib.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#9067 Fix gizmo line width issue when using perspective
  crates/bevy_gizmos/src/lines.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, A-Gizmos

#9084 Include tone_mapping fn in tonemapping_test_patterns
  assets/shaders/tonemapping_test_patterns.wgsl
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#9183 Clarify immediate mode in `Gizmos` documentation
  crates/bevy_gizmos/src/gizmos.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Gizmos

#9281 Implement reflect trait on new glam types (I64Vec and U64Vec)
  crates/bevy_reflect/src/impls/glam.rs
Labels: S-Ready-For-Final-Review, A-Reflection, A-Math

#9310 Extend the default render range of 2D camera
  crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#9285 Remove the `With<Parent>` query filter from `bevy_ui::render::extract_uinode_borders`
  crates/bevy_ui/src/render/mod.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#7609 Improve `bevy_winit` documentation
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_config.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/window/low_power.rs
Labels: C-Docs, A-Windowing, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#9291 Add `EntityMap::clear`
  crates/bevy_ecs/src/entity/map_entities.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review
