Repository bevyengine/bevy, pull requests merged in 2023-10, with the labels that each got.

#9981 ignore time channel error
  crates/bevy_render/src/renderer/mod.rs
  crates/bevy_time/src/lib.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Time

#9966 Parallelize extract_meshes
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/render/mesh.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#9949 Finish documenting `bevy_scene`
  crates/bevy_scene/src/bundle.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_scene/src/scene.rs
  crates/bevy_scene/src/scene_loader.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_scene/src/serde.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Scenes

#9990 Fix comment grammar
  crates/bevy_core_pipeline/src/skybox/skybox.wgsl
Labels: C-Docs, A-Rendering

#9984 Only attempt to copy resources that still exist from scenes
  crates/bevy_scene/src/scene.rs
Labels: C-Bug, C-Crash, S-Ready-For-Final-Review, A-Scenes

#9956 Moved `fq_std` from `bevy_reflect_derive` to `bevy_macro_utils`
  crates/bevy_macro_utils/Cargo.toml
  crates/bevy_macro_utils/src/attrs.rs
  crates/bevy_macro_utils/src/bevy_manifest.rs
  crates/bevy_macro_utils/src/fq_std.rs
  crates/bevy_macro_utils/src/label.rs
  crates/bevy_macro_utils/src/lib.rs
  crates/bevy_macro_utils/src/symbol.rs
  crates/bevy_reflect/bevy_reflect_derive/src/container_attributes.rs
  crates/bevy_reflect/bevy_reflect_derive/src/documentation.rs
  crates/bevy_reflect/bevy_reflect_derive/src/enum_utility.rs
  crates/bevy_reflect/bevy_reflect_derive/src/from_reflect.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/enums.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/tuple_structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/values.rs
  crates/bevy_reflect/bevy_reflect_derive/src/lib.rs
  crates/bevy_reflect/bevy_reflect_derive/src/trait_reflection.rs
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Reflection, A-Utils

#9991 Revert "macOS Sonoma (14.0) / Xcode 15.0 — Compatibility Fixes + Docs…
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/lib.rs
Labels: A-Windowing, O-MacOS

#9912 `as_deref_mut()` method for Mut-like types
  crates/bevy_ecs/src/change_detection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#9959 refactor: Change Option<With<T>> query params to Has<T>
  crates/bevy_animation/src/lib.rs
  crates/bevy_pbr/src/render/mesh.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#9315 Improve TypeUuid's derive macro error messages
  crates/bevy_reflect/bevy_reflect_derive/src/lib.rs
  crates/bevy_reflect/bevy_reflect_derive/src/type_uuid.rs
  crates/bevy_reflect_compile_fail_tests/tests/type_uuid_derive.rs
  crates/bevy_reflect_compile_fail_tests/tests/type_uuid_derive/derive_type_uuid.rs
  crates/bevy_reflect_compile_fail_tests/tests/type_uuid_derive/derive_type_uuid.stderr
Labels: C-Code-Quality, C-Usability, S-Ready-For-Final-Review, A-Reflection

#9545 Replaced `parking_lot` with `std::sync`
  crates/bevy_audio/Cargo.toml
  crates/bevy_reflect/Cargo.toml
  crates/bevy_reflect/src/type_registry.rs
  crates/bevy_reflect/src/utility.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/render_phase/draw.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/view/window/mod.rs
  crates/bevy_render/src/view/window/screenshot.rs
Labels: C-Dependencies, C-Code-Quality, S-Ready-For-Final-Review

#9741 Hide `UnsafeWorldCell::unsafe_world`
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/removal_detection.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Unsoundness

#9824 Add inline(never) to bench systems
  benches/benches/bevy_ecs/iteration/iter_frag.rs
  benches/benches/bevy_ecs/iteration/iter_frag_foreach.rs
  benches/benches/bevy_ecs/iteration/iter_frag_foreach_sparse.rs
  benches/benches/bevy_ecs/iteration/iter_frag_foreach_wide.rs
  benches/benches/bevy_ecs/iteration/iter_frag_foreach_wide_sparse.rs
  benches/benches/bevy_ecs/iteration/iter_frag_sparse.rs
  benches/benches/bevy_ecs/iteration/iter_frag_wide.rs
  benches/benches/bevy_ecs/iteration/iter_frag_wide_sparse.rs
  benches/benches/bevy_ecs/iteration/iter_simple.rs
  benches/benches/bevy_ecs/iteration/iter_simple_foreach.rs
  benches/benches/bevy_ecs/iteration/iter_simple_foreach_sparse_set.rs
  benches/benches/bevy_ecs/iteration/iter_simple_foreach_wide.rs
  benches/benches/bevy_ecs/iteration/iter_simple_foreach_wide_sparse_set.rs
  benches/benches/bevy_ecs/iteration/iter_simple_sparse_set.rs
  benches/benches/bevy_ecs/iteration/iter_simple_system.rs
  benches/benches/bevy_ecs/iteration/iter_simple_wide.rs
  benches/benches/bevy_ecs/iteration/iter_simple_wide_sparse_set.rs
Labels: C-Usability, S-Ready-For-Final-Review

#9825 Add a public API to ArchetypeGeneration/Id
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/function_system.rs
Labels: C-Enhancement, A-ECS, C-Performance, S-Ready-For-Final-Review

#9994 Fixed: README.md
  README.md
Labels: C-Docs, A-Build-System, A-Meta, S-Ready-For-Final-Review

#9992 Import the second UV map if present in glTF files.
  crates/bevy_gltf/src/vertex_attributes.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh.wgsl
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: A-Rendering, A-Assets, C-Usability, S-Ready-For-Final-Review

#9989 Various accessibility API updates.
  crates/bevy_a11y/Cargo.toml
  crates/bevy_a11y/src/lib.rs
  crates/bevy_ui/src/accessibility.rs
  crates/bevy_window/Cargo.toml
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/accessibility.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Accessibility, A-UI, P-High, S-Ready-For-Final-Review

#9796 Allow `clippy::type_complexity` in more places.
  crates/bevy_asset/src/lib.rs
  docs/linters.md
  examples/3d/anti_aliasing.rs
  examples/3d/shadow_caster_receiver.rs
  examples/3d/ssao.rs
  examples/ecs/custom_query_param.rs
  examples/ecs/state.rs
  examples/games/alien_cake_addict.rs
  examples/games/game_menu.rs
  examples/input/text_input.rs
  examples/mobile/src/lib.rs
  examples/tools/scene_viewer/scene_viewer_plugin.rs
  examples/ui/button.rs
  tools/ci/src/main.rs
Labels: A-Build-System, C-Examples, C-Code-Quality, S-Ready-For-Final-Review, C-Testing

#9998 Finish documenting `bevy_gltf`
  crates/bevy_gltf/src/lib.rs
  crates/bevy_gltf/src/loader.rs
Labels: C-Docs, A-Assets, S-Ready-For-Final-Review, A-Animation

#7328 Allow overriding global wireframe setting.
  crates/bevy_pbr/src/wireframe.rs
  examples/3d/wireframe.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#9895 Ignore ambiguous components or resources
  crates/bevy_app/src/app.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#10022 wireframes: workaround for DX12
  crates/bevy_pbr/src/render/wireframe.wgsl
Labels: A-Rendering, S-Ready-For-Final-Review, O-DX12

#10010 Finish documenting `bevy_gilrs`
  clippy.toml
  crates/bevy_gilrs/src/lib.rs
Labels: C-Docs, A-Input, S-Ready-For-Final-Review

#10012 Fix some warnings shown in nightly
  crates/bevy_hierarchy/src/child_builder.rs
  examples/shader/post_processing.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#10026 add test for nested scopes
  crates/bevy_tasks/src/task_pool.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Tasks

#9931 UI node outlines
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/ui_node.rs
  examples/ui/borders.rs
Labels: C-Enhancement, A-UI, S-Ready-For-Final-Review

#10023 Alternate wireframe override api
  crates/bevy_pbr/src/wireframe.rs
  examples/3d/wireframe.rs
Labels: A-Rendering, C-Performance, C-Usability, S-Ready-For-Final-Review

#10035 Updates for rust 1.73
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/plugin.rs
  crates/bevy_audio/src/audio_output.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_ecs/src/world/world_cell.rs
  crates/bevy_ecs_compile_fail_tests/tests/ui/entity_ref_mut_lifetime_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_lifetime_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_to_readonly.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/system_query_get_lifetime_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/system_query_get_many_lifetime_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/system_query_get_many_mut_lifetime_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/system_query_iter_lifetime_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/system_query_iter_many_mut_lifetime_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/system_query_set_get_lifetime_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/system_query_set_iter_lifetime_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/system_state_iter_mut_overlap_safety.stderr
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_input/src/input.rs
  crates/bevy_input/src/keyboard.rs
  crates/bevy_input/src/mouse.rs
  crates/bevy_input/src/touch.rs
  crates/bevy_reflect/bevy_reflect_derive/src/derive_data.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/extract_component.rs
  crates/bevy_render/src/extract_resource.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_asset.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/render_resource/buffer_vec.rs
  crates/bevy_render/src/render_resource/gpu_array_buffer.rs
  crates/bevy_render/src/render_resource/storage_buffer.rs
  crates/bevy_render/src/render_resource/uniform_buffer.rs
  crates/bevy_render/src/settings.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_transform/src/lib.rs
  crates/bevy_winit/src/lib.rs
Labels: S-Ready-For-Final-Review

#10030 fix custom shader imports
  assets/shaders/custom_material.wgsl
  assets/shaders/custom_material_import.wgsl
  crates/bevy_render/src/render_resource/shader.rs
Labels: C-Bug, A-Rendering, A-Assets, S-Ready-For-Final-Review

#10003 Removed `anyhow`
  Cargo.toml
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/io/android.rs
  crates/bevy_asset/src/io/file/file_watcher.rs
  crates/bevy_asset/src/io/file/mod.rs
  crates/bevy_asset/src/io/gated.rs
  crates/bevy_asset/src/io/memory.rs
  crates/bevy_asset/src/io/processor_gated.rs
  crates/bevy_asset/src/io/wasm.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/loader.rs
  crates/bevy_asset/src/meta.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/processor/process.rs
  crates/bevy_asset/src/saver.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_audio/src/audio_source.rs
  crates/bevy_gltf/src/loader.rs
  crates/bevy_render/src/render_resource/shader.rs
  crates/bevy_render/src/texture/compressed_image_saver.rs
  crates/bevy_render/src/texture/exr_texture_loader.rs
  crates/bevy_render/src/texture/hdr_texture_loader.rs
  crates/bevy_render/src/texture/image_loader.rs
  crates/bevy_render/src/texture/image_texture_conversion.rs
  crates/bevy_scene/src/scene_loader.rs
  crates/bevy_text/src/font_loader.rs
  examples/asset/custom_asset.rs
  examples/asset/processing/processing.rs
Labels: A-Assets, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#10020 Allow Bevy to start from non-main threads on supported platforms
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_winit/src/lib.rs
Labels: A-Windowing, S-Ready-For-Final-Review

#10031 Fix TextureAtlasBuilder padding
  crates/bevy_sprite/src/texture_atlas_builder.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#9941 fix example mesh2d_manual
  crates/bevy_sprite/src/mesh2d/mesh.rs
  examples/2d/mesh2d_manual.rs
Labels: A-Rendering, C-Examples

#8006 PCF For DirectionalLight/SpotLight Shadows
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/shadow_sampling.wgsl
  crates/bevy_pbr/src/render/shadows.wgsl
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, C-Breaking-Change

#10002 Refactor the render instance logic in #9903 so that it's easier for other components to adopt.
  crates/bevy_pbr/src/material.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_instances.rs
Labels: A-Rendering, C-Performance, C-Usability, S-Ready-For-Final-Review

#10051 Fix 2d_shapes and general 2D mesh instancing
  crates/bevy_internal/Cargo.toml
  crates/bevy_sprite/Cargo.toml
  crates/bevy_sprite/src/mesh2d/mesh.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, C-Regression

#9282 Improve selection of iOS device in mobile example
  examples/mobile/Makefile
Labels: C-Examples, O-iOS, S-Ready-For-Final-Review

#10053 fix webgl2 crash
  crates/bevy_pbr/src/render/shadow_sampling.wgsl
Labels: A-Rendering, O-WebGL2

#9614 fix orthographic cluster aabb for spotlight culling
  crates/bevy_pbr/src/light.rs
Labels: C-Bug, A-Rendering

#8768 reflect: `TypePath` part 2
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/reflect/bundle.rs
  crates/bevy_ecs/src/reflect/entity_commands.rs
  crates/bevy_reflect/bevy_reflect_derive/src/derive_data.rs
  crates/bevy_reflect/bevy_reflect_derive/src/from_reflect.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/enums.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/tuple_structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/values.rs
  crates/bevy_reflect/src/array.rs
  crates/bevy_reflect/src/enums/dynamic_enum.rs
  crates/bevy_reflect/src/enums/enum_trait.rs
  crates/bevy_reflect/src/enums/mod.rs
  crates/bevy_reflect/src/fields.rs
  crates/bevy_reflect/src/from_reflect.rs
  crates/bevy_reflect/src/impls/smallvec.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/list.rs
  crates/bevy_reflect/src/map.rs
  crates/bevy_reflect/src/reflect.rs
  crates/bevy_reflect/src/serde/de.rs
  crates/bevy_reflect/src/serde/mod.rs
  crates/bevy_reflect/src/serde/ser.rs
  crates/bevy_reflect/src/struct_trait.rs
  crates/bevy_reflect/src/tuple.rs
  crates/bevy_reflect/src/tuple_struct.rs
  crates/bevy_reflect/src/type_info.rs
  crates/bevy_reflect/src/type_path.rs
  crates/bevy_reflect/src/type_registry.rs
  crates/bevy_reflect/src/utility.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/scene.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_scene/src/serde.rs
  examples/reflection/generic_reflection.rs
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review, A-Reflection, D-Complex

#9800 More ergonomic spatial audio
  crates/bevy_audio/src/audio.rs
  crates/bevy_audio/src/audio_output.rs
  crates/bevy_audio/src/lib.rs
  crates/bevy_audio/src/pitch.rs
  crates/bevy_audio/src/sinks.rs
  examples/audio/decodable.rs
  examples/audio/spatial_audio_2d.rs
  examples/audio/spatial_audio_3d.rs
Labels: C-Enhancement, A-Audio, S-Ready-For-Final-Review, C-Breaking-Change

#10001 Make builder types take and return `Self`
  crates/bevy_ecs/src/storage/table.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/dynamic_scene_builder.rs
  crates/bevy_scene/src/scene_filter.rs
  crates/bevy_scene/src/serde.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Scenes, C-Breaking-Change

#10056 Add consuming builder methods for more ergonomic `Mesh` creation
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/mesh/shape/capsule.rs
  crates/bevy_render/src/mesh/shape/cylinder.rs
  crates/bevy_render/src/mesh/shape/icosphere.rs
  crates/bevy_render/src/mesh/shape/mod.rs
  crates/bevy_render/src/mesh/shape/regular_polygon.rs
  crates/bevy_render/src/mesh/shape/torus.rs
  crates/bevy_render/src/mesh/shape/uvsphere.rs
  examples/3d/generate_custom_mesh.rs
  examples/3d/lines.rs
  examples/3d/parallax_mapping.rs
  examples/animation/custom_skinned_mesh.rs
  examples/shader/custom_vertex_attribute.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#9302 wgpu 0.17
  .github/example-run/minimising.ron
  .github/example-run/resizing.ron
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/ssao/gtao.wgsl
  crates/bevy_pbr/src/ssao/spatial_denoise.wgsl
  crates/bevy_render/Cargo.toml
Labels: A-Rendering, C-Dependencies, S-Ready-For-Final-Review

#10068 Migrate `Quat` reflection strategy from "value" to "struct"
  crates/bevy_reflect/src/impls/glam.rs
  crates/bevy_reflect/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#10070 foxes shouldn't march in sync
  examples/stress_tests/many_foxes.rs
Labels: C-Examples

#10044 Implement serialize and deserialize for some UI types
  crates/bevy_ui/src/ui_node.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#5314 use `Material` for wireframes
  crates/bevy_pbr/src/render/wireframe.wgsl
  crates/bevy_pbr/src/wireframe.rs
  examples/3d/wireframe.rs
Labels: A-Rendering, C-Code-Quality, C-Usability, S-Ready-For-Final-Review

#10074 Document that gizmo `depth_bias` has no effect in 2D
  crates/bevy_gizmos/src/lib.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Gizmos

#10080 Extract common wireframe filters in type alias
  crates/bevy_pbr/src/wireframe.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#10092 Fix tonemapping test patten
  assets/shaders/tonemapping_test_patterns.wgsl
Labels: C-Bug, C-Examples, S-Ready-For-Final-Review

#10079 Removed `once_cell`
  crates/bevy_reflect/Cargo.toml
  crates/bevy_reflect/src/utility.rs
Labels: C-Dependencies, C-Code-Quality, S-Ready-For-Final-Review

#10090 Change `AxisSettings` livezone default
  crates/bevy_input/src/gamepad.rs
Labels: C-Bug, A-Input, S-Ready-For-Final-Review, C-Breaking-Change

#9258 Deferred Renderer
  Cargo.toml
  assets/shaders/array_texture.wgsl
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/deferred/copy_deferred_lighting_id.wgsl
  crates/bevy_core_pipeline/src/deferred/copy_lighting_id.rs
  crates/bevy_core_pipeline/src/deferred/mod.rs
  crates/bevy_core_pipeline/src/deferred/node.rs
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_pbr/src/deferred/deferred_lighting.wgsl
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/deferred/pbr_deferred_functions.wgsl
  crates/bevy_pbr/src/deferred/pbr_deferred_types.wgsl
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass.wgsl
  crates/bevy_pbr/src/prepass/prepass_bindings.wgsl
  crates/bevy_pbr/src/prepass/prepass_io.wgsl
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.wgsl
  crates/bevy_pbr/src/render/pbr.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
  crates/bevy_pbr/src/render/pbr_prepass_functions.wgsl
  crates/bevy_pbr/src/render/pbr_types.wgsl
  crates/bevy_pbr/src/render/rgb9e5.wgsl
  crates/bevy_pbr/src/render/utils.wgsl
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_render/src/texture/fallback_image.rs
  crates/bevy_render/src/texture/mod.rs
  examples/3d/deferred_rendering.rs
  examples/README.md
  tests/3d/no_prepass.rs
Labels: A-Rendering, C-Breaking-Change

#5303 Configurable colors for wireframe
  crates/bevy_pbr/src/render/wireframe.wgsl
  crates/bevy_pbr/src/wireframe.rs
  examples/3d/wireframe.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#10078 Fix UI borders
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/render_pass.rs
Labels: C-Bug, A-Rendering, A-UI

#10105 pbr shader cleanup
  assets/shaders/animate_shader.wgsl
  assets/shaders/array_texture.wgsl
  assets/shaders/cubemap_unlit.wgsl
  assets/shaders/custom_material.wgsl
  assets/shaders/custom_material_screenspace_texture.wgsl
  assets/shaders/fallback_image_test.wgsl
  assets/shaders/line_material.wgsl
  assets/shaders/shader_defs.wgsl
  assets/shaders/show_prepass.wgsl
  assets/shaders/texture_binding_array.wgsl
  assets/shaders/tonemapping_test_patterns.wgsl
  crates/bevy_pbr/src/deferred/deferred_lighting.wgsl
  crates/bevy_pbr/src/prepass/prepass.wgsl
  crates/bevy_pbr/src/prepass/prepass_io.wgsl
  crates/bevy_pbr/src/render/forward_io.wgsl
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh.wgsl
  crates/bevy_pbr/src/render/mesh_vertex_output.wgsl
  crates/bevy_pbr/src/render/pbr.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
  crates/bevy_pbr/src/render/pbr_prepass_functions.wgsl
  crates/bevy_pbr/src/render/wireframe.wgsl
  crates/bevy_sprite/src/mesh2d/color_material.wgsl
  crates/bevy_sprite/src/mesh2d/mesh2d.wgsl
  crates/bevy_sprite/src/mesh2d/mesh2d_vertex_output.wgsl
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#10100 Fix text2d view-visibility
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_text/src/text2d.rs
Labels: C-Bug, A-Rendering, P-High

#9220 hacks for running (and screenshotting) the examples in CI on a github runner
  tools/example-showcase/extra-window-resized-events.patch
  tools/example-showcase/fixed-window-position.patch
  tools/example-showcase/reduce-light-cluster-config.patch
  tools/example-showcase/remove-desktop-app-mode.patch
  tools/example-showcase/src/main.rs
Labels: A-Build-System, C-Examples, S-Ready-For-Final-Review

#9360 GLTF loader: handle warning NODE_SKINNED_MESH_WITHOUT_SKIN
  crates/bevy_gltf/src/loader.rs
Labels: C-Bug, C-Enhancement, A-Rendering, S-Ready-For-Final-Review, A-Diagnostics

#9885 Multiple Asset Sources
  Cargo.toml
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/io/android.rs
  crates/bevy_asset/src/io/embedded/embedded_watcher.rs
  crates/bevy_asset/src/io/embedded/mod.rs
  crates/bevy_asset/src/io/file/file_watcher.rs
  crates/bevy_asset/src/io/file/mod.rs
  crates/bevy_asset/src/io/gated.rs
  crates/bevy_asset/src/io/memory.rs
  crates/bevy_asset/src/io/mod.rs
  crates/bevy_asset/src/io/processor_gated.rs
  crates/bevy_asset/src/io/provider.rs
  crates/bevy_asset/src/io/source.rs
  crates/bevy_asset/src/io/wasm.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/loader.rs
  crates/bevy_asset/src/path.rs
  crates/bevy_asset/src/processor/log.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/processor/process.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_gltf/src/loader.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_tasks/src/single_threaded_task_pool.rs
  crates/bevy_utils/src/cow_arc.rs
  docs/cargo_features.md
  examples/asset/custom_asset_reader.rs
  examples/asset/hot_asset_reloading.rs
  examples/asset/processing/e.txt
  examples/asset/processing/processing.rs
  examples/scene/scene.rs
  examples/shader/post_processing.rs
  examples/tools/scene_viewer/main.rs
Labels: C-Enhancement, A-Assets

#10109 Allow optional extraction of resources from the main world
  crates/bevy_render/src/extract_resource.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#10117 ssao use unlit_color instead of white
  crates/bevy_pbr/src/render/pbr.wgsl
Labels: C-Bug, A-Rendering

#10119 Make loading warning for no file ext more descriptive
  crates/bevy_asset/src/server/mod.rs
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review

#9993 add and fix shields in Readmes
  README.md
  crates/bevy_app/README.md
  crates/bevy_ecs/README.md
  crates/bevy_mikktspace/README.md
  crates/bevy_ptr/README.md
  crates/bevy_reflect/README.md
  crates/bevy_tasks/README.md
  crates/bevy_utils/Readme.md
Labels: A-Meta, S-Ready-For-Final-Review

#10128 Fix missing explicit lifetime name for copy_deferred_lighting_id name
  crates/bevy_core_pipeline/src/deferred/copy_lighting_id.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#10121 Fix load_folder for non-default Asset Sources
  crates/bevy_asset/src/server/mod.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#10123 only set up processed source if asset plugin is not unprocessed
  crates/bevy_asset/src/io/source.rs
  crates/bevy_asset/src/lib.rs
Labels: A-Assets, O-iOS

#9736 Hot reload labeled assets whose source asset is not loaded
  crates/bevy_asset/src/server/info.rs
  crates/bevy_asset/src/server/mod.rs
Labels: C-Bug, A-Assets

#9751 Return an error when loading non-existent labels
  crates/bevy_asset/src/path.rs
  crates/bevy_asset/src/server/mod.rs
Labels: A-Assets, C-Usability

#8964 Unify `FixedTime` and `Time` while fixing several problems
  Cargo.toml
  crates/bevy_diagnostic/src/frame_time_diagnostics_plugin.rs
  crates/bevy_diagnostic/src/log_diagnostics_plugin.rs
  crates/bevy_gilrs/src/rumble.rs
  crates/bevy_render/src/globals.rs
  crates/bevy_time/src/common_conditions.rs
  crates/bevy_time/src/fixed.rs
  crates/bevy_time/src/fixed_timestep.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_time/src/real.rs
  crates/bevy_time/src/stopwatch.rs
  crates/bevy_time/src/time.rs
  crates/bevy_time/src/virt.rs
  examples/2d/rotation.rs
  examples/README.md
  examples/ecs/fixed_timestep.rs
  examples/ecs/iter_combinations.rs
  examples/ecs/time.rs
  examples/games/breakout.rs
  examples/stress_tests/bevymark.rs
Labels: C-Bug, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, D-Complex, S-Controversial, A-Time

#10132 Fixed mod.rs in rendering to support Radeon Cards
  crates/bevy_render/src/view/window/mod.rs
Labels: C-Bug, A-Rendering, C-Crash, S-Ready-For-Final-Review

#9025 Explain usage of prepass shaders in docs for `Material` trait
  crates/bevy_pbr/src/material.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#10111 Change visibility of `bevy::core::update_frame_count` to `pub`
  crates/bevy_core/src/lib.rs
Labels: A-Core, C-Usability, S-Ready-For-Final-Review

#10142 Better link for prepare_windows docs
  docs/profiling.md
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#10145 Time: demote delta time clamping warning to debug
  crates/bevy_time/src/virt.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Time

#10144 Fix unlit missing parameters
  crates/bevy_pbr/src/render/pbr.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#10124 Use chain in breakout example
  examples/games/breakout.rs
Labels: A-ECS, C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#10151 make CI less failing on cargo deny bans
  deny.toml
Labels: A-Build-System, C-Dependencies, S-Ready-For-Final-Review

#10103 bevy_reflect: Fix dynamic type serialization
  crates/bevy_reflect/src/serde/mod.rs
  crates/bevy_reflect/src/serde/ser.rs
  crates/bevy_reflect/src/type_path.rs
Labels: S-Ready-For-Final-Review, C-Regression, A-Reflection

#10136 `*_PREPASS` Shader Def Cleanup
  crates/bevy_pbr/src/deferred/deferred_lighting.wgsl
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass_utils.wgsl
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/pbr.wgsl
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#10152 fix typo in time.rs example
  examples/ecs/time.rs
Labels: C-Examples, A-Time

#10148 add test on Android 14 / Pixel 8
  .github/workflows/daily.yml
Labels: A-Build-System, O-Android, S-Ready-For-Final-Review

#10161 Correct Scene loader error description
  crates/bevy_scene/src/scene_loader.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Scenes

#10160 check for any prepass phase
  crates/bevy_pbr/src/prepass/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#7820 allow extensions to StandardMaterial
  Cargo.toml
  assets/shaders/extended_material.wgsl
  crates/bevy_pbr/src/deferred/deferred_lighting.wgsl
  crates/bevy_pbr/src/deferred/pbr_deferred_functions.wgsl
  crates/bevy_pbr/src/extended_material.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/pbr.wgsl
  crates/bevy_pbr/src/render/pbr_fragment.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  examples/README.md
  examples/shader/extended_material.rs
  examples/shader/texture_binding_array.rs
Labels: C-Enhancement, A-Rendering, C-Breaking-Change

#10171 Added section for contributing and links for issues and PRs
  README.md
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review

#10173 fix typos in crates/bevy_app/src/app.rs
  crates/bevy_app/src/app.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-App

#10174 Fix orphaned contributing paragraph
  README.md
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review

#9826 Prevent black frames during startup
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_winit/src/lib.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review

#10191 chore: use ExtractComponent derive macro for EnvironmentMapLight and FogSettings
  crates/bevy_pbr/src/environment_map/mod.rs
  crates/bevy_pbr/src/fog.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#10197 remove unused import on android
  crates/bevy_asset/src/io/android.rs
Labels: A-Assets, O-Android, S-Ready-For-Final-Review

#10179 add on_real_time_timer run condition
  crates/bevy_time/src/common_conditions.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Time

#10202 Log an error when registering an AssetSource after AssetPlugin has been built
  crates/bevy_asset/src/lib.rs
Labels: A-Assets, C-Usability

#10194 Add `asset_processor` feature and remove AssetMode::ProcessedDev
  Cargo.toml
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/lib.rs
  crates/bevy_internal/Cargo.toml
  docs/cargo_features.md
  examples/asset/processing/processing.rs
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review

#10156 Variable `MeshPipeline` View Bind Group Layout
  clippy.toml
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass_bindings.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.wgsl
  crates/bevy_pbr/src/render/mod.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#9694 Bind group entries
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/node.rs
  crates/bevy_core_pipeline/src/deferred/copy_lighting_id.rs
  crates/bevy_core_pipeline/src/fxaa/node.rs
  crates/bevy_core_pipeline/src/msaa_writeback.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/node.rs
  crates/bevy_core_pipeline/src/upscaling/node.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/environment_map/mod.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass_bindings.rs
  crates/bevy_pbr/src/render/mesh_bindings.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/render_resource/bind_group_entries.rs
  crates/bevy_render/src/render_resource/mod.rs
  crates/bevy_render/src/render_resource/uniform_buffer.rs
  crates/bevy_render/src/renderer/render_device.rs
  crates/bevy_render/src/view/window/mod.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_utils/macros/src/lib.rs
  examples/shader/compute_shader_game_of_life.rs
  examples/shader/post_processing.rs
  examples/shader/texture_binding_array.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, S-Controversial

#10189 Tidy up UI node docs
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#10211 `ParamSet`s containing non-send parameters should also be non-send
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/system/system_param.rs
Labels: C-Bug, A-ECS, C-Crash, S-Ready-For-Final-Review

#10222 Detect cubemap for dds textures
  crates/bevy_render/src/texture/dds.rs
  crates/bevy_render/src/texture/image.rs
Labels: A-Rendering, C-Usability, C-Breaking-Change

#10178 Fix alignment on ios simulator
  crates/bevy_render/src/render_resource/uniform_buffer.rs
  examples/mobile/.cargo/config.toml
  examples/mobile/build_rust_deps.sh
Labels: A-Rendering, O-iOS

#10221 Add convenient methods for Image
  crates/bevy_render/src/texture/compressed_image_saver.rs
  crates/bevy_render/src/texture/image.rs
  crates/bevy_sprite/src/lib.rs
  examples/3d/tonemapping.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#7575 bevy_reflect: Fix ignored/skipped field order
  crates/bevy_reflect/bevy_reflect_derive/Cargo.toml
  crates/bevy_reflect/bevy_reflect_derive/src/derive_data.rs
  crates/bevy_reflect/bevy_reflect_derive/src/from_reflect.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/enums.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/tuple_structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/lib.rs
  crates/bevy_reflect/bevy_reflect_derive/src/registration.rs
  crates/bevy_reflect/bevy_reflect_derive/src/serialization.rs
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/serde/de.rs
  crates/bevy_reflect/src/serde/mod.rs
  crates/bevy_reflect/src/serde/ser.rs
  crates/bevy_reflect/src/serde/type_data.rs
  crates/bevy_reflect/src/tuple_struct.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Reflection, C-Breaking-Change

#10217 Implement source into Display for AssetPath
  crates/bevy_asset/src/path.rs
Labels: A-Assets, C-Usability

#10206 re-export `debug_glam_assert` feature
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_math/Cargo.toml
  docs/cargo_features.md
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#10182 Use “specular occlusion” term to consistently extinguish fresnel on Ambient and Environment Map lights
  crates/bevy_pbr/src/environment_map/environment_map.wgsl
  crates/bevy_pbr/src/render/pbr_ambient.wgsl
Labels: C-Bug, A-Rendering, C-Usability, S-Ready-For-Final-Review

#10208 assets: use blake3 instead of md5
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/meta.rs
Labels: A-Assets

#10230 Remove unused import warning when default_font feature is disabled
  crates/bevy_text/src/lib.rs
Labels: A-UI, C-Code-Quality, S-Ready-For-Final-Review

#10195 fix run-once runners
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_winit/src/lib.rs
Labels: C-Bug, C-Usability, S-Ready-For-Final-Review, A-App, C-Breaking-Change

#10226 Fix fog color being inaccurate
  crates/bevy_pbr/src/render/fog.rs
  examples/3d/atmospheric_fog.rs
  examples/3d/fog.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, C-Breaking-Change

#10008 Global TaskPool API improvements
  benches/benches/bevy_ecs/iteration/heavy_compute.rs
  crates/bevy_core/src/task_pool_options.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_tasks/src/usages.rs
  crates/bevy_transform/src/systems.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Tasks, C-Breaking-Change

#10158 Application lifetime events (suspend audio on Android)
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/src/lib.rs
  examples/mobile/src/lib.rs
Labels: A-Audio, A-Windowing, O-Android, S-Ready-For-Final-Review

#10227 Replace all usages of texture_descritor.size.* with the helper methods
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/texture/fallback_image.rs
  crates/bevy_render/src/texture/image.rs
  crates/bevy_render/src/texture/image_texture_conversion.rs
  crates/bevy_sprite/src/dynamic_texture_atlas_builder.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_sprite/src/texture_atlas_builder.rs
  crates/bevy_text/src/font_atlas_set.rs
  crates/bevy_ui/src/widget/image.rs
  examples/3d/skybox.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#9726 View Transformations
  crates/bevy_pbr/src/deferred/pbr_deferred_functions.wgsl
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh.wgsl
  crates/bevy_pbr/src/render/mesh_functions.wgsl
  crates/bevy_pbr/src/render/view_transformations.wgsl
  crates/bevy_render/src/camera/camera.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#10249 fix deferred example fog values
  examples/3d/deferred_rendering.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#10251 WebGL2: fix import path for unpack_unorm3x4_plus_unorm_20_
  crates/bevy_pbr/src/deferred/deferred_lighting.wgsl
Labels: A-Rendering

#9982 Add `ImageSamplerDescriptor` as an image loader setting
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_gltf/src/loader.rs
  crates/bevy_render/src/texture/compressed_image_saver.rs
  crates/bevy_render/src/texture/image.rs
  crates/bevy_render/src/texture/image_loader.rs
Labels: C-Bug, A-Rendering, A-Assets

#9847 Use wildcard imports in bevy_pbr
  crates/bevy_pbr/src/environment_map/mod.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_bindings.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_pbr/src/wireframe.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#10259 Make mesh attr vertex count mismatch warn more readable
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#10264 few fmt tweaks
  Cargo.toml
  crates/bevy_asset/Cargo.toml
  crates/bevy_input/Cargo.toml
  crates/bevy_utils/Cargo.toml
Labels: C-Code-Quality, S-Ready-For-Final-Review

#10262 Reduce noise in asset processing example
  Cargo.toml
  examples/README.md
  examples/asset/processing/asset_processing.rs
Labels: C-Examples, A-Assets, S-Ready-For-Final-Review

#7762 Replace all labels with interned labels
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/main_schedule.rs
  crates/bevy_derive/src/lib.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/macros/src/set.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/graph_utils.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/world/error.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_macro_utils/src/label.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_utils/src/intern.rs
  crates/bevy_utils/src/label.rs
  crates/bevy_utils/src/lib.rs
Labels: A-ECS, C-Performance, C-Usability, C-Breaking-Change, D-Complex, S-Controversial

#9528 Adding AssetPath::resolve() method.
  crates/bevy_asset/src/path.rs
Labels: A-Assets, C-Usability

#9804 Assets: fix first hot reloading
  crates/bevy_asset/src/processor/mod.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#10271 Fix crash with certain right-aligned text
  crates/bevy_ui/src/widget/text.rs
Labels: C-Bug, C-Crash, A-UI, S-Ready-For-Final-Review

#10198 Non-blocking load_untyped using a wrapper asset
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/server/mod.rs
Labels: C-Enhancement, A-Assets, S-Ready-For-Final-Review

#10210 Reuse and hot reload folder handles
  crates/bevy_asset/src/server/info.rs
  crates/bevy_asset/src/server/mod.rs
Labels: C-Enhancement, A-Assets

#10254 Image Sampler Improvements
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_gltf/src/loader.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/texture/compressed_image_saver.rs
  crates/bevy_render/src/texture/fallback_image.rs
  crates/bevy_render/src/texture/image.rs
  crates/bevy_render/src/texture/image_loader.rs
  crates/bevy_render/src/texture/mod.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  examples/3d/anti_aliasing.rs
  examples/3d/tonemapping.rs
Labels: C-Bug, A-Rendering, C-Usability

#10276 Fix sampling of diffuse env map texture with non-uniform control flow
  crates/bevy_pbr/src/environment_map/environment_map.wgsl
Labels: C-Bug, A-Rendering

#10253 Log a warning when the `tonemapping_luts` feature is disabled but required for the selected tonemapper.
  Cargo.toml
  crates/bevy_core_pipeline/Cargo.toml
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  docs/cargo_features.md
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#10279 Additional AssetPath unit tests.
  crates/bevy_asset/src/path.rs
Labels: A-Assets, C-Code-Quality

#10275 default inherited visibility when parent has invalid components
  crates/bevy_render/src/view/visibility/mod.rs
Labels: C-Bug, A-Rendering, C-Crash, A-Hierarchy

#10286 Use `clippy::doc_markdown` more.
  clippy.toml
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/bloom/settings.rs
  crates/bevy_mikktspace/src/generated.rs
  crates/bevy_render/src/render_resource/storage_buffer.rs
  crates/bevy_winit/src/winit_config.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#10200 Smaller TAA fixes
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_core_pipeline/src/taa/taa.wgsl
  crates/bevy_pbr/src/prepass/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#10294 Fix outdated comment referencing CoreSet
  examples/ecs/apply_deferred.rs
Labels: A-ECS, C-Examples, S-Ready-For-Final-Review

#9913 docs: Update input_toggle_active example
  crates/bevy_input/src/common_conditions.rs
Labels: C-Docs, A-Input, S-Ready-For-Final-Review

#10289 Slightly improve `CursorIcon` doc.
  crates/bevy_window/src/cursor.rs
Labels: C-Docs, A-Windowing, S-Ready-For-Final-Review

#10295 Implement `Neg` for `Val`
  crates/bevy_ui/src/geometry.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#10204 Example time api
  Cargo.toml
  examples/README.md
  examples/time/time.rs
  examples/time/timers.rs
  examples/time/virtual_time.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Time

#10297 `normalize` method for `Rect`
  crates/bevy_math/src/rects/rect.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#10270 Truncate attribute buffer data rather than attribute buffers
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Bug, A-Rendering, P-High, S-Ready-For-Final-Review

#10296 Implement `Display` for `Val`
  crates/bevy_ui/src/geometry.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#10252 [bevy_text] Document what happens when font is not specified
  crates/bevy_text/src/text.rs
Labels: C-Docs, A-UI

#10150 make deferred_rendering simpler to render for CI
  examples/3d/deferred_rendering.rs
Labels: A-Rendering, A-Build-System, C-Examples

#10299 Add `Cubic` prefix to all cubic curve generators
  crates/bevy_math/src/cubic_splines.rs
  crates/bevy_math/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math, C-Breaking-Change

#10240 Derive Error for more error types
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/query/error.rs
  crates/bevy_ecs/src/system/system_registry.rs
  crates/bevy_render/src/render_asset.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_transform/Cargo.toml
  crates/bevy_transform/src/helper.rs
  crates/bevy_ui/src/layout/mod.rs
  examples/games/contributors.rs
Labels: C-Code-Quality, C-Usability, S-Ready-For-Final-Review

#10303 Update UI alignment docs
  crates/bevy_ui/src/layout/convert.rs
  crates/bevy_ui/src/ui_node.rs
Labels: C-Bug, C-Docs, A-UI, S-Ready-For-Final-Review, C-Breaking-Change

#10304 Fix deferred lighting pass values not all working on M1 in WebGL2
  crates/bevy_core_pipeline/src/deferred/mod.rs
Labels: C-Bug, A-Rendering, O-MacOS, S-Ready-For-Final-Review

#10306 Add frustum to shader View
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/view.wgsl
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#10326 Fix handling of `double_sided` for normal maps
  crates/bevy_pbr/src/render/pbr_fragment.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review
