Repository bevyengine/bevy, pull requests merged in 2023-05, with the labels that each got.

#8510 Added reference to ParallelCommands in the Commands doc
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: C-Docs, S-Ready-For-Final-Review

#8512 avoid panic with parented scenes on deleted entities
  crates/bevy_scene/src/scene_spawner.rs
Labels: C-Bug, C-Crash, S-Ready-For-Final-Review, A-Scenes

#8402 `MeasureFunc` improvements
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/measurement.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_ui/src/widget/text.rs
Labels: C-Performance, A-UI, S-Ready-For-Final-Review, C-Breaking-Change

#7335 Make scene handling of entity references robust
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/entity/map_entities.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/reflect.rs
  crates/bevy_hierarchy/src/components/children.rs
  crates/bevy_hierarchy/src/components/parent.rs
  crates/bevy_render/src/mesh/mesh/skinning.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/dynamic_scene_builder.rs
  crates/bevy_scene/src/scene.rs
  crates/bevy_scene/src/serde.rs
  crates/bevy_window/src/window.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, A-Scenes, C-Breaking-Change, D-Complex, S-Controversial

#8522 Expose sorting methods in `Children`
  crates/bevy_hierarchy/src/components/children.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#8488 Take example screenshots in CI
  .github/example-run/breakout.ron
  .github/example-run/load_gltf.ron
  .github/workflows/ci.yml
  crates/bevy_app/src/ci_testing.rs
  crates/bevy_app/src/lib.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_time/Cargo.toml
  crates/bevy_time/src/lib.rs
Labels: A-Rendering, A-Build-System, A-UI, S-Ready-For-Final-Review

#7570 Rename map_entities and map_specific_entities
  crates/bevy_ecs/src/reflect.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/scene.rs
Labels: A-ECS, C-Code-Quality, A-Scenes, C-Breaking-Change

#8500 added match statement instead of if-else block
  crates/bevy_sprite/src/mesh2d/mesh.rs
Labels: C-Code-Quality

#8536 fix typo in gamepad AxisSettings docs
  crates/bevy_input/src/gamepad.rs
Labels: C-Docs, A-Input, S-Ready-For-Final-Review

#8529 Manually implement common traits for `EventId`
  crates/bevy_ecs/src/event.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#8336 Webgpu support
  .github/workflows/ci.yml
  Cargo.toml
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/plugin.rs
  crates/bevy_core_pipeline/src/blit/mod.rs
  crates/bevy_core_pipeline/src/bloom/bloom.wgsl
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_core_pipeline/src/core_2d/main_pass_2d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transparent_pass_3d_node.rs
  crates/bevy_core_pipeline/src/fxaa/mod.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/tonemapping_shared.wgsl
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/parallax_mapping.wgsl
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/globals.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/pipelined_rendering.rs
  crates/bevy_render/src/render_phase/draw_state.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/settings.rs
  crates/bevy_render/src/texture/mod.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/window.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/lib.rs
  docs-template/EXAMPLE_README.md.tpl
  docs/cargo_features.md
  examples/README.md
  examples/shader/compute_shader_game_of_life.rs
  examples/shader/shader_instancing.rs
  tools/build-wasm-example/src/main.rs
Labels: A-Rendering, O-Web, A-App

#8542 Fix typos in gamepad AxisSettings
  crates/bevy_input/src/gamepad.rs
Labels: C-Docs, A-Input

#8550 Fix wording on DetectChanges::is_changed
  crates/bevy_ecs/src/change_detection.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#8559 Use `cmp` of Self in implementaions of `partial_cmp`
  crates/bevy_asset/src/handle.rs
  crates/bevy_core/src/name.rs
Labels: A-Assets, C-Code-Quality, A-Core, S-Ready-For-Final-Review

#8521 UI layout tree debug print
  crates/bevy_ui/src/layout/debug.rs
  crates/bevy_ui/src/layout/mod.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#8549 Replace the local text queues in the text systems with flags stored in a component
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/widget/text.rs
Labels: C-Bug, C-Performance, A-UI, C-Code-Quality, S-Ready-For-Final-Review

#8564 conversions between [u8; 4] and Color
  crates/bevy_render/src/color/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#6815 Allow custom depth texture usage
  crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#8561 new example showcase tool
  Cargo.toml
  tools/example-showcase/Cargo.toml
  tools/example-showcase/src/main.rs
  tools/example_showcase.sh
Labels: C-Examples

#8531 Add Reflect and FromReflect for AssetPath
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/path.rs
  crates/bevy_core/src/lib.rs
  crates/bevy_reflect/src/impls/std.rs
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review, A-Reflection

#8118 Add ViewNode to simplify render node management
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transparent_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/fxaa/mod.rs
  crates/bevy_core_pipeline/src/fxaa/node.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_core_pipeline/src/tonemapping/node.rs
  crates/bevy_core_pipeline/src/upscaling/node.rs
  crates/bevy_render/src/render_graph/node.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#8567 Replace remaining uses of `&T, Changed<T>` with `Ref` in UI system queries
  crates/bevy_ui/src/accessibility.rs
  crates/bevy_ui/src/layout/mod.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#8546 Update MSRV desc in README.md
  README.md
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review

#8579 Re-introduce comments about frustum culling
  examples/stress_tests/many_animated_sprites.rs
  examples/stress_tests/many_sprites.rs
Labels: C-Docs, A-Rendering, C-Examples, S-Ready-For-Final-Review

#8575 Added Vec append to BufferVec - Issue #3531
  crates/bevy_render/src/render_resource/buffer_vec.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#8585 Merge ScheduleRunnerSettings into ScheduleRunnerPlugin
  crates/bevy_app/src/schedule_runner.rs
  examples/app/headless.rs
  examples/ecs/ecs_guide.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-App, C-Breaking-Change

#8588 Rename `UnsafeWorldCell::read_change_tick`
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: A-ECS, C-Usability, C-Breaking-Change

#8587 Improve documentation for `UnsafeWorldCell::world_mut`
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#8594 Simplify the way run conditions are stored in the schedule
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#8551 Fix `Node::physical_rect` and add a `physical_size` method
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/text.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#8582 Remove mod.rs in scene_viewer
  examples/tools/scene_viewer/mod.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#8573 update syn, encase, glam and hexasphere
  benches/Cargo.toml
  crates/bevy_derive/Cargo.toml
  crates/bevy_ecs/macros/Cargo.toml
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/macros/src/fetch.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_encase_derive/Cargo.toml
  crates/bevy_macro_utils/Cargo.toml
  crates/bevy_macro_utils/src/attrs.rs
  crates/bevy_macro_utils/src/lib.rs
  crates/bevy_math/Cargo.toml
  crates/bevy_mikktspace/Cargo.toml
  crates/bevy_reflect/Cargo.toml
  crates/bevy_reflect/bevy_reflect_derive/Cargo.toml
  crates/bevy_reflect/bevy_reflect_derive/src/container_attributes.rs
  crates/bevy_reflect/bevy_reflect_derive/src/derive_data.rs
  crates/bevy_reflect/bevy_reflect_derive/src/documentation.rs
  crates/bevy_reflect/bevy_reflect_derive/src/field_attributes.rs
  crates/bevy_reflect/bevy_reflect_derive/src/type_uuid.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/macros/Cargo.toml
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/macros/src/extract_component.rs
  crates/bevy_utils/macros/Cargo.toml
Labels: C-Dependencies, S-Ready-For-Final-Review, A-Math

#8503 Delay asset hot reloading
  crates/bevy_asset/src/asset_server.rs
  crates/bevy_asset/src/debug_asset_server.rs
  crates/bevy_asset/src/filesystem_watcher.rs
  crates/bevy_asset/src/io/android_asset_io.rs
  crates/bevy_asset/src/io/file_asset_io.rs
  crates/bevy_asset/src/io/mod.rs
  crates/bevy_asset/src/io/wasm_asset_io.rs
  crates/bevy_asset/src/lib.rs
  examples/asset/custom_asset_io.rs
  examples/asset/hot_asset_reloading.rs
  examples/scene/scene.rs
  examples/shader/post_processing.rs
  examples/tools/scene_viewer/main.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review, C-Breaking-Change

#8548 Flatten UI `Style` properties that use `Size` + remove `Size`
  crates/bevy_ui/src/geometry.rs
  crates/bevy_ui/src/layout/convert.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/ui_node.rs
  examples/ecs/apply_system_buffers.rs
  examples/ecs/state.rs
  examples/games/alien_cake_addict.rs
  examples/games/game_menu.rs
  examples/stress_tests/many_buttons.rs
  examples/stress_tests/many_glyphs.rs
  examples/ui/button.rs
  examples/ui/flex_layout.rs
  examples/ui/grid.rs
  examples/ui/overflow.rs
  examples/ui/overflow_debug.rs
  examples/ui/relative_cursor_position.rs
  examples/ui/size_constraints.rs
  examples/ui/text_debug.rs
  examples/ui/text_wrap_debug.rs
  examples/ui/transparency_ui.rs
  examples/ui/ui.rs
  examples/ui/ui_scaling.rs
  examples/ui/z_index.rs
  examples/window/scale_factor_override.rs
  examples/window/window_resizing.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#8605 Fix a change detection test
  crates/bevy_ecs/src/change_detection.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, C-Testing

#8552 bevy_derive: Add `#[deref]` attribute
  Cargo.toml
  crates/bevy_derive/src/derefs.rs
  crates/bevy_derive/src/lib.rs
  crates/bevy_macros_compile_fail_tests/Cargo.toml
  crates/bevy_macros_compile_fail_tests/README.md
  crates/bevy_macros_compile_fail_tests/src/lib.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_derive.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_derive/invalid_attribute.fail.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_derive/invalid_attribute.fail.stderr
  crates/bevy_macros_compile_fail_tests/tests/deref_derive/invalid_item.fail.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_derive/invalid_item.fail.stderr
  crates/bevy_macros_compile_fail_tests/tests/deref_derive/missing_attribute.fail.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_derive/missing_attribute.fail.stderr
  crates/bevy_macros_compile_fail_tests/tests/deref_derive/multiple_attributes.fail.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_derive/multiple_attributes.fail.stderr
  crates/bevy_macros_compile_fail_tests/tests/deref_derive/multiple_fields.pass.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_derive/single_field.pass.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/invalid_attribute.fail.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/invalid_attribute.fail.stderr
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/invalid_item.fail.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/invalid_item.fail.stderr
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/mismatched_target_type.fail.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/mismatched_target_type.fail.stderr
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/missing_attribute.fail.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/missing_attribute.fail.stderr
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/missing_deref.fail.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/missing_deref.fail.stderr
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/multiple_attributes.fail.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/multiple_attributes.fail.stderr
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/multiple_fields.pass.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/single_field.pass.rs
  tools/ci/src/main.rs
Labels: C-Usability, S-Ready-For-Final-Review

#8553 fix missed examples in WebGPU update
  crates/bevy_core_pipeline/src/taa/mod.rs
  examples/2d/mesh2d_manual.rs
  examples/shader/post_processing.rs
  examples/shader/texture_binding_array.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#8578 Fix outdated doc in bevy_render
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#8622 Update ruzstd and basis universal
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/texture/ktx2.rs
Labels: A-Rendering, C-Dependencies, S-Ready-For-Final-Review

#8625 audio and browsers section for wasm examples
  docs-template/EXAMPLE_README.md.tpl
  examples/README.md
Labels: C-Docs, C-Examples, A-Audio, O-Web

#8636 Optimize wasm examples for the website
  tools/build-wasm-example/src/main.rs
  tools/example-showcase/Cargo.toml
  tools/example-showcase/src/main.rs
Labels: C-Examples

#8598 Add documentation to `last_change_tick`
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: C-Docs, A-ECS

#8635 Remove outdated example code/comment
  examples/ui/overflow_debug.rs
Labels: C-Examples, A-UI, A-Gizmos

#8639 Remove unused field in FontAtlasSet
  crates/bevy_text/src/font_atlas_set.rs
Labels: A-Rendering, C-Code-Quality

#8631 Fix bloom wasm support
  Cargo.toml
  crates/bevy_core_pipeline/src/bloom/mod.rs
Labels: A-Rendering, O-Web

#8634 Update Camera::hdr docs
  crates/bevy_render/src/camera/camera.rs
Labels: C-Docs, A-Rendering

#8643 Make `TextureAtlas::texture_handles` `pub` instead of `pub(crate)` (#8633)
  crates/bevy_sprite/src/texture_atlas.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#8623 update ahash and hashbrown
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/path.rs
  crates/bevy_utils/Cargo.toml
  crates/bevy_utils/src/lib.rs
  examples/3d/tonemapping.rs
Labels: C-Dependencies, S-Ready-For-Final-Review, C-Breaking-Change

#8627 Fix look_to variable naming
  crates/bevy_transform/src/components/transform.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Transform, C-Breaking-Change

#8640 Correct RequestRedraw documentation
  crates/bevy_window/src/event.rs
Labels: C-Docs, A-Windowing, S-Ready-For-Final-Review

#8642 Make Material2d pipeline systems public
  crates/bevy_sprite/src/mesh2d/material.rs
Labels: C-Enhancement, A-Rendering, C-Usability, S-Ready-For-Final-Review

#8653 Move bevy_ui accessibility systems to `PostUpdate`.
  crates/bevy_ui/src/accessibility.rs
  crates/bevy_winit/src/accessibility.rs
Labels: C-Accessibility, S-Ready-For-Final-Review, C-Breaking-Change

#8664 Hide naga info logs & Derive PartialEq on Timer and Stopwatch
  crates/bevy_log/src/lib.rs
  crates/bevy_time/src/stopwatch.rs
  crates/bevy_time/src/timer.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Diagnostics

#8668 implement `Deref` for `State<S>`
  crates/bevy_ecs/src/schedule/state.rs
Labels: A-ECS, C-Usability

#8682 Fix screenspace_texture example shader compiler error in WebGPU (Browser)
  assets/shaders/custom_material_screenspace_texture.wgsl
Labels: A-Rendering, C-Examples, C-Crash, O-Web, S-Ready-For-Final-Review

#8683 Disable asset_loading and texture_atlas examples when building for wasm / WebGPU
  Cargo.toml
Labels: C-Bug, A-Rendering, C-Examples, C-Crash, O-Web

#8681 Change present mode on many_buttons and many_glyphs from Immediate to AutoNoVsync
  examples/stress_tests/many_buttons.rs
  examples/stress_tests/many_glyphs.rs
Labels: C-Bug, C-Examples, A-Windowing, C-Crash, O-Web, S-Ready-For-Final-Review

#8674 Allow missing docs on wasm implementation of BoxedFuture
  crates/bevy_utils/src/lib.rs
Labels: C-Docs, O-Web, S-Ready-For-Final-Review, A-Diagnostics

#8688 fix warning: variable does not need to be mutable
  crates/bevy_app/src/plugin_group.rs
  crates/bevy_render/src/view/window.rs
Labels: C-Code-Quality

#8697 Add documentation to `UnsafeWorldCell::increment_change_tick`
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#8700 fix new clippy lints before they reach stable
  examples/2d/mesh2d_manual.rs
  examples/3d/blend_modes.rs
  examples/3d/parallax_mapping.rs
  examples/3d/skybox.rs
  examples/3d/spotlight.rs
  examples/3d/tonemapping.rs
  examples/diagnostics/log_diagnostics.rs
  examples/games/contributors.rs
  examples/stress_tests/bevymark.rs
  examples/stress_tests/many_animated_sprites.rs
  examples/stress_tests/many_buttons.rs
  examples/stress_tests/many_cubes.rs
  examples/stress_tests/many_gizmos.rs
  examples/stress_tests/many_glyphs.rs
  examples/stress_tests/many_lights.rs
  examples/stress_tests/many_sprites.rs
  examples/stress_tests/text_pipeline.rs
  examples/stress_tests/transform_hierarchy.rs
  examples/ui/text.rs
  examples/window/window_resizing.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#8701 Fix screenshots on Wayland + Nvidia
  crates/bevy_render/src/texture/image_texture_conversion.rs
  crates/bevy_render/src/view/window.rs
  crates/bevy_render/src/view/window/screenshot.rs
Labels: C-Bug, A-Rendering, C-Examples

#6697 Add `MAY_DISCARD` shader def, enabling early depth tests for most cases
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#8292 Improve safety for the multi-threaded executor using `UnsafeWorldCell`
  benches/benches/bevy_ecs/iteration/heavy_compute.rs
  benches/benches/bevy_ecs/iteration/iter_simple_system.rs
  benches/benches/bevy_ecs/world/world_get.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/world/identifier.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#8504 shader_prepass example: disable MSAA for maximum compatibility
  assets/shaders/show_prepass.wgsl
  examples/shader/shader_prepass.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#8514 bevy_reflect: Allow `#[reflect(default)]` on enum variant fields
  crates/bevy_reflect/bevy_reflect_derive/src/enum_utility.rs
  crates/bevy_reflect/bevy_reflect_derive/src/lib.rs
  crates/bevy_reflect/src/lib.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Reflection

#8678 Disable wasm / webgpu building of wireframe example
  Cargo.toml
Labels: C-Bug, A-Rendering, C-Examples, O-Web, S-Ready-For-Final-Review

#8704 Apply codebase changes in preparation for `StandardMaterial` transmission
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_core_pipeline/src/upscaling/node.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/fog.wgsl
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/pbr.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/utils.wgsl
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_render/src/texture/fallback_image.rs
  crates/bevy_render/src/texture/mod.rs
  crates/bevy_render/src/view/mod.rs
Labels: A-Rendering, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#8692 Document query errors
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#8711 Add `CubicCurve::segment_count` + `iter_samples` adjustment
  crates/bevy_math/src/cubic_splines.rs
Labels: C-Performance, C-Usability, S-Ready-For-Final-Review, A-Animation, A-Math

#8725 Improve encapsulation for commands and add docs
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: C-Docs, A-ECS, C-Code-Quality, C-Breaking-Change

#8721 Make the `Condition` trait generic
  crates/bevy_ecs/src/schedule/condition.rs
Labels: A-ECS, C-Usability

#8714 Add or_else combinator to run_conditions.rs
  examples/ecs/run_conditions.rs
Labels: A-ECS, C-Examples
