Repository bevyengine/bevy, pull requests merged in 2023-04, with the labels that each got.

#8281 Fix typo in bevy_reflect README
  crates/bevy_reflect/README.md
Labels: C-Docs, S-Ready-For-Final-Review, A-Reflection

#8174 Use `UnsafeWorldCell` to increase code quality for `SystemParam`
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/removal_detection.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/identifier.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_render/src/extract_param.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#8283 Reflect `Component` and `Default` of `BloomSettings`
  crates/bevy_core_pipeline/src/bloom/settings.rs
Labels: A-Rendering, C-Usability, A-Reflection

#8287 Fix UI node docs
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, A-UI

#8289 make the examples use the States derive macro
  examples/2d/texture_atlas.rs
  examples/ecs/generic_system.rs
Labels: A-ECS, C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#8275 Built-in skybox
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/fullscreen_vertex_shader/fullscreen.wgsl
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_core_pipeline/src/skybox/skybox.wgsl
  crates/bevy_pbr/src/environment_map/environment_map.wgsl
  examples/3d/skybox.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#7422 Add port of AMD's Robust Contrast Adaptive Sharpening
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/node.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/robust_contrast_adaptive_sharpening.wgsl
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/lib.rs
  examples/3d/anti_aliasing.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#8295 Update `increment_change_tick` to return a strongly-typed `Tick`
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#8136 Make bevy_render an optional dependency of bevy_scene
  crates/bevy_gltf/Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_scene/Cargo.toml
  crates/bevy_scene/src/bundle.rs
  crates/bevy_scene/src/scene_loader.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, A-Scenes

#8119 Extend the `WorldQuery` macro to tuple structs
  crates/bevy_ecs/macros/src/fetch.rs
  crates/bevy_ecs/src/query/fetch.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#8260 Remove OnUpdate system set
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/state.rs
  examples/2d/texture_atlas.rs
  examples/ecs/generic_system.rs
  examples/ecs/state.rs
  examples/games/alien_cake_addict.rs
  examples/games/game_menu.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#8279 Add a performance regression issue template
  .github/ISSUE_TEMPLATE/performance_regression.md
Labels: C-Enhancement, A-Meta, S-Ready-For-Final-Review, S-Controversial

#8299 Remove unnecesssary values Vec from DynamicUniformBuffer and DynamicStorageBuffer
  crates/bevy_render/src/render_resource/storage_buffer.rs
  crates/bevy_render/src/render_resource/uniform_buffer.rs
Labels: A-Rendering, C-Performance, C-Breaking-Change

#8301 Remove capacity fields from all Buffer wrapper types
  crates/bevy_render/src/render_resource/storage_buffer.rs
  crates/bevy_render/src/render_resource/uniform_buffer.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#8285 Changed spelling linebreak_behaviour to linebreak_behavior
  crates/bevy_input/src/touch.rs
  crates/bevy_text/src/glyph_brush.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_text/src/text.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/widget/text.rs
  crates/bevy_window/src/event.rs
  crates/bevy_winit/src/converters.rs
  crates/bevy_winit/src/lib.rs
  examples/2d/text2d.rs
  examples/3d/tonemapping.rs
  examples/input/touch_input.rs
  examples/stress_tests/many_glyphs.rs
  examples/stress_tests/text_pipeline.rs
Labels: A-UI, C-Breaking-Change

#8298 Use RenderGraphApp in more places
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_core_pipeline/src/core_2d/main_pass_2d_node.rs
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transparent_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/fxaa/mod.rs
  crates/bevy_core_pipeline/src/msaa_writeback.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/node.rs
  crates/bevy_core_pipeline/src/upscaling/node.rs
  crates/bevy_render/src/render_graph/app.rs
  crates/bevy_render/src/render_graph/node.rs
Labels: C-Enhancement, A-Rendering

#8294 Remove the corresponding measure from Taffy when a `CalculatedSize` component is removed.
  crates/bevy_ui/src/flex/mod.rs
Labels: C-Bug, A-UI

#8145 Expose `AudioSink::empty()`
  crates/bevy_audio/src/sinks.rs
Labels: A-Audio

#8197 Fix size of clipped text glyphs.
  crates/bevy_ui/src/render/mod.rs
Labels: C-Bug, A-Rendering, A-UI

#8306 Consistent screen-space coordinates
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_ui/src/focus.rs
  crates/bevy_winit/src/lib.rs
  examples/3d/blend_modes.rs
  examples/input/text_input.rs
Labels: A-Rendering, A-Windowing, A-UI, C-Code-Quality, C-Usability, C-Breaking-Change

#8198 Add `overflow_debug` example
  Cargo.toml
  examples/README.md
  examples/ui/overflow_debug.rs
Labels: C-Examples, A-UI

#8313 Suppress the `clippy::type_complexity` lint
  crates/bevy_a11y/src/lib.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_app/src/lib.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_audio/src/lib.rs
  crates/bevy_core/src/lib.rs
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_derive/src/lib.rs
  crates/bevy_diagnostic/src/lib.rs
  crates/bevy_dylib/src/lib.rs
  crates/bevy_dynamic_plugin/src/lib.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs_compile_fail_tests/src/lib.rs
  crates/bevy_encase_derive/src/lib.rs
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gltf/src/lib.rs
  crates/bevy_hierarchy/src/lib.rs
  crates/bevy_input/src/lib.rs
  crates/bevy_internal/src/lib.rs
  crates/bevy_log/src/lib.rs
  crates/bevy_macro_utils/src/lib.rs
  crates/bevy_math/src/lib.rs
  crates/bevy_mikktspace/src/lib.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_ptr/src/lib.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_tasks/src/lib.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_transform/src/lib.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_utils/src/lib.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/src/lib.rs
Labels: C-Usability, A-Meta

#8291 Non-breaking change* from UK spellings to US
  crates/bevy_app/src/app.rs
  crates/bevy_core/src/lib.rs
  crates/bevy_core_pipeline/src/fxaa/fxaa.wgsl
  crates/bevy_core_pipeline/src/tonemapping/tonemapping_shared.wgsl
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_input/src/touch.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/shadows.wgsl
  crates/bevy_reflect/bevy_reflect_derive/src/field_attributes.rs
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_tasks/src/task_pool.rs
  crates/bevy_text/src/text.rs
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/system.rs
  examples/2d/rotation.rs
  examples/3d/skybox.rs
  examples/games/contributors.rs
  examples/games/game_menu.rs
  examples/input/touch_input.rs
  examples/ui/text_debug.rs
  examples/ui/z_index.rs
Labels: C-Docs, C-Code-Quality, S-Ready-For-Final-Review

#8334 Added documentation to the fields within derived read-only types
  crates/bevy_ecs/macros/src/fetch.rs
Labels: C-Docs, A-ECS

#7264 Fix transform propagation of orphaned entities
  crates/bevy_transform/src/systems.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Transform, C-Breaking-Change, A-Hierarchy

#8316 fix invalid bone weights
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Bug, A-Rendering, A-Animation

#7706 Ability to set a Global Volume
  crates/bevy_audio/Cargo.toml
  crates/bevy_audio/src/audio.rs
  crates/bevy_audio/src/audio_output.rs
  crates/bevy_audio/src/lib.rs
  examples/audio/decodable.rs
Labels: A-Audio, C-Usability, S-Ready-For-Final-Review

#7732 Move event traces to detailed_trace!
  crates/bevy_ecs/src/event.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review

#8359 Only trigger state transitons if `next_state != old_state`
  crates/bevy_ecs/src/schedule/state.rs
Labels: A-ECS, S-Ready-For-Final-Review, C-Breaking-Change

#8219 Cleaned up panic messages
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_tasks/src/task_pool.rs
Labels: A-ECS, C-Usability

#8361 Improved AnimationPlugin declaration.
  crates/bevy_animation/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Animation

#8364 Fix panics and docs when using World schedules
  crates/bevy_ecs/src/world/mod.rs
Labels: C-Bug, C-Docs, A-ECS, C-Crash

#8083 Inline more ECS functions
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/storage/blob_vec.rs
  crates/bevy_ecs/src/storage/sparse_set.rs
  crates/bevy_ecs/src/world/identifier.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review

#8370 Explain why default_nearest is used in pixel_perfect example
  examples/2d/pixel_perfect.rs
Labels: A-Rendering, C-Examples

#8350 added multi-line string formatting
  crates/bevy_render/src/render_resource/pipeline_specializer.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#8368 Add a regression test for change detection between piped systems
  crates/bevy_ecs/src/system/system_piping.rs
Labels: A-ECS, C-Testing

#7656 `UiRect` axes constructor
  crates/bevy_ui/src/geometry.rs
Labels: A-UI, C-Usability

#8380 Sync pbr_types.wgsl StandardMaterial values
  crates/bevy_pbr/src/render/pbr_types.wgsl
Labels: A-Rendering

#8388 Alien Cake Addict example: don't exit when player lose
  examples/games/alien_cake_addict.rs
Labels: C-Examples

#8363 Fix docs for fixed timestep
  crates/bevy_time/src/fixed_timestep.rs
Labels: C-Docs, A-Time

#5928 Add parallax mapping to bevy PBR
  Cargo.toml
  assets/textures/parallax_example/cube_color.png
  assets/textures/parallax_example/cube_depth.png
  assets/textures/parallax_example/cube_normal.png
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/parallax.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/render/parallax_mapping.wgsl
  crates/bevy_pbr/src/render/pbr.wgsl
  crates/bevy_pbr/src/render/pbr_bindings.wgsl
  crates/bevy_pbr/src/render/pbr_types.wgsl
  examples/3d/parallax_mapping.rs
  examples/README.md
Labels: C-Enhancement, A-Rendering

#8376 Remove old post_processing example
  Cargo.toml
  assets/shaders/custom_material_chromatic_aberration.wgsl
  assets/shaders/post_processing.wgsl
  examples/README.md
  examples/shader/post_process_pass.rs
  examples/shader/post_processing.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#8387 Add a `scope` API for world schedules
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_time/src/fixed_timestep.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#8405 Minor typo fixup
  Cargo.toml
  examples/README.md
Labels: C-Docs, A-ECS, C-Examples

#8412 Fix pbr shader breaking on missing UVs
  crates/bevy_pbr/src/render/pbr.wgsl
Labels: C-Bug, A-Rendering, A-Animation

#7085 Improve or-with disjoint checks
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/system/mod.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, D-Complex

#7764 bevy_reflect: Add benches for `Struct::clone_dynamic` and `Reflect::get_type_info`
  benches/benches/bevy_reflect/struct.rs
Labels: C-Performance, S-Ready-For-Final-Review, A-Reflection, C-Testing

#7778 Add a missing safety invariant to `System::run_unsafe`
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/system.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Unsoundness

#7779 `text_system` split
  crates/bevy_text/src/pipeline.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/Cargo.toml
  crates/bevy_ui/src/flex/mod.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/measurement.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_ui/src/widget/text.rs
Labels: C-Bug, A-UI, C-Code-Quality, S-Ready-For-Final-Review

#8195 Fix the UV calculations for clipped and flipped ImageNodes
  crates/bevy_ui/src/render/mod.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#8272 add a feature for memory tracing with tracy
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_log/Cargo.toml
  crates/bevy_log/src/lib.rs
  docs/cargo_features.md
Labels: C-Performance, S-Ready-For-Final-Review, A-Diagnostics

#8396 Better error message when index does not exist in texture atlas
  crates/bevy_sprite/src/render/mod.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Diagnostics

#8194 Adding a bezier curve example
  Cargo.toml
  examples/README.md
  examples/animation/cubic_curve.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Animation, A-Math

#8400 Fix get_vertex_buffer_data doc
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#8413 Add examples page build instructions
  CONTRIBUTING.md
  docs-template/EXAMPLE_README.md.tpl
  examples/README.md
Labels: C-Docs, C-Examples, C-Usability, S-Ready-For-Final-Review

#8026 Add CSS Grid support to `bevy_ui`
  Cargo.toml
  crates/bevy_ui/Cargo.toml
  crates/bevy_ui/src/layout/convert.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/ui_node.rs
  examples/README.md
  examples/ui/grid.rs
Labels: C-Enhancement, A-UI, S-Ready-For-Final-Review

#8422 Fix text systems broken when resolving merge conflicts in #8026
  crates/bevy_ui/src/lib.rs
Labels: C-Bug, A-UI

#8418 Add `many-buttons` commandline options to force text and layout recomputation
  examples/stress_tests/many_buttons.rs
Labels: C-Performance, A-UI, S-Ready-For-Final-Review, A-Diagnostics

#8346 fix panic when moving child
  crates/bevy_hierarchy/src/child_builder.rs
Labels: C-Bug, C-Crash, A-Hierarchy

#8425 Fix text measurement algorithm
  crates/bevy_ui/src/widget/text.rs
  examples/ui/grid.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#8430 Register some extra types to type registry
  crates/bevy_core/src/lib.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/ui_node.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, A-Reflection, A-Math

#8428 Add Reflection Macros to TextureAtlasSprite
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/texture_atlas.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, A-Reflection

#8419 Reorganize system modules
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system_piping.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#8180 Avoid spawning gizmo meshes when no gizmos are being drawn
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_gizmos/src/lib.rs
Labels: C-Bug, A-Rendering, C-Performance

#8095 Split UI `Overflow` by axis
  Cargo.toml
  crates/bevy_ui/src/layout/convert.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/update.rs
  examples/README.md
  examples/ui/overflow.rs
  examples/ui/overflow_debug.rs
  examples/ui/ui.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#8326 Add `any_component_removed` condition
  crates/bevy_ecs/src/schedule/condition.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review

#8434 do not crash when rendering only one gizmo
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_gizmos/src/lib.rs
Labels: C-Bug, A-Gizmos

#8437 Allow `bevy_ui` crate to compile without the `text` feature enabled
  crates/bevy_ui/src/lib.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review, C-Regression

#8436 Fix boxed labels
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_macro_utils/src/lib.rs
  crates/bevy_utils/src/label.rs
Labels: C-Bug, A-ECS, C-Usability

#8403 Simplify world schedule methods
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/main_schedule.rs
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_macro_utils/src/lib.rs
  crates/bevy_utils/src/label.rs
Labels: A-ECS, C-Code-Quality, C-Breaking-Change, S-Controversial

#7163 Add screenshot api
  Cargo.toml
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/camera_driver_node.rs
  crates/bevy_render/src/render_resource/texture.rs
  crates/bevy_render/src/renderer/graph_runner.rs
  crates/bevy_render/src/renderer/mod.rs
  crates/bevy_render/src/texture/image_texture_conversion.rs
  crates/bevy_render/src/view/window.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_render/src/view/window/screenshot.wgsl
  examples/README.md
  examples/window/screenshot.rs
Labels: A-Rendering, C-Testing, D-Complex

#8444 bevy_pbr: Do not cull meshes without Aabbs from cascades
  crates/bevy_pbr/src/light.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#8443 typo on schedule StateTransitions name in example
  examples/ecs/state.rs
Labels: A-ECS, C-Examples

#8450 Fix 1.69 CI clippy lints
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/storage/sparse_set.rs
  crates/bevy_ecs_compile_fail_tests/tests/ui/entity_ref_mut_lifetime_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/system_param_derive_readonly.stderr
  crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/generics.fail.stderr
Labels: C-Code-Quality

#8445 add a default font
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_text/Cargo.toml
  crates/bevy_text/src/FiraMono-subset.ttf
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/text.rs
  docs/cargo_features.md
  examples/2d/bloom_2d.rs
  examples/3d/3d_gizmos.rs
  examples/3d/anti_aliasing.rs
  examples/3d/atmospheric_fog.rs
  examples/3d/blend_modes.rs
  examples/3d/bloom_3d.rs
  examples/3d/fog.rs
  examples/3d/parallax_mapping.rs
  examples/3d/pbr.rs
  examples/3d/tonemapping.rs
  examples/async_tasks/external_source_external_thread.rs
  examples/ecs/apply_system_buffers.rs
  examples/ecs/state.rs
  examples/games/alien_cake_addict.rs
  examples/games/breakout.rs
  examples/games/game_menu.rs
  examples/mobile/src/lib.rs
  examples/scene/scene.rs
  examples/shader/shader_prepass.rs
  examples/stress_tests/bevymark.rs
  examples/stress_tests/many_buttons.rs
  examples/stress_tests/many_gizmos.rs
  examples/stress_tests/many_glyphs.rs
  examples/tools/gamepad_viewer.rs
  examples/window/low_power.rs
  examples/window/scale_factor_override.rs
  examples/window/window_resizing.rs
Labels: A-Assets, A-UI, S-Ready-For-Final-Review, S-Controversial

#8222 CI: comment on PR when missing feature/example update
  .github/workflows/ci.yml
Labels: C-Bug, A-Build-System

#8184 Fix Box<dyn Reflect> struct with a hashmap in it panicking when clone_value is called on it
  crates/bevy_reflect/src/impls/std.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Reflection

#8456 also import the default handle when feature disabled
  crates/bevy_text/src/text.rs
Labels: C-Bug, A-UI

#8371 ChildBuilder docs improvement
  crates/bevy_hierarchy/src/child_builder.rs
Labels: C-Docs, A-Hierarchy

#8466 `measure_text_system` text query fix
  crates/bevy_ui/src/widget/text.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#8330 Handle vertex_uvs if they are present in default prepass fragment shader
  crates/bevy_pbr/src/prepass/prepass.wgsl
  examples/shader/shader_prepass.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#8117 Fixed several missing links in docs.
  crates/bevy_animation/src/lib.rs
  crates/bevy_app/src/app.rs
  crates/bevy_asset/src/asset_server.rs
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/io/android_asset_io.rs
  crates/bevy_asset/src/io/file_asset_io.rs
  crates/bevy_asset/src/io/mod.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/reflect.rs
  crates/bevy_core/src/lib.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/storage/blob_vec.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_hierarchy/src/valid_parent_check_plugin.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_ptr/src/lib.rs
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
  crates/bevy_reflect/src/type_registry.rs
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_graph/edge.rs
  crates/bevy_render/src/render_phase/draw.rs
  crates/bevy_render/src/renderer/mod.rs
  crates/bevy_render/src/texture/image.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_sprite/src/collide_aabb.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_tasks/src/task_pool.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_transform/src/commands.rs
  crates/bevy_transform/src/components/global_transform.rs
  crates/bevy_ui/src/camera_config.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_config.rs
  examples/3d/transparency_3d.rs
  examples/animation/animated_transform.rs
  examples/async_tasks/async_compute.rs
  examples/audio/decodable.rs
  examples/ecs/custom_query_param.rs
  examples/ecs/removal_detection.rs
  examples/tools/scene_viewer/camera_controller_plugin.rs
  examples/ui/relative_cursor_position.rs
Labels: C-Docs

#8473 Update docs to reflect that the shallowest and not the deepest penetr…
  crates/bevy_sprite/src/collide_aabb.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Math

#8479 docs(bevy_render): Remove copy-pasted docstring
  crates/bevy_render/src/texture/image.rs
Labels: C-Docs, S-Ready-For-Final-Review

#8476 Remove `Children` component when calling `despawn_descendants`
  crates/bevy_hierarchy/src/hierarchy.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Hierarchy

#7761 UI text wrapping and `LineBreakOn` example
  Cargo.toml
  examples/README.md
  examples/ui/text_wrap_debug.rs
Labels: C-Examples, A-UI, S-Ready-For-Final-Review

#7885 Add `Aabb` calculation for `Sprite`, `TextureAtlasSprite` and `Mesh2d`
  crates/bevy_sprite/src/lib.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#8475 stress test examples: add missing warns
  examples/stress_tests/many_buttons.rs
  examples/stress_tests/many_glyphs.rs
  examples/stress_tests/text_pipeline.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#8485 Fix panic when using debug_asset_server
  crates/bevy_text/src/font.rs
  crates/bevy_text/src/lib.rs
Labels: C-Bug, C-Crash, S-Ready-For-Final-Review, C-Regression

#8362 Re-add the "frame" span for tracy comparisons
  crates/bevy_app/src/app.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Diagnostics

#8470 bevy_asset: Add `LoadContext::get_handle_untyped`
  crates/bevy_asset/src/loader.rs
Labels: A-Assets

#8491 make glsl and spirv support optional
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/render_resource/shader.rs
  docs/cargo_features.md
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, C-Breaking-Change

#8496 bevy_reflect: Add `ReflectFromReflect` to the prelude
  crates/bevy_reflect/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#8495 bevy_ui: Add `FromReflect` derives
  crates/bevy_ui/src/camera_config.rs
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/geometry.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/button.rs
  crates/bevy_ui/src/widget/label.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, A-Reflection

#6971 bevy_reflect: Better proxies
  benches/benches/bevy_reflect/struct.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/enums.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/tuple_structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/values.rs
  crates/bevy_reflect/src/array.rs
  crates/bevy_reflect/src/enums/dynamic_enum.rs
  crates/bevy_reflect/src/enums/mod.rs
  crates/bevy_reflect/src/from_reflect.rs
  crates/bevy_reflect/src/impls/smallvec.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/list.rs
  crates/bevy_reflect/src/map.rs
  crates/bevy_reflect/src/reflect.rs
  crates/bevy_reflect/src/serde/de.rs
  crates/bevy_reflect/src/serde/mod.rs
  crates/bevy_reflect/src/serde/ser.rs
  crates/bevy_reflect/src/struct_trait.rs
  crates/bevy_reflect/src/tuple.rs
  crates/bevy_reflect/src/tuple_struct.rs
  crates/bevy_reflect/src/type_info.rs
  crates/bevy_reflect/src/utility.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#8446 Updated to wgpu 0.16.0, wgpu-hal 0.16.0 and naga 0.12.0
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/render_resource/shader.rs
  crates/bevy_render/src/texture/dds.rs
  crates/bevy_render/src/texture/fallback_image.rs
  crates/bevy_render/src/texture/image.rs
  crates/bevy_render/src/texture/ktx2.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
Labels: A-Rendering, C-Dependencies, S-Ready-For-Final-Review, C-Breaking-Change

#8478 standardize instructions in examples
  examples/3d/3d_gizmos.rs
  examples/3d/anti_aliasing.rs
  examples/3d/atmospheric_fog.rs
  examples/3d/bloom_3d.rs
  examples/3d/fog.rs
  examples/3d/lighting.rs
  examples/3d/parallax_mapping.rs
  examples/3d/shadow_biases.rs
Labels: C-Examples

#8499 `many_glyphs` `recompute-text` option
  examples/stress_tests/many_glyphs.rs
Labels: C-Examples, C-Performance

#8497 Fix panic in example: text_wrap_debug.rs
  examples/ui/text_wrap_debug.rs
Labels: C-Examples, C-Crash, A-UI, S-Ready-For-Final-Review

#8455 Screenshots in wasm
  Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/view/window/screenshot.rs
  examples/window/screenshot.rs
Labels: C-Enhancement, A-Rendering, O-Web, A-Diagnostics

#8441 Register `UiImageSize`
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/widget/image.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection
