Repository bevyengine/bevy, pull requests merged in 2023-08, with the labels that each got.

#9329 fix typo in a link - Mesh docs
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Docs, S-Ready-For-Final-Review

#9312 Add a paragraph to the lifetimeless module doc
  crates/bevy_ecs/src/system/system_param.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#7611 Change `WinitPlugin` defaults to limit game update rate when window is not visible
  crates/bevy_winit/src/winit_config.rs
Labels: C-Bug, A-Windowing, O-MacOS, C-Usability, S-Ready-For-Final-Review, S-Controversial

#8841 Document when Camera::viewport_to_world and related methods return None
  crates/bevy_render/src/camera/camera.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#9320 Improve font size related docs
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/text.rs
Labels: C-Docs

#9253 Fix `ambiguous_with` breaking run conditions
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#9343 include toplevel shader-associated defs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
Labels: C-Enhancement, A-Rendering

#9331 Improve execution of examples in CI
  examples/3d/bloom_3d.rs
  examples/3d/pbr.rs
  examples/3d/shadow_biases.rs
  examples/3d/spotlight.rs
  examples/3d/tonemapping.rs
  examples/async_tasks/external_source_external_thread.rs
  examples/ecs/iter_combinations.rs
  examples/ecs/parallel_query.rs
Labels: A-Rendering, A-Build-System, C-Examples, S-Ready-For-Final-Review

#9332 update documentation on AudioSink
  crates/bevy_audio/src/sinks.rs
Labels: C-Docs, A-Audio, S-Ready-For-Final-Review

#9345 Fix incorrent doc comment for the set method of `ContentSize`
  crates/bevy_ui/src/measurement.rs
Labels: C-Docs, A-UI

#9361 Fix post_processing example on webgl2
  assets/shaders/post_processing.wgsl
  examples/shader/post_processing.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#9344 Improved text widget doc comments
  crates/bevy_ui/src/widget/text.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#9348 Fix doc warning in bevy_tasks
  crates/bevy_tasks/src/single_threaded_task_pool.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Tasks, A-Diagnostics

#9048 Refactor parsing in bevy_reflect path module
  crates/bevy_reflect/src/path/mod.rs
  crates/bevy_reflect/src/path/parse.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Reflection

#8980 Prevent setting parent as itself
  crates/bevy_hierarchy/src/child_builder.rs
Labels: C-Bug, C-Usability, S-Ready-For-Final-Review, A-Hierarchy

#9127 use ViewNodeRunner in the post_processing example
  examples/shader/post_processing.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#9322 bevy_reflect: Fix combined field attributes
  crates/bevy_reflect/bevy_reflect_derive/src/field_attributes.rs
  crates/bevy_reflect/bevy_reflect_derive/src/lib.rs
  crates/bevy_reflect/src/lib.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Reflection

#9346 Change the default for the `measure_func` field of `ContentSize` to None.
  crates/bevy_ui/src/measurement.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9372 Slightly better message when contributor modifies examples template
  .github/workflows/ci-comment-failures.yml
Labels: C-Docs, A-Build-System, C-Examples, S-Ready-For-Final-Review

#9399 Fix gamepad viewer being marked as a non-wasm example
  Cargo.toml
Labels: C-Examples, O-Web, S-Ready-For-Final-Review

#9155 Fix non-visible motion vector text in shader prepass example
  examples/shader/shader_prepass.rs
Labels: C-Bug, A-Rendering, C-Examples

#9092 Update `Camera`'s `Frustum` only when its `GlobalTransform` or `CameraProjection` changed
  crates/bevy_render/src/view/visibility/mod.rs
Labels: A-Rendering, A-ECS, C-Performance, C-Usability

#9154 Rustdoc: Scrape examples
  Cargo.toml
Labels: C-Docs

#9140 bevy_reflect: Opt-out attribute for `TypePath`
  crates/bevy_reflect/bevy_reflect_derive/src/container_attributes.rs
  crates/bevy_reflect/bevy_reflect_derive/src/derive_data.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/typed.rs
  crates/bevy_reflect/bevy_reflect_derive/src/lib.rs
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
  crates/bevy_reflect/src/lib.rs
Labels: A-Reflection, C-Compile-Failure

#9396 Use bevy crates imports instead of bevy internal. post_processing example
  examples/shader/post_processing.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#9387 Add glam swizzles traits to prelude
  crates/bevy_math/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#9392 Expose `animation_clip` paths
  crates/bevy_animation/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Animation

#9327 Make Anchor Copy
  crates/bevy_sprite/src/sprite.rs
Labels: A-Rendering, C-Usability

#8750 elaborate on TaskPool and bevy tasks
  crates/bevy_tasks/README.md
  crates/bevy_tasks/src/task_pool.rs
  crates/bevy_tasks/src/usages.rs
  examples/async_tasks/async_compute.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Tasks

#9418 Add `replace_if_neq` to `DetectChangesMut`
  crates/bevy_ecs/src/change_detection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#9406 Unnecessary line in game_menu example
  examples/games/game_menu.rs
Labels: C-Examples, A-UI, S-Ready-For-Final-Review

#9336 audio sinks don't need their custom drop anymore
  crates/bevy_audio/src/audio_output.rs
  crates/bevy_audio/src/sinks.rs
Labels: C-Bug, A-Audio, S-Ready-For-Final-Review

#9394 Move window.rs to window/mod.rs in bevy_render
  crates/bevy_render/src/view/window/mod.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#9385 Adding `Copy, Clone, Debug` to derived traits of `ExecutorKind`
  crates/bevy_ecs/src/schedule/executor/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#9388 enable multithreading on benches
  benches/Cargo.toml
Labels: S-Ready-For-Final-Review, C-Regression

#9370 webgl feature renamed to webgl2
  docs-template/EXAMPLE_README.md.tpl
  examples/README.md
Labels: C-Docs, C-Examples, S-Ready-For-Final-Review, O-WebGL2

#9427 Example Comment Typo Fix
  examples/2d/2d_gizmos.rs
Labels: C-Docs, C-Examples

#9429 allow asset loader pre-registration
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/asset_server.rs
  crates/bevy_asset/src/assets.rs
  crates/bevy_gltf/src/lib.rs
  crates/bevy_render/src/texture/image_texture_loader.rs
  crates/bevy_render/src/texture/mod.rs
Labels: C-Bug, A-Assets, C-Usability, S-Controversial

#9416 Reduce the size of MeshUniform to improve performance
  assets/shaders/custom_vertex_attribute.wgsl
  assets/shaders/instancing.wgsl
  crates/bevy_math/src/affine3.rs
  crates/bevy_math/src/lib.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass.wgsl
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh.wgsl
  crates/bevy_pbr/src/render/mesh_functions.wgsl
  crates/bevy_pbr/src/render/mesh_types.wgsl
  crates/bevy_pbr/src/render/wireframe.wgsl
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/primitives/mod.rs
  crates/bevy_render/src/render_phase/rangefinder.rs
  crates/bevy_render/src/view/visibility/mod.rs
  examples/shader/shader_instancing.rs
Labels: A-Rendering, C-Performance

#9313 Add `SceneInstanceReady`
  crates/bevy_scene/src/lib.rs
  crates/bevy_scene/src/scene_spawner.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Scenes

#9431 Fix incorrect documentation link in `DetectChangesMut`
  crates/bevy_ecs/src/change_detection.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#9101 Fix crash when drawing line gizmo with less than 2 vertices
  crates/bevy_gizmos/src/lib.rs
Labels: C-Bug, C-Crash, S-Ready-For-Final-Review, A-Gizmos

#9428 Add missing documentation to `bevy_time`
  crates/bevy_time/README.md
  crates/bevy_time/src/fixed_timestep.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_time/src/time.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Time

#9446 input: allow multiple gamepad inputs to be registered for one button in one frame
  crates/bevy_gilrs/src/gilrs_system.rs
  crates/bevy_input/src/gamepad.rs
Labels: C-Bug, A-Input, S-Ready-For-Final-Review

#9444 Change `UiScale` to a tuple struct
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_ui/src/widget/text.rs
  examples/ui/ui_scaling.rs
  examples/ui/viewport_debug.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#9456 Fix `Window::set_cursor_position`
  crates/bevy_winit/src/system.rs
Labels: C-Bug, A-Input, A-Windowing, S-Ready-For-Final-Review

#9462 Fix temporal jitter bug
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/view/mod.rs
Labels: C-Bug, A-Rendering

#9470 Fix gizmo lines deforming or disappearing when partially behind the camera
  crates/bevy_gizmos/src/lines.wgsl
Labels: C-Bug, A-Rendering

#9453 fix asset loader preregistration for multiple assets
  crates/bevy_asset/src/asset_server.rs
Labels: C-Bug, A-Assets

#9482 Make WgpuSettings::default() check WGPU_POWER_PREF
  crates/bevy_render/src/settings.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#9489 switch CI jobs between windows and linux for example execution
  .github/workflows/ci-comment-failures.yml
  .github/workflows/ci.yml
  .github/workflows/validation-jobs.yml
Labels: A-Build-System, S-Ready-For-Final-Review

#9468 Bevy Input Docs : lib.rs
  crates/bevy_input/src/lib.rs
Labels: C-Docs, A-Input, S-Ready-For-Final-Review

#9469 Bevy Input Docs : gamepad.rs
  crates/bevy_input/src/gamepad.rs
Labels: C-Docs, A-Input, S-Ready-For-Final-Review

#9451 Add `SpawnScene` to prelude
  crates/bevy_app/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Scenes

#9493 Fix point light radius
  crates/bevy_gltf/src/loader.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#9008 Add `GamepadButtonInput` event
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input/src/lib.rs
  examples/input/gamepad_input_events.rs
Labels: C-Enhancement, A-Input, S-Ready-For-Final-Review

#9460 Implement `Debug` for `UnsafeWorldCell`
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review

#9485 Remove Resource and add Debug to TaskPoolOptions
  crates/bevy_core/src/task_pool_options.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Tasks, C-Breaking-Change

#9355 User controlled window visibility
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/window/window_settings.rs
Labels: C-Enhancement, C-Examples, A-Windowing, S-Ready-For-Final-Review

#9516 Remove the bevy_dylib feature
  Cargo.toml
Labels: C-Usability, A-Meta, S-Ready-For-Final-Review, C-Breaking-Change

#9481 Remove unnecessary doc string
  crates/bevy_ui/src/node_bundles.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#9505 fix wireframe after MeshUniform size reduction
  crates/bevy_pbr/src/render/wireframe.wgsl
Labels: C-Bug, A-Rendering

#9513 fix shader_material_glsl example
  assets/shaders/custom_material.vert
Labels: A-Rendering, C-Examples

#9201 [RAINBOW EFFECT] Added methods to get HSL components from Color
  crates/bevy_render/src/color/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#9484 Include note of common profiling issue
  docs/profiling.md
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review, A-Diagnostics

#9547 fix bevy imports. windows_settings.rs example
  examples/window/window_settings.rs
Labels: C-Examples, S-Ready-For-Final-Review

#9467 Bevy Input Docs : the modules
  crates/bevy_input/src/axis.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input/src/input.rs
  crates/bevy_input/src/keyboard.rs
  crates/bevy_input/src/lib.rs
  crates/bevy_input/src/mouse.rs
  crates/bevy_input/src/touch.rs
  crates/bevy_input/src/touchpad.rs
Labels: C-Docs, A-Input, S-Ready-For-Final-Review

#9548 `round_ties_up` fix
  crates/bevy_ui/src/layout/mod.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#9539 fix incorrect docs for `JustifyItems` and `JustifySelf`
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#9553 Add support for KHR_materials_emissive_strength
  crates/bevy_gltf/Cargo.toml
  crates/bevy_gltf/src/loader.rs
Labels: A-Assets

#9555 ktx2: Fix Rgb8 -> Rgba8Unorm conversion
  crates/bevy_render/src/texture/ktx2.rs
Labels: C-Bug, A-Rendering

#9562 Fix CI for Rust 1.72
  crates/bevy_animation/src/lib.rs
  crates/bevy_asset/src/asset_server.rs
  crates/bevy_asset/src/io/file_asset_io.rs
  crates/bevy_core_pipeline/src/blit/mod.rs
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/node.rs
  crates/bevy_core_pipeline/src/msaa_writeback.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_ecs/macros/src/fetch.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_exact_sized_iterator_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_iter_combinations_mut_iterator_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_iter_many_mut_iterator_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/system_param_derive_readonly.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/world_query_derive.stderr
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_math/src/cubic_splines.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_reflect/bevy_reflect_derive/src/derive_data.rs
  crates/bevy_reflect/src/map.rs
  crates/bevy_reflect/src/struct_trait.rs
  crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/generics.fail.stderr
  crates/bevy_render/src/color/mod.rs
  crates/bevy_render/src/mesh/morph.rs
  crates/bevy_render/src/pipelined_rendering.rs
  crates/bevy_render/src/render_graph/graph.rs
  crates/bevy_render/src/render_graph/node.rs
  crates/bevy_ui/src/render/render_pass.rs
  crates/bevy_winit/src/lib.rs
  examples/2d/texture_atlas.rs
  examples/3d/bloom_3d.rs
  examples/animation/morph_targets.rs
  examples/games/breakout.rs
  examples/shader/post_processing.rs
  examples/shader/texture_binding_array.rs
  examples/stress_tests/many_gizmos.rs
  examples/tools/scene_viewer/morph_viewer_plugin.rs
  examples/ui/overflow_debug.rs
  tools/ci/src/main.rs
Labels: C-Code-Quality, P-High, S-Ready-For-Final-Review

#9364 Add reflect path parsing benchmark
  benches/Cargo.toml
  benches/benches/bevy_reflect/path.rs
Labels: C-Performance, S-Ready-For-Final-Review, A-Reflection

#9371 Make the reflect path parser utf-8-unaware
  crates/bevy_reflect/src/path/mod.rs
  crates/bevy_reflect/src/path/parse.rs
Labels: C-Performance, S-Ready-For-Final-Review, A-Reflection

#9581 Relax In/Out bounds on impl Debug for dyn System
  crates/bevy_ecs/src/system/system.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#9566 Added `Val::ZERO` Constant
  crates/bevy_ui/src/geometry.rs
  crates/bevy_ui/src/layout/convert.rs
  crates/bevy_ui/src/ui_node.rs
  examples/3d/blend_modes.rs
  examples/3d/pbr.rs
  examples/ui/font_atlas_debug.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#9587 change 'collapse_type_name' to retain enum types
  crates/bevy_utils/src/short_names.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Utils

#9588 Improve various `Debug` implementations
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_param.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#9236 Reorder render sets, refactor bevy_sprite to take advantage
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/msaa_writeback.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_core_pipeline/src/upscaling/mod.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/fog.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/camera/mod.rs
  crates/bevy_render/src/extract_component.rs
  crates/bevy_render/src/globals.rs
  crates/bevy_render/src/gpu_component_array_buffer.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/mesh/mod.rs
  crates/bevy_render/src/render_asset.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_render/src/texture/mod.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/window/mod.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/render_pass.rs
  examples/2d/mesh2d_manual.rs
  examples/shader/compute_shader_game_of_life.rs
  examples/shader/shader_instancing.rs
Labels: A-Rendering, C-Code-Quality

#9576 Make `run_if_inner` public and rename to `run_if_dyn`
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#9579 Refactor build_schedule and related errors
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/set.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#8526 Add `system.map(...)` for transforming the output of a system
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_utils/src/lib.rs
  examples/ecs/system_piping.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review

#8855 Check cursor position for out of bounds of the window
  crates/bevy_window/src/window.rs
Labels: A-Windowing, C-Usability, S-Ready-For-Final-Review

#9002 API updates to the AnimationPlayer
  crates/bevy_animation/src/lib.rs
  examples/animation/animated_fox.rs
  examples/stress_tests/many_foxes.rs
  examples/tools/scene_viewer/animation_plugin.rs
Labels: C-Enhancement, C-Usability, S-Ready-For-Final-Review, A-Animation, C-Breaking-Change

#9111 Cleanup some bevy_text pipeline.rs
  crates/bevy_text/src/glyph_brush.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_text/src/text.rs
  crates/bevy_ui/src/widget/text.rs
Labels: A-UI, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#9136 Improve documentation relating to `Frustum` and `HalfSpace`
  crates/bevy_render/src/primitives/mod.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_sprite/src/lib.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#9165 bevy_scene: Add `ReflectBundle`
  crates/bevy_ecs/src/reflect/bundle.rs
  crates/bevy_ecs/src/reflect/mod.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Reflection

#9306 Reorganize `Events` and `EventSequence` code
  crates/bevy_ecs/src/event.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#9407 check root node for animations
  crates/bevy_animation/src/lib.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Animation

#9461 Replaced EntityMap with HashMap
  crates/bevy_ecs/src/entity/map_entities.rs
  crates/bevy_ecs/src/reflect/map_entities.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/scene.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_scene/src/serde.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9490 Fix panic when using `.load_folder()` with absolute paths
  crates/bevy_asset/src/io/file_asset_io.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#9518 Add `Without<Parent>` filter to `sync_simple_transforms`' orphaned entities query
  crates/bevy_transform/src/systems.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Transform

#9537 Update defaults for OrthographicProjection
  crates/bevy_render/src/camera/projection.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9577 clean up configure_set(s) erroring
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review

#9589 Relax more `Sync` bounds on `Local`
  crates/bevy_ecs/src/system/system_param.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#9592 Rename `ManualEventIterator`
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/removal_detection.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#9604 Replaced `EntityCommand` Implementation for `FnOnce`
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9609 Remove `Val`'s `try_*` arithmetic methods
  crates/bevy_ui/src/ui_node.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9480 Clarify what happens when setting the audio volume
  crates/bevy_audio/src/sinks.rs
Labels: C-Docs, A-Audio, S-Ready-For-Final-Review

#9542 Add a variant of `Events::update` that returns the removed events
  crates/bevy_ecs/src/event.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#9600 Move schedule name into `Schedule`
  benches/benches/bevy_ecs/components/archetype_updates.rs
  benches/benches/bevy_ecs/empty_archetypes.rs
  benches/benches/bevy_ecs/scheduling/run_condition.rs
  benches/benches/bevy_ecs/scheduling/running_systems.rs
  benches/benches/bevy_ecs/scheduling/schedule.rs
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/main_schedule.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_time/src/time.rs
  crates/bevy_transform/src/systems.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9419 Allow disjoint mutable world access via `EntityMut`
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/reflect/bundle.rs
  crates/bevy_ecs/src/reflect/component.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_hierarchy/src/hierarchy.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review, A-Reflection, C-Breaking-Change, D-Complex, C-Unsoundness

#9621 Do not panic on non-UI child of UI entity
  crates/bevy_ui/src/update.rs
Labels: C-Bug, C-Crash, A-UI, S-Ready-For-Final-Review

#9568 Rename `Val` `evaluate` to `resolve` and implement viewport variant support
  crates/bevy_ui/src/ui_node.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9613 Remove unused regex dep from bevy_render
  crates/bevy_render/Cargo.toml
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#9619 Replace uses of `entity.insert` with tuple bundles in `game_menu` example
  examples/games/game_menu.rs
Labels: C-Examples, S-Ready-For-Final-Review

#9617 port old ambiguity tests over
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#9629 remove VecSwizzles imports
  examples/2d/rotation.rs
  examples/transforms/scale.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#9612 Check for bevy_internal imports in CI
  .github/workflows/ci.yml
  examples/animation/animated_fox.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#9638 Move default docs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_render/src/view/visibility/render_layers.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Utils

#9631 Refactor `EventReader::iter` to `read`
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_ecs/examples/events.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/removal_detection.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_gilrs/src/rumble.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input/src/keyboard.rs
  crates/bevy_input/src/mouse.rs
  crates/bevy_input/src/touch.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/render_asset.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/view/window/mod.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_window/src/system.rs
  crates/bevy_winit/src/accessibility.rs
  crates/bevy_winit/src/lib.rs
  examples/3d/shadow_biases.rs
  examples/3d/skybox.rs
  examples/3d/split_screen.rs
  examples/3d/tonemapping.rs
  examples/app/drag_and_drop.rs
  examples/async_tasks/external_source_external_thread.rs
  examples/audio/pitch.rs
  examples/ecs/event.rs
  examples/input/char_input_events.rs
  examples/input/gamepad_input_events.rs
  examples/input/keyboard_input_events.rs
  examples/input/mouse_input_events.rs
  examples/input/text_input.rs
  examples/input/touch_input_events.rs
  examples/mobile/src/lib.rs
  examples/tools/gamepad_viewer.rs
  examples/tools/scene_viewer/camera_controller_plugin.rs
  examples/ui/size_constraints.rs
  examples/ui/ui.rs
  examples/window/window_resizing.rs
  tests/how_to_test_systems.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#9640 Change `Urect::width` & `Urect::height` to be const
  crates/bevy_math/src/rects/urect.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#9651 fix typo
  crates/bevy_window/src/system.rs
Labels: S-Ready-For-Final-Review, A-Diagnostics

#9657 Change `Window::physical_cursor_position` to use the physical size of the window
  crates/bevy_window/src/window.rs
Labels: C-Bug, A-Input, A-Windowing, S-Ready-For-Final-Review

#9646 Fixing some doc comments
  crates/bevy_animation/src/lib.rs
  crates/bevy_asset/src/assets.rs
  crates/bevy_audio/src/audio.rs
  crates/bevy_audio/src/audio_source.rs
  crates/bevy_transform/src/commands.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Docs, S-Ready-For-Final-Review

#9650 Fix anonymous set name stack overflow
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review
