Repository bevyengine/bevy, pull requests merged in 2024-06, with the labels that each got.

#13533 Allow bevy_transform to be used as a barebones dependency
  crates/bevy_transform/Cargo.toml
  crates/bevy_transform/src/components/global_transform.rs
  crates/bevy_transform/src/components/transform.rs
  crates/bevy_transform/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Transform, X-Contentious

#13610 Implemented GizmoPrimitive2d for `Arc2d`, `CircularSegment`, `CircularSector`, and make arc_2d use counter-clockwise angle.
  crates/bevy_gizmos/src/arcs.rs
  crates/bevy_gizmos/src/primitives/dim2.rs
  examples/math/render_primitives.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math, A-Gizmos, X-Uncontroversial, D-Straightforward

#13616 Simplify state transitions
  crates/bevy_app/src/sub_app.rs
  crates/bevy_state/src/state/freely_mutable_state.rs
  crates/bevy_state/src/state/state_set.rs
  crates/bevy_state/src/state/transitions.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, D-Modest

#13551 Use correct minimal version of meshopt
  crates/bevy_pbr/Cargo.toml
Labels: C-Bug, A-Rendering, C-Dependencies, S-Ready-For-Final-Review

#13626 Combine transition systems of `Substates`
  crates/bevy_state/macros/src/states.rs
  crates/bevy_state/src/lib.rs
  crates/bevy_state/src/state/freely_mutable_state.rs
  crates/bevy_state/src/state/resources.rs
  crates/bevy_state/src/state/state_set.rs
  crates/bevy_state/src/state/sub_states.rs
  crates/bevy_state/src/state/transitions.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, X-Contentious, D-Modest

#13612 Update to `rodio` 0.18
  crates/bevy_audio/Cargo.toml
Labels: A-Audio, C-Dependencies, S-Ready-For-Final-Review

#13617 Add Skybox Motion Vectors
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_core_pipeline/src/skybox/prepass.rs
  crates/bevy_core_pipeline/src/skybox/skybox_prepass.wgsl
  crates/bevy_pbr/src/meshlet/gpu_scene.rs
  crates/bevy_pbr/src/meshlet/material_draw_nodes.rs
  crates/bevy_pbr/src/meshlet/visibility_buffer_raster_node.rs
  crates/bevy_pbr/src/prepass/mod.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, X-Uncontroversial, D-Modest

#13003 Meshlet single pass depth downsampling (SPD)
  crates/bevy_pbr/src/meshlet/downsample_depth.wgsl
  crates/bevy_pbr/src/meshlet/fill_cluster_buffers.wgsl
  crates/bevy_pbr/src/meshlet/gpu_scene.rs
  crates/bevy_pbr/src/meshlet/pipelines.rs
  crates/bevy_pbr/src/meshlet/visibility_buffer_raster_node.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, X-Uncontroversial, D-Modest

#13238 More idiomatic texture atlas builder
  crates/bevy_sprite/src/texture_atlas_builder.rs
  examples/2d/texture_atlas.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#13366 fix: upgrade to winit v0.30
  Cargo.toml
  crates/bevy_a11y/Cargo.toml
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_tasks/Cargo.toml
  crates/bevy_utils/Cargo.toml
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_window/src/raw_handle.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/accessibility.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/state.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_config.rs
  crates/bevy_winit/src/winit_event.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/README.md
  examples/mobile/src/lib.rs
  examples/window/custom_user_event.rs
  examples/window/low_power.rs
  examples/window/scale_factor_override.rs
  tools/example-showcase/extra-window-resized-events.patch
  tools/example-showcase/remove-desktop-app-mode.patch
Labels: A-Windowing, C-Dependencies, S-Ready-For-Final-Review, D-Complex, C-Needs-Release-Note, X-Uncontroversial

#13453 add handling of all missing gltf extras: scene, mesh & materials
  Cargo.toml
  assets/models/extras/gltf_extras.glb
  crates/bevy_gltf/src/lib.rs
  crates/bevy_gltf/src/loader.rs
  examples/3d/load_gltf_extras.rs
  examples/README.md
Labels: C-Enhancement, A-Rendering, A-Assets, S-Ready-For-Final-Review, C-Needs-Release-Note, X-Uncontroversial, D-Modest

#13525 Add Hash for Tick
  crates/bevy_ecs/src/component.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review, A-Networking

#13624 Handle wgsl errors in the game of life example
  examples/shader/compute_shader_game_of_life.rs
Labels: D-Trivial, C-Examples, S-Ready-For-Final-Review, X-Uncontroversial, D-Shaders

#13605 Additional options to mesh primitives
  crates/bevy_render/src/mesh/primitives/dim3/cone.rs
  crates/bevy_render/src/mesh/primitives/dim3/cylinder.rs
  crates/bevy_render/src/mesh/primitives/dim3/torus.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, A-Math, C-Breaking-Change

#13628 Extra info on Image debug assertions
  crates/bevy_render/src/texture/image.rs
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review, C-Testing, X-Uncontroversial

#13630 Make `SceneEntityMapper` constructor/destructor public
  crates/bevy_ecs/src/entity/map_entities.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Scenes, A-Networking

#13637 Move state installation methods from `bevy_app` to `bevy_state`
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/main_schedule.rs
  crates/bevy_app/src/sub_app.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_state/Cargo.toml
  crates/bevy_state/src/app.rs
  crates/bevy_state/src/lib.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-App, C-Breaking-Change

#13638 Clean up substate code a bit
  crates/bevy_state/src/state/state_set.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, D-Macros

#13580 Add subdivisions to PlaneMeshBuilder
  crates/bevy_render/src/mesh/primitives/dim3/plane.rs
  examples/3d/3d_shapes.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, A-Math, D-Straightforward

#13640 Move clustering-related types and functions into their own module.
  crates/bevy_pbr/src/cluster/assign.rs
  crates/bevy_pbr/src/cluster/mod.rs
  crates/bevy_pbr/src/cluster/test.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/render/light.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#13636 Add compass direction constants to `Dir2`
  crates/bevy_math/src/direction.rs
  crates/bevy_math/src/rotation2d.rs
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Math

#13648 feat: Reflection implementations on Identifier
  crates/bevy_ecs/src/identifier/mod.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review, A-Reflection

#13650 Map entities from a resource when written to the world.
  crates/bevy_ecs/src/reflect/map_entities.rs
  crates/bevy_ecs/src/reflect/mod.rs
  crates/bevy_scene/src/dynamic_scene.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Reflection, A-Scenes, C-Needs-Release-Note

#13489 Normalise matrix naming
  assets/shaders/array_texture.wgsl
  assets/shaders/custom_gltf_2d.wgsl
  assets/shaders/custom_vertex_attribute.wgsl
  assets/shaders/instancing.wgsl
  assets/shaders/irradiance_volume_voxel_visualization.wgsl
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_core_pipeline/src/skybox/skybox.wgsl
  crates/bevy_core_pipeline/src/skybox/skybox_prepass.wgsl
  crates/bevy_gizmos/src/line_joints.wgsl
  crates/bevy_gizmos/src/lines.wgsl
  crates/bevy_gltf/src/loader.rs
  crates/bevy_pbr/src/cluster/assign.rs
  crates/bevy_pbr/src/deferred/pbr_deferred_functions.wgsl
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/light_probe/irradiance_volume.wgsl
  crates/bevy_pbr/src/light_probe/light_probe.wgsl
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/meshlet/cull_meshlets.wgsl
  crates/bevy_pbr/src/meshlet/gpu_scene.rs
  crates/bevy_pbr/src/meshlet/visibility_buffer_raster.wgsl
  crates/bevy_pbr/src/meshlet/visibility_buffer_resolve.wgsl
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass.wgsl
  crates/bevy_pbr/src/prepass/prepass_bindings.wgsl
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh.wgsl
  crates/bevy_pbr/src/render/mesh_functions.wgsl
  crates/bevy_pbr/src/render/mesh_preprocess.wgsl
  crates/bevy_pbr/src/render/mesh_types.wgsl
  crates/bevy_pbr/src/render/mesh_view_types.wgsl
  crates/bevy_pbr/src/render/pbr_fragment.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_prepass_functions.wgsl
  crates/bevy_pbr/src/render/pbr_transmission.wgsl
  crates/bevy_pbr/src/render/shadows.wgsl
  crates/bevy_pbr/src/render/skinning.wgsl
  crates/bevy_pbr/src/render/view_transformations.wgsl
  crates/bevy_pbr/src/ssao/gtao.wgsl
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/projection.rs
  crates/bevy_render/src/primitives/mod.rs
  crates/bevy_render/src/render_phase/rangefinder.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/view.wgsl
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/mesh2d/mesh2d.wgsl
  crates/bevy_sprite/src/mesh2d/mesh2d_functions.wgsl
  crates/bevy_sprite/src/mesh2d/mesh2d_types.wgsl
  crates/bevy_sprite/src/render/sprite.wgsl
  crates/bevy_transform/src/components/global_transform.rs
  crates/bevy_transform/src/components/transform.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui.wgsl
  crates/bevy_ui/src/render/ui_material.wgsl
  examples/2d/mesh2d_manual.rs
  examples/3d/irradiance_volumes.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, C-Needs-Release-Note, X-Blessed

#13655 Regenerate light cluster patch file
  tools/example-showcase/reduce-light-cluster-config.patch
Labels: C-Bug, D-Trivial, A-Build-System, S-Ready-For-Final-Review, C-Regression, X-Uncontroversial, D-Domain-Agnostic

#13653 Added CompassQuadrant and CompassOctant as per #13647
  crates/bevy_math/src/compass.rs
  crates/bevy_math/src/lib.rs
Labels: C-Enhancement, D-Trivial, A-Input, S-Ready-For-Final-Review, A-Math, C-Needs-Release-Note, X-Contentious

#13450 Implement PBR anisotropy per `KHR_materials_anisotropy`.
  Cargo.toml
  assets/models/AnisotropyBarnLamp/AnisotropyBarnLamp.bin
  assets/models/AnisotropyBarnLamp/AnisotropyBarnLamp.gltf
  assets/models/AnisotropyBarnLamp/AnisotropyBarnLamp_anisotropy.ktx2
  assets/models/AnisotropyBarnLamp/AnisotropyBarnLamp_basecolor.jpeg
  assets/models/AnisotropyBarnLamp/AnisotropyBarnLamp_normalbump.ktx2
  assets/models/AnisotropyBarnLamp/AnisotropyBarnLamp_occlusionroughnessmetal.ktx2
  assets/shaders/array_texture.wgsl
  crates/bevy_gltf/src/loader.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/render/pbr_bindings.wgsl
  crates/bevy_pbr/src/render/pbr_fragment.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_lighting.wgsl
  crates/bevy_pbr/src/render/pbr_types.wgsl
  examples/3d/anisotropy.rs
  examples/README.md
  typos.toml
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, C-Needs-Release-Note, X-Uncontroversial, D-Modest

#13349 document need to update Aabb in Mesh::(with_)insert_attribute
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#12334 Add axes_2d gizmo.
  crates/bevy_gizmos/src/arrows.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Gizmos

#13662 Add `on_unimplemented` Diagnostics to Most Public Traits (#13347)
  Cargo.toml
  crates/bevy_app/src/plugin.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/map_entities.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/exclusive_system_param.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_reflect/compile_fail/tests/reflect_derive/generics_fail.rs
  crates/bevy_reflect/compile_fail/tests/reflect_derive/generics_fail.stderr
  crates/bevy_reflect/src/from_reflect.rs
  crates/bevy_reflect/src/path/mod.rs
  crates/bevy_reflect/src/reflect.rs
  crates/bevy_reflect/src/type_info.rs
  crates/bevy_reflect/src/type_path.rs
  crates/bevy_reflect/src/type_registry.rs
  crates/bevy_state/src/state/freely_mutable_state.rs
  crates/bevy_state/src/state/states.rs
  crates/bevy_state/src/state/sub_states.rs
Labels: C-Enhancement, D-Trivial, A-ECS, S-Ready-For-Final-Review, X-Uncontroversial

#13404 Fix a few typos
  crates/bevy_ecs/src/event.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#13660 rename touchpad to gesture, and add new gestures
  crates/bevy_input/src/gestures.rs
  crates/bevy_input/src/lib.rs
  crates/bevy_input/src/touchpad.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/state.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_event.rs
  examples/input/mouse_input_events.rs
  examples/mobile/src/lib.rs
Labels: C-Enhancement, A-Input, O-MacOS, O-iOS, S-Ready-For-Final-Review

#13579 Generalize `StateTransitionEvent<S>` to allow identity transitions
  Cargo.toml
  crates/bevy_state/src/lib.rs
  crates/bevy_state/src/state/freely_mutable_state.rs
  crates/bevy_state/src/state/mod.rs
  crates/bevy_state/src/state/transitions.rs
  crates/bevy_state/src/state_scoped.rs
  examples/README.md
  examples/state/custom_transitions.rs
  examples/state/states.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review, C-Needs-Release-Note, X-Contentious

#13670 `Dir2` -> `Rotation2d` conversions
  crates/bevy_math/src/direction.rs
  crates/bevy_math/src/rotation2d.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math, X-Uncontroversial, D-Straightforward

#13584 Add dynamic slice based variants of get_many_entities methods
  crates/bevy_ecs/src/world/mod.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review, X-Uncontroversial, D-Modest, D-Unsafe

#13667 Add `binding()` helper function to `BufferVec`
  crates/bevy_render/src/render_resource/buffer_vec.rs
  crates/bevy_render/src/render_resource/gpu_array_buffer.rs
Labels: D-Trivial, A-Rendering, C-Usability, S-Ready-For-Final-Review

#13423 Implement subpixel morphological antialiasing, or SMAA.
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_core_pipeline/src/smaa/SMAAAreaLUT.ktx2
  crates/bevy_core_pipeline/src/smaa/SMAASearchLUT.ktx2
  crates/bevy_core_pipeline/src/smaa/mod.rs
  crates/bevy_core_pipeline/src/smaa/smaa.wgsl
  examples/3d/anti_aliasing.rs
  typos.toml
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, D-Complex, C-Needs-Release-Note, X-Uncontroversial

#13346 Extrusion bounded
  crates/bevy_math/src/bounding/bounded3d/extrusion.rs
  crates/bevy_math/src/bounding/bounded3d/mod.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math

#13478 Meshable extrusions
  crates/bevy_render/src/mesh/primitives/dim2.rs
  crates/bevy_render/src/mesh/primitives/dim3/conical_frustum.rs
  crates/bevy_render/src/mesh/primitives/dim3/cuboid.rs
  crates/bevy_render/src/mesh/primitives/dim3/tetrahedron.rs
  crates/bevy_render/src/mesh/primitives/dim3/triangle3d.rs
  crates/bevy_render/src/mesh/primitives/extrusion.rs
  crates/bevy_render/src/mesh/primitives/mod.rs
  examples/3d/3d_shapes.rs
  examples/math/render_primitives.rs
  examples/math/sampling_primitives.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, A-Math, C-Breaking-Change, C-Needs-Release-Note, X-Contentious, D-Modest

#13668 Use `BufferVec` for `gpu_readback` example
  examples/shader/gpu_readback.rs
Labels: D-Trivial, A-Rendering, C-Examples, S-Needs-Review

#13674 Forward exit codes in default app runner
  crates/bevy_app/src/app.rs
Labels: C-Bug, A-App, X-Uncontroversial, D-Straightforward, S-Needs-Review

#13676 Meshable extrusions - Part 2
  crates/bevy_render/src/mesh/primitives/dim2.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math, X-Uncontroversial, D-Straightforward

#13678 flush key_input cache when Bevy loses focus (Adopted)
  crates/bevy_input/src/keyboard.rs
  crates/bevy_input/src/lib.rs
  crates/bevy_winit/src/state.rs
  crates/bevy_winit/src/winit_event.rs
Labels: C-Bug, A-Input, A-Windowing, S-Ready-For-Final-Review

#13679 Skip tonemapping in case it is none
  crates/bevy_core_pipeline/src/tonemapping/node.rs
Labels: D-Trivial, A-Rendering, C-Performance, S-Ready-For-Final-Review, X-Uncontroversial

#13684 Allow creation of random `Rotation2d`
  crates/bevy_math/src/sampling/standard.rs
Labels: C-Enhancement, D-Trivial, S-Ready-For-Final-Review, A-Math, X-Uncontroversial

#13686 make sure windows are dropped on main thread
  crates/bevy_winit/src/system.rs
Labels: C-Bug, A-Windowing, O-MacOS, S-Ready-For-Final-Review, D-Straightforward

#13688 Allow `Bounded3d` implementations for custom primitives
  crates/bevy_math/src/bounding/bounded3d/extrusion.rs
  crates/bevy_math/src/bounding/bounded3d/mod.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math

#13691 hashing error in bevy_reflect now includes the type (bevyengine#13646)
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/map.rs
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Reflection

#13694 Rename `Rotation2d` to `Rot2`
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_math/src/bounding/bounded2d/mod.rs
  crates/bevy_math/src/bounding/bounded2d/primitive_impls.rs
  crates/bevy_math/src/direction.rs
  crates/bevy_math/src/lib.rs
  crates/bevy_math/src/rotation2d.rs
  crates/bevy_math/src/sampling/standard.rs
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Math, X-Contentious

#13506 Avoid a panic when loading labelled assets
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/server/info.rs
Labels: C-Bug, A-Assets, P-Crash, S-Ready-For-Final-Review

#13558 Add labels to Gltf Node and Mesh assets
  crates/bevy_gltf/src/lib.rs
  crates/bevy_gltf/src/loader.rs
Labels: C-Enhancement, A-Assets, S-Ready-For-Final-Review

#13697 make UI text rendering camera driven
  crates/bevy_ui/src/widget/text.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#13699 async_compute example: don't block in the task
  Cargo.toml
  examples/async_tasks/async_compute.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Tasks

#13700 Allow loading assets with custom async behavior
  crates/bevy_asset/src/server/mod.rs
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review

#13710 Made `Mesh::merge` take a reference of `Mesh`.
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/mesh/primitives/extrusion.rs
Labels: D-Trivial, A-Rendering, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#13705 Misc meshlet changes
  crates/bevy_pbr/src/meshlet/cull_clusters.wgsl
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/meshlet/pipelines.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#13716 Use TBN in apply_normal_mapping in pbr_prepass
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#13715 Provide more information when a filewatcher failure is hit.
  crates/bevy_asset/src/io/file/file_watcher.rs
Labels: D-Trivial, A-Assets, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial

#13704 Fix links to `Transform` in `Transform` and `GlobalTransform` docs
  crates/bevy_transform/src/components/global_transform.rs
  crates/bevy_transform/src/components/transform.rs
Labels: C-Bug, C-Docs, S-Ready-For-Final-Review, A-Transform

#13419 Allow mix of hdr and non-hdr cameras to same render target
  crates/bevy_core_pipeline/src/upscaling/mod.rs
  crates/bevy_core_pipeline/src/upscaling/node.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/clear_color.rs
  crates/bevy_render/src/texture/texture_attachment.rs
  crates/bevy_render/src/view/mod.rs
Labels: C-Bug, A-Rendering, X-Uncontroversial, D-Modest, S-Needs-Review

#13721 rename bevy_state_macros to bevy_state_macros_official
  crates/bevy_state/Cargo.toml
  crates/bevy_state/macros/Cargo.toml
  crates/bevy_state/src/condition.rs
  crates/bevy_state/src/state/mod.rs
  crates/bevy_state/src/state/resources.rs
  crates/bevy_state/src/state/sub_states.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, X-Blessed

#13722 Update crate metadata for bevy state
  crates/bevy_state/Cargo.toml
  crates/bevy_state/macros/Cargo.toml
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#13718 Document the Release Candidate process
  .github/workflows/ci.yml
  .github/workflows/validation-jobs.yml
  docs/release_checklist.md
Labels: C-Docs, A-Meta

#13706 improved the error message by insert_boxed (issue #13646) (again)
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/map.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#13736 Make the component types of the new animation players clonable.
  crates/bevy_animation/src/lib.rs
  crates/bevy_animation/src/transition.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Animation

#13717 Uncouple `DynamicTextureAtlasBuilder` from assets
  crates/bevy_sprite/src/dynamic_texture_atlas_builder.rs
  crates/bevy_text/src/font_atlas.rs
  crates/bevy_text/src/font_atlas_set.rs
  crates/bevy_text/src/glyph_brush.rs
Labels: D-Trivial, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, A-Text, X-Uncontroversial

#13727 Add `mappings` to `EntityMapper`
  crates/bevy_ecs/src/entity/map_entities.rs
  crates/bevy_ecs/src/label.rs
  crates/bevy_utils/src/lib.rs
  crates/bevy_utils/src/object_safe.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, D-Straightforward

#13737 Clear messed up feature flag on AppExitStates impl
  crates/bevy_state/src/app.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, P-Compile-Failure

#13756 view.inverse_clip_from_world should be world_from_clip
  crates/bevy_gizmos/src/lines.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, A-Gizmos

#13774 Fix EntityCommands::despawn docs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_hierarchy/src/hierarchy.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#13779 Let init_non_send_resource require FromWorld instead of Default
  crates/bevy_app/src/app.rs
Labels: C-Bug, S-Ready-For-Final-Review, C-Regression, A-App

#13776 Fix minor doc typo
  crates/bevy_time/src/stopwatch.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Time

#12720 2D top-down camera example
  Cargo.toml
  examples/README.md
  examples/camera/2d_top_down_camera.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#13719 Add segments to `ExtrusionBuilder`
  crates/bevy_render/src/mesh/primitives/extrusion.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math, X-Uncontroversial, D-Straightforward

#13741 Stable interpolation and smooth following
  Cargo.toml
  crates/bevy_math/src/common_traits.rs
  crates/bevy_math/src/lib.rs
  examples/README.md
  examples/math/smooth_follow.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math, C-Needs-Release-Note, X-Contentious

#13745 Improve error handling for `AssetServer::add_async`
  crates/bevy_asset/src/server/mod.rs
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#13752 Remove unused mip_bias parameter from apply_normal_mapping
  assets/shaders/array_texture.wgsl
  crates/bevy_pbr/src/render/pbr_fragment.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#13759 Adds back in way to convert color to u8 array, implemented for the two RGB color types, also renames Color::linear to Color::to_linear.
  crates/bevy_color/src/color.rs
  crates/bevy_color/src/color_ops.rs
  crates/bevy_color/src/linear_rgba.rs
  crates/bevy_color/src/srgba.rs
  crates/bevy_pbr/src/fog.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/volumetric_fog/mod.rs
  crates/bevy_sprite/src/mesh2d/color_material.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/mod.rs
Labels: C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward, A-Color

#13761 Meshlet misc
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/meshlet/meshlet_mesh_material.wgsl
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/meshlet/visibility_buffer_resolve.wgsl
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#13763 Add more granular system sets for state transition schedule ordering
  crates/bevy_state/src/lib.rs
  crates/bevy_state/src/state/freely_mutable_state.rs
  crates/bevy_state/src/state/mod.rs
  crates/bevy_state/src/state/state_set.rs
  crates/bevy_state/src/state/sub_states.rs
  crates/bevy_state/src/state/transitions.rs
  examples/state/custom_transitions.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, X-Contentious

#13766 Clarify error message due to missing shader file
  crates/bevy_render/src/render_resource/pipeline_cache.rs
Labels: D-Trivial, A-Rendering, C-Usability, S-Ready-For-Final-Review

#13772 fix docs around `StateTransition` and remove references to `apply_sta…
  crates/bevy_app/src/main_schedule.rs
  crates/bevy_state/src/state/resources.rs
  crates/bevy_state/src/state/transitions.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#13783 Make FOG_ENABLED a shader_def instead of material flag
  crates/bevy_pbr/src/deferred/pbr_deferred_types.wgsl
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_types.wgsl
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#13784 Re-name and Extend Run Conditions API
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_state/src/condition.rs
  examples/ecs/run_conditions.rs
  examples/math/render_primitives.rs
Labels: C-Enhancement, A-ECS, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, X-Contentious

#13740 Update serialize flag for bevy_ecs
  crates/bevy_app/Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_scene/Cargo.toml
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#13788 Added an illustration to the compass direction docs (issue 13664)
  crates/bevy_math/src/compass.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Math

#13762 Remove extra call to clear_trackers
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/sub_app.rs
  crates/bevy_ecs/src/removal_detection.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#13693 Poll system information in separate tasks
  crates/bevy_diagnostic/Cargo.toml
  crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs
Labels: C-Bug, C-Performance, S-Ready-For-Final-Review, A-Diagnostics, A-Dev-Tools

#13775 Fix meshlet vertex attribute interpolation
  crates/bevy_pbr/src/meshlet/visibility_buffer_resolve.wgsl
  crates/bevy_pbr/src/render/mesh_functions.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#13800 Revert Align Scene::write_to_world_with to match DynamicScene::write_to_world_with
  crates/bevy_scene/src/scene.rs
  crates/bevy_scene/src/scene_spawner.rs
Labels: C-Bug, D-Trivial, P-High, S-Ready-For-Final-Review, A-Scenes, X-Uncontroversial

#13795 Custom primitives example
  Cargo.toml
  examples/README.md
  examples/math/custom_primitives.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Math

#13791 Add `from_color` to `StandardMaterial` and `ColorMaterial`
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_sprite/src/mesh2d/color_material.rs
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review, X-Contentious

#13801 Split event.rs into a full module.
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/event/base.rs
  crates/bevy_ecs/src/event/collections.rs
  crates/bevy_ecs/src/event/iterators.rs
  crates/bevy_ecs/src/event/mod.rs
  crates/bevy_ecs/src/event/reader.rs
  crates/bevy_ecs/src/event/registry.rs
  crates/bevy_ecs/src/event/update.rs
  crates/bevy_ecs/src/event/writer.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#13803 Revert "Make FOG_ENABLED a shader_def instead of material flag (#13783)"
  crates/bevy_pbr/src/deferred/pbr_deferred_types.wgsl
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_types.wgsl
Labels: C-Bug, D-Trivial, A-Rendering, S-Needs-Review

#13804 Revert "constrain WorldQuery::init_state argument to ComponentInitial…
  crates/bevy_ecs/macros/src/world_query.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/query/builder.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/query/world_query.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#13812 Fix minor typos in query join docs
  crates/bevy_ecs/src/system/query.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#13824 Highlight dependency on shader files in examples
  examples/2d/custom_gltf_vertex_attribute.rs
  examples/3d/irradiance_volumes.rs
  examples/3d/lines.rs
  examples/3d/ssr.rs
  examples/3d/tonemapping.rs
  examples/shader/animate_shader.rs
  examples/shader/array_texture.rs
  examples/shader/custom_vertex_attribute.rs
  examples/shader/extended_material.rs
  examples/shader/fallback_image.rs
  examples/shader/gpu_readback.rs
  examples/shader/post_processing.rs
  examples/shader/shader_defs.rs
  examples/shader/shader_instancing.rs
  examples/shader/shader_material.rs
  examples/shader/shader_material_2d.rs
  examples/shader/shader_material_glsl.rs
  examples/shader/shader_material_screenspace_texture.rs
  examples/shader/shader_prepass.rs
  examples/shader/texture_binding_array.rs
  examples/ui/ui_material.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#13808 Ensure that events are updated even when using a bare-bones Bevy App
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/event/collections.rs
  crates/bevy_ecs/src/event/mod.rs
  crates/bevy_ecs/src/event/registry.rs
  crates/bevy_ecs/src/event/update.rs
  crates/bevy_time/src/lib.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, A-Time, D-Modest

#13834 run windows ci on rust 1.78
  .github/workflows/validation-jobs.yml
Labels: A-Build-System, S-Waiting-on-Author

#13833 Add missing plugins to doc of DefaultPlugins
  crates/bevy_internal/src/default_plugins.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-App

#13540 Use dynamic uniform buffer in post processing example
  examples/shader/post_processing.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#13814 reduce the antialias strength
  crates/bevy_ui/src/render/ui.wgsl
Labels: C-Bug, A-Rendering, A-UI, S-Ready-For-Final-Review

#13842 Ensure that events are updated even when using a bare-bones Bevy App (#13808)
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_time/src/lib.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, A-App

#13186 Wgpu 0.20
  crates/bevy_color/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/diagnostic/internal.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/render_resource/mod.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/renderer/mod.rs
Labels: A-Rendering, C-Dependencies, S-Ready-For-Final-Review, X-Uncontroversial, D-Modest

#13849 Mention updating Bevy book code validation for release candidates
  docs/release_checklist.md
Labels: C-Enhancement, D-Trivial, A-Meta, S-Ready-For-Final-Review

#13846 fix non-exact text h-alignment
  crates/bevy_text/src/glyph_brush.rs
  crates/bevy_text/src/pipeline.rs
Labels: C-Bug, A-Text, X-Uncontroversial, D-Straightforward, S-Needs-Review

#13817 Fix is_plugin_added::<Self>() being true during build
  crates/bevy_app/src/app.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-App

#13848 Restore overwrite capabilities of `insert_state`
  crates/bevy_state/src/app.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#10839 Generalised ECS reactivity with Observers
  Cargo.toml
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/README.md
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/event/base.rs
  crates/bevy_ecs/src/event/writer.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/observer/entity_observer.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/observer/trigger_event.rs
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/observer_system.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/command_queue.rs
  crates/bevy_ecs/src/world/component_constants.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/spawn_batch.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  examples/README.md
  examples/ecs/observers.rs
Labels: C-Enhancement, A-ECS, X-Controversial, S-Needs-SME

#13858 text position: use size instead of bounds
  crates/bevy_text/src/pipeline.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Text, D-Straightforward

#13870 Allow bevy_color use without bevy_reflect support
  crates/bevy_color/Cargo.toml
  crates/bevy_color/src/color.rs
  crates/bevy_color/src/hsla.rs
  crates/bevy_color/src/hsva.rs
  crates/bevy_color/src/hwba.rs
  crates/bevy_color/src/laba.rs
  crates/bevy_color/src/lcha.rs
  crates/bevy_color/src/lib.rs
  crates/bevy_color/src/linear_rgba.rs
  crates/bevy_color/src/oklaba.rs
  crates/bevy_color/src/oklcha.rs
  crates/bevy_color/src/srgba.rs
  crates/bevy_color/src/xyza.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Color

#13862 remove inaccurate warning from `in_state`
  crates/bevy_state/src/condition.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#13877 Warn about missing `StatesPlugin` when installing states
  crates/bevy_state/src/app.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#13879 Make time_system public
  crates/bevy_time/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Time

#13880 fix typo
  crates/bevy_winit/src/winit_config.rs
Labels: C-Docs, D-Trivial, A-Windowing

#13884 observers example doesn't follow standards
  examples/ecs/observers.rs
Labels: A-ECS, C-Examples, S-Ready-For-Final-Review

#13696 Fix phantom key presses in winit on focus change (#13299)
  crates/bevy_winit/src/state.rs
Labels: C-Bug, A-Input, O-Linux, O-Windows, S-Ready-For-Final-Review, D-Straightforward

#13789 Use a unstable sort to sort component ids in `bevy_ecs`
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/schedule/graph_utils.rs
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: A-ECS, C-Performance, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward, D-Domain-Agnostic

#13830 Made some things in bevy_render `Debug`.
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_render/src/view/visibility/mod.rs
Labels: D-Trivial, A-Rendering, C-Usability, S-Ready-For-Final-Review

#13841 Update accesskit and accesskit_winit
  crates/bevy_a11y/Cargo.toml
  crates/bevy_winit/Cargo.toml
Labels: C-Dependencies, A-Accessibility, A-UI, S-Ready-For-Final-Review, X-Contentious

#13886 Update observer archetype flags for sparse components
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/observer/mod.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#13896 Fix parameter name of all_tuples's document
  crates/bevy_utils/macros/src/lib.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Utils

#13898 Fix minor typo
  .cargo/config_fast_builds.toml
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, X-Uncontroversial

#13883 Add cross gizmos
  crates/bevy_gizmos/src/cross.rs
  crates/bevy_gizmos/src/grid.rs
  crates/bevy_gizmos/src/lib.rs
  examples/gizmos/2d_gizmos.rs
  examples/gizmos/3d_gizmos.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Gizmos, C-Needs-Release-Note, X-Uncontroversial

#13899 Fix lints introduced in Rust beta 1.80
  crates/bevy_animation/src/lib.rs
  crates/bevy_app/src/panic_handler.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/path.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_core_pipeline/src/auto_exposure/compensation_curve.rs
  crates/bevy_core_pipeline/src/auto_exposure/settings.rs
  crates/bevy_dev_tools/src/lib.rs
  crates/bevy_ecs/src/event/collections.rs
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/storage/blob_vec.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_gizmos/src/arcs.rs
  crates/bevy_gizmos/src/rounded_box.rs
  crates/bevy_log/src/lib.rs
  crates/bevy_pbr/src/fog.rs
  crates/bevy_pbr/src/light_probe/irradiance_volume.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/pipelined_rendering.rs
  crates/bevy_render/src/primitives/mod.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/scene.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/texture_slice/computed_slices.rs
  crates/bevy_sprite/src/texture_slice/mod.rs
  crates/bevy_text/src/text.rs
  crates/bevy_transform/src/components/transform.rs
  crates/bevy_transform/src/systems.rs
  crates/bevy_ui/src/texture_slice.rs
  crates/bevy_ui/src/widget/text.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/winit_config.rs
  examples/camera/first_person_view_model.rs
  examples/ecs/component_hooks.rs
  tools/example-showcase/src/main.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#13867 bevy_reflect: Improve reflection serialization error messages
  crates/bevy_reflect/src/serde/de.rs
  crates/bevy_reflect/src/serde/ser.rs
Labels: C-Docs, D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Reflection

#13894 Reuse VisibleEntities in check_light_mesh_visibilty
  crates/bevy_pbr/src/light/mod.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, D-Straightforward

#13905 Refactor check_light_mesh_visibility for performance #1
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light/mod.rs
Labels: A-Rendering, C-Performance, C-Code-Quality, S-Ready-For-Final-Review

#13904 Improve MeshletMesh::from_mesh performance
  crates/bevy_pbr/src/meshlet/from_mesh.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#13297 Specify units in `AmbientLight::brightness` docs
  crates/bevy_pbr/src/light/ambient_light.rs
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review, D-Domain-Expert

#13907 Use smooth_nudge in 2d_top_down_camera example
  examples/camera/2d_top_down_camera.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Math

#13916 Fix typo in `Query::single_mut` docs
  crates/bevy_ecs/src/system/query.rs
Labels: C-Docs, D-Trivial, A-ECS

#13919 `IntoSystemConfigs::chain_ignore_deferred`'s return type fix
  crates/bevy_ecs/src/schedule/config.rs
Labels: A-ECS, C-Usability, C-Breaking-Change, D-Straightforward

#13908 Shader code paths
  tools/example-showcase/Cargo.toml
  tools/example-showcase/src/main.rs
Labels: A-Build-System, C-Examples, S-Needs-Review

#13924 Fixed a link to Blender's mikktspace docs
  crates/bevy_mikktspace/README.md
Labels: C-Docs

#13897 Improve error handling for log filter
  crates/bevy_log/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Diagnostics

#13837 Use a well defined type for sides in RegularPolygon
  crates/bevy_gizmos/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_render/src/mesh/primitives/dim2.rs
Labels: S-Ready-For-Final-Review, A-Math, C-Breaking-Change

#13927 Use u32 for all resolution/subdivision fields in bevy_gizmos
  crates/bevy_gizmos/src/arcs.rs
  crates/bevy_gizmos/src/circles.rs
  crates/bevy_gizmos/src/primitives/dim2.rs
  crates/bevy_gizmos/src/primitives/dim3.rs
  crates/bevy_gizmos/src/primitives/helpers.rs
  crates/bevy_gizmos/src/rounded_box.rs
Labels: S-Ready-For-Final-Review, C-Breaking-Change, A-Gizmos

#13921 bug: Fix 9-slice textures with asymmetric borders.
  crates/bevy_sprite/src/texture_slice/mod.rs
  crates/bevy_sprite/src/texture_slice/slicer.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#13929 docs(bevy_state): fix broken links in init_state and insert_state
  crates/bevy_state/src/app.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#13932 Fix typo in `ComponentId` docs: `of` -> `or`
  crates/bevy_ecs/src/component.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#13934 Change World::inspect_entity to return an Iterator instead of Vec
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, X-Uncontroversial, D-Straightforward

#13935 Use a ship in Transform::align example
  assets/models/ship/craft_speederD.gltf
  assets/models/ship/craft_speederD_data.bin
  examples/transforms/align.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Transform

#13939 Move `StateTransitionSteps` registration to states plugin
  crates/bevy_state/src/app.rs
  examples/state/custom_transitions.rs
Labels: C-Bug, D-Trivial, A-ECS, S-Ready-For-Final-Review, A-App

#13913 Make meshlet processing deterministic
  crates/bevy_pbr/src/meshlet/from_mesh.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#13930 Use u32 for resolution/subdivision in primitive meshing
  crates/bevy_render/src/mesh/primitives/dim2.rs
  crates/bevy_render/src/mesh/primitives/dim3/capsule.rs
  crates/bevy_render/src/mesh/primitives/dim3/sphere.rs
  crates/bevy_render/src/mesh/primitives/extrusion.rs
Labels: A-Rendering, S-Ready-For-Final-Review, A-Math, C-Breaking-Change

#13941 feat: add insert_after and insert_startup_before
  crates/bevy_app/src/main_schedule.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-App, X-Uncontroversial, D-Straightforward

#13942 Correctly check physical size when updating winit
  crates/bevy_winit/src/system.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review

#13951 Use default window and font sizes in sprite_slice example
  examples/2d/sprite_slice.rs
Labels: D-Trivial, A-Rendering, C-Examples, S-Ready-For-Final-Review

#13952 Omit font size where it closely matches the default in examples
  examples/3d/anisotropy.rs
  examples/3d/blend_modes.rs
  examples/ecs/one_shot_systems.rs
  examples/ui/display_and_visibility.rs
  examples/ui/flex_layout.rs
  examples/ui/grid.rs
Labels: D-Trivial, C-Examples, C-Code-Quality, S-Ready-For-Final-Review
