Repository bevyengine/bevy, pull requests merged in 2024-04, with the labels that each got.

#12818 Remove unused `ImePreedit` component from `text_input` example
  examples/input/text_input.rs
Labels: C-Examples, A-Input, C-Code-Quality

#12811 remove `DeterministicRenderingConfig`
  Cargo.toml
  crates/bevy_render/src/deterministic.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/view/visibility/mod.rs
  examples/3d/deterministic.rs
  examples/README.md
Labels: A-Rendering, C-Breaking-Change

#12832 Fix wrong dependency in weekly ci
  .github/workflows/weekly.yml
Labels: C-Bug, A-Build-System, S-Ready-For-Final-Review

#12817 Remove redundant imports
  crates/bevy_color/src/hsla.rs
  crates/bevy_color/src/hsva.rs
  crates/bevy_color/src/hwba.rs
  crates/bevy_color/src/laba.rs
  crates/bevy_color/src/lcha.rs
  crates/bevy_color/src/oklaba.rs
  crates/bevy_color/src/oklcha.rs
  crates/bevy_ecs/src/entity/hash.rs
  crates/bevy_ecs/src/query/builder.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/stepping.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_math/src/direction.rs
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_reflect/src/path/mod.rs
  crates/bevy_render/src/texture/image.rs
  crates/bevy_render/src/texture/image_texture_conversion.rs
  crates/bevy_time/src/common_conditions.rs
  crates/bevy_transform/src/systems.rs
  examples/3d/3d_viewport_to_world.rs
  examples/3d/shadow_caster_receiver.rs
  examples/animation/cubic_curve.rs
  examples/animation/custom_skinned_mesh.rs
  examples/animation/gltf_skinned_mesh.rs
  examples/app/return_after_run.rs
  examples/asset/custom_asset.rs
  examples/ecs/component_change_detection.rs
  examples/ecs/dynamic.rs
  examples/gizmos/light_gizmos.rs
  examples/input/char_input_events.rs
  examples/input/gamepad_input.rs
  examples/shader/compute_shader_game_of_life.rs
  examples/stress_tests/many_animated_sprites.rs
  examples/stress_tests/many_buttons.rs
  examples/stress_tests/many_glyphs.rs
  examples/stress_tests/many_lights.rs
  examples/stress_tests/many_sprites.rs
  examples/stress_tests/text_pipeline.rs
  examples/tools/gamepad_viewer.rs
  examples/tools/scene_viewer/main.rs
  examples/transforms/align.rs
  examples/ui/text_debug.rs
  examples/window/low_power.rs
  examples/window/transparent_window.rs
  tests/how_to_test_systems.rs
  tools/ci/src/main.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review, C-Testing, A-Cross-Cutting

#12833 Normalize warning messages with Nvidia drivers
  crates/bevy_render/src/view/window/mod.rs
Labels: C-Bug, A-Rendering

#12815 Add `RemovedComponentEvents::iter`
  crates/bevy_ecs/src/removal_detection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#12556 fix previous_position / previous_force being discarded too early
  crates/bevy_input/src/touch.rs
Labels: C-Bug, A-Input, O-Android, O-iOS, S-Ready-For-Final-Review

#12688 Add `Tetrahedron` primitive to `bevy_math::primitives`
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_reflect/src/impls/math/primitives3d.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math, C-Needs-Release-Note

#12734 Meshing for `Annulus` primitive
  crates/bevy_reflect/src/impls/math/primitives2d.rs
  crates/bevy_reflect/src/impls/math/primitives3d.rs
  crates/bevy_render/src/mesh/primitives/dim2.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, A-Math, C-Needs-Release-Note

#12791 Micro-optimize `queue_material_meshes`, primarily to remove bit manipulation.
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/render_resource/pipeline_specializer.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  examples/2d/mesh2d_manual.rs
  examples/shader/shader_instancing.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#12363 many_cubes: Add no automatic batching and generation of different meshes
  examples/stress_tests/many_cubes.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#12801 [bevy_ui/layout] Extract UiSurface to its own file
  crates/bevy_ui/src/layout/debug.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/layout/ui_surface.rs
  crates/bevy_ui/src/lib.rs
Labels: A-UI, C-Code-Quality, S-Ready-For-Final-Review

#12844 Remove unnecessary branch in query iteration
  crates/bevy_ecs/src/storage/table.rs
Labels: A-ECS, C-Performance

#12855 Move `close_on_esc` to `bevy_dev_tools`
  crates/bevy_dev_tools/src/close_on_esc.rs
  crates/bevy_dev_tools/src/lib.rs
  crates/bevy_window/Cargo.toml
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/system.rs
  crates/bevy_window/src/window.rs
  examples/2d/rotation.rs
  examples/3d/parallax_mapping.rs
  examples/games/alien_cake_addict.rs
  examples/games/breakout.rs
  examples/window/multiple_windows.rs
  tests/window/resizing.rs
Labels: C-Examples, A-Windowing, C-Breaking-Change, A-Dev-Tools

#12854 Changed the order of arguments for the Arc gizmo docs
  crates/bevy_gizmos/src/arcs.rs
Labels: C-Docs, A-Gizmos

#12829 Add methods `iter_resources` and `iter_resources_mut`
  crates/bevy_ecs/src/world/mod.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review, A-Networking, C-Needs-Release-Note, A-Dev-Tools

#12802 [bevy_ui/layout] Update tests to get GlobalTransform properly
  crates/bevy_ui/src/layout/mod.rs
Labels: A-UI, C-Testing, A-Transform

#12842 Add `EntityWorldMut::remove_by_id`
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: C-Enhancement, A-ECS

#12859 remove close_on_esc
  crates/bevy_dev_tools/src/close_on_esc.rs
  crates/bevy_dev_tools/src/lib.rs
Labels: S-Ready-For-Final-Review, C-Breaking-Change, A-Dev-Tools

#12828 Ignore query parameters in AssetPaths when determining the extension
  crates/bevy_asset/src/path.rs
Labels: C-Bug, A-Assets

#12865 fixing line comment in 2d_shapes.rs example
  examples/2d/2d_shapes.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Math

#12867 Change `Tetrahedron` default origin to `(0, 0, 0)`
  crates/bevy_math/src/primitives/dim3.rs
Labels: C-Bug, A-Math

#12846 Cluster small table/archetype into single Task in parallel iteration
  benches/benches/bevy_ecs/iteration/mod.rs
  benches/benches/bevy_ecs/iteration/par_iter_simple.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/query/state.rs
Labels: A-ECS, C-Performance

#12709 Error info has been added to LoadState::Failed
  crates/bevy_asset/src/io/mod.rs
  crates/bevy_asset/src/io/source.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/loader.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/server/info.rs
  crates/bevy_asset/src/server/mod.rs
Labels: A-Assets, C-Usability, C-Breaking-Change, C-Needs-Release-Note

#12862 Disable RAY_QUERY and RAY_TRACING_ACCELERATION_STRUCTURE by default
  crates/bevy_render/src/renderer/mod.rs
Labels: C-Bug, A-Rendering, C-Crash

#12879 document how to publish patches
  docs/release_checklist.md
Labels: A-Meta, S-Ready-For-Final-Review

#12857 Random sampling of directions and quaternions
  crates/bevy_math/Cargo.toml
  crates/bevy_math/src/lib.rs
  crates/bevy_math/src/sampling/mod.rs
  crates/bevy_math/src/sampling/shape_sampling.rs
  crates/bevy_math/src/sampling/standard.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math

#12866 Relax BufferVec's type constraints
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/meshlet/gpu_scene.rs
  crates/bevy_pbr/src/render/morph.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/render_resource/buffer_vec.rs
Labels: A-Rendering, C-Usability

#12874 Added method to get waiting pipelines IDs from pipeline cache.
  crates/bevy_render/src/render_resource/pipeline_cache.rs
Labels: A-Rendering, C-Usability

#12845 fix msaa shift with irradiance volumes in mesh pipeline key
  crates/bevy_pbr/src/render/mesh.rs
Labels: A-Rendering, C-Crash, S-Ready-For-Final-Review

#12872 Fix broken link in mesh docs
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Bug, C-Docs, A-Rendering, S-Ready-For-Final-Review

#12861 Fixes #12000: When viewport is set to camera and switched to SizedFul…
  crates/bevy_render/src/camera/camera.rs
  tests/window/change_window_mode.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review

#12888 Fix skybox wrong alpha
  crates/bevy_core_pipeline/src/skybox/skybox.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#12608 Fix example showcase wasm window settings patch
  tools/example-showcase/window-settings-wasm.patch
Labels: C-Bug, C-Examples, S-Ready-For-Final-Review

#12896 Implement `From<&'w mut EntityMut>` for `EntityMut<'w>`
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: A-ECS, C-Usability

#12606 more robust gpu image use
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/node.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#12902 Add previous_view_uniforms.inverse_view
  crates/bevy_pbr/src/meshlet/material_draw_nodes.rs
  crates/bevy_pbr/src/meshlet/visibility_buffer_resolve.wgsl
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass.wgsl
  crates/bevy_pbr/src/prepass/prepass_bindings.wgsl
  crates/bevy_pbr/src/render/pbr_prepass_functions.wgsl
Labels: C-Enhancement, A-Rendering, C-Breaking-Change

#12895 Make some `ReflectComponent`/`ReflectBundle` methods work with `EntityMut` too
  crates/bevy_ecs/src/reflect/bundle.rs
  crates/bevy_ecs/src/reflect/component.rs
Labels: A-ECS, C-Usability, A-Reflection

#12907 Bump crate-ci/typos from 1.19.0 to 1.20.4
  .github/workflows/ci.yml
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  typos.toml
Labels: C-Dependencies

#12772 Moves intern and label modules into bevy_ecs
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/intern.rs
  crates/bevy_ecs/src/label.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_render/src/render_graph/graph.rs
  crates/bevy_render/src/render_graph/node.rs
  crates/bevy_utils/src/lib.rs
Labels: A-ECS, C-Code-Quality, C-Breaking-Change, A-Utils

#12585 Fix potential out-of-bounds access in pbr_functions.wgsl
  crates/bevy_pbr/src/render/light.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#12877 Add gpu readback example
  Cargo.toml
  assets/shaders/gpu_readback.wgsl
  examples/README.md
  examples/shader/gpu_readback.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#12882 Add example for using .meta files
  Cargo.toml
  examples/README.md
  examples/asset/asset_settings.rs
  examples/asset/files/bevy_pixel_dark.png
  examples/asset/files/bevy_pixel_dark_with_meta.png
  examples/asset/files/bevy_pixel_dark_with_meta.png.meta
  examples/asset/files/bevy_pixel_dark_with_settings.png
Labels: C-Examples, A-Assets, S-Ready-For-Final-Review

#12893 Document the lifetime requirement of `byte_offset` and `byte_add`
  crates/bevy_ecs/src/storage/blob_vec.rs
  crates/bevy_ptr/src/lib.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, C-Unsoundness, A-Pointers

#12894 Fixed a bug where skybox ddsfile would crash from wgpu
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/texture/dds.rs
Labels: A-Rendering, A-Assets, S-Ready-For-Final-Review

#12897 Fix example game of life
  assets/shaders/game_of_life.wgsl
  examples/shader/compute_shader_game_of_life.rs
Labels: C-Bug, A-Rendering, C-Examples, S-Ready-For-Final-Review

#12906 Fix strings not interpolating in weely ci run
  .github/workflows/weekly.yml
Labels: C-Bug, A-Build-System, S-Ready-For-Final-Review

#12858 Clean up some low level dependencies
  crates/bevy_animation/Cargo.toml
  crates/bevy_animation/src/lib.rs
  crates/bevy_app/Cargo.toml
  crates/bevy_color/Cargo.toml
  crates/bevy_color/src/linear_rgba.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_macro_utils/Cargo.toml
  crates/bevy_macro_utils/src/label.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_scene/Cargo.toml
  crates/bevy_tasks/Cargo.toml
Labels: C-Dependencies, S-Ready-For-Final-Review, C-Breaking-Change, A-Cross-Cutting

#12686 Meshing for `Triangle3d` primitive
  crates/bevy_render/src/mesh/primitives/dim2.rs
  crates/bevy_render/src/mesh/primitives/dim3/mod.rs
  crates/bevy_render/src/mesh/primitives/dim3/triangle3d.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math, C-Breaking-Change, C-Needs-Release-Note

#12863 Created loading screen example
  Cargo.toml
  examples/README.md
  examples/games/loading_screen.rs
Labels: A-Rendering, C-Examples, A-Assets, S-Ready-For-Final-Review

#12827 Consolidate Render(Ui)Materials(2d) into RenderAssets
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/node.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_pbr/src/extended_material.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light_probe/environment_map.rs
  crates/bevy_pbr/src/light_probe/irradiance_volume.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/lightmap/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/meshlet/material_draw_prepare.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/mesh/mod.rs
  crates/bevy_render/src/render_asset.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/texture/image.rs
  crates/bevy_render/src/texture/mod.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_sprite/src/dynamic_texture_atlas_builder.rs
  crates/bevy_sprite/src/mesh2d/color_material.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  examples/2d/mesh2d_manual.rs
  examples/shader/compute_shader_game_of_life.rs
  examples/shader/shader_instancing.rs
  examples/shader/texture_binding_array.rs
Labels: C-Enhancement, A-Rendering, A-Assets, S-Ready-For-Final-Review, C-Breaking-Change

#12913 Fix beta CI
  crates/bevy_tasks/src/task_pool.rs
  crates/bevy_winit/src/winit_config.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review, A-Tasks

#12915 Use `impl Into<Color>` for `gizmos.primitive_3d(...)`
  crates/bevy_gizmos/src/primitives/dim3.rs
Labels: C-Usability, A-Gizmos

#12773 Generate `MeshUniform`s on the GPU via compute shader where available.
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/lightmap/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_preprocess.wgsl
  crates/bevy_pbr/src/render/mod.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/batching/no_gpu_preprocessing.rs
  crates/bevy_render/src/maths.wgsl
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_render/src/render_resource/buffer_vec.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  examples/shader/shader_instancing.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, C-Breaking-Change

#12841 Small CI tool improvements
  tools/ci/src/main.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#12914 Add tetrahedron gizmos
  crates/bevy_gizmos/src/primitives/dim3.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Gizmos

#12910 Implement percentage-closer filtering (PCF) for point lights.
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/light/point_light.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/meshlet/material_draw_prepare.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/shadow_sampling.wgsl
  crates/bevy_pbr/src/render/shadows.wgsl
  crates/bevy_render/src/maths.wgsl
  examples/3d/3d_shapes.rs
  examples/3d/shadow_biases.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, C-Needs-Release-Note

#12918 Enable `clippy::ref_as_ptr`
  Cargo.toml
  crates/bevy_mikktspace/src/generated.rs
  crates/bevy_render/src/mesh/mod.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#12582 Divide the single `VisibleEntities` list into separate lists for 2D meshes, 3D meshes, lights, and UI elements, for performance.
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/lib.rs
  examples/2d/mesh2d_manual.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, C-Breaking-Change

#12923 tools: Refactor CI to use `argh`
  tools/ci/Cargo.toml
  tools/ci/src/commands/ci.rs
  tools/ci/src/commands/mod.rs
  tools/ci/src/commands/prepare.rs
  tools/ci/src/commands/subcommands/bench_check_command.rs
  tools/ci/src/commands/subcommands/cfg_check_command.rs
  tools/ci/src/commands/subcommands/clippy_command.rs
  tools/ci/src/commands/subcommands/compile_check_command.rs
  tools/ci/src/commands/subcommands/compile_command.rs
  tools/ci/src/commands/subcommands/compile_fail_command.rs
  tools/ci/src/commands/subcommands/doc_check_command.rs
  tools/ci/src/commands/subcommands/doc_command.rs
  tools/ci/src/commands/subcommands/doc_test_command.rs
  tools/ci/src/commands/subcommands/example_check_command.rs
  tools/ci/src/commands/subcommands/format_command.rs
  tools/ci/src/commands/subcommands/lints_command.rs
  tools/ci/src/commands/subcommands/mod.rs
  tools/ci/src/commands/subcommands/test_check_command.rs
  tools/ci/src/commands/subcommands/test_command.rs
  tools/ci/src/main.rs
Labels: C-Enhancement, A-Build-System, C-Examples, S-Ready-For-Final-Review

#12927 Fix some nightly Clippy lints
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/schedule/stepping.rs
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/utility.rs
  crates/bevy_render/src/extract_component.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Cross-Cutting

#12943 fix bevy_hierarchy crate optional feature `bevy_app`
  crates/bevy_hierarchy/src/lib.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Hierarchy

#12947 Add archetypal to Access Debug impl
  crates/bevy_ecs/src/query/access.rs
Labels: A-ECS, C-Usability

#12936 Optimize Event Updates
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/sub_app.rs
  crates/bevy_ecs/examples/events.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_time/src/virt.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review, C-Breaking-Change, C-Needs-Release-Note

#12945 Fix rendering of sprites, text, and meshlets after #12582.
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/text2d.rs
Labels: C-Bug, A-Rendering, P-High, S-Ready-For-Final-Review, C-Breaking-Change

#12950 Remove the system task span
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
Labels: A-ECS, C-Performance, A-Diagnostics

#12957 Don't examine every entity when extracting `SpriteSource`s.
  crates/bevy_sprite/src/lib.rs
Labels: C-Bug, A-Rendering, C-Performance, S-Ready-For-Final-Review

#12931 fix find_current_keyframe panic
  crates/bevy_animation/src/lib.rs
Labels: C-Crash, S-Ready-For-Final-Review, A-Animation

#12850 Create custom action for installing Linux dependencies
  .github/actions/install-linux-deps/action.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/validation-jobs.yml
  .github/workflows/weekly.yml
Labels: A-Build-System, C-Usability, S-Ready-For-Final-Review

#12948 Fix crates not building individually
  crates/bevy_color/Cargo.toml
  crates/bevy_dev_tools/Cargo.toml
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gltf/src/loader.rs
Labels: S-Ready-For-Final-Review, C-Compile-Failure, A-Gizmos, A-Dev-Tools, A-Cross-Cutting

#12629 Fixed crash when transcoding one- or two-channel KTX2 textures
  crates/bevy_render/src/texture/ktx2.rs
Labels: C-Bug, A-Rendering

#12961 Fix some doc warnings
  Cargo.toml
  examples/2d/mesh2d.rs
  examples/2d/mesh2d_vertex_color_texture.rs
  examples/app/log_layers_ecs.rs
  examples/asset/asset_decompression.rs
  examples/asset/custom_asset.rs
  examples/asset/processing/asset_processing.rs
  examples/ecs/custom_query_param.rs
Labels: C-Docs, A-Cross-Cutting

#12964 fail when an example doesn't set doc-scrape-examples
  tools/build-templated-pages/src/examples.rs
Labels: A-Build-System, C-Examples

#12922 Fix 2D BatchedInstanceBuffer clear
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/batching/no_gpu_preprocessing.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
Labels: A-Rendering, C-Performance

#12919 Update docs of `set_if_neq` and `replace_if_neq`
  crates/bevy_ecs/src/change_detection.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review

#12977 fix shadow pass trace
  crates/bevy_internal/Cargo.toml
  crates/bevy_pbr/src/render/light.rs
Labels: C-Bug, A-Rendering, A-Diagnostics

#12970 Implement alpha to coverage (A2C) support.
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/pbr_fragment.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_prepass_functions.wgsl
  crates/bevy_pbr/src/render/pbr_types.wgsl
  crates/bevy_render/src/alpha.rs
  examples/3d/transparency_3d.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#11890 Add double end arrow to gizmos
  crates/bevy_gizmos/src/arrows.rs
  examples/gizmos/2d_gizmos.rs
  examples/gizmos/3d_gizmos.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Gizmos

#12769 Normalization anchor for sprite slice in dimensions of this slice
  crates/bevy_sprite/src/texture_slice/computed_slices.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#12969 Cleanup the multithreaded executor
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_utils/src/syncunsafecell.rs
Labels: A-ECS, C-Code-Quality

#12980 Fix beta lints
  clippy.toml
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/meta.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/server/info.rs
  crates/bevy_core/src/task_pool_options.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_ecs/src/identifier/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/stepping.rs
  crates/bevy_ecs/src/storage/blob_vec.rs
  crates/bevy_input/src/keyboard.rs
  crates/bevy_internal/src/lib.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/meshlet/gpu_scene.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_reflect/src/map.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/render_graph/context.rs
  crates/bevy_render/src/render_graph/edge.rs
  crates/bevy_render/src/texture/image.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_text/src/font_loader.rs
  crates/bevy_text/src/text.rs
  crates/bevy_window/src/window.rs
  examples/asset/processing/asset_processing.rs
  examples/math/render_primitives.rs
Labels: C-Docs, C-Code-Quality, S-Ready-For-Final-Review, A-Cross-Cutting

#12971 impl `Reflect` for `EntityHashSet`
  crates/bevy_reflect/src/impls/std.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection, A-Utils

#12989 Add `Cascades` to the type registry, fixing lights in glTF.
  crates/bevy_pbr/src/lib.rs
Labels: S-Ready-For-Final-Review

#12938 Fix extensionless image loading panic
  crates/bevy_render/src/texture/image_loader.rs
Labels: A-Assets, C-Crash, S-Ready-For-Final-Review

#12986 Make `Transform::rotate_axis` and `Transform::rotate_local_axis` use `Dir3`
  crates/bevy_transform/src/components/transform.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Transform, A-Math, C-Breaking-Change

#12738 fix: incorrect sprite size for aabb when sprite has rect and no custom_size
  crates/bevy_sprite/src/lib.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#12993 Implement clone for most bundles.
  crates/bevy_audio/src/audio.rs
  crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
  crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_pbr/src/bundle.rs
  crates/bevy_pbr/src/light_probe/environment_map.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_render/src/primitives/mod.rs
  crates/bevy_scene/src/bundle.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Cross-Cutting

#12999 grammar fix
  examples/ui/grid.rs
Labels: C-Docs, A-UI

#13004 Fix a copy-paste typo doc
  crates/bevy_asset/src/io/mod.rs
Labels: C-Docs, A-Assets

#13005 Fix extensionless image loading panic
  crates/bevy_render/src/texture/image_loader.rs
Labels: A-Assets, C-Crash, S-Ready-For-Final-Review

#13008 Add missing Default impl to ExtendedMaterial.
  crates/bevy_pbr/src/extended_material.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#13002 Added deref trait for Mesh2dHandle
  crates/bevy_sprite/src/mesh2d/mesh.rs
Labels: A-Rendering, A-Assets, C-Usability, S-Ready-For-Final-Review

#13012 Document Camera coordinate space
  crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#12426 separating finite and infinite 3d planes
  crates/bevy_gizmos/src/primitives/dim3.rs
  crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_math/src/ray.rs
  crates/bevy_reflect/src/impls/math/primitives3d.rs
  crates/bevy_render/src/mesh/primitives/dim3/plane.rs
  examples/3d/3d_viewport_to_world.rs
  examples/3d/irradiance_volumes.rs
  examples/math/render_primitives.rs
  examples/stress_tests/many_cubes.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, A-Math

#13020 Math primitives cleanup
  crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
Labels: C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Testing, A-Math

#13000 fix: use try_insert instead of insert in bevy_ui to prevent panics when despawning ui nodes
  crates/bevy_ui/src/accessibility.rs
  crates/bevy_ui/src/texture_slice.rs
  crates/bevy_ui/src/update.rs
Labels: A-ECS, C-Crash, S-Ready-For-Final-Review

#13033 Fix uses of "it's" vs "its".
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_ecs/examples/resources.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/storage/blob_vec.rs
  crates/bevy_ecs/src/storage/resource.rs
  crates/bevy_ecs/src/storage/table.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_gizmos/src/arcs.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_math/src/cubic_splines.rs
  crates/bevy_ptr/README.md
  crates/bevy_reflect/src/path/access.rs
  crates/bevy_reflect/src/path/error.rs
  crates/bevy_reflect/src/type_info.rs
  crates/bevy_time/src/time.rs
  crates/bevy_ui/src/geometry.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_utils/src/parallel_queue.rs
  crates/bevy_window/src/event.rs
Labels: C-Docs, A-Cross-Cutting

#13037 Remove unused nightly toolchain environmental variable
  .github/workflows/daily.yml
  .github/workflows/weekly.yml
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#12954 Expose `desired_maximum_frame_latency` through window creation
  crates/bevy_render/src/view/window/mod.rs
  crates/bevy_window/src/window.rs
Labels: A-Rendering, C-Performance, C-Usability, S-Ready-For-Final-Review

#12998 Adding explanation for loading additonal audio formats to example
  examples/audio/audio.rs
Labels: C-Docs, A-Audio, S-Ready-For-Final-Review

#13030 Fix Clippy lints on WASM
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_asset/src/io/wasm.rs
  crates/bevy_ecs/README.md
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_tasks/src/single_threaded_task_pool.rs
  crates/bevy_transform/README.md
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Cross-Cutting

#13034 Use WireframeColor to override global color
  crates/bevy_pbr/src/wireframe.rs
  examples/3d/wireframe.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#13044 Make SystemParam::new_archetype and QueryState::new_archetype unsafe functions
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_gizmos/src/gizmos.rs
Labels: A-ECS, C-Breaking-Change, C-Unsoundness

#13049 Fix doc when state is missing
  crates/bevy_ecs/src/schedule/condition.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#13015 use a u64 for MeshPipelineKey
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Bug, A-Rendering

#13047 ButtonInput docs - performance cost adjustment
  crates/bevy_input/src/button_input.rs
Labels: C-Docs, A-Input, S-Ready-For-Final-Review

#13059 Switch monolithic lib to module re-exports
  crates/bevy_internal/src/lib.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Cross-Cutting

#12816 Correctly handle UI hierarchy without a camera
  crates/bevy_ui/src/layout/mod.rs
Labels: C-Bug, C-Crash, A-UI, C-Usability, S-Ready-For-Final-Review

#12983 Remove unecessary lint `#[allow(...)]`
  crates/bevy_winit/src/winit_config.rs
Labels: A-Windowing, C-Code-Quality, S-Ready-For-Final-Review

#13022 Make `AppExit` more specific about exit reason.
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/lib.rs
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_dev_tools/src/ci_testing.rs
  crates/bevy_render/src/pipelined_rendering.rs
  crates/bevy_window/src/system.rs
  crates/bevy_winit/src/lib.rs
  examples/app/custom_loop.rs
  examples/ecs/ecs_guide.rs
  examples/games/desk_toy.rs
  examples/games/game_menu.rs
  examples/time/time.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-App, C-Breaking-Change, C-Needs-Release-Note

#13046 Added `ButtonInput` docs usage example
  crates/bevy_input/src/button_input.rs
Labels: C-Docs, A-Input, S-Ready-For-Final-Review

#12609 Improve output of example showcase patches CI workflow
  .github/workflows/validation-jobs.yml
Labels: C-Enhancement, A-Build-System, S-Ready-For-Final-Review

#13065 Additional doc aliases for `WindingOrder` in `bevy_math`
  crates/bevy_math/src/primitives/mod.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Math

#13062 Bump async-task
  crates/bevy_tasks/Cargo.toml
Labels: C-Dependencies, A-Tasks, C-Compile-Failure

#13060 Small CI improvements
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/validation-jobs.yml
Labels: A-Build-System, C-Code-Quality

#13056 Clarify comment about camera coordinate system
  examples/3d/generate_custom_mesh.rs
Labels: C-Docs, A-Rendering, C-Examples, S-Ready-For-Final-Review

#13067 Expose mutable Animation Clips
  crates/bevy_animation/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Animation

#13071 Remove async-task as a dependency
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/src/task.rs
  crates/bevy_tasks/src/task_pool.rs
Labels: C-Dependencies, S-Ready-For-Final-Review, A-Tasks

#13077 install rust target for arm ios simulator
  .github/workflows/validation-jobs.yml
Labels: A-Build-System, P-High, O-iOS, S-Ready-For-Final-Review

#13074 Simplify runner app exit code.
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_winit/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-App

#13076 Remove unused push constants
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  examples/2d/mesh2d_manual.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#12996 new example: sprite animation in response to an event
  Cargo.toml
  crates/bevy_sprite/src/bundle.rs
  crates/bevy_sprite/src/texture_atlas.rs
  examples/2d/sprite_animation.rs
  examples/README.md
Labels: C-Examples, S-Ready-For-Final-Review, A-Animation

#13081 Use `ptr::from_ref` and `ptr::addr_eq` in macro
  crates/bevy_ecs/src/label.rs
Labels: A-ECS, C-Code-Quality

#12672 Make dynamic_linking a no-op on wasm targets
  Cargo.toml
  src/lib.rs
Labels: A-Build-System, O-Web, C-Usability, S-Ready-For-Final-Review, C-Needs-Release-Note

#12984 Add `#[track_caller]` to `Query` methods
  crates/bevy_ecs/src/system/query.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#9924 Per-Object Motion Blur
  Cargo.toml
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_core_pipeline/src/motion_blur/mod.rs
  crates/bevy_core_pipeline/src/motion_blur/motion_blur.wgsl
  crates/bevy_core_pipeline/src/motion_blur/node.rs
  crates/bevy_core_pipeline/src/motion_blur/pipeline.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  examples/3d/motion_blur.rs
  examples/README.md
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, C-Needs-Release-Note

#11477 Fix custom pipeline in mesh2d_manual rendering other meshes
  examples/2d/mesh2d_manual.rs
Labels: C-Bug, A-Rendering, C-Examples

#13090 Better SystemId to Entity conversions
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/system_registry.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#13101 Restructure `ci` modules
  tools/ci/src/ci.rs
  tools/ci/src/commands/bench_check.rs
  tools/ci/src/commands/cfg_check.rs
  tools/ci/src/commands/clippy.rs
  tools/ci/src/commands/compile.rs
  tools/ci/src/commands/compile_check.rs
  tools/ci/src/commands/compile_fail.rs
  tools/ci/src/commands/doc.rs
  tools/ci/src/commands/doc_check.rs
  tools/ci/src/commands/doc_test.rs
  tools/ci/src/commands/example_check.rs
  tools/ci/src/commands/format.rs
  tools/ci/src/commands/lints.rs
  tools/ci/src/commands/mod.rs
  tools/ci/src/commands/subcommands/mod.rs
  tools/ci/src/commands/test.rs
  tools/ci/src/commands/test_check.rs
  tools/ci/src/main.rs
  tools/ci/src/prepare.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#13087 Use Vec3A for 3D bounding volumes and raycasts
  crates/bevy_math/src/bounding/bounded2d/mod.rs
  crates/bevy_math/src/bounding/bounded3d/mod.rs
  crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs
  crates/bevy_math/src/bounding/mod.rs
  crates/bevy_math/src/bounding/raycast3d.rs
  crates/bevy_math/src/direction.rs
Labels: C-Performance, S-Ready-For-Final-Review, A-Math, C-Breaking-Change

#13083 chore: fix some comments
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_ptr/README.md
  crates/bevy_ui/src/render/ui.wgsl
  examples/app/logs.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Cross-Cutting

#13102 iter_with_data
  crates/bevy_reflect/src/type_registry.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Reflection, A-Dev-Tools

#13100 Remove `version` field for non-publish crates and update descriptions
  benches/Cargo.toml
  crates/bevy_ecs_compile_fail_tests/Cargo.toml
  crates/bevy_macros_compile_fail_tests/Cargo.toml
  crates/bevy_reflect_compile_fail_tests/Cargo.toml
  errors/Cargo.toml
  examples/mobile/Cargo.toml
  tools/build-templated-pages/Cargo.toml
  tools/build-wasm-example/Cargo.toml
  tools/ci/Cargo.toml
  tools/example-showcase/Cargo.toml
Labels: S-Ready-For-Final-Review, A-Cross-Cutting

#13096 Added vmin and vmax to the gridtrack impls, repeatedgridtrack impls
  crates/bevy_ui/src/layout/convert.rs
  crates/bevy_ui/src/ui_node.rs
Labels: C-Enhancement, A-UI, S-Ready-For-Final-Review

#12622 Throttle render assets
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/render_asset.rs
  crates/bevy_render/src/texture/image.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#13026 Cleanup extract_meshes
  crates/bevy_pbr/src/render/mesh.rs
Labels: A-Rendering, C-Performance, C-Code-Quality, S-Ready-For-Final-Review

#12839 UI: pass the untransformed node size to the shader
  crates/bevy_ui/src/render/mod.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#11808 Fix `CameraProjection` panic and improve `CameraProjectionPlugin`
  crates/bevy_pbr/src/lib.rs
  crates/bevy_render/src/camera/projection.rs
  crates/bevy_render/src/view/visibility/mod.rs
Labels: C-Bug, C-Enhancement, A-Rendering, S-Ready-For-Final-Review, C-Breaking-Change

#13112 asset throttling: don't be exhausted if there is no limit
  crates/bevy_render/src/render_asset.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#4964 Add error when extract resource build fails
  crates/bevy_render/src/extract_resource.rs
Labels: A-Rendering, C-Usability, A-Diagnostics

#12898 Meshlet LOD-compatible two-pass occlusion culling
  crates/bevy_pbr/src/meshlet/cull_meshlets.wgsl
  crates/bevy_pbr/src/meshlet/gpu_scene.rs
  crates/bevy_pbr/src/meshlet/material_draw_prepare.rs
  crates/bevy_pbr/src/meshlet/meshlet_bindings.wgsl
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/meshlet/pipelines.rs
  crates/bevy_pbr/src/meshlet/visibility_buffer_raster.wgsl
  crates/bevy_pbr/src/meshlet/visibility_buffer_raster_node.rs
  crates/bevy_pbr/src/meshlet/visibility_buffer_resolve.wgsl
  crates/bevy_pbr/src/meshlet/write_index_buffer.wgsl
  crates/bevy_pbr/src/prepass/mod.rs
  examples/3d/meshlet.rs
Labels: C-Enhancement, A-Rendering

#13124 Restore dragons to their seat of power
  crates/bevy_pbr/src/meshlet/mod.rs
Labels: C-Bug, C-Docs, A-Rendering, S-Ready-For-Final-Review

#12889 Implement GPU frustum culling.
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/deferred/mod.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_preprocess.wgsl
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/batching/no_gpu_preprocessing.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/maths.wgsl
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_render/src/render_resource/buffer_vec.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/render_pass.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  examples/2d/mesh2d_manual.rs
  examples/3d/deferred_rendering.rs
  examples/shader/shader_instancing.rs
  examples/stress_tests/many_cubes.rs
Labels: C-Enhancement, A-Rendering, C-Needs-Release-Note

#12761 Update `App:is_plugin_added` to work inside `Plugin::finish` and `Plugin::clean`
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/sub_app.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-App

#13141 Fix typo in `bevy_render/src/batching/gpu_preprocessing.rs`
  crates/bevy_render/src/batching/gpu_preprocessing.rs
Labels: C-Bug, C-Docs, A-Rendering, S-Ready-For-Final-Review

#12499 Make `from_reflect_or_world` also try `ReflectDefault` and improve some comments and panic messages
  crates/bevy_ecs/src/reflect/bundle.rs
  crates/bevy_ecs/src/reflect/component.rs
  crates/bevy_ecs/src/reflect/mod.rs
  crates/bevy_ecs/src/reflect/resource.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Reflection

#12868 Deprecate `ReceivedCharacter`
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/winit_event.rs
  examples/input/char_input_events.rs
  examples/input/text_input.rs
Labels: A-Input, A-Windowing, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#13137 Small changes to `ci` tool
  tools/ci/src/ci.rs
  tools/ci/src/commands/bench_check.rs
  tools/ci/src/commands/cfg_check.rs
  tools/ci/src/commands/clippy.rs
  tools/ci/src/commands/compile.rs
  tools/ci/src/commands/compile_check.rs
  tools/ci/src/commands/compile_fail.rs
  tools/ci/src/commands/doc.rs
  tools/ci/src/commands/doc_check.rs
  tools/ci/src/commands/doc_test.rs
  tools/ci/src/commands/example_check.rs
  tools/ci/src/commands/format.rs
  tools/ci/src/commands/lints.rs
  tools/ci/src/commands/mod.rs
  tools/ci/src/commands/test.rs
  tools/ci/src/commands/test_check.rs
  tools/ci/src/main.rs
  tools/ci/src/prepare.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#13144 Don't ignore unbatchable sorted items.
  crates/bevy_render/src/batching/gpu_preprocessing.rs
Labels: C-Bug, A-Rendering

#10690 Upgrade to Taffy 0.4
  crates/bevy_ui/Cargo.toml
  crates/bevy_ui/src/layout/convert.rs
  crates/bevy_ui/src/layout/debug.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/layout/ui_surface.rs
  crates/bevy_ui/src/measurement.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_ui/src/widget/text.rs
  examples/ui/display_and_visibility.rs
Labels: C-Enhancement, C-Dependencies, A-UI, S-Ready-For-Final-Review, C-Needs-Release-Note
