Repository bevyengine/bevy, pull requests merged in 2024-02, with the labels that each got.

#11640 Add Clone to intersection test types
  crates/bevy_math/src/bounding/raytest2d.rs
  crates/bevy_math/src/bounding/raytest3d.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#11129 Rephrase comment about Local<T> for clarity. (Adopted)
  examples/ecs/ecs_guide.rs
Labels: A-ECS, C-Examples, S-Ready-For-Final-Review

#11641 Adding derive Reflect for tick structs
  crates/bevy_core/src/lib.rs
  crates/bevy_ecs/src/component.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Reflection

#11029 Add the ability to manually create ParsedPaths (+ cleanup)
  crates/bevy_reflect/src/path/access.rs
  crates/bevy_reflect/src/path/error.rs
  crates/bevy_reflect/src/path/mod.rs
  crates/bevy_reflect/src/path/parse.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#11650 Implement `approx` traits for direction types
  crates/bevy_math/Cargo.toml
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#11649 Support rotating `Direction3d` by `Quat`
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#10383 Fix embedded asset path manipulation
  Cargo.toml
  crates/bevy_asset/src/io/embedded/mod.rs
  examples/README.md
  examples/asset/bevy_pixel_light.png
  examples/asset/embedded_asset.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#11627 Gate diffuse and specular transmission behind shader defs
  assets/shaders/array_texture.wgsl
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/render/pbr_fragment.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#11635 Rename RayTest to RayCast
  crates/bevy_math/src/bounding/mod.rs
  crates/bevy_math/src/bounding/raycast2d.rs
  crates/bevy_math/src/bounding/raycast3d.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Math, C-Breaking-Change

#11604 return Direction3d from Transform::up and friends
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_transform/src/components/transform.rs
  examples/3d/tonemapping.rs
  examples/helpers/camera_controller.rs
  examples/transforms/transform.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Transform, A-Math

#11662 Subtract 1 from text positions to account for glyph texture padding.
  crates/bevy_text/src/glyph_brush.rs
Labels: C-Bug, A-Text

#11072 Drawing Primitives with Gizmos
  crates/bevy_gizmos/src/arcs.rs
  crates/bevy_gizmos/src/arrows.rs
  crates/bevy_gizmos/src/circles.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gizmos/src/primitives/dim2.rs
  crates/bevy_gizmos/src/primitives/dim3.rs
  crates/bevy_gizmos/src/primitives/helpers.rs
  crates/bevy_gizmos/src/primitives/mod.rs
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
  examples/2d/2d_gizmos.rs
  examples/3d/3d_gizmos.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Gizmos

#11528 Fix bug where events are not being dropped
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/event.rs
  crates/bevy_time/src/lib.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#4482 Animatable trait for interpolation and blending
  crates/bevy_animation/src/animatable.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_animation/src/util.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Animation

#11660 Allow prepare_windows to run off main thread.
  crates/bevy_render/src/view/window/mod.rs
Labels: A-Rendering, A-Windowing, C-Performance

#10774 Make Archetypes.archetype_component_count private
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Code-Quality

#8453 System Stepping implemented as Resource
  Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/main_schedule.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/stepping.rs
  crates/bevy_internal/Cargo.toml
  docs/cargo_features.md
  examples/README.md
  examples/ecs/system_stepping.rs
  examples/games/breakout.rs
  examples/games/stepping.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review, A-Editor, A-App, A-Diagnostics, S-Controversial

#11675 Add helpers for translate, rotate, and scale operations - Mesh
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#11666 Add example for bounding volumes and intersection tests
  Cargo.toml
  examples/2d/bounding_2d.rs
  examples/README.md
Labels: C-Examples, S-Ready-For-Final-Review, A-Math

#11639 Implement meshing for `Capsule2d`
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_render/src/mesh/primitives/dim2.rs
  examples/2d/2d_shapes.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, A-Math

#11672 Allow prepare_windows to run off main thread on all platforms
  crates/bevy_render/src/view/window/mod.rs
Labels: A-Rendering, A-Windowing, C-Performance, S-Ready-For-Final-Review

#11678 Update tracing-tracy requirement from 0.10.4 to 0.11.0 and tracy-client requirement from 0.16.4 to 0.17.0
  crates/bevy_log/Cargo.toml
  crates/bevy_log/src/lib.rs
Labels: C-Dependencies, S-Ready-For-Final-Review

#11684 Use TypeIdMap whenever possible
  crates/bevy_app/src/plugin_group.rs
  crates/bevy_asset/src/server/info.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/stepping.rs
  crates/bevy_gizmos/src/config.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_reflect/src/type_registry.rs
  crates/bevy_render/src/render_phase/draw.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_utils/src/lib.rs
Labels: C-Performance, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#9920 Deprecated Various Component Methods from `Query` and `QueryState`
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_lifetime_safety.rs
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_lifetime_safety.stderr
  crates/bevy_ui/src/focus.rs
  examples/ui/size_constraints.rs
Labels: A-ECS, C-Breaking-Change

#11139 CameraProjection::compute_frustum
  crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
  crates/bevy_render/src/camera/projection.rs
  crates/bevy_render/src/view/visibility/mod.rs
Labels: A-Rendering, C-Usability

#11686 bevy_reflect: Reflect `&'static str`
  crates/bevy_reflect/src/impls/std.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#11709 Fix a few typos in error docs
  errors/B0001.md
  errors/B0002.md
Labels: C-Docs, S-Ready-For-Final-Review

#11703 CONTRIBUTING.md: Mention splitting complex PRs
  CONTRIBUTING.md
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review

#11705 Added formats to `MeshVertexAttribute` constant's docstrings
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Docs, A-Rendering

#7650 Add `name` to `bevy::window::Window`
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/window/window_settings.rs
Labels: A-Windowing, O-Linux, S-Ready-For-Final-Review, C-Breaking-Change

#10812 Async pipeline compilation
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/node.rs
  crates/bevy_core_pipeline/src/fxaa/node.rs
  crates/bevy_core_pipeline/src/upscaling/mod.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_pbr/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_utils/src/futures.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, C-Breaking-Change

#11002 Send `SceneInstanceReady` only once per scene
  crates/bevy_scene/src/scene_spawner.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Scenes

#11068 Improve DynamicStruct::insert
  crates/bevy_reflect/src/struct_trait.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#11699 fix(primitives): fix polygon gizmo rendering bug
  crates/bevy_gizmos/src/primitives/dim2.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Gizmos

#11690 Hash stability guarantees
  crates/bevy_reflect/src/utility.rs
  crates/bevy_utils/src/lib.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Utils

#11693 Use `warn_once` where relevant instead of manually implementing a single warn check
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/extract_resource.rs
  crates/bevy_text/src/glyph_brush.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/widget/text.rs
Labels: A-Rendering, C-Code-Quality, A-Diagnostics

#11720 don't run `create_surfaces` system if not needed
  crates/bevy_render/src/view/window/mod.rs
Labels: A-Rendering, A-Windowing, C-Performance, S-Ready-For-Final-Review

#11671 sort by pipeline then mesh for non transparent passes for massively better batching
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/deferred/mod.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#11725 bevy_render: use the non-send marker from bevy_core
  crates/bevy_render/src/view/window/mod.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#11733 Added remove_indices to Mesh
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: A-Rendering, C-Usability

#11726 Don't unconditionally enable bevy_render or bevy_assets if mutli-threaded feature is enabled
  crates/bevy_internal/Cargo.toml
Labels: C-Bug, A-Core, S-Ready-For-Final-Review

#11728 `System::type_id` Consistency
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/stepping.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#11722 Include UI node size in the vertex inputs for UiMaterial.
  crates/bevy_ui/src/render/ui_material.wgsl
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_vertex_output.wgsl
Labels: C-Enhancement, A-Rendering, A-UI, S-Ready-For-Final-Review

#11721 Deprecating hashbrown reexports
  crates/bevy_utils/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Utils

#11688 Implement `Meshable` for some 3D primitives
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_render/src/mesh/primitives/dim3/capsule.rs
  crates/bevy_render/src/mesh/primitives/dim3/cuboid.rs
  crates/bevy_render/src/mesh/primitives/dim3/cylinder.rs
  crates/bevy_render/src/mesh/primitives/dim3/mod.rs
  crates/bevy_render/src/mesh/primitives/dim3/plane.rs
  crates/bevy_render/src/mesh/primitives/dim3/sphere.rs
  crates/bevy_render/src/mesh/primitives/dim3/torus.rs
  crates/bevy_render/src/mesh/primitives/mod.rs
  examples/3d/3d_shapes.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, A-Math

#10268 Implement irradiance volumes.
  Cargo.toml
  assets/irradiance_volumes/Example.vxgi.ktx2
  assets/models/IrradianceVolumeExample/IrradianceVolumeExample.glb
  assets/shaders/irradiance_volume_voxel_visualization.wgsl
  crates/bevy_core_pipeline/src/tonemapping/tonemapping_shared.wgsl
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/light_probe/environment_map.rs
  crates/bevy_pbr/src/light_probe/environment_map.wgsl
  crates/bevy_pbr/src/light_probe/irradiance_volume.rs
  crates/bevy_pbr/src/light_probe/irradiance_volume.wgsl
  crates/bevy_pbr/src/light_probe/light_probe.wgsl
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.wgsl
  crates/bevy_pbr/src/render/mesh_view_types.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  examples/3d/irradiance_volumes.rs
  examples/README.md
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#11747 fix create_surfaces system ordering
  crates/bevy_render/src/view/window/mod.rs
Labels: C-Bug, A-Rendering, A-Windowing, S-Ready-For-Final-Review

#11745 Mesh insert indices
  crates/bevy_gltf/src/loader.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/mesh/primitives/dim2.rs
  crates/bevy_render/src/mesh/primitives/dim3/capsule.rs
  crates/bevy_render/src/mesh/primitives/dim3/cuboid.rs
  crates/bevy_render/src/mesh/primitives/dim3/cylinder.rs
  crates/bevy_render/src/mesh/primitives/dim3/plane.rs
  crates/bevy_render/src/mesh/primitives/dim3/sphere.rs
  crates/bevy_render/src/mesh/primitives/dim3/torus.rs
  crates/bevy_render/src/mesh/shape/capsule.rs
  crates/bevy_render/src/mesh/shape/cylinder.rs
  crates/bevy_render/src/mesh/shape/icosphere.rs
  crates/bevy_render/src/mesh/shape/mod.rs
  crates/bevy_render/src/mesh/shape/regular_polygon.rs
  crates/bevy_render/src/mesh/shape/torus.rs
  crates/bevy_render/src/mesh/shape/uvsphere.rs
  examples/2d/mesh2d_manual.rs
  examples/3d/generate_custom_mesh.rs
  examples/animation/custom_skinned_mesh.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#11664 Add `ReflectKind`
  crates/bevy_asset/src/path.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/enums.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/tuple_structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/values.rs
  crates/bevy_reflect/src/array.rs
  crates/bevy_reflect/src/enums/dynamic_enum.rs
  crates/bevy_reflect/src/impls/smallvec.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/list.rs
  crates/bevy_reflect/src/map.rs
  crates/bevy_reflect/src/path/access.rs
  crates/bevy_reflect/src/path/error.rs
  crates/bevy_reflect/src/path/mod.rs
  crates/bevy_reflect/src/reflect.rs
  crates/bevy_reflect/src/struct_trait.rs
  crates/bevy_reflect/src/tuple.rs
  crates/bevy_reflect/src/tuple_struct.rs
  crates/bevy_render/src/render_asset.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Reflection

#11751 Don't try to create a uniform buffer for light probes if there are no views.
  crates/bevy_pbr/src/light_probe/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#11758 Properly check for result when getting pipeline in Msaa
  crates/bevy_core_pipeline/src/msaa_writeback.rs
Labels: C-Bug, A-Rendering

#11764 Typo in [`ScheduleLabel`] derive macro
  crates/bevy_ecs/macros/src/lib.rs
Labels: C-Bug, A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#11769 Mention Resource where missing from component/resource related type docs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/component.rs
Labels: C-Docs, A-ECS

#11737 wait for render app when main world is dropped
  crates/bevy_render/src/pipelined_rendering.rs
Labels: C-Bug, A-Rendering, C-Crash, C-Breaking-Change

#11781 Cache the QueryState used to drop swapchain TextureViews
  crates/bevy_render/src/renderer/mod.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#9172 Multithreaded render command encoding
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/deferred/node.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_render/src/render_graph/node.rs
  crates/bevy_render/src/renderer/graph_runner.rs
  crates/bevy_render/src/renderer/mod.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, C-Breaking-Change

#11780 Optional ImageScaleMode
  crates/bevy_sprite/src/bundle.rs
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_sprite/src/texture_slice/computed_slices.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/texture_slice.rs
  examples/2d/sprite_slice.rs
  examples/2d/sprite_tile.rs
  examples/ui/ui_texture_slice.rs
Labels: A-Rendering, C-Performance, A-UI, S-Ready-For-Final-Review, C-Breaking-Change

#11798 Fix `Quad` deprecation message mentioning a type that doesn't exist
  crates/bevy_render/src/mesh/shape/mod.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#11785 Update ahash to 0.8.7
  crates/bevy_utils/Cargo.toml
Labels: C-Dependencies, A-Utils

#11803 Stop extracting mesh entities to the render world.
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/render_phase/draw.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/render_pass.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  examples/shader/shader_instancing.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, C-Breaking-Change

#11810 doc(bevy_reflect): add note about trait bounds on `impl_type_path`
  crates/bevy_reflect/bevy_reflect_derive/src/lib.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Reflection

#11700 Expose query accesses
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/state.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#11805 Stop copying the light probe array to the stack in the shader.
  crates/bevy_pbr/src/light_probe/environment_map.wgsl
  crates/bevy_pbr/src/light_probe/irradiance_volume.wgsl
  crates/bevy_pbr/src/light_probe/light_probe.wgsl
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#11735 Avoid unwraps in winit fullscreen handling code
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Bug, A-Windowing, C-Crash, S-Ready-For-Final-Review

#11791 Derive Ord for GamepadButtonType.
  crates/bevy_input/src/gamepad.rs
Labels: A-Input, C-Usability

#11767 mipmap levels can be 0 and they should be interpreted as 1
  crates/bevy_core_pipeline/Cargo.toml
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_gltf/Cargo.toml
  crates/bevy_gltf/src/loader.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_render/src/texture/dds.rs
  crates/bevy_render/src/texture/image.rs
  crates/bevy_render/src/texture/image_loader.rs
Labels: C-Bug, A-Rendering, A-Assets, S-Ready-For-Final-Review

#11818 Replace pointer castings (`as`) by their API equivalent
  Cargo.toml
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_mikktspace/src/lib.rs
  crates/bevy_ptr/src/lib.rs
  crates/bevy_utils/src/synccell.rs
  crates/bevy_utils/src/syncunsafecell.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, A-Pointers

#11498 Move `EntityHash` related types into `bevy_ecs`
  benches/Cargo.toml
  benches/benches/bevy_ecs/world/entity_hash.rs
  benches/benches/bevy_ecs/world/mod.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/entity/hash.rs
  crates/bevy_ecs/src/entity/map_entities.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/reflect/map_entities.rs
  crates/bevy_ecs/src/reflect/mod.rs
  crates/bevy_gltf/src/loader.rs
  crates/bevy_pbr/src/bundle.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/lightmap/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/morph.rs
  crates/bevy_pbr/src/render/skin.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_render/src/extract_instances.rs
  crates/bevy_render/src/primitives/mod.rs
  crates/bevy_render/src/view/window/mod.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/scene.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_scene/src/serde.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_utils/src/lib.rs
  crates/bevy_winit/src/accessibility.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, A-Utils

#11622 bevy_dynamic_plugin: fix `unsafe_op_in_unsafe_fn` lint
  crates/bevy_dynamic_plugin/src/lib.rs
  crates/bevy_dynamic_plugin/src/loader.rs
Labels: S-Ready-For-Final-Review, D-Complex, C-Unsoundness

#11687 Add a method for detecting changes within a certain scope
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#11777 bevy_reflect_derive: Clean up attribute logic
  crates/bevy_reflect/bevy_reflect_derive/src/container_attributes.rs
  crates/bevy_reflect/bevy_reflect_derive/src/derive_data.rs
  crates/bevy_reflect/bevy_reflect_derive/src/field_attributes.rs
  crates/bevy_reflect/bevy_reflect_derive/src/from_reflect.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/enums.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/tuple_structs.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/typed.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/values.rs
  crates/bevy_reflect/bevy_reflect_derive/src/lib.rs
  crates/bevy_reflect/bevy_reflect_derive/src/reflect_value.rs
  crates/bevy_reflect/bevy_reflect_derive/src/registration.rs
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
  crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/custom_where.fail.rs
  crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/custom_where.fail.stderr
  crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/custom_where.pass.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Reflection

#11800 Put asset_events behind a run condition
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/lib.rs
Labels: A-Assets, C-Performance, S-Ready-For-Final-Review

#11822 Fix double indirection when applying command queues
  crates/bevy_ecs/src/system/commands/command_queue.rs
Labels: A-ECS, C-Performance, C-Code-Quality, S-Ready-For-Final-Review

#11644 Use Asset Path Extension for `AssetLoader` Disambiguation
  crates/bevy_asset/src/loader.rs
  crates/bevy_asset/src/server/loaders.rs
  crates/bevy_asset/src/server/mod.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#11710 Add delta to CursorMoved event
  crates/bevy_window/src/event.rs
  crates/bevy_winit/src/lib.rs
Labels: A-Input, C-Usability

#11792 Fix global wireframe behavior not being applied on new meshes
  crates/bevy_pbr/src/wireframe.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Gizmos

#11456 Add `Mesh::merge`
  crates/bevy_render/src/mesh/mesh/mod.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#11783 Call a TextureAtlasLayout a layout and not an atlas
  crates/bevy_sprite/src/texture_atlas.rs
  examples/2d/sprite_sheet.rs
  examples/2d/texture_atlas.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#11855 Fix small docs misformat in `BundleInfo::new`
  crates/bevy_ecs/src/bundle.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#11856 Use `std::thread::sleep` instead of spin-waiting in the async_compute example
  examples/async_tasks/async_compute.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Tasks

#11838 `FilteredEntityRef` conversions
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#11860 Overwrite gizmo group in `insert_gizmo_group`
  crates/bevy_gizmos/src/lib.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Gizmos

#11697 Dedicated primitive example
  Cargo.toml
  examples/2d/2d_gizmos.rs
  examples/3d/3d_gizmos.rs
  examples/README.md
  examples/math/render_primitives.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Math

#11865 Use question mark operator when possible
  crates/bevy_animation/src/lib.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ui/src/focus.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#11581 Change light defaults & fix light examples
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_render/src/camera/camera.rs
  examples/3d/3d_gizmos.rs
  examples/3d/3d_scene.rs
  examples/3d/3d_shapes.rs
  examples/3d/3d_viewport_to_world.rs
  examples/3d/animated_material.rs
  examples/3d/anti_aliasing.rs
  examples/3d/atmospheric_fog.rs
  examples/3d/blend_modes.rs
  examples/3d/deferred_rendering.rs
  examples/3d/fog.rs
  examples/3d/generate_custom_mesh.rs
  examples/3d/lighting.rs
  examples/3d/lightmaps.rs
  examples/3d/load_gltf.rs
  examples/3d/orthographic.rs
  examples/3d/parallax_mapping.rs
  examples/3d/parenting.rs
  examples/3d/pbr.rs
  examples/3d/reflection_probes.rs
  examples/3d/render_to_texture.rs
  examples/3d/shadow_biases.rs
  examples/3d/shadow_caster_receiver.rs
  examples/3d/spherical_area_lights.rs
  examples/3d/split_screen.rs
  examples/3d/spotlight.rs
  examples/3d/ssao.rs
  examples/3d/tonemapping.rs
  examples/3d/transmission.rs
  examples/3d/transparency_3d.rs
  examples/3d/two_passes.rs
  examples/3d/update_gltf_scene.rs
  examples/3d/vertex_colors.rs
  examples/3d/wireframe.rs
  examples/animation/animated_fox.rs
  examples/animation/cubic_curve.rs
  examples/animation/morph_targets.rs
  examples/asset/asset_loading.rs
  examples/asset/hot_asset_reloading.rs
  examples/audio/spatial_audio_3d.rs
  examples/ecs/iter_combinations.rs
  examples/shader/array_texture.rs
  examples/shader/extended_material.rs
  examples/shader/post_processing.rs
  examples/shader/shader_material_screenspace_texture.rs
  examples/shader/shader_prepass.rs
  examples/stress_tests/many_cubes.rs
  examples/stress_tests/many_foxes.rs
  examples/stress_tests/many_lights.rs
  examples/tools/scene_viewer/main.rs
  examples/transforms/3d_rotation.rs
  examples/transforms/scale.rs
  examples/transforms/transform.rs
  examples/transforms/translation.rs
  examples/ui/render_ui_to_texture.rs
  examples/window/low_power.rs
  examples/window/multiple_windows.rs
  examples/window/screenshot.rs
Labels: A-Rendering, C-Examples, C-Usability, C-Breaking-Change

#11867 Un-hardcode positions and colors in `2d_shapes` example
  examples/2d/2d_shapes.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review, A-Math

#11868 New Exposure and Lighting Defaults (and calibrate examples)
  crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_pbr/src/light.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/view/mod.rs
  examples/3d/3d_gizmos.rs
  examples/3d/3d_scene.rs
  examples/3d/3d_shapes.rs
  examples/3d/3d_viewport_to_world.rs
  examples/3d/animated_material.rs
  examples/3d/anti_aliasing.rs
  examples/3d/atmospheric_fog.rs
  examples/3d/blend_modes.rs
  examples/3d/deferred_rendering.rs
  examples/3d/fog.rs
  examples/3d/generate_custom_mesh.rs
  examples/3d/lighting.rs
  examples/3d/lightmaps.rs
  examples/3d/load_gltf.rs
  examples/3d/orthographic.rs
  examples/3d/parallax_mapping.rs
  examples/3d/parenting.rs
  examples/3d/pbr.rs
  examples/3d/reflection_probes.rs
  examples/3d/render_to_texture.rs
  examples/3d/shadow_biases.rs
  examples/3d/spherical_area_lights.rs
  examples/3d/spotlight.rs
  examples/3d/ssao.rs
  examples/3d/tonemapping.rs
  examples/3d/transmission.rs
  examples/3d/transparency_3d.rs
  examples/3d/two_passes.rs
  examples/3d/update_gltf_scene.rs
  examples/3d/vertex_colors.rs
  examples/3d/wireframe.rs
  examples/animation/animated_fox.rs
  examples/animation/cubic_curve.rs
  examples/animation/custom_skinned_mesh.rs
  examples/animation/morph_targets.rs
  examples/asset/asset_loading.rs
  examples/audio/spatial_audio_3d.rs
  examples/ecs/iter_combinations.rs
  examples/games/alien_cake_addict.rs
  examples/shader/array_texture.rs
  examples/shader/post_processing.rs
  examples/shader/shader_material_screenspace_texture.rs
  examples/shader/shader_prepass.rs
  examples/stress_tests/many_lights.rs
  examples/window/screenshot.rs
  tests/window/minimising.rs
  tests/window/resizing.rs
Labels: A-Rendering

#11880 Change MeshUniform::new() to be public.
  crates/bevy_pbr/src/render/mesh.rs
Labels: A-Rendering, C-Usability

#11882 Rename Core Render Graph Labels
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/fxaa/mod.rs
  crates/bevy_core_pipeline/src/msaa_writeback.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_render/src/render_graph/graph.rs
  crates/bevy_ui/src/render/mod.rs
  examples/shader/post_processing.rs
Labels: C-Bug, A-Rendering, C-Usability, S-Ready-For-Final-Review

#11878 Implement and register Reflect (value) for CameraRenderGraph and CameraMainTextureUsages
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/mod.rs
Labels: C-Bug, A-Reflection, A-Scenes

#11889 Add type registrations for animation types
  crates/bevy_animation/src/lib.rs
  crates/bevy_core/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Animation, A-Reflection

#11884 Support optional clear color in ColorAttachment.
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_render/src/texture/texture_attachment.rs
  crates/bevy_render/src/view/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#11847 Add configuration for async pipeline creation on RenderPlugin
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  examples/3d/wireframe.rs
  examples/app/no_renderer.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#11893 irradiance: use textureSampleLevel for WebGPU support
  crates/bevy_pbr/src/light_probe/irradiance_volume.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#11870 Fix asset loader registration warning
  crates/bevy_asset/src/server/loaders.rs
Labels: A-Assets, S-Ready-For-Final-Review, A-Diagnostics

#11894 WebGPU: fix web-sys version
  crates/bevy_render/Cargo.toml
Labels: C-Dependencies, S-Ready-For-Final-Review, O-WebGPU

#11907 Derive Reflect for Exposure
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#11911 Irradiance volume example tweaks
  examples/3d/irradiance_volumes.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#11909 Disable irradiance volumes on WebGL and WebGPU.
  crates/bevy_pbr/src/light_probe/irradiance_volume.rs
  crates/bevy_pbr/src/light_probe/irradiance_volume.wgsl
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.wgsl
Labels: A-Rendering

#11914 Remove `naga_oil` dependency from `bevy_pbr`
  crates/bevy_internal/Cargo.toml
  crates/bevy_pbr/Cargo.toml
  crates/bevy_render/Cargo.toml
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#11928 Add bevy_gizmos/macros to publish script
  tools/publish.sh
Labels: C-Bug, A-Build-System, A-Meta

#11935 revert PointLightBundle to DirectionalLightBundle change made to asset_loading example between 0.12.1 and 0.13.0
  examples/asset/asset_loading.rs
Labels: A-Rendering, C-Examples, A-Assets, S-Ready-For-Final-Review

#11934 Add single-f32 constructors for a few (very few) primitives
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_render/src/mesh/primitives/dim3/plane.rs
Labels: C-Usability, A-Math

#11938 scene example: remove unnecessary reflect(FromWorld)
  examples/scene/scene.rs
Labels: C-Examples, A-Scenes

#11955 typo
  crates/bevy_window/src/window.rs
Labels: C-Docs, A-Windowing, S-Ready-For-Final-Review

#11961 Qualify embedded_asset expansion with $crate::
  crates/bevy_asset/src/io/embedded/mod.rs
Labels: A-Assets, C-Usability

#11952 Update documentation for WorldQuery and filters
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/world_query.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#11962 Fix dds feature dependencies in bevy_core_pipeline
  crates/bevy_core_pipeline/Cargo.toml
Labels: C-Bug, A-Rendering, C-Compile-Failure

#11966 Add the serde feature to bitflags for bevy_render.
  crates/bevy_render/Cargo.toml
Labels: A-Rendering, C-Compile-Failure

#11936 text2d example: animate_scale no longer unnecessarily performs the same translation at each Update
  examples/2d/text2d.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Text

#11973 Update to toml_edit 0.22
  crates/bevy_macro_utils/Cargo.toml
  tools/build-templated-pages/Cargo.toml
  tools/build-templated-pages/src/features.rs
  tools/example-showcase/Cargo.toml
Labels: C-Dependencies

#11939 rename Camera3dBundle's 'dither' field to 'deband_dither' to align with Camera2dBundle
  crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
Labels: A-Rendering, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#7348 refactor: Extract parallel queue abstraction
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/system/commands/parallel_scope.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_utils/Cargo.toml
  crates/bevy_utils/src/lib.rs
  crates/bevy_utils/src/parallel_queue.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, D-Complex, A-Utils

#10506 Implement Debug for SpriteBundle and SpriteSheetBundle
  crates/bevy_sprite/src/bundle.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#7743 also look in just_pressed touches for position
  crates/bevy_input/src/touch.rs
Labels: A-Input, O-Android, O-iOS, S-Ready-For-Final-Review

#11840 Add method for querying whether a given short type path is ambiguous
  crates/bevy_reflect/src/type_registry.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Reflection

#11854 Gltf loader now shows which file is missing pre baked tangents
  crates/bevy_gltf/src/loader.rs
Labels: A-Rendering, A-Assets, C-Usability, S-Ready-For-Final-Review

#11872 Prevent panic when multiple Enter inputs received in `text_input` example
  examples/input/text_input.rs
Labels: C-Examples, A-Input, C-Crash, S-Ready-For-Final-Review

#11921 Use the scroll wheel to control the camera speed in examples
  examples/helpers/camera_controller.rs
  examples/tools/scene_viewer/main.rs
Labels: C-Examples, C-Usability, S-Ready-For-Final-Review

#11959 Stepping disabled performance fix
  benches/benches/bevy_ecs/scheduling/mod.rs
  benches/benches/bevy_ecs/scheduling/schedule.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: A-ECS, C-Performance, C-Usability, S-Ready-For-Final-Review, C-Regression

#11900 Add a `[lints]` entry for workspace members missing it
  crates/bevy_gizmos/macros/Cargo.toml
  crates/bevy_gizmos/macros/src/lib.rs
  errors/Cargo.toml
  errors/src/lib.rs
  tools/build-templated-pages/Cargo.toml
  tools/build-templated-pages/src/main.rs
  tools/build-wasm-example/Cargo.toml
  tools/build-wasm-example/src/main.rs
  tools/ci/Cargo.toml
  tools/ci/src/main.rs
  tools/example-showcase/Cargo.toml
  tools/example-showcase/src/main.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#11875 Simplify and improve `overflow_debug` example
  examples/ui/overflow_debug.rs
Labels: C-Examples, A-UI, C-Code-Quality

#11983 Replace references to old book with quick start guide
  README.md
  src/lib.rs
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review

#11804 Allow Mesh-related queue phase systems to parallelize
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/render_resource/resource_macros.rs
Labels: A-Rendering, C-Performance

#12003 Fix example docs on embedded_asset macro
  crates/bevy_asset/src/io/embedded/mod.rs
Labels: C-Docs, A-Assets, S-Ready-For-Final-Review

#12010 Update `split_screen` example with 4 cameras
  examples/3d/split_screen.rs
Labels: A-Rendering, C-Examples, A-Windowing, S-Ready-For-Final-Review, C-Regression

#11968 Fix MSAA writeback when 3 or more cameras have the same target.
  crates/bevy_render/src/view/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, C-Regression

#12014 Fix docs for quaternion interpolation
  crates/bevy_animation/src/animatable.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Animation

#11904 Add support for KHR_texture_transform
  crates/bevy_gltf/Cargo.toml
  crates/bevy_gltf/src/loader.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/render/mesh_functions.wgsl
  crates/bevy_pbr/src/render/mesh_types.wgsl
  crates/bevy_pbr/src/render/pbr_fragment.wgsl
  crates/bevy_pbr/src/render/pbr_prepass_functions.wgsl
  crates/bevy_pbr/src/render/pbr_types.wgsl
  crates/bevy_render/src/maths.wgsl
  crates/bevy_sprite/src/mesh2d/mesh2d_functions.wgsl
  crates/bevy_sprite/src/mesh2d/mesh2d_types.wgsl
  crates/bevy_sprite/src/render/sprite.wgsl
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, C-Breaking-Change

#12012 Move AlphaMode into bevy_render
  crates/bevy_gltf/src/loader.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_render/src/alpha.rs
  crates/bevy_render/src/lib.rs
Labels: A-Rendering, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#12004 Update async-channel to 2.2.0
  crates/bevy_ecs/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_tasks/Cargo.toml
Labels: A-ECS, C-Dependencies, A-Tasks

#11916 Move gizmos examples in the separate folder
  Cargo.toml
  examples/README.md
  examples/gizmos/2d_gizmos.rs
  examples/gizmos/3d_gizmos.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review, A-Gizmos

#12028 Parse missing mime types
  crates/bevy_render/src/texture/image.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#12022 Create imported_assets directory with full path
  crates/bevy_asset/src/io/file/mod.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#12032 Make Globals visible in vertex shaders
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, C-Regression

#12030 Fix `SystemTypeSet::system_type` being out of sync with `System::type_id`
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#11861 bevy_ecs address trivial cases of `unsafe_op_in_unsafe_fn`
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/query/world_query.rs
  crates/bevy_ecs/src/reflect/component.rs
  crates/bevy_ecs/src/reflect/resource.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/storage/blob_vec.rs
  crates/bevy_ecs/src/storage/resource.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Code-Quality

#12029 Document all members of `bevy_dynamic_plugin`
  crates/bevy_dynamic_plugin/src/lib.rs
  crates/bevy_dynamic_plugin/src/loader.rs
Labels: C-Docs, A-Modding

#12037 Fix taplo CI - toml fmt
  .github/workflows/ci.yml
  crates/bevy_transform/Cargo.toml
Labels: C-Bug, A-Build-System, S-Ready-For-Final-Review

#12038 fix some typos
  crates/bevy_app/src/app.rs
  crates/bevy_asset/src/path.rs
  crates/bevy_asset/src/transformer.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_ecs/src/identifier/error.rs
  crates/bevy_ecs/src/identifier/masks.rs
  crates/bevy_ecs/src/query/builder.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/reflect/from_world.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_gizmos/src/primitives/dim3.rs
  crates/bevy_input/src/keyboard.rs
  crates/bevy_macro_utils/src/bevy_manifest.rs
  crates/bevy_mikktspace/src/generated.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/path/error.rs
  crates/bevy_reflect/src/path/mod.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_utils/src/parallel_queue.rs
  examples/app/logs.rs
  examples/app/return_after_run.rs
  examples/asset/asset_decompression.rs
  examples/asset/processing/asset_processing.rs
  examples/ecs/dynamic.rs
  examples/ecs/send_and_receive_events.rs
  examples/math/render_primitives.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#12047 Fixed Ui Image slicing
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_ui/src/texture_slice.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#12052 FIX: iOS Simulator not rendering due to missing CUBE_ARRAY_TEXTURES
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.wgsl
  crates/bevy_pbr/src/render/shadows.wgsl
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
Labels: A-Rendering, O-iOS

#12053 Make more things pub in the renderer
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/light.rs
Labels: A-Rendering, C-Code-Quality

#12051 set pipeline to queued when shader is not yet available
  crates/bevy_render/src/render_resource/pipeline_cache.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#12060 Improve file watcher error msg
  crates/bevy_asset/src/io/source.rs
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review

#12013 Upstreaming bevy_color.
  crates/bevy_color/Cargo.toml
  crates/bevy_color/crates/gen_tests/Cargo.toml
  crates/bevy_color/crates/gen_tests/README.md
  crates/bevy_color/crates/gen_tests/src/main.rs
  crates/bevy_color/src/color.rs
  crates/bevy_color/src/color_difference.rs
  crates/bevy_color/src/color_ops.rs
  crates/bevy_color/src/color_range.rs
  crates/bevy_color/src/hsla.rs
  crates/bevy_color/src/lcha.rs
  crates/bevy_color/src/lib.rs
  crates/bevy_color/src/linear_rgba.rs
  crates/bevy_color/src/oklaba.rs
  crates/bevy_color/src/srgba.rs
  crates/bevy_color/src/test_colors.rs
  crates/bevy_color/src/testing.rs
  tools/publish.sh
Labels: C-Enhancement, A-Rendering, A-UI, S-Ready-For-Final-Review, S-Controversial, C-Needs-Release-Note

#12041 Add a release step, add links to the github release note
  docs/release_checklist.md
Labels: A-Meta, S-Ready-For-Final-Review

#12046 Remove unnecessary wildcards from `LogPlugin` and convert warnings to errors.
  crates/bevy_log/src/lib.rs
Labels: C-Code-Quality, A-Diagnostics

#12074 fix typo: converstion -> conversion
  crates/bevy_color/src/lib.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#12067 bevy_color: adding 'palettes' module.
  crates/bevy_color/src/color_range.rs
  crates/bevy_color/src/lib.rs
  crates/bevy_color/src/palettes/basic.rs
  crates/bevy_color/src/palettes/css.rs
  crates/bevy_color/src/palettes/mod.rs
  crates/bevy_color/src/srgba.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review
