Repository bevyengine/bevy, pull requests merged in 2024-11, with the labels that each got.

#16187 simplify example, replace get_single to Single Query
  examples/2d/2d_viewport_to_world.rs
  examples/3d/camera_sub_view.rs
  examples/3d/pbr.rs
  examples/asset/alter_mesh.rs
  examples/asset/alter_sprite.rs
  examples/audio/audio_control.rs
  examples/camera/2d_top_down_camera.rs
  examples/camera/first_person_view_model.rs
  examples/helpers/camera_controller.rs
  examples/math/cubic_splines.rs
  examples/mobile/src/lib.rs
  examples/window/screenshot.rs
Labels: A-ECS, C-Examples, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#16093 Correctly feature gate `custom_cursor`
  crates/bevy_winit/src/converters.rs
  crates/bevy_winit/src/cursor.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/state.rs
  examples/window/window_settings.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review, D-Straightforward

#16213 Implement `Measured2d` for `Arc2d`-based primitives.
  crates/bevy_math/src/primitives/dim2.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#16218 Fix fallible param notes
  crates/bevy_ecs/src/system/query.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#16111 Meshlet normal-aware LOD and meshoptimizer upgrade
  Cargo.toml
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/meshlet/from_mesh.rs
  crates/bevy_pbr/src/meshlet/mod.rs
  examples/3d/meshlet.rs
Labels: A-Rendering, S-Ready-For-Final-Review, D-Straightforward

#16157 Fix blending for CameraOutputMode::Skip
  crates/bevy_core_pipeline/src/upscaling/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, D-Straightforward

#16188 move mesh uniform construction out of Core3d
  crates/bevy_pbr/src/render/gpu_preprocess.rs
Labels: A-Rendering, C-Performance, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#16202 Fix WGSL formatting inconsistency on mesh_view_binding
  crates/bevy_pbr/src/render/mesh_view_bindings.wgsl
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#16211 Improved the global transform api to access rotation and scale
  crates/bevy_transform/src/components/global_transform.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Transform, D-Straightforward

#16228 Remove unused debug identifiers for `ComponentHooks` methods
  crates/bevy_ecs/src/component.rs
Labels: D-Trivial, A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#16222 Gamepad improvements
  crates/bevy_input/src/axis.rs
  crates/bevy_input/src/gamepad.rs
  examples/input/gamepad_input.rs
  examples/input/gamepad_rumble.rs
  examples/tools/gamepad_viewer.rs
Labels: A-Input, C-Usability, S-Ready-For-Final-Review, P-Regression

#16234 Bump accesskit and accesskit_winit.
  crates/bevy_a11y/Cargo.toml
  crates/bevy_a11y/src/lib.rs
  crates/bevy_ui/src/accessibility.rs
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/accessibility.rs
  examples/ui/scroll.rs
  examples/ui/ui.rs
Labels: D-Trivial, C-Dependencies, A-Accessibility, S-Ready-For-Final-Review

#16220 Support creating asset directories
  crates/bevy_asset/src/io/file/file_asset.rs
  crates/bevy_asset/src/io/file/sync_file_asset.rs
  crates/bevy_asset/src/io/mod.rs
Labels: C-Feature, A-Assets, S-Ready-For-Final-Review, D-Straightforward

#16229 Expose picking pointer state as a resource
  crates/bevy_picking/src/events.rs
  crates/bevy_picking/src/lib.rs
Labels: S-Ready-For-Final-Review, P-Regression, D-Straightforward, A-Picking

#16197 Use `stack_z_offsets` in all the cases we create a `TransparentUi`
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
Labels: A-Rendering, S-Ready-For-Final-Review, D-Straightforward

#16233 Use `Name` component for gamepad
  crates/bevy_gilrs/src/gilrs_system.rs
  crates/bevy_input/Cargo.toml
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input/src/lib.rs
  examples/tools/gamepad_viewer.rs
Labels: A-Input, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Straightforward

#16236 Bump crate-ci/typos from 1.26.8 to 1.27.0
  .github/workflows/ci.yml
  crates/bevy_math/src/common_traits.rs
  crates/bevy_math/src/curve/adaptors.rs
  crates/bevy_math/src/curve/mod.rs
Labels: D-Trivial, A-Build-System, C-Dependencies, S-Needs-Review

#16198 BRP System Ordering
  crates/bevy_remote/src/lib.rs
Labels: A-Networking, D-Straightforward, S-Needs-Review

#15988 Upgrade to wgpu 23
  crates/bevy_color/Cargo.toml
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_image/Cargo.toml
  crates/bevy_image/src/dds.rs
  crates/bevy_image/src/ktx2.rs
  crates/bevy_mesh/Cargo.toml
  crates/bevy_reflect/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_winit/Cargo.toml
  examples/mobile/bevy_mobile_example.xcodeproj/project.pbxproj
Labels: A-Rendering, C-Dependencies, S-Ready-For-Final-Review

#16253 chore(deps): remove unused `uuid` dependency from `bevy_core`
  crates/bevy_core/Cargo.toml
Labels: D-Trivial, C-Dependencies, A-Core, S-Ready-For-Final-Review

#16255 properly flag using `CustomCursor::Url` in wasm
  crates/bevy_winit/src/cursor.rs
Labels: D-Trivial, A-Windowing, O-Web, S-Ready-For-Final-Review, P-Compile-Failure

#16262 Require `ContentSize` for `UiImage`
  crates/bevy_ui/src/widget/image.rs
Labels: C-Bug, D-Trivial, A-UI, S-Ready-For-Final-Review

#16263 Enable EntityRef tests that now pass.
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: D-Trivial, A-ECS, S-Ready-For-Final-Review, C-Testing

#16269 Make `ComponentTicks` field public
  crates/bevy_ecs/src/component.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, P-Regression, A-Networking

#16147 Make doc CI use nightly
  .github/workflows/ci.yml
  .github/workflows/weekly.yml
  tools/ci/src/commands/doc_check.rs
Labels: A-Build-System, C-Usability, S-Ready-For-Final-Review, X-Controversial, D-Straightforward

#16142 Make `BinnedRenderPhase` fields for accessing batchable and unbatchable entities public
  crates/bevy_render/src/render_phase/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#16279 Incorporate all node weights in additive blending
  crates/bevy_animation/src/animation_curves.rs
  crates/bevy_animation/src/graph.rs
  examples/animation/animation_masks.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Animation

#16281 Fix `alien_cake_addict` example
  examples/games/alien_cake_addict.rs
Labels: A-ECS, C-Examples, P-Regression, D-Straightforward, S-Needs-Review

#16241 Move UI example to testbed
  .github/workflows/validation-jobs.yml
  Cargo.toml
  examples/README.md
  examples/testbed/ui.rs
Labels: D-Trivial, C-Examples, A-UI, S-Ready-For-Final-Review, X-Contentious, S-Needs-Help

#16271 UiImage -> ImageNode, UiImageSize -> ImageNodeSize
  crates/bevy_ui/src/accessibility.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/render_pass.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
  crates/bevy_ui/src/widget/image.rs
  examples/3d/auto_exposure.rs
  examples/games/game_menu.rs
  examples/stress_tests/many_buttons.rs
  examples/testbed/ui.rs
  examples/ui/font_atlas_debug.rs
  examples/ui/overflow.rs
  examples/ui/overflow_clip_margin.rs
  examples/ui/overflow_debug.rs
  examples/ui/ui_scaling.rs
  examples/ui/ui_texture_atlas.rs
  examples/ui/ui_texture_atlas_slice.rs
  examples/ui/ui_texture_slice.rs
  examples/ui/ui_texture_slice_flip_and_tile.rs
Labels: D-Trivial, A-UI, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#16282 Allow or fix dead code in `benches`
  benches/benches/bevy_ecs/benches.rs
  benches/benches/bevy_ecs/components/add_remove.rs
  benches/benches/bevy_ecs/components/mod.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review, C-Benchmarks, D-Straightforward

#16265 Fix typos in `bevy_picking` module docs
  crates/bevy_picking/src/lib.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-Picking

#16287 AudioPlayer::new()
  crates/bevy_audio/src/audio.rs
  crates/bevy_audio/src/lib.rs
  examples/audio/audio.rs
  examples/audio/audio_control.rs
  examples/audio/spatial_audio_2d.rs
  examples/audio/spatial_audio_3d.rs
  examples/mobile/src/lib.rs
Labels: A-Audio, C-Usability

#16295 Fix issue template label
  .github/ISSUE_TEMPLATE/performance_regression.md
Labels: C-Bug, D-Trivial, A-Meta, S-Ready-For-Final-Review

#16298 Fixed issue with `derive_more` `Display` Implementations
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_gltf/src/vertex_attributes.rs
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, A-Diagnostics, X-Uncontroversial

#16301 Expose Pipeline Compilation Zero Initialize Workgroup Memory Option
  crates/bevy_core_pipeline/src/auto_exposure/pipeline.rs
  crates/bevy_core_pipeline/src/blit/mod.rs
  crates/bevy_core_pipeline/src/bloom/downsampling_pipeline.rs
  crates/bevy_core_pipeline/src/bloom/upsampling_pipeline.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_core_pipeline/src/deferred/copy_lighting_id.rs
  crates/bevy_core_pipeline/src/dof/mod.rs
  crates/bevy_core_pipeline/src/fxaa/mod.rs
  crates/bevy_core_pipeline/src/motion_blur/pipeline.rs
  crates/bevy_core_pipeline/src/oit/resolve/mod.rs
  crates/bevy_core_pipeline/src/post_process/mod.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_core_pipeline/src/skybox/prepass.rs
  crates/bevy_core_pipeline/src/smaa/mod.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/meshlet/material_pipeline_prepare.rs
  crates/bevy_pbr/src/meshlet/pipelines.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_pbr/src/ssr/mod.rs
  crates/bevy_pbr/src/volumetric_fog/render.rs
  crates/bevy_render/src/render_resource/pipeline.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/pipeline.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
  examples/2d/mesh2d_manual.rs
  examples/shader/compute_shader_game_of_life.rs
  examples/shader/custom_phase_item.rs
  examples/shader/custom_post_processing.rs
  examples/shader/gpu_readback.rs
  examples/shader/specialized_mesh_pipeline.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#16283 Return Error instead of panicking when reading invalid dds file
  crates/bevy_image/src/dds.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#16310 Fix permissions of rust source files
  crates/bevy_animation/src/lib.rs
  crates/bevy_hierarchy/src/lib.rs
Labels: D-Trivial, S-Ready-For-Final-Review, A-Cross-Cutting

#16293 Handle failed cursor grab mode changes so that the cursor grab mode change can be attempted again
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#16302 UI/text Example - Clarity Improvements
  examples/ui/text.rs
Labels: C-Examples, A-UI, S-Ready-For-Final-Review, D-Straightforward

#16321 Allow jobs to upgrade to macos-15 (using -latest)
  .github/workflows/ci.yml
Labels: D-Trivial, A-Build-System, C-Performance, S-Needs-Review

#16327 Rename `Rot2::angle_between` to `Rot2::angle_to`
  crates/bevy_math/src/rotation2d.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math, M-Needs-Migration-Guide, D-Straightforward

#16199 Disable lint that interferes with rust beta CI compatibility
  Cargo.toml
Labels: D-Trivial, A-Build-System, S-Needs-Review

#15482 bevy_reflect: Add `ReflectDeserializerProcessor`
  crates/bevy_reflect/src/serde/de/arrays.rs
  crates/bevy_reflect/src/serde/de/deserializer.rs
  crates/bevy_reflect/src/serde/de/enums.rs
  crates/bevy_reflect/src/serde/de/lists.rs
  crates/bevy_reflect/src/serde/de/maps.rs
  crates/bevy_reflect/src/serde/de/mod.rs
  crates/bevy_reflect/src/serde/de/options.rs
  crates/bevy_reflect/src/serde/de/processor.rs
  crates/bevy_reflect/src/serde/de/sets.rs
  crates/bevy_reflect/src/serde/de/struct_utils.rs
  crates/bevy_reflect/src/serde/de/structs.rs
  crates/bevy_reflect/src/serde/de/tuple_structs.rs
  crates/bevy_reflect/src/serde/de/tuple_utils.rs
  crates/bevy_reflect/src/serde/de/tuples.rs
Labels: C-Feature, S-Ready-For-Final-Review, A-Reflection, D-Modest

#16210 Add EntityMut::get_mut_by_id_unchecked
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Straightforward, D-Unsafe

#16261 Add more Glam types and constructors to prelude
  benches/benches/bevy_math/bezier.rs
  crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs
  crates/bevy_math/src/lib.rs
  examples/shader/custom_phase_item.rs
  examples/tools/scene_viewer/main.rs
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Math

#16300 Clean up some yaml mistakes
  .github/workflows/ci.yml
  .github/workflows/validation-jobs.yml
Labels: D-Trivial, A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#16336 Gitignore all target folders
  .gitignore
Labels: C-Bug, D-Trivial, A-Meta, S-Ready-For-Final-Review

#15156 Do not re-check visibility or re-render shadow maps for point and spot lights for each view
  Cargo.toml
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_render/src/texture/texture_attachment.rs
  examples/README.md
  examples/stress_tests/many_cameras_lights.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#16337 Fix missing import
  crates/bevy_core_pipeline/src/smaa/mod.rs
Labels: C-Bug, D-Trivial, A-Core, S-Ready-For-Final-Review, P-Compile-Failure

#13045 Support `on_thread_spawn` and `on_thread_destroy` for `TaskPoolPlugin`
  crates/bevy_core/src/task_pool_options.rs
  crates/bevy_tasks/src/single_threaded_task_pool.rs
Labels: C-Feature, S-Ready-For-Final-Review, A-Tasks, M-Needs-Migration-Guide, D-Modest

#16288 Fix panic in UiSurface if Node is removed and re-added
  crates/bevy_ui/src/layout/mod.rs
Labels: C-Bug, P-Crash, A-UI, S-Needs-Review

#16351 Remove the measure func for image nodes with the default UI texture
  crates/bevy_ui/src/widget/image.rs
Labels: C-Bug, A-UI, D-Straightforward, S-Needs-Review

#16358 Fix not being able to run bevy_ui tests
  crates/bevy_dev_tools/Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_ui/Cargo.toml
Labels: A-UI, C-Testing, A-Text, D-Straightforward, S-Needs-Review

#16356 don't check doc in beta ci as it requires nightly
  .github/workflows/weekly.yml
Labels: C-Bug, A-Build-System, S-Ready-For-Final-Review

#16357 undeprecate `component_reads_and_writes`
  crates/bevy_ecs/src/query/access.rs
Labels: D-Trivial, A-ECS, X-Controversial, S-Needs-SME

#16340 Add `unregister_system` command
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/system_registry.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#16374 Trivial `bevy_picking` refactor
  crates/bevy_picking/src/pointer.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Picking

#16367 Use normal constructors for EasingCurve, FunctionCurve, ConstantCurve
  crates/bevy_animation/src/animation_curves.rs
  crates/bevy_gizmos/src/curves.rs
  crates/bevy_gltf/src/loader.rs
  crates/bevy_math/src/curve/easing.rs
  crates/bevy_math/src/curve/mod.rs
  examples/animation/eased_motion.rs
  examples/animation/easing_functions.rs
  examples/gizmos/2d_gizmos.rs
  examples/gizmos/3d_gizmos.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#16347 Minor docs fixes
  crates/bevy_picking/src/backend.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-Picking

#16264 Text2d scalefactor change detection fix
  crates/bevy_text/src/text2d.rs
Labels: C-Bug, A-Text, S-Needs-Review

#16181 UI anti-aliasing fix
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/pipeline.rs
  crates/bevy_ui/src/render/render_pass.rs
  crates/bevy_ui/src/render/ui.wgsl
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
  examples/testbed/ui_layout_rounding.rs
Labels: C-Bug, A-Rendering, A-UI, D-Modest, S-Needs-Review

#16382 Make PCSS experimental
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/light/directional_light.rs
  crates/bevy_pbr/src/light/point_light.rs
  crates/bevy_pbr/src/light/spot_light.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  docs/cargo_features.md
Labels: A-Rendering, C-Usability, X-Uncontroversial, D-Straightforward, S-Needs-Review

#16390 `many_buttons` `--respawn` arg
  examples/stress_tests/many_buttons.rs
Labels: C-Examples, A-UI, S-Ready-For-Final-Review, C-Benchmarks, D-Straightforward

#16231 Picking out order
  crates/bevy_picking/src/events.rs
Labels: C-Bug, A-Input, A-UI, S-Ready-For-Final-Review, D-Complex, A-Picking

#16399 remove ViewUniformOffset from inactive cameras
  crates/bevy_render/src/camera/camera.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#16401 Headless by features
  Cargo.toml
  crates/bevy_dev_tools/src/ci_testing/mod.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_internal/src/lib.rs
  crates/bevy_internal/src/prelude.rs
  docs/cargo_features.md
  examples/app/headless.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-App

#16404 Fix meshlet private item regression
  crates/bevy_pbr/src/meshlet/mod.rs
Labels: A-Rendering, P-Regression

#16400 Expose BRP system scheduling and add system set
  crates/bevy_remote/src/lib.rs
Labels: C-Feature, C-Usability, A-Editor, S-Needs-Review

#16405 Bind only the written parts of storage buffers.
  crates/bevy_render/src/render_resource/storage_buffer.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, D-Straightforward

#16333 Fix MSRVs for standalone crates
  crates/bevy_color/Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_math/Cargo.toml
  crates/bevy_ptr/Cargo.toml
  crates/bevy_reflect/Cargo.toml
Labels: C-Bug, D-Trivial, A-Cross-Cutting, X-Blessed, S-Needs-Review

#16415 Add missing exports in bevy_ecs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Needs-Review

#16410 Fix bubbling of runtime requirements for `#[require(...)]` attribute
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/lib.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#15548 bevy_reflect: Add `ReflectSerializerProcessor`
  crates/bevy_reflect/src/serde/de/processor.rs
  crates/bevy_reflect/src/serde/ser/arrays.rs
  crates/bevy_reflect/src/serde/ser/enums.rs
  crates/bevy_reflect/src/serde/ser/lists.rs
  crates/bevy_reflect/src/serde/ser/maps.rs
  crates/bevy_reflect/src/serde/ser/mod.rs
  crates/bevy_reflect/src/serde/ser/processor.rs
  crates/bevy_reflect/src/serde/ser/serializer.rs
  crates/bevy_reflect/src/serde/ser/sets.rs
  crates/bevy_reflect/src/serde/ser/structs.rs
  crates/bevy_reflect/src/serde/ser/tuple_structs.rs
  crates/bevy_reflect/src/serde/ser/tuples.rs
Labels: C-Feature, S-Ready-For-Final-Review, A-Reflection, D-Complex

#16418 Properly set accessible value on label nodes
  crates/bevy_ui/src/accessibility.rs
Labels: C-Bug, A-Accessibility, S-Ready-For-Final-Review

#16419 remove gcd impl from bevy_render
  crates/bevy_render/src/mesh/allocator.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#16369 add docs to view uniform frustum field
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/view.wgsl
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#16373 add docs to clip_from_view
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/view.wgsl
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#16425 Revert most of #16222 and add gamepad accessors
  crates/bevy_input/src/button_input.rs
  crates/bevy_input/src/gamepad.rs
  examples/input/gamepad_input.rs
  examples/input/gamepad_rumble.rs
  examples/tools/gamepad_viewer.rs
Labels: A-Input, C-Usability, S-Needs-Review

#16393 Rename box shadow rendering variable names
  crates/bevy_ui/src/render/box_shadow.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#16428 Fix `bevy_hierarchy` failing to compile without `reflect` feature
  crates/bevy_hierarchy/src/events.rs
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, P-Compile-Failure, A-Hierarchy

#16370 Adds some helpful methods to TextFont
  crates/bevy_text/src/text.rs
Labels: C-Feature, D-Trivial, A-UI, S-Ready-For-Final-Review, A-Text

#16452 Fix detailed_trace!
  crates/bevy_ecs/Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_utils/Cargo.toml
  crates/bevy_utils/src/lib.rs
Labels: C-Bug, A-Utils, S-Needs-Review

#16449 Add a note to the on_unimplemented message for `QueryData` recommending `&T` and `&mut T`.
  crates/bevy_ecs/src/query/fetch.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review

#16443 Correcting misspellings
  crates/bevy_ecs/src/system/query.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#16440 AnimationEvent -> Event and other improvements
  crates/bevy_animation/Cargo.toml
  crates/bevy_animation/derive/Cargo.toml
  crates/bevy_animation/derive/src/lib.rs
  crates/bevy_animation/src/animation_event.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_app/src/main_schedule.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_ui/Cargo.toml
  crates/bevy_ui/src/lib.rs
  examples/animation/animated_fox.rs
  examples/animation/animation_events.rs
  tools/publish.sh
Labels: C-Usability, S-Ready-For-Final-Review, A-Animation

#16375 Only use physical coords internally in `bevy_ui`
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/picking_backend.rs
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/pipeline.rs
  crates/bevy_ui/src/render/render_pass.rs
  crates/bevy_ui/src/render/ui.wgsl
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/update.rs
  crates/bevy_ui/src/widget/text.rs
  examples/ui/overflow_debug.rs
  examples/ui/ui_texture_slice_flip_and_tile.rs
Labels: C-Bug, A-UI, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Uncontroversial

#16441 Fix adding a subtree of required components to an existing tree replacing shallower required component constructors
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: C-Bug, A-ECS, S-Needs-Review

#16476 Fix dynamic linking failures from the `AnimationEventFn` change.
  crates/bevy_animation/src/lib.rs
Labels: C-Bug, S-Ready-For-Final-Review, P-Regression, A-Animation, A-Reflection

#16470 Fix the picking backend features not actually disabling the features
  Cargo.toml
  benches/Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_picking/Cargo.toml
  crates/bevy_picking/src/lib.rs
  crates/bevy_sprite/Cargo.toml
  crates/bevy_ui/Cargo.toml
  docs/cargo_features.md
Labels: C-Bug, S-Ready-For-Final-Review, A-Picking

#16475 Fix off-by-one error on `Image::get_color_at` and `Image::set_color_at`.
  crates/bevy_image/src/image.rs
Labels: C-Bug, A-Rendering, P-Crash, S-Ready-For-Final-Review

#16467 Refresh `RenderVisibilityRanges` when a visibility range is removed from the scene.
  crates/bevy_render/src/view/visibility/range.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#16473 Add flags to `SpritePlugin` and `UiPlugin` to allow disabling their picking backend (without needing to disable features).
  crates/bevy_sprite/src/lib.rs
  crates/bevy_ui/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Picking

#16468 Only use the AABB center for mesh visibility range testing if specified.
  crates/bevy_render/src/view/visibility/range.rs
  examples/3d/visibility_range.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, P-Regression, M-Needs-Migration-Guide

#16461 Make render world sync marker components `Copy`
  crates/bevy_render/src/sync_world.rs
Labels: D-Trivial, A-Rendering, C-Usability, S-Ready-For-Final-Review

#16464 Dont enable bevy_remote by default
  Cargo.toml
  docs/cargo_features.md
Labels: D-Trivial, C-Usability, A-Networking, S-Waiting-on-Author

#16462 Use default storage for `TemporaryRenderEntity`
  crates/bevy_render/src/sync_world.rs
Labels: D-Trivial, A-Rendering, C-Performance, C-Code-Quality, S-Ready-For-Final-Review

#16483 and -> an
  crates/bevy_render/src/render_resource/bind_group.rs
Labels: C-Docs, D-Trivial, A-Rendering

#16481 cleanup bevy_render/lib.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/settings.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Straightforward

#16488 Make some examples deterministic
  examples/2d/cpu_draw.rs
  examples/2d/transparency_2d.rs
  examples/animation/animated_fox.rs
  examples/ecs/parallel_query.rs
Labels: A-Build-System, C-Examples, S-Ready-For-Final-Review

#16486 Add screenshot check on UI
  .github/example-run/alien_cake_addict.ron
  .github/example-run/breakout.ron
  .github/example-run/testbed_ui.ron
  .github/workflows/ci.yml
  .github/workflows/validation-jobs.yml
  examples/testbed/ui.rs
Labels: C-Feature, A-Rendering, A-Build-System, A-UI, S-Ready-For-Final-Review, D-Straightforward

#16485 remove check on windows screenshots
  .github/workflows/validation-jobs.yml
Labels: A-Rendering, A-Build-System, S-Ready-For-Final-Review, D-Straightforward

#16493 Fix `Single` doc links
  crates/bevy_ecs/src/system/query.rs
Labels: C-Docs, D-Trivial, A-ECS, S-Ready-For-Final-Review

#16489 Simple integration testing (adopted)
  docs-template/EXAMPLE_README.md.tpl
  examples/README.md
  tests/how_to_test_apps.rs
Labels: C-Examples, S-Ready-For-Final-Review, C-Testing, A-Cross-Cutting, D-Straightforward

#16506 `BorderRadius::percent` fix
  crates/bevy_ui/src/ui_node.rs
Labels: C-Bug, D-Trivial, A-UI, S-Ready-For-Final-Review

#16513 use wgpu patch 23.0.1
  crates/bevy_image/Cargo.toml
  crates/bevy_mesh/Cargo.toml
  crates/bevy_render/Cargo.toml
Labels: D-Trivial, A-Rendering, C-Dependencies, S-Ready-For-Final-Review

#16517 Update `sysinfo` version to 0.32.1
  crates/bevy_diagnostic/Cargo.toml
Labels: D-Trivial, C-Dependencies

#16523 Revert "Update `sysinfo` version to 0.32.1 (#16517)"
  crates/bevy_diagnostic/Cargo.toml
Labels: C-Bug, D-Trivial, A-Build-System, S-Ready-For-Final-Review

#16524 Skip empty spans when updating text buffers
  crates/bevy_text/src/pipeline.rs
Labels: C-Bug, A-Text

#16527 Clarify that `bevy_app::App.world()` (and mut variant) returns the main `SubApp`'s `World`
  crates/bevy_app/src/app.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-App, D-Straightforward

#16530 Fix CAS shader alpha accessor
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/robust_contrast_adaptive_sharpening.wgsl
Labels: C-Bug, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#16533 Fix CAS toggle broken by retained render world
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
Labels: C-Bug, A-Rendering, D-Straightforward, S-Needs-Review

#16542 Fix newline in AnimationEvaluationState docs
  crates/bevy_animation/src/lib.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-Animation, P-Critical

#16540 fix: scroll list is non-scrollable
  examples/testbed/ui.rs
Labels: C-Bug, C-Examples, S-Ready-For-Final-Review, A-Picking

#16536 Improve ZIndex docs
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review, D-Straightforward

#16546 Clarify inheritance behavior of required components
  crates/bevy_ecs/src/component.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#16548 Reduce iOS cpu usage
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_config.rs
  examples/mobile/src/lib.rs
Labels: C-Performance, P-High, O-iOS, S-Ready-For-Final-Review

#16551 Make `bevy_gltf` compile without `bevy_animation` feature
  crates/bevy_gltf/src/loader.rs
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, A-Animation, P-Compile-Failure, A-glTF

#16557 Fix example build for wasm
  examples/3d/blend_modes.rs
  examples/3d/motion_blur.rs
Labels: D-Trivial, C-Examples, O-Web

#16552 Remove duplicated default feature
  Cargo.toml
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review

#16565 fix QueryIter::sort_unstable_by
  crates/bevy_ecs/src/query/iter.rs
Labels: C-Bug, D-Trivial, A-ECS, S-Ready-For-Final-Review

#16573 Fix a couple typos
  crates/bevy_ecs/src/storage/blob_array.rs
  crates/bevy_ecs/src/traversal.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review
