Repository bevyengine/bevy, pull requests merged in 2024-03, with the labels that each got.

#12211 Add coordinate axes gizmo
  crates/bevy_gizmos/src/arrows.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Editor, A-Gizmos, C-Needs-Release-Note

#12178 Update cargo deny
  deny.toml
Labels: A-Build-System, C-Dependencies

#12220 bloom: use emissive instead of base_color for emissive
  crates/bevy_pbr/src/pbr_material.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#10756 Component Lifecycle Hooks and a Deferred World
  Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/system/commands/command_queue.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/spawn_batch.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  examples/README.md
  examples/ecs/component_hooks.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review, S-Controversial

#12223 Build dev docs like docs.rs
  .github/workflows/docs.yml
Labels: C-Docs

#12230 Explicitly run `+nightly` for `-Zcheck-cfg` pass in ci.
  tools/ci/src/main.rs
Labels: A-Build-System, S-Ready-For-Final-Review

#12216 Intern mesh vertex buffer layouts so that we don't have to compare them over and over.
  crates/bevy_pbr/src/extended_material.rs
  crates/bevy_pbr/src/lightmap/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/mesh/mod.rs
  crates/bevy_render/src/render_resource/pipeline_specializer.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  examples/2d/custom_gltf_vertex_attribute.rs
  examples/3d/lines.rs
  examples/shader/custom_vertex_attribute.rs
  examples/shader/shader_defs.rs
  examples/shader/shader_instancing.rs
  examples/shader/shader_material_glsl.rs
  examples/stress_tests/many_cubes.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, C-Breaking-Change

#12238 Add `size` and `physical_size` to `window`
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_window/src/window.rs
  examples/3d/split_screen.rs
  examples/games/contributors.rs
  examples/stress_tests/bevymark.rs
Labels: A-Windowing, C-Usability, S-Ready-For-Final-Review

#12247 Update `wgpu` to v0.19.3 and unpin `web-sys`.
  .github/workflows/ci.yml
  Cargo.toml
  crates/bevy_color/Cargo.toml
  crates/bevy_render/Cargo.toml
  docs-template/EXAMPLE_README.md.tpl
  docs/cargo_features.md
  examples/README.md
  tools/build-wasm-example/src/main.rs
Labels: A-Rendering, C-Dependencies, C-Code-Quality, C-Usability, S-Ready-For-Final-Review

#12244 Replace init_component_info with register_component_hooks
  crates/bevy_ecs/src/component.rs
  examples/ecs/component_hooks.rs
Labels: C-Bug, A-ECS, C-Unsoundness

#12257 Add nightly hint to config.toml
  .cargo/config_fast_builds.toml
Labels: C-Docs, S-Ready-For-Final-Review

#12253 Update engine_style_guide with guideline to link to the error code when using bevy engine error codes
  .github/contributing/engine_style_guide.md
Labels: C-Docs, C-Enhancement, S-Ready-For-Final-Review

#12250 Batching: replace GpuArrayBufferIndex::index with a u32
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/render_resource/batched_uniform_buffer.rs
  crates/bevy_render/src/render_resource/gpu_array_buffer.rs
Labels: A-Rendering, C-Code-Quality, C-Breaking-Change

#12249 Document instability of Entity's internal representation
  crates/bevy_ecs/src/entity/mod.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#12254 Replace bevy_log's tracing reexport with bevy_utils'
  crates/bevy_animation/Cargo.toml
  crates/bevy_animation/src/lib.rs
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/io/android.rs
  crates/bevy_asset/src/io/embedded/embedded_watcher.rs
  crates/bevy_asset/src/io/file/file_watcher.rs
  crates/bevy_asset/src/io/file/mod.rs
  crates/bevy_asset/src/io/processor_gated.rs
  crates/bevy_asset/src/io/source.rs
  crates/bevy_asset/src/io/wasm.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/meta.rs
  crates/bevy_asset/src/processor/log.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/server/info.rs
  crates/bevy_asset/src/server/loaders.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_core_pipeline/Cargo.toml
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_diagnostic/Cargo.toml
  crates/bevy_diagnostic/src/log_diagnostics_plugin.rs
  crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs
  crates/bevy_gilrs/Cargo.toml
  crates/bevy_gilrs/src/rumble.rs
  crates/bevy_gizmos/Cargo.toml
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gltf/Cargo.toml
  crates/bevy_gltf/src/loader.rs
  crates/bevy_hierarchy/Cargo.toml
  crates/bevy_hierarchy/src/valid_parent_check_plugin.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/extract_resource.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/render_graph/app.rs
  crates/bevy_render/src/render_resource/bind_group_layout_entries.rs
  crates/bevy_render/src/view/window/mod.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_sprite/Cargo.toml
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/texture_atlas_builder.rs
  crates/bevy_sprite/src/texture_slice/mod.rs
  crates/bevy_sprite/src/texture_slice/slicer.rs
  crates/bevy_ui/Cargo.toml
  crates/bevy_ui/src/layout/debug.rs
  crates/bevy_ui/src/layout/mod.rs
Labels: C-Dependencies, C-Code-Quality, S-Ready-For-Final-Review, A-Diagnostics

#12266 PBR: use attenuation instead of base_color for attenuation
  crates/bevy_pbr/src/pbr_material.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#12234 Move commands module into bevy::ecs::world
  benches/benches/bevy_ecs/world/commands.rs
  crates/bevy_ecs/src/reflect/entity_commands.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/system_registry.rs
  crates/bevy_ecs/src/world/command_queue.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_hierarchy/src/hierarchy.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_transform/src/commands.rs
  crates/bevy_transform/src/systems.rs
  crates/bevy_ui/src/stack.rs
  examples/async_tasks/async_compute.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#12270 remove repetitive code
  crates/bevy_asset/src/path.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/query/builder.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/world_cell.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_tasks/src/thread_executor.rs
  examples/time/virtual_time.rs
Labels: C-Docs

#11278 Fix fit_canvas_to_parent
  crates/bevy_window/src/window.rs
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/system.rs
  examples/wasm/index.html
  examples/window/window_settings.rs
  tools/example-showcase/window-settings-wasm.patch
Labels: C-Bug, A-Windowing, O-Web, S-Ready-For-Final-Review

#12083 Use NonMaxUsize for non-component SparseSets
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/storage/sparse_set.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review

#12276 Implement `Mul` between `f32` and direction types
  crates/bevy_math/src/direction.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#12228 Add basic light gizmos
  Cargo.toml
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gizmos/src/light.rs
  crates/bevy_gizmos/src/primitives/dim3.rs
  examples/README.md
  examples/gizmos/light_gizmos.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Gizmos, C-Needs-Release-Note

#12218 Deprecate `SpriteSheetBundle` and `AtlasImageBundle`
  crates/bevy_sprite/src/bundle.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/texture_atlas_builder.rs
  crates/bevy_ui/src/node_bundles.rs
  examples/2d/sprite_sheet.rs
  examples/2d/texture_atlas.rs
  examples/stress_tests/many_animated_sprites.rs
  examples/ui/ui_texture_atlas.rs
Labels: A-Rendering, A-UI, C-Usability, S-Ready-For-Final-Review

#11165 Decouple `BackgroundColor` from `UiImage`
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/texture_slice.rs
  crates/bevy_ui/src/ui_node.rs
  examples/3d/split_screen.rs
  examples/ecs/state.rs
  examples/games/game_menu.rs
  examples/stress_tests/many_buttons.rs
  examples/ui/button.rs
  examples/ui/display_and_visibility.rs
  examples/ui/overflow.rs
  examples/ui/size_constraints.rs
  examples/ui/transparency_ui.rs
  examples/ui/ui_texture_atlas.rs
  examples/ui/ui_texture_slice.rs
Labels: A-Rendering, A-UI, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, C-Needs-Release-Note

#12265 fix example lightmaps after color migration
  crates/bevy_color/src/srgba.rs
  examples/3d/lightmaps.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#12100 Add WinitEvent aggregate event for synchronized window event reading
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/winit_event.rs
Labels: C-Enhancement, A-Input, S-Ready-For-Final-Review, C-Needs-Release-Note

#12045 Add access to `App` within `LogPlugin::update_subscriber`
  Cargo.toml
  crates/bevy_log/src/lib.rs
  examples/README.md
  examples/app/log_layers.rs
  examples/app/log_layers_ecs.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, C-Breaking-Change, A-Diagnostics

#12278 Improve error messages for denormalized directions
  crates/bevy_math/src/direction.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#12284 Update `Input` to `ButtonInput` in a couple places at keyboard input docs
  crates/bevy_input/src/keyboard.rs
Labels: C-Docs, A-Input, S-Ready-For-Final-Review

#12264 `#[reflect(Default)]` for Handle/Mesh2dHandle
  crates/bevy_asset/src/handle.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
Labels: C-Enhancement, A-Assets, A-Reflection

#12197 Add the ability to request a redraw from an external source
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_config.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review, C-Regression

#5781 bevy_reflect: Recursive registration
  crates/bevy_reflect/bevy_reflect_derive/src/derive_data.rs
  crates/bevy_reflect/bevy_reflect_derive/src/impls/enums.rs
  crates/bevy_reflect/bevy_reflect_derive/src/registration.rs
  crates/bevy_reflect/bevy_reflect_derive/src/utility.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/tuple.rs
  crates/bevy_reflect/src/type_registry.rs
  crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/generics.fail.rs
  crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/generics.fail.stderr
  crates/bevy_render/src/render_asset.rs
  examples/reflection/generic_reflection.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection, C-Breaking-Change, S-Controversial, C-Needs-Release-Note

#12239 Fix winit control flow when re-focusing game
  crates/bevy_winit/src/lib.rs
Labels: C-Bug, A-Windowing, O-Web, S-Ready-For-Final-Review

#12268 Fix #12255 Updating TargetCamera on multi camera scenes not allowing layout to be calculated
  crates/bevy_ui/src/layout/mod.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#12295 Improve components hooks docs
  crates/bevy_ecs/src/component.rs
  examples/ecs/component_hooks.rs
Labels: C-Docs, A-ECS, C-Examples, S-Ready-For-Final-Review

#12289 bevy_ecs: Fix up docs for `World::run_system` and `World::run_system_with_input`
  crates/bevy_ecs/src/system/system_registry.rs
Labels: C-Docs, A-ECS

#12242 Quality-of-life updates for running CI locally
  tools/ci/src/main.rs
Labels: A-Build-System, C-Usability

#12306 remove background color from UI example image
  examples/ui/ui.rs
Labels: C-Examples, A-UI

#11681 Support transforming bounding volumes
  crates/bevy_math/src/bounding/bounded2d/mod.rs
  crates/bevy_math/src/bounding/bounded3d/mod.rs
  crates/bevy_math/src/bounding/mod.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math

#12308 bevy_utils: Add `BuildHasher` parameter to `bevy_utils::Entry` type alias
  crates/bevy_asset/src/server/info.rs
  crates/bevy_reflect/src/type_registry.rs
  crates/bevy_utils/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Utils

#12309 Fix duplicate dependencies on raw-window-handle
  crates/bevy_audio/Cargo.toml
  deny.toml
Labels: A-Build-System, C-Dependencies, S-Ready-For-Final-Review

#11141 Rewrite part of Commands rustdoc
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#12311 Remove ComponentStorage and associated types
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  examples/ecs/component_hooks.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#12307 Remove initialize_resource<T> and friends
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#12248 update comment on `emissive` field of `StandardMaterial` struct to mention large color channel values
  crates/bevy_pbr/src/pbr_material.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#12315 Add note about rotations for `Aabb3d`
  crates/bevy_math/src/bounding/bounded3d/mod.rs
Labels: C-Docs, A-Math

#12316 don't depend directly on oboe
  crates/bevy_audio/Cargo.toml
Labels: A-Audio, C-Dependencies, O-Android

#12323 Use floats mathed from 8-bit values in basic color palette
  crates/bevy_color/src/palettes/basic.rs
  examples/2d/bounding_2d.rs
  examples/stress_tests/bevymark.rs
  examples/ui/grid.rs
  examples/ui/viewport_debug.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#12321 Fix `with_scale_factor_override` improperly setting `scale_factor_override`
  crates/bevy_window/src/window.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#12328 Fix green colors becoming darker in various examples
  crates/bevy_color/src/palettes/css.rs
  examples/2d/bounding_2d.rs
  examples/2d/text2d.rs
  examples/3d/lighting.rs
  examples/3d/shadow_caster_receiver.rs
  examples/3d/transmission.rs
  examples/3d/wireframe.rs
  examples/audio/spatial_audio_2d.rs
  examples/audio/spatial_audio_3d.rs
  examples/ecs/hierarchy.rs
  examples/games/game_menu.rs
  examples/gizmos/2d_gizmos.rs
  examples/gizmos/3d_gizmos.rs
  examples/stress_tests/bevymark.rs
  examples/ui/text_debug.rs
  examples/ui/ui.rs
  examples/ui/viewport_debug.rs
  examples/ui/z_index.rs
  examples/window/low_power.rs
Labels: C-Examples, S-Ready-For-Final-Review

#12333 Fix "dark grey" colors becoming lighter in various examples
  examples/3d/split_screen.rs
  examples/ui/borders.rs
  examples/ui/flex_layout.rs
  examples/ui/grid.rs
  examples/ui/overflow.rs
  examples/ui/overflow_debug.rs
Labels: C-Examples, S-Ready-For-Final-Review

#12269 Clean up pointer use in BundleSpawner/BundleInserter
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ptr/src/lib.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Unsoundness

#12339 Fix ios simulator support
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  docs/cargo_features.md
  examples/mobile/.cargo/config.toml
  examples/mobile/Cargo.toml
Labels: C-Bug, O-iOS

#12342 Fix directional light shadow frustum culling near clip plane to infinity
  crates/bevy_pbr/src/light.rs
  crates/bevy_pbr/src/render/light.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#11341 Add bevy_dev_tools crate
  Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/lib.rs
  crates/bevy_dev_tools/Cargo.toml
  crates/bevy_dev_tools/src/ci_testing.rs
  crates/bevy_dev_tools/src/lib.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_internal/src/lib.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_time/Cargo.toml
  crates/bevy_time/src/lib.rs
  docs/cargo_features.md
  tools/publish.sh
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Editor, S-Controversial

#12331 We must have googly eyes (new Game example)
  Cargo.toml
  examples/README.md
  examples/games/desk_toy.rs
Labels: C-Enhancement, C-Examples, C-Needs-Release-Note

#12355 Fix `ImageLoader` not being initialized with `webp` or `pnm` features
  crates/bevy_render/src/texture/mod.rs
Labels: C-Bug, A-Rendering, A-Assets, C-Compile-Failure

#12313 Disentangle bevy_utils/bevy_core's reexported dependencies
  Cargo.toml
  crates/bevy_animation/Cargo.toml
  crates/bevy_animation/src/lib.rs
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/plugin.rs
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/handle.rs
  crates/bevy_asset/src/id.rs
  crates/bevy_core/Cargo.toml
  crates/bevy_core/src/lib.rs
  crates/bevy_core_pipeline/Cargo.toml
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/deferred/mod.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/graph_utils.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/stepping.rs
  crates/bevy_gizmos/Cargo.toml
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gltf/Cargo.toml
  crates/bevy_gltf/src/loader.rs
  crates/bevy_hierarchy/Cargo.toml
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_hierarchy/src/components/children.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_reflect/Cargo.toml
  crates/bevy_reflect/src/impls/smallvec.rs
  crates/bevy_reflect/src/impls/uuid.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/mesh/mesh/mod.rs
  crates/bevy_render/src/render_asset.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_render/src/render_resource/batched_uniform_buffer.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/render_resource/buffer_vec.rs
  crates/bevy_render/src/render_resource/gpu_array_buffer.rs
  crates/bevy_render/src/renderer/graph_runner.rs
  crates/bevy_render/src/texture/image_texture_conversion.rs
  crates/bevy_ui/Cargo.toml
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/render/render_pass.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_utils/Cargo.toml
  crates/bevy_utils/src/lib.rs
  crates/bevy_utils/src/uuid.rs
  examples/asset/asset_decompression.rs
  examples/asset/custom_asset.rs
  examples/asset/processing/asset_processing.rs
  examples/games/contributors.rs
Labels: C-Dependencies, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change, A-Utils

#12350 Use `.register_asset_source()` in `extra_asset_source` example
  examples/asset/extra_source.rs
Labels: C-Examples, A-Assets, S-Ready-For-Final-Review

#11981 Improve Bloom 3D lighting
  crates/bevy_core_pipeline/src/bloom/settings.rs
  examples/3d/bloom_3d.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#11989 Implement the `AnimationGraph`, allowing for multiple animations to be blended together.
  Cargo.toml
  assets/animation_graphs/Fox.animgraph.ron
  crates/bevy_animation/Cargo.toml
  crates/bevy_animation/src/graph.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_animation/src/transition.rs
  crates/bevy_asset/src/id.rs
  crates/bevy_reflect/Cargo.toml
  crates/bevy_reflect/src/impls/petgraph.rs
  crates/bevy_reflect/src/lib.rs
  examples/3d/irradiance_volumes.rs
  examples/README.md
  examples/animation/animated_fox.rs
  examples/animation/animated_transform.rs
  examples/animation/animation_graph.rs
  examples/animation/morph_targets.rs
  examples/stress_tests/many_foxes.rs
  examples/tools/scene_viewer/animation_plugin.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Editor, C-Breaking-Change, D-Complex, C-Needs-Release-Note

#12361 Fix incorrect link in UiMaterial documentation
  crates/bevy_ui/src/ui_material.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#12343 Fix dim emissive values in `lighting` example
  examples/3d/lighting.rs
Labels: C-Bug, C-Examples, S-Ready-For-Final-Review

#12370 Fix minimal plugins in ci
  crates/bevy_internal/src/default_plugins.rs
Labels: C-Bug, A-Build-System, S-Ready-For-Final-Review

#12371 move ci testing to dev_tools
  crates/bevy_dev_tools/Cargo.toml
  crates/bevy_dev_tools/src/ci_testing.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_time/Cargo.toml
  crates/bevy_time/src/lib.rs
Labels: C-Bug, A-Build-System, C-Code-Quality, S-Ready-For-Final-Review, A-Dev-Tools

#12373 Remove "features" feature
  crates/bevy_diagnostic/Cargo.toml
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Diagnostics

#12375 Fix gizmos panicking given bad output from `GlobalTransform::to_scale_rotation_translation`
  crates/bevy_gizmos/src/gizmos.rs
Labels: C-Bug, C-Crash, A-Gizmos

#12338 Contribution guidelines for `bevy_audio`
  crates/bevy_audio/CONTRIBUTING.md
  crates/bevy_audio/src/lib.rs
Labels: C-Docs, A-Audio, S-Ready-For-Final-Review

#12366 Add "all-features = true" to docs.rs metadata for most crates
  Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/lib.rs
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/lib.rs
  crates/bevy_audio/Cargo.toml
  crates/bevy_audio/src/lib.rs
  crates/bevy_core/Cargo.toml
  crates/bevy_core/src/lib.rs
  crates/bevy_core_pipeline/Cargo.toml
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_dev_tools/Cargo.toml
  crates/bevy_dev_tools/src/lib.rs
  crates/bevy_diagnostic/Cargo.toml
  crates/bevy_diagnostic/src/lib.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/lib.rs
  crates/bevy_gizmos/Cargo.toml
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gltf/Cargo.toml
  crates/bevy_gltf/src/lib.rs
  crates/bevy_hierarchy/Cargo.toml
  crates/bevy_hierarchy/src/lib.rs
  crates/bevy_input/Cargo.toml
  crates/bevy_input/src/lib.rs
  crates/bevy_log/Cargo.toml
  crates/bevy_log/src/lib.rs
  crates/bevy_math/Cargo.toml
  crates/bevy_math/src/lib.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/lib.rs
  crates/bevy_reflect/Cargo.toml
  crates/bevy_reflect/src/lib.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/lib.rs
  crates/bevy_scene/Cargo.toml
  crates/bevy_scene/src/lib.rs
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/src/lib.rs
  crates/bevy_text/Cargo.toml
  crates/bevy_text/src/lib.rs
  crates/bevy_time/Cargo.toml
  crates/bevy_time/src/lib.rs
  crates/bevy_transform/Cargo.toml
  crates/bevy_transform/src/lib.rs
  crates/bevy_ui/Cargo.toml
  crates/bevy_ui/src/lib.rs
  crates/bevy_window/Cargo.toml
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/Cargo.toml
  crates/bevy_winit/src/lib.rs
  src/lib.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#12335 Improve gizmo axes example
  examples/gizmos/axes.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Gizmos

#12385 CI testing: don't crash if screenshot manager resource is not available
  crates/bevy_dev_tools/src/ci_testing.rs
Labels: C-Bug, A-Build-System, S-Ready-For-Final-Review

#12389 Move AssetEvents to Last
  crates/bevy_asset/src/lib.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#12396 try_insert NoAutomaticBatching
  crates/bevy_pbr/src/render/morph.rs
  crates/bevy_pbr/src/render/skin.rs
Labels: A-Rendering, C-Crash, S-Ready-For-Final-Review

#12395 don't attempt to set cursor relative position for zero sized nodes
  crates/bevy_ui/src/focus.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#12305 Simplified backtraces
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_render/src/pipelined_rendering.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Diagnostics

#12406 Implement MutUntyped::from(mut_typed)
  crates/bevy_ecs/src/change_detection.rs
Labels: C-Enhancement, A-ECS

#10126 Add table showing complexity of methods for Input
  crates/bevy_input/src/button_input.rs
Labels: C-Docs, A-Input, S-Ready-For-Final-Review

#12421 fix deprecations from toml_edit
  crates/bevy_macro_utils/Cargo.toml
  crates/bevy_macro_utils/src/bevy_manifest.rs
  tools/build-templated-pages/Cargo.toml
  tools/build-templated-pages/src/examples.rs
  tools/build-templated-pages/src/features.rs
  tools/example-showcase/Cargo.toml
  tools/example-showcase/src/main.rs
Labels: P-High, S-Ready-For-Final-Review, A-Diagnostics

#12407 Fix leftover references to children when despawning audio entities
  crates/bevy_audio/Cargo.toml
  crates/bevy_audio/src/audio.rs
  crates/bevy_audio/src/audio_output.rs
Labels: C-Bug, A-Audio, S-Ready-For-Final-Review, C-Breaking-Change

#12400 Mention in docs about the query iteration order and result uniqueness.
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#12384 correctly set up background color in mobile example
  examples/mobile/src/lib.rs
Labels: C-Bug, C-Examples, A-UI, S-Ready-For-Final-Review

#11535 Query Joins
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
Labels: C-Enhancement, A-ECS, S-Ready-For-Final-Review, D-Complex, C-Needs-Release-Note

#11658 Add `Rotation2d`
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_math/Cargo.toml
  crates/bevy_math/src/bounding/bounded2d/mod.rs
  crates/bevy_math/src/bounding/bounded2d/primitive_impls.rs
  crates/bevy_math/src/bounding/bounded3d/mod.rs
  crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs
  crates/bevy_math/src/bounding/mod.rs
  crates/bevy_math/src/direction.rs
  crates/bevy_math/src/lib.rs
  crates/bevy_math/src/rotation2d.rs
  crates/bevy_reflect/src/impls/math/rotation2d.rs
  crates/bevy_reflect/src/lib.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Math, C-Needs-Release-Note

#12252 Gizmo line joints
  crates/bevy_gizmos/src/config.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gizmos/src/line_joints.wgsl
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  examples/gizmos/2d_gizmos.rs
  examples/gizmos/3d_gizmos.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, C-Breaking-Change, A-Gizmos, C-Needs-Release-Note

#12382 Fps overlay
  Cargo.toml
  crates/bevy_dev_tools/Cargo.toml
  crates/bevy_dev_tools/src/fps_overlay.rs
  crates/bevy_dev_tools/src/lib.rs
  examples/README.md
  examples/dev_tools/fps_overlay.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Dev-Tools

#12401 Gizmos: Replace PositionItem with Vec3
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_gizmos/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Gizmos

#12424 Send GamepadEvent for gamepads connected at startup
  crates/bevy_gilrs/src/gilrs_system.rs
Labels: C-Bug, A-Input

#12425 Update funding link
  .github/FUNDING.yml
  README.md
Labels: A-Meta

#12142 Add `scale_around_center` method to `BoundingVolume` trait
  crates/bevy_math/src/bounding/bounded2d/mod.rs
  crates/bevy_math/src/bounding/bounded3d/mod.rs
  crates/bevy_math/src/bounding/mod.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math

#12302 Allow setting RenderAssetUsages for gLTF meshes & materials during load
  crates/bevy_gltf/src/loader.rs
Labels: C-Enhancement, A-Rendering, A-Assets, S-Ready-For-Final-Review, C-Breaking-Change

#12433 bevy_reflect: Remove `U32Visitor`
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_reflect/src/serde/de.rs
Labels: C-Code-Quality, A-Reflection

#12413 Reduce steady-state allocations in ui_stack_system
  crates/bevy_ui/src/stack.rs
Labels: C-Performance, A-UI, S-Ready-For-Final-Review

#12391 Add more comprehensive crate level docs for bevy_ptr
  crates/bevy_ptr/README.md
Labels: C-Docs, S-Ready-For-Final-Review, A-Pointers

#12437 low_power example: pick nits
  examples/window/low_power.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#12436 SystemId should manually implement `Eq`
  crates/bevy_ecs/src/system/system_registry.rs
Labels: A-ECS, C-Usability

#12429 Fix blurry text
  crates/bevy_ui/src/render/mod.rs
Labels: C-Bug, A-Rendering, A-UI, S-Ready-For-Final-Review

#12369 Extracting ambient light from light.rs, and creating light directory
  crates/bevy_pbr/src/light/ambient_light.rs
  crates/bevy_pbr/src/light/mod.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#12439 Fix `z` scale being `0.0` in breakout example
  examples/games/breakout.rs
Labels: C-Examples, C-Code-Quality

#12430 Gizmo 3d grids
  crates/bevy_gizmos/src/grid.rs
  examples/gizmos/2d_gizmos.rs
Labels: C-Enhancement, S-Ready-For-Final-Review, A-Gizmos, C-Needs-Release-Note

#12466 Make a note about the performance of Query::is_empty
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#12464 Fix: deserialize `DynamicEnum` using index
  crates/bevy_reflect/src/serde/de.rs
  crates/bevy_reflect/src/serde/ser.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Reflection, A-Scenes

#12477 Breakout refactor
  examples/games/breakout.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#12486 order systems in axes example
  examples/gizmos/axes.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Gizmos

#12482 change doc for SphereKind::Ico to reflect that the triangles are equa…
  crates/bevy_render/src/mesh/primitives/dim3/sphere.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Math

#12487 Add `with_left`, `with_right`, `with_top`, `with_bottom` to `UiRect`
  crates/bevy_ui/src/geometry.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#12495 Add reflect for type id
  crates/bevy_reflect/src/impls/std.rs
Labels: C-Usability, A-Reflection

#12440 Fix CI desktop mode patch
  tools/example-showcase/remove-desktop-app-mode.patch
Labels: A-Build-System, S-Ready-For-Final-Review

#12456 change file location for showcase patch for light
  tools/example-showcase/reduce-light-cluster-config.patch
Labels: A-Build-System, S-Ready-For-Final-Review

#12505 stop retrying removed assets
  crates/bevy_pbr/src/material.rs
  crates/bevy_render/src/render_asset.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#12435 Split ScheduleGraph::process_configs function (adopted)
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#12528 Reflect default in colorspaces in `bevy_color`
  crates/bevy_color/src/color.rs
  crates/bevy_color/src/hsla.rs
  crates/bevy_color/src/hsva.rs
  crates/bevy_color/src/hwba.rs
  crates/bevy_color/src/laba.rs
  crates/bevy_color/src/lcha.rs
  crates/bevy_color/src/linear_rgba.rs
  crates/bevy_color/src/oklaba.rs
  crates/bevy_color/src/oklcha.rs
  crates/bevy_color/src/srgba.rs
  crates/bevy_color/src/xyza.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#12484 Uniform point sampling methods for some primitive shapes.
  crates/bevy_math/Cargo.toml
  crates/bevy_math/src/lib.rs
  crates/bevy_math/src/shape_sampling.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math, C-Needs-Release-Note

#12526 Solve some oklaba inconsistencies
  crates/bevy_color/src/color.rs
  crates/bevy_color/src/oklaba.rs
  crates/bevy_color/src/oklcha.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#12530 Use `Dir3` in `Transform` APIs
  crates/bevy_transform/src/components/transform.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Transform

#12474 Remove archetype_component_access from QueryState
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/system_param.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review, C-Breaking-Change

#12512 Update to fixedbitset 0.5
  crates/bevy_animation/Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_sprite/Cargo.toml
Labels: C-Dependencies, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#12515 make alien_cake_addict deterministic with a seeded random
  examples/games/alien_cake_addict.rs
Labels: A-Build-System, C-Examples, S-Ready-For-Final-Review

#12518 make align deterministic with a seeded random
  examples/transforms/align.rs
Labels: A-Build-System, C-Examples, S-Ready-For-Final-Review

#12457 check that patches are not broken
  .github/workflows/validation-jobs.yml
Labels: A-Build-System, S-Ready-For-Final-Review

#12531 remove link to inexistent example
  crates/bevy_transform/src/components/transform.rs
Labels: C-Docs, C-Examples, S-Ready-For-Final-Review

#9135 Add pipeline statistics
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/core_2d/main_pass_2d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transparent_pass_3d_node.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/diagnostic/internal.rs
  crates/bevy_render/src/diagnostic/mod.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_phase/draw_state.rs
  crates/bevy_render/src/renderer/graph_runner.rs
  crates/bevy_render/src/renderer/mod.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, A-Diagnostics, C-Needs-Release-Note, A-Dev-Tools

#12525 Add trait for clamping colors
  crates/bevy_color/src/color_ops.rs
  crates/bevy_color/src/hsla.rs
  crates/bevy_color/src/hsva.rs
  crates/bevy_color/src/hwba.rs
  crates/bevy_color/src/laba.rs
  crates/bevy_color/src/lcha.rs
  crates/bevy_color/src/linear_rgba.rs
  crates/bevy_color/src/oklaba.rs
  crates/bevy_color/src/oklcha.rs
  crates/bevy_color/src/srgba.rs
  crates/bevy_color/src/xyza.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#12533 Compute texture slices after layout
  crates/bevy_ui/src/lib.rs
Labels: C-Bug, A-UI

#12519 make example font_atlas_debug deterministic with a seeded random
  examples/ui/font_atlas_debug.rs
Labels: A-Build-System, C-Examples, S-Ready-For-Final-Review

#12459 send Unused event when asset is actually unused
  crates/bevy_asset/src/assets.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#12348 Beautify example showcase site URLs
  tools/example-showcase/src/main.rs
Labels: C-Examples, S-Ready-For-Final-Review

#12419 Add into_ methods for EntityMut and EntityWorldMut that consume self.
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#12503 add reflect for BinaryHeap
  crates/bevy_reflect/src/impls/std.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#12532 feat: derive some common traits on some UI types
  crates/bevy_text/src/text.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/button.rs
Labels: A-UI, C-Usability

#12551 Remove WorldCell
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_ecs/src/world/world_cell.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Breaking-Change

#11115 Explain Camera2dBundle.projection needs to be set carefully
  crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
Labels: C-Docs, A-Core, S-Ready-For-Final-Review

#12451 Fix pink colors in examples
  examples/3d/lighting.rs
  examples/3d/wireframe.rs
  examples/stress_tests/many_lights.rs
  examples/ui/grid.rs
Labels: C-Examples, S-Ready-For-Final-Review

#12513 fast-fail in as_bind_group
  crates/bevy_render/macros/src/as_bind_group.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#12516 Add methods to return the inner value for direction types
  crates/bevy_math/src/direction.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Math

#12538 Add setting to enable/disable shadows to MaterialPlugin
  crates/bevy_pbr/src/material.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review, C-Breaking-Change

#12550 Use async-fn in traits rather than BoxedFuture
  crates/bevy_animation/src/graph.rs
  crates/bevy_asset/src/io/android.rs
  crates/bevy_asset/src/io/file/file_asset.rs
  crates/bevy_asset/src/io/file/sync_file_asset.rs
  crates/bevy_asset/src/io/gated.rs
  crates/bevy_asset/src/io/memory.rs
  crates/bevy_asset/src/io/mod.rs
  crates/bevy_asset/src/io/processor_gated.rs
  crates/bevy_asset/src/io/source.rs
  crates/bevy_asset/src/io/wasm.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/loader.rs
  crates/bevy_asset/src/meta.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/processor/process.rs
  crates/bevy_asset/src/saver.rs
  crates/bevy_asset/src/server/loaders.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_asset/src/transformer.rs
  crates/bevy_audio/src/audio_source.rs
  crates/bevy_gltf/src/loader.rs
  crates/bevy_render/src/render_resource/shader.rs
  crates/bevy_render/src/texture/compressed_image_saver.rs
  crates/bevy_render/src/texture/exr_texture_loader.rs
  crates/bevy_render/src/texture/hdr_texture_loader.rs
  crates/bevy_render/src/texture/image_loader.rs
  crates/bevy_scene/src/scene_loader.rs
  crates/bevy_text/src/font_loader.rs
  crates/bevy_utils/src/lib.rs
  examples/asset/asset_decompression.rs
  examples/asset/custom_asset.rs
  examples/asset/custom_asset_reader.rs
  examples/asset/processing/asset_processing.rs
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change, C-Needs-Release-Note

#12080 bevy_color: Add Tailwind palette
  crates/bevy_color/src/palettes/mod.rs
  crates/bevy_color/src/palettes/tailwind.rs
Labels: C-Enhancement, A-Rendering, S-Ready-For-Final-Review

#11237 Add a gizmo-based overlay to show UI node outlines (Adopted)
  crates/bevy_dev_tools/Cargo.toml
  crates/bevy_dev_tools/src/debug_overlay/inset.rs
  crates/bevy_dev_tools/src/debug_overlay/mod.rs
  crates/bevy_dev_tools/src/lib.rs
  examples/ui/ui.rs
Labels: C-Enhancement, A-UI, S-Ready-For-Final-Review, A-Gizmos, C-Needs-Release-Note, A-Dev-Tools

#12557 refactor: separate out `PanicHandlerPlugin`
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_internal/src/lib.rs
  crates/bevy_log/Cargo.toml
  crates/bevy_log/src/lib.rs
  crates/bevy_panic_handler/Cargo.toml
  crates/bevy_panic_handler/src/lib.rs
Labels: O-Web, C-Usability, S-Ready-For-Final-Review, C-Breaking-Change

#12500 Add border radius to UI nodes (adopted)
  Cargo.toml
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/pipeline.rs
  crates/bevy_ui/src/render/render_pass.rs
  crates/bevy_ui/src/render/ui.wgsl
  crates/bevy_ui/src/texture_slice.rs
  crates/bevy_ui/src/ui_node.rs
  examples/README.md
  examples/ui/button.rs
  examples/ui/rounded_borders.rs
Labels: C-Enhancement, A-UI, S-Ready-For-Final-Review, C-Needs-Release-Note

#12575 Color maths 4
  crates/bevy_color/src/laba.rs
  crates/bevy_color/src/lib.rs
  crates/bevy_color/src/linear_rgba.rs
  crates/bevy_color/src/oklaba.rs
  crates/bevy_color/src/xyza.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, A-Animation, A-Math

#12583 Fix `Oklab` and `Oklch` color space inconsistency
  crates/bevy_color/src/oklaba.rs
  crates/bevy_color/src/oklcha.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#12599 UI: don't multiply color channels by alpha
  crates/bevy_ui/src/render/ui.wgsl
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#12601 UI: rounded border should use camera instead of windows
  crates/bevy_ui/src/render/mod.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#12623 Fix Ci failing over dead code in tests
  crates/bevy_asset/src/server/loaders.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/command_queue.rs
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_exact_sized_iterator_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_iter_combinations_mut_iterator_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/query_iter_many_mut_iterator_safety.stderr
  crates/bevy_ecs_compile_fail_tests/tests/ui/system_param_derive_readonly.stderr
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_macros_compile_fail_tests/tests/deref_mut_derive/missing_deref.fail.stderr
  crates/bevy_reflect_compile_fail_tests/tests/reflect_derive/generics.fail.stderr
  crates/bevy_winit/src/winit_windows.rs
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review, P-Critical

#12605 Make `AssetAction::Ignore` not copy assets to `imported_assets`
  crates/bevy_asset/src/processor/mod.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review, C-Breaking-Change

#12626 typo: 'plateform' -> 'platform'
  crates/bevy_winit/src/lib.rs
Labels: C-Docs, S-Ready-For-Final-Review

#12630 Update `borders` example to match `rounded_borders` example
  examples/ui/borders.rs
Labels: C-Examples, A-UI, S-Ready-For-Final-Review

#12574 Make cardinal splines include endpoints
  crates/bevy_math/src/cubic_splines.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Math, C-Breaking-Change

#12602 rounded border: remove dead code in shader
  crates/bevy_ui/src/render/ui.wgsl
Labels: A-UI, C-Code-Quality
