Repository bevyengine/bevy, pull requests merged in 2025-04, with the labels that each got.

#18649 Add notes to fallible commands
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#18654 Add Advice for Relocations to Migration Guide Template
  release-content/migration_guides_template.md
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#18666 Include SystemParamValidationError in RunSystemError and RegisteredSystemError
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_registry.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#18667 Update relationship commands to use `EntityCommands` instead of `Commands`
  crates/bevy_ecs/src/relationship/related_methods.rs
Labels: C-Bug, A-ECS, C-Code-Quality, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#18672 Switch ChildOf back to tuple struct
  benches/benches/bevy_ecs/entity_cloning.rs
  crates/bevy_ecs/src/entity/clone_entities.rs
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/relationship/related_methods.rs
  crates/bevy_input_focus/src/lib.rs
  crates/bevy_input_focus/src/tab_navigation.rs
  crates/bevy_picking/src/events.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_text/src/text.rs
  crates/bevy_transform/src/helper.rs
  crates/bevy_transform/src/systems.rs
  crates/bevy_ui/src/experimental/ghost_hierarchy.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/update.rs
  crates/bevy_winit/src/accessibility.rs
  examples/3d/mixed_lighting.rs
  examples/3d/visibility_range.rs
  examples/animation/gltf_skinned_mesh.rs
  examples/tools/scene_viewer/animation_plugin.rs
  examples/ui/ghost_nodes.rs
Labels: A-ECS, C-Usability

#18656 Bump crate-ci/typos from 1.30.2 to 1.31.0
  .github/workflows/ci.yml
  crates/bevy_ecs/src/event/base.rs
  crates/bevy_pbr/src/atmosphere/functions.wgsl
Labels: D-Trivial, A-Build-System, C-Dependencies, C-Code-Quality, S-Needs-Review

#18652 Fix issues in log_diagnostics example
  examples/diagnostics/log_diagnostics.rs
Labels: C-Examples, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#18675 Implement `insert_children` for `EntityCommands`
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/relationship/related_methods.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#18681 Fix indentation of `bevy/query` `strict` parameter in docs
  crates/bevy_remote/src/lib.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-Dev-Tools

#18683 Improve error message for missing events
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/event/mutator.rs
  crates/bevy_ecs/src/event/reader.rs
  crates/bevy_ecs/src/event/writer.rs
  crates/bevy_ecs/src/system/system_param.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#18621 Code quality cleanup pass for #[require]
  crates/bevy_ecs/macros/src/component.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, D-Straightforward, D-Macros

#18676 add reflect for SocketAddr
  crates/bevy_reflect/src/impls/std.rs
Labels: C-Feature, D-Trivial, S-Ready-For-Final-Review, A-Reflection, X-Uncontroversial

#18695 use entity set collections type aliases instead of defaults
  crates/bevy_ecs/src/entity/entity_set.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/entity/unique_array.rs
  crates/bevy_ecs/src/entity/unique_slice.rs
  crates/bevy_ecs/src/entity/unique_vec.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#18702 Add `#[deprecated(since = "0.16.0", ...)]` to items missing it
  crates/bevy_asset/src/handle.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/world/mod.rs
  release-content/migration_guides.md
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-Cross-Cutting

#18696 fix typo
  crates/bevy_color/src/color_ops.rs
  crates/bevy_picking/src/events.rs
  examples/transforms/transform.rs
Labels: C-Docs, D-Trivial, A-Cross-Cutting, S-Needs-Review

#18718 Add `PartialEq` and `Hash` reflections for `AnimationNodeIndex`
  crates/bevy_animation/src/lib.rs
  crates/bevy_reflect/src/impls/petgraph.rs
Labels: D-Trivial, C-Usability, A-Reflection, S-Needs-Review

#18712 Fix motion blur on skinned meshes
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/mesh.rs
Labels: C-Bug, A-Rendering

#18693 Add accessors to `DynamicEnum` for the `DynamicVariant`
  crates/bevy_reflect/src/enums/dynamic_enum.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection, D-Straightforward

#18721 Expose `TextureFormatFeatureFlags`, `TextureFormatFeatures` from wgpu
  crates/bevy_render/src/render_resource/mod.rs
Labels: D-Trivial, A-Rendering, C-Usability, S-Ready-For-Final-Review

#18731 Add `Default` for all schedule labels
  crates/bevy_app/src/main_schedule.rs
  crates/bevy_remote/src/lib.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_state/src/state/transitions.rs
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-App

#18694 Newtype `hashbrown`
  crates/bevy_picking/src/hover.rs
  crates/bevy_platform_support/Cargo.toml
  crates/bevy_platform_support/src/collections.rs
  crates/bevy_platform_support/src/collections/hash_map.rs
  crates/bevy_platform_support/src/collections/hash_set.rs
  crates/bevy_platform_support/src/collections/hash_table.rs
  crates/bevy_platform_support/src/collections/mod.rs
  crates/bevy_scene/src/scene_spawner.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, P-Regression, M-Needs-Migration-Guide, A-Utils, X-Contentious, D-Modest

#18715 Fix `many_foxes` + motion blur = crash on WebGL
  crates/bevy_pbr/src/render/skin.rs
Labels: C-Bug, A-Rendering

#18727 Remove WebGL padding from `MotionBlur`
  crates/bevy_core_pipeline/src/motion_blur/mod.rs
  crates/bevy_core_pipeline/src/motion_blur/node.rs
  crates/bevy_core_pipeline/src/motion_blur/pipeline.rs
  examples/3d/motion_blur.rs
Labels: A-Rendering, C-Code-Quality, O-WebGL2, X-Uncontroversial, D-Straightforward, S-Needs-Review

#18582 Web support for atmosphere
  crates/bevy_pbr/src/atmosphere/functions.wgsl
  crates/bevy_pbr/src/atmosphere/mod.rs
  crates/bevy_pbr/src/atmosphere/render_sky.wgsl
  crates/bevy_pbr/src/atmosphere/resources.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, O-WebGPU, D-Straightforward

#18754 clarified docs for bundle removal commands
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: C-Docs, D-Trivial, A-ECS, S-Ready-For-Final-Review

#18706 Fix AccessKit node bounds
  crates/bevy_ui/src/accessibility.rs
Labels: C-Bug, A-Accessibility, A-UI, S-Ready-For-Final-Review

#18746 Expose the added tick for change detection, both getting and setting.
  crates/bevy_ecs/src/change_detection.rs
Labels: C-Feature, D-Trivial, A-ECS, S-Ready-For-Final-Review

#18699 Change with_related to work with a Bundle and added with_relationships method
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/relationship/related_methods.rs
  crates/bevy_ecs/src/spawn.rs
  examples/ecs/relationships.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#18025 Add bindless support back to `ExtendedMaterial`.
  Cargo.toml
  assets/shaders/extended_material_bindless.wgsl
  crates/bevy_pbr/src/extended_material.rs
  crates/bevy_pbr/src/material_bind_groups.rs
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/render_resource/bindless.rs
  examples/README.md
  examples/shader/extended_material_bindless.rs
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review

#18761 Fix unbatchable meshes.
  crates/bevy_render/src/render_phase/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#18752 Fix `get_render_pipeline_state` / `get_compute_pipeline_state` panic
  crates/bevy_render/src/render_resource/pipeline_cache.rs
Labels: C-Bug, D-Trivial, A-Rendering, P-Crash, S-Ready-For-Final-Review

#18771 Make the `StandardMaterial` bindless index table have a fixed size regardless of the features that are enabled.
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/render/pbr_bindings.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#18587 Add binned 2d/3d Wireframe render phase
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_pbr/src/render/wireframe.wgsl
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_sprite/src/mesh2d/wireframe2d.rs
  crates/bevy_sprite/src/mesh2d/wireframe2d.wgsl
  examples/2d/2d_shapes.rs
  examples/2d/wireframe_2d.rs
  examples/3d/3d_shapes.rs
  examples/3d/wireframe.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, D-Complex, D-Shaders

#18772 Fix forward decal depth_fade_factor.
  crates/bevy_pbr/src/decal/forward.rs
  crates/bevy_pbr/src/decal/forward_decal.wgsl
Labels: C-Bug, A-Rendering, D-Straightforward, S-Needs-Review

#18768 Small docs PR for `PointLightShadowMap`/`DirectionalLightShadowMap`
  crates/bevy_pbr/src/light/directional_light.rs
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/light/point_light.rs
Labels: C-Docs, A-Rendering, S-Needs-Review

#18783 Add `?`
  crates/bevy_input/Cargo.toml
Labels: C-Bug, D-Trivial, A-Input, P-Compile-Failure, X-Uncontroversial, S-Needs-Review, O-Embedded

#18791 Fix newline in `PointLightShadowMap` comment
  crates/bevy_pbr/src/light/mod.rs
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#18794 Make some changes to the migration guide recommendations
  release-content/migration_guides.md
  release-content/migration_guides_template.md
Labels: C-Docs, S-Ready-For-Final-Review, A-Cross-Cutting, D-Straightforward

#18438 Fix documentation: incorrect references to the `Update` schedule in `ExitCondition`
  crates/bevy_window/src/lib.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#18798 Ignore RenderEntity during entity clones
  crates/bevy_render/src/sync_world.rs
Labels: C-Bug, A-Rendering, A-ECS, S-Ready-For-Final-Review

#18785 Fix system param validation for piped systems
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/system/combinator.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, X-Contentious, D-Straightforward

#18769 Allowlist mali drivers for gpu preprocessing support.
  crates/bevy_core_pipeline/src/experimental/mip_generation/mod.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/lib.rs
Labels: C-Bug, A-Rendering, O-Android, S-Needs-Review

#18782 Allow partial support for `bevy_log` in `no_std`
  Cargo.toml
  crates/bevy_animation/Cargo.toml
  crates/bevy_dylib/src/lib.rs
  crates/bevy_gltf/Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_internal/src/lib.rs
  crates/bevy_internal/src/prelude.rs
  crates/bevy_log/Cargo.toml
  crates/bevy_log/src/android_tracing.rs
  crates/bevy_log/src/lib.rs
  crates/bevy_log/src/plugin.rs
  crates/bevy_text/Cargo.toml
  crates/bevy_transform/Cargo.toml
  crates/bevy_winit/Cargo.toml
  docs/cargo_features.md
Labels: C-Feature, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Utils, X-Contentious, D-Straightforward, O-Embedded

#18807 don't disable std in bevy_dylib
  crates/bevy_dylib/src/lib.rs
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, P-Compile-Failure

#18814 Mark render assets as modified when removed from the asset server
  crates/bevy_render/src/render_asset.rs
Labels: C-Bug, A-Rendering, S-Needs-Review

#18836 Make sure the mesh actually exists before we try to specialize.
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/wireframe2d.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#18804 Use never_say_never hack to work around Rust 2024 regression for fn traits
  crates/bevy_ecs/src/error/command_handling.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/never.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/observer_system.rs
  crates/bevy_ecs/src/system/schedule_system.rs
Labels: C-Bug, A-ECS, D-Complex, X-Blessed, S-Needs-Review

#18824 Fix wrong method call in relationship replacement command
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/relationship/related_methods.rs
Labels: C-Bug, A-ECS, S-Needs-Review

#18826 Expose the output curve type in with_derivative
  crates/bevy_math/src/common_traits.rs
  crates/bevy_math/src/curve/derivatives/mod.rs
Labels: C-Bug, D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Math

#18828 Don't restrict the scene viewer to loading assets from approved paths.
  examples/tools/scene_viewer/main.rs
Labels: C-Examples, A-Assets, S-Needs-Review

#18835 Add `remove_children` and `remove_related` to `EntityWorldMut` and `EntityCommands`
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/relationship/related_methods.rs
Labels: C-Bug, A-ECS, S-Needs-Review

#18825 Fix the ordering of the systems introduced in #18734.
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/meshlet/instance_manager.rs
  crates/bevy_pbr/src/render/mesh.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#18833 Panic on overlapping one-to-one relationships
  crates/bevy_ecs/src/relationship/relationship_source_collection.rs
Labels: C-Bug, A-ECS

#18845 Revert attempt to fix memory leak
  crates/bevy_render/src/render_asset.rs
Labels: C-Bug, A-Rendering, S-Needs-Review

#18846 Swap order of eviction/extraction when extracting for specialization
  crates/bevy_pbr/src/material.rs
  crates/bevy_sprite/src/mesh2d/material.rs
Labels: C-Bug, A-Rendering, S-Needs-Review

#18891 don't overflow when relations are empty
  crates/bevy_ecs/src/relationship/relationship_source_collection.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#18926 Fix minor typo on `bevy_ecs` example
  crates/bevy_ecs/examples/events.rs
Labels: D-Trivial, A-ECS, C-Examples, S-Ready-For-Final-Review

#18924 Remove unused query param
  crates/bevy_ui/src/picking_backend.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Picking

#18839 Make the example android app explicitly handle some device config change events to avoid getting the activity destroyed
  examples/mobile/android_example/app/src/main/AndroidManifest.xml
  examples/mobile/android_example_native/app/src/main/AndroidManifest.xml
Labels: C-Bug, C-Examples, O-Android, S-Ready-For-Final-Review

#18850 `FontAtlasSet` fixes
  crates/bevy_text/src/font_atlas_set.rs
Labels: C-Bug, C-Docs, S-Ready-For-Final-Review, A-Text

#18899 Create `EntityCommands::remove_if`
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#18651 Update cosmic-text to 0.14
  crates/bevy_text/Cargo.toml
  crates/bevy_text/src/pipeline.rs
Labels: D-Trivial, C-Dependencies, S-Ready-For-Final-Review, A-Text

#18951 Fix game_of_life shader relying on Naga bug
  assets/shaders/game_of_life.wgsl
Labels: C-Bug, A-Rendering, S-Needs-Review

#18655 Update spin requirement from 0.9.8 to 0.10.0
  crates/bevy_platform/Cargo.toml
Labels: D-Trivial, C-Dependencies, S-Ready-For-Final-Review, A-Utils, O-Embedded

#18870 Removed conversion from pointer physical coordinates to viewport local coordinates in bevy_picking make_ray function
  crates/bevy_picking/src/backend.rs
Labels: C-Bug, A-Picking

#18938 Fully qualify crate paths in `BevyManifest`
  crates/bevy_macro_utils/src/bevy_manifest.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Utils

#18832 Fixes #15389, added docs to RawHandleWrapper::_window field
  crates/bevy_window/src/raw_handle.rs
Labels: C-Docs, A-Windowing, S-Ready-For-Final-Review

#18827 Added derive Reflect to UntypedHandle and UntypedAssetId
  crates/bevy_asset/src/handle.rs
  crates/bevy_asset/src/id.rs
Labels: C-Feature, A-Assets, S-Ready-For-Final-Review, A-Reflection

#18688 Make `AccessConflicts::is_empty` public
  crates/bevy_ecs/src/query/access.rs
Labels: D-Trivial, A-ECS, S-Ready-For-Final-Review

#18988 fix new nightly lint on mikktspace
  crates/bevy_mikktspace/src/generated.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review

#19002 Fix a few subcrate import paths in examples
  examples/camera/custom_projection.rs
  examples/diagnostics/log_diagnostics.rs
  examples/ui/directional_navigation.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#18907 Add a method to clear all related entity to `EntityCommands` and friends
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/relationship/related_methods.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#18935 Change the default visual box for `OverflowClipMargin` to `PaddingBox`
  crates/bevy_ui/src/ui_node.rs
  release-content/migration-guides/overflowclipbox_default_is_now_paddingbox.md
Labels: C-Bug, D-Trivial, A-UI, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#18729 Expose deferred screen edges setting for ios devices
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/converters.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/mobile/src/lib.rs
Labels: A-Windowing, O-iOS, S-Ready-For-Final-Review, D-Straightforward
