Repository bevyengine/bevy, pull requests merged in 2025-08, with the labels that each got.

#20359 use transpose not inverse in shadow map transform
  crates/bevy_light/src/cascade.rs
Labels: A-Rendering, S-Needs-Review

#19232 enable wayland by default
  .github/actions/install-linux-deps/action.yml
  Cargo.toml
  docs/cargo_features.md
Labels: D-Trivial, A-Rendering, C-Usability, X-Controversial, S-Waiting-on-Author, S-Needs-SME

#20346 Side: Fix `ci` tool when running with `--test-threads`
  tools/ci/src/commands/test.rs
Labels: A-Build-System, S-Ready-For-Final-Review, C-Testing, D-Straightforward

#20388 dont depend on bevy_render in bevy_scene
  crates/bevy_gltf/Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_scene/Cargo.toml
  crates/bevy_scene/src/components.rs
Labels: D-Trivial, A-Rendering, C-Dependencies, S-Ready-For-Final-Review, A-Scenes

#20369 Clean `bevy_tasks` features (Adopted)
  crates/bevy_app/Cargo.toml
  crates/bevy_asset/Cargo.toml
  crates/bevy_diagnostic/Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_platform/Cargo.toml
  crates/bevy_platform/src/lib.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/src/executor.rs
  crates/bevy_tasks/src/futures.rs
  crates/bevy_tasks/src/lib.rs
  crates/bevy_tasks/src/single_threaded_task_pool.rs
  crates/bevy_tasks/src/usages.rs
  crates/bevy_tasks/src/wasm_task.rs
  crates/bevy_transform/Cargo.toml
  crates/bevy_winit/Cargo.toml
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Tasks, D-Straightforward

#20339 Reflect non-callback components and resources in bevy_core_widgets and bevy_feathers
  crates/bevy_core_widgets/Cargo.toml
  crates/bevy_core_widgets/src/callback.rs
  crates/bevy_core_widgets/src/core_radio.rs
  crates/bevy_core_widgets/src/core_scrollbar.rs
  crates/bevy_core_widgets/src/core_slider.rs
  crates/bevy_feathers/src/alpha_pattern.rs
  crates/bevy_feathers/src/controls/button.rs
  crates/bevy_feathers/src/controls/checkbox.rs
  crates/bevy_feathers/src/controls/color_swatch.rs
  crates/bevy_feathers/src/controls/radio.rs
  crates/bevy_feathers/src/controls/slider.rs
  crates/bevy_feathers/src/controls/toggle_switch.rs
  crates/bevy_feathers/src/cursor.rs
  crates/bevy_feathers/src/font_styles.rs
  crates/bevy_feathers/src/handle_or_path.rs
  crates/bevy_feathers/src/theme.rs
Labels: A-UI, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#20392 fix some camera component links
  crates/bevy_camera/src/camera.rs
  crates/bevy_camera/src/primitives.rs
Labels: A-Rendering, S-Needs-Review

#20361 add ref doc and extract a couple vars and skip a sqrt in shadow cascades
  crates/bevy_light/src/cascade.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#20403 MainPassResolutionOverride changes
  crates/bevy_camera/src/camera.rs
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transmissive_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transparent_pass_3d_node.rs
  crates/bevy_core_pipeline/src/deferred/node.rs
  crates/bevy_core_pipeline/src/oit/resolve/node.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_pbr/src/meshlet/material_shade_nodes.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/view.wgsl
  crates/bevy_solari/src/realtime/node.rs
  crates/bevy_solari/src/realtime/prepare.rs
  crates/bevy_solari/src/realtime/restir_di.wgsl
  crates/bevy_solari/src/realtime/restir_gi.wgsl
  examples/shader/custom_render_phase.rs
Labels: A-Rendering, S-Ready-For-Final-Review, D-Straightforward

#20360 use iterators and zip instead of enumeration and indexing in shadow map cascades
  crates/bevy_light/src/cascade.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20423 Improve `WithRelated` ergonomics
  crates/bevy_ecs/src/spawn.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review, D-Domain-Agnostic

#20428 Fix examples REAMDE markdown
  docs-template/EXAMPLE_README.md.tpl
  examples/README.md
Labels: C-Docs, D-Trivial, C-Examples, S-Ready-For-Final-Review

#20419 use the wasm-release profile for smaller bins and longer builds
  tools/build-wasm-example/src/main.rs
Labels: A-Build-System, S-Ready-For-Final-Review

#20415 Move advanced shader examples to separate category
  Cargo.toml
  examples/README.md
  examples/shader_advanced/custom_phase_item.rs
  examples/shader_advanced/custom_post_processing.rs
  examples/shader_advanced/custom_render_phase.rs
  examples/shader_advanced/custom_shader_instancing.rs
  examples/shader_advanced/custom_vertex_attribute.rs
  examples/shader_advanced/specialized_mesh_pipeline.rs
  examples/shader_advanced/texture_binding_array.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review, D-Straightforward

#20417 `CubicSegment::iter_uniformly` should be public
  crates/bevy_math/src/cubic_splines/mod.rs
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Math

#20416 Fix security issues on actions
  .github/workflows/ci.yml
  .github/workflows/dependencies.yml
  .github/workflows/example-run-report.yml
  .github/workflows/example-run.yml
  .github/workflows/send-screenshots-to-pixeleagle.yml
  .github/workflows/update-caches.yml
  .github/workflows/validation-jobs.yml
  .github/workflows/weekly.yml
Labels: A-Build-System, S-Ready-For-Final-Review, D-Straightforward

#20401 Fix full_ui example overflowing scroll position
  examples/testbed/full_ui.rs
Labels: D-Trivial, C-Examples, A-UI, S-Ready-For-Final-Review

#20362 Use the default directional light intensity constant
  examples/3d/shadow_biases.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20363 Add light_consts::lumens::VERY_LARGE_CINEMA_LIGHT
  crates/bevy_light/src/lib.rs
  crates/bevy_light/src/point_light.rs
  examples/3d/shadow_biases.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20107 Clean up specialized_mesh_pipeline
  examples/shader_advanced/specialized_mesh_pipeline.rs
Labels: C-Bug, A-Rendering, C-Examples, O-Web, S-Ready-For-Final-Review, D-Straightforward

#20288 Remove generic parameter from `Access`, since it's always `ComponentId`
  crates/bevy_asset/src/asset_changed.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/macros/src/query_data.rs
  crates/bevy_ecs/macros/src/world_query.rs
  crates/bevy_ecs/src/entity_disabling.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/lifecycle.rs
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/query/builder.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/query/world_query.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/node.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/schedule_system.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_name.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/filtered_resource.rs
  crates/bevy_ecs/src/world/identifier.rs
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_render/src/extract_param.rs
  crates/bevy_render/src/sync_world.rs
  release-content/migration-guides/non-generic-access.md
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#20424 Implement field_at[_mut] for Struct DynamicVariant
  crates/bevy_reflect/src/enums/dynamic_enum.rs
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, A-Reflection

#20422 Color sliders
  crates/bevy_feathers/src/controls/color_slider.rs
  crates/bevy_feathers/src/controls/mod.rs
  examples/ui/feathers.rs
  release-content/release-notes/feathers.md
Labels: C-Feature, A-UI, S-Ready-For-Final-Review, A-Editor, M-Needs-Release-Note

#20433 Make `HierarchyPropagatePlugin` scheduling configurable
  crates/bevy_app/src/propagate.rs
  crates/bevy_feathers/src/lib.rs
Labels: C-Usability, A-App, X-Contentious, D-Straightforward, S-Needs-Review

#19011 Improve error for when you try running a one-shot system with wrong `SystemId` type
  crates/bevy_ecs/src/system/system_registry.rs
  release-content/migration-guides/incorrect-type-error-on-run-system-command.md
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Uncontroversial, D-Straightforward

#20348 `spec_v2` style and patterns
  crates/bevy_render/macros/src/specializer.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_resource/bind_group_layout.rs
  crates/bevy_render/src/render_resource/pipeline.rs
  crates/bevy_render/src/render_resource/specializer.rs
  examples/shader_advanced/custom_phase_item.rs
  release-content/migration-guides/composable_specialization.md
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, D-Modest

#20431 try to fix GitHub Actions permissions
  .github/workflows/example-run-report.yml
Labels: C-Bug, D-Trivial, A-Build-System, S-Ready-For-Final-Review

#20458 Update docs to use MATERIAL_BIND_GROUP
  crates/bevy_pbr/src/material.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  examples/shader_advanced/texture_binding_array.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20448 Add VERBOSE_SHADER_ERROR
  crates/bevy_render/src/render_resource/pipeline_cache.rs
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review, A-Diagnostics

#20470 stop re-exporting RenderAssetUsages from bevy_render
  crates/bevy_render/src/erased_render_asset.rs
  release-content/migration-guides/bevy_render_reorganization.md
Labels: D-Trivial, A-Rendering, A-Assets, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#20469 add module doc to bevy_render
  crates/bevy_render/src/lib.rs
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#20471 Make bevy_picking not depend on bevy_render
  crates/bevy_camera/src/camera.rs
  crates/bevy_core_pipeline/src/oit/mod.rs
  crates/bevy_picking/Cargo.toml
  crates/bevy_picking/src/backend.rs
  crates/bevy_picking/src/events.rs
  crates/bevy_picking/src/hover.rs
  crates/bevy_picking/src/input.rs
  crates/bevy_picking/src/mesh_picking/mod.rs
  crates/bevy_picking/src/mesh_picking/ray_cast/mod.rs
  crates/bevy_picking/src/pointer.rs
  crates/bevy_picking/src/window.rs
  crates/bevy_render/src/camera.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_ui/src/focus.rs
  release-content/migration-guides/bevy_render_reorganization.md
Labels: A-Rendering, S-Ready-For-Final-Review

#20472 Make bevy_animation not depend on bevy_render
  crates/bevy_animation/Cargo.toml
  crates/bevy_animation/src/lib.rs
  crates/bevy_mesh/src/lib.rs
  crates/bevy_render/src/mesh/mod.rs
Labels: A-Rendering, C-Dependencies, C-Performance, S-Ready-For-Final-Review, A-Animation

#20473 Stop using mesh re-exports in-repo and add bevy_mesh prelude
  crates/bevy_gizmos/Cargo.toml
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_internal/src/prelude.rs
  crates/bevy_mesh/src/lib.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/decal/forward.rs
  crates/bevy_pbr/src/extended_material.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/meshlet/material_pipeline_prepare.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_bindings.rs
  crates/bevy_pbr/src/render/morph.rs
  crates/bevy_pbr/src/render/skin.rs
  crates/bevy_pbr/src/volumetric_fog/mod.rs
  crates/bevy_pbr/src/volumetric_fog/render.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/mesh/allocator.rs
  crates/bevy_render/src/mesh/mod.rs
  crates/bevy_render/src/render_resource/mod.rs
  crates/bevy_render/src/render_resource/pipeline.rs
  crates/bevy_render/src/render_resource/pipeline_specializer.rs
  crates/bevy_sprite/Cargo.toml
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/mesh2d/wireframe2d.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_sprite/src/tilemap_chunk/mod.rs
  crates/bevy_ui_render/Cargo.toml
  crates/bevy_ui_render/src/box_shadow.rs
  crates/bevy_ui_render/src/gradient.rs
  crates/bevy_ui_render/src/pipeline.rs
  crates/bevy_ui_render/src/ui_material_pipeline.rs
  crates/bevy_ui_render/src/ui_texture_slice_pipeline.rs
  examples/2d/custom_gltf_vertex_attribute.rs
  examples/2d/mesh2d_arcs.rs
  examples/2d/mesh2d_manual.rs
  examples/3d/generate_custom_mesh.rs
  examples/3d/lines.rs
  examples/3d/query_gltf_primitives.rs
  examples/3d/vertex_colors.rs
  examples/animation/custom_skinned_mesh.rs
  examples/animation/gltf_skinned_mesh.rs
  examples/asset/alter_mesh.rs
  examples/math/custom_primitives.rs
  examples/math/random_sampling.rs
  examples/shader/automatic_instancing.rs
  examples/shader/extended_material_bindless.rs
  examples/shader/shader_defs.rs
  examples/shader/storage_buffer.rs
  examples/shader_advanced/custom_phase_item.rs
  examples/shader_advanced/custom_render_phase.rs
  examples/shader_advanced/custom_shader_instancing.rs
  examples/shader_advanced/custom_vertex_attribute.rs
  examples/shader_advanced/specialized_mesh_pipeline.rs
  tests/3d/test_invalid_skinned_mesh.rs
Labels: A-Rendering, C-Dependencies, C-Code-Quality, S-Ready-For-Final-Review

#20477 Use bevy::camera in examples instead of bevy::render::camera re-export
  examples/2d/2d_viewport_to_world.rs
  examples/2d/pixel_grid_snap.rs
  examples/3d/atmosphere.rs
  examples/3d/camera_sub_view.rs
  examples/3d/depth_of_field.rs
  examples/3d/lighting.rs
  examples/3d/order_independent_transparency.rs
  examples/3d/orthographic.rs
  examples/3d/pbr.rs
  examples/3d/render_to_texture.rs
  examples/3d/split_screen.rs
  examples/3d/transmission.rs
  examples/3d/visibility_range.rs
  examples/app/headless_renderer.rs
  examples/camera/2d_on_ui.rs
  examples/camera/custom_projection.rs
  examples/camera/first_person_view_model.rs
  examples/camera/projection_zoom.rs
  examples/gizmos/axes.rs
  examples/math/custom_primitives.rs
  examples/shader_advanced/custom_phase_item.rs
  examples/shader_advanced/custom_render_phase.rs
  examples/shader_advanced/custom_shader_instancing.rs
  examples/shader_advanced/specialized_mesh_pipeline.rs
  examples/stress_tests/many_cameras_lights.rs
  examples/stress_tests/many_cubes.rs
  examples/stress_tests/many_lights.rs
  examples/stress_tests/many_text2d.rs
  examples/testbed/ui.rs
  examples/tools/scene_viewer/main.rs
  examples/ui/directional_navigation.rs
  examples/ui/relative_cursor_position.rs
  examples/ui/render_ui_to_texture.rs
  examples/ui/viewport_node.rs
  examples/window/monitor_info.rs
  examples/window/multiple_windows.rs
  tests/3d/test_invalid_skinned_mesh.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20478 Use bevy_camera in ui, sprite, text instead of bevy_render::camera re-export
  crates/bevy_sprite/Cargo.toml
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/mesh2d/wireframe2d.rs
  crates/bevy_sprite/src/picking_backend.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_text/Cargo.toml
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/Cargo.toml
  crates/bevy_ui/src/accessibility.rs
  crates/bevy_ui/src/experimental/ghost_hierarchy.rs
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/picking_backend.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/update.rs
  crates/bevy_ui/src/widget/viewport.rs
  crates/bevy_ui_render/Cargo.toml
  crates/bevy_ui_render/src/box_shadow.rs
  crates/bevy_ui_render/src/lib.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#20480 Use bevy_camera in aa, feathers, gizmos, gltf instead of bevy_render::camera re-export
  crates/bevy_anti_aliasing/Cargo.toml
  crates/bevy_anti_aliasing/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_anti_aliasing/src/fxaa/mod.rs
  crates/bevy_anti_aliasing/src/taa/mod.rs
  crates/bevy_feathers/Cargo.toml
  crates/bevy_feathers/src/controls/checkbox.rs
  crates/bevy_feathers/src/controls/radio.rs
  crates/bevy_gizmos/Cargo.toml
  crates/bevy_gizmos/src/aabb.rs
  crates/bevy_gizmos/src/config.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_gizmos/src/retained.rs
  crates/bevy_gltf/src/loader/mod.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20479 Use bevy_camera in pbr, core pipelines, render instead of bevy_render::camera re-export
  crates/bevy_core_pipeline/src/bloom/settings.rs
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transmissive_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transparent_pass_3d_node.rs
  crates/bevy_core_pipeline/src/deferred/node.rs
  crates/bevy_core_pipeline/src/dof/mod.rs
  crates/bevy_core_pipeline/src/motion_blur/mod.rs
  crates/bevy_core_pipeline/src/oit/mod.rs
  crates/bevy_core_pipeline/src/oit/resolve/node.rs
  crates/bevy_core_pipeline/src/post_process/mod.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_core_pipeline/src/upscaling/mod.rs
  crates/bevy_core_pipeline/src/upscaling/node.rs
  crates/bevy_pbr/src/atmosphere/mod.rs
  crates/bevy_pbr/src/atmosphere/resources.rs
  crates/bevy_pbr/src/decal/clustered.rs
  crates/bevy_pbr/src/fog.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/lightmap/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/meshlet/material_pipeline_prepare.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/morph.rs
  crates/bevy_pbr/src/render/skin.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_pbr/src/ssr/mod.rs
  crates/bevy_pbr/src/volumetric_fog/render.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/render_graph/camera_driver_node.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/window/screenshot.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20465 Update documentation of HitData coordinates range in ui::picking_backend
  crates/bevy_ui/src/picking_backend.rs
Labels: C-Docs, D-Trivial, A-UI, S-Ready-For-Final-Review, A-Picking

#20483 Add a prelude to bevy_camera
  crates/bevy_camera/src/lib.rs
  crates/bevy_internal/src/prelude.rs
Labels: D-Trivial, A-Rendering, C-Usability, S-Ready-For-Final-Review

#20406 Solari radiance cache
  crates/bevy_pbr/src/render/utils.wgsl
  crates/bevy_solari/src/realtime/mod.rs
  crates/bevy_solari/src/realtime/node.rs
  crates/bevy_solari/src/realtime/prepare.rs
  crates/bevy_solari/src/realtime/restir_gi.wgsl
  crates/bevy_solari/src/realtime/world_cache_compact.wgsl
  crates/bevy_solari/src/realtime/world_cache_query.wgsl
  crates/bevy_solari/src/realtime/world_cache_update.wgsl
  release-content/release-notes/bevy_solari.md
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, D-Complex

#20486 Use bevy_camera in solari, meshlets, dev_tools, clustering, pcss instead of bevy_render::camera re-export
  crates/bevy_dev_tools/Cargo.toml
  crates/bevy_dev_tools/src/fps_overlay.rs
  crates/bevy_dev_tools/src/picking_debug.rs
  crates/bevy_pbr/src/meshlet/instance_manager.rs
  crates/bevy_pbr/src/meshlet/material_pipeline_prepare.rs
  crates/bevy_pbr/src/meshlet/material_shade_nodes.rs
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/meshlet/resource_manager.rs
  crates/bevy_solari/Cargo.toml
  crates/bevy_solari/src/pathtracer/extract.rs
  crates/bevy_solari/src/realtime/extract.rs
  crates/bevy_solari/src/realtime/prepare.rs
  crates/bevy_ui_render/src/debug_overlay.rs
  examples/3d/clustered_decals.rs
  examples/3d/light_textures.rs
  examples/3d/pcss.rs
  examples/3d/solari.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20488 Use bevy_light in pbr instead of bevy_pbr::light re-export + add bevy_light prelude
  benches/Cargo.toml
  benches/benches/bevy_render/render_layers.rs
  crates/bevy_core_pipeline/src/motion_blur/mod.rs
  crates/bevy_gizmos/Cargo.toml
  crates/bevy_gizmos/src/light.rs
  crates/bevy_internal/src/prelude.rs
  crates/bevy_light/src/lib.rs
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/meshlet/instance_manager.rs
  crates/bevy_pbr/src/meshlet/material_pipeline_prepare.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_pbr/src/volumetric_fog/render.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#20352 Fix UB, panic and compiler error in `bevy_tasks`
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/src/lib.rs
  crates/bevy_tasks/src/single_threaded_task_pool.rs
  crates/bevy_tasks/src/task.rs
  crates/bevy_tasks/src/wasm_task.rs
Labels: P-Crash, S-Ready-For-Final-Review, A-Tasks, D-Complex, P-Compile-Failure, P-Unsound, D-Unsafe, D-Async

#20156 Optimize solari initial and temporal DI
  crates/bevy_solari/src/realtime/node.rs
  crates/bevy_solari/src/realtime/prepare.rs
  crates/bevy_solari/src/realtime/restir_di.wgsl
  crates/bevy_solari/src/scene/raytracing_scene_bindings.wgsl
  release-content/release-notes/bevy_solari.md
Labels: C-Bug, A-Rendering, C-Performance, S-Ready-For-Final-Review, M-Needs-Release-Note

#20461 Fix panic in `FpsOverlay` with disabled `FrameTimeGraph`
  crates/bevy_dev_tools/src/fps_overlay.rs
Labels: P-Crash, S-Ready-For-Final-Review, A-Dev-Tools, D-Straightforward

#20496 Fix doc paths to not use deprecated re-exports
  crates/bevy_anti_aliasing/src/fxaa/mod.rs
  crates/bevy_anti_aliasing/src/smaa/mod.rs
  crates/bevy_anti_aliasing/src/taa/mod.rs
  crates/bevy_core_pipeline/src/dof/mod.rs
  crates/bevy_core_pipeline/src/msaa_writeback.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_mesh/src/components.rs
  crates/bevy_pbr/src/light_probe/environment_map.rs
  crates/bevy_pbr/src/lightmap/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/mesh_material.rs
  crates/bevy_pbr/src/meshlet/asset.rs
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/render/mesh_bindings.rs
  crates/bevy_pbr/src/ssr/mod.rs
  crates/bevy_pbr/src/volumetric_fog/mod.rs
  crates/bevy_remote/src/lib.rs
  crates/bevy_render/src/camera.rs
  crates/bevy_render/src/experimental/occlusion_culling/mod.rs
  crates/bevy_render/src/globals.rs
  crates/bevy_render/src/renderer/render_device.rs
  crates/bevy_render/src/texture/manual_texture_view.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/ui_node.rs
  examples/3d/meshlet.rs
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#20498 Yeet RenderAssetUsages re-export
  crates/bevy_core_pipeline/src/auto_exposure/compensation_curve.rs
  crates/bevy_core_pipeline/src/post_process/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_pbr/src/light_probe/generate.rs
  crates/bevy_render/src/render_asset.rs
  crates/bevy_render/src/storage.rs
  crates/bevy_render/src/texture/fallback_image.rs
  crates/bevy_render/src/texture/gpu_image.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_text/src/font_atlas.rs
  crates/bevy_text/src/font_atlas_set.rs
  examples/2d/cpu_draw.rs
  examples/2d/mesh2d_manual.rs
  examples/3d/3d_shapes.rs
  examples/3d/anti_aliasing.rs
  examples/3d/generate_custom_mesh.rs
  examples/3d/lines.rs
  examples/3d/motion_blur.rs
  examples/animation/custom_skinned_mesh.rs
  examples/asset/alter_mesh.rs
  examples/asset/alter_sprite.rs
  examples/math/custom_primitives.rs
  examples/shader/compute_shader_game_of_life.rs
  examples/shader/gpu_readback.rs
  examples/shader_advanced/specialized_mesh_pipeline.rs
  examples/stress_tests/bevymark.rs
  examples/stress_tests/many_cubes.rs
  examples/ui/render_ui_to_texture.rs
  tests/3d/test_invalid_skinned_mesh.rs
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review

#20501 Fix release content metadata
  release-content/migration-guides/LightVisibilityClass_rename.md
  release-content/migration-guides/UI_scroll_position_is_now_logical.md
  release-content/migration-guides/anchor_is_removed_from_sprite.md
  release-content/migration-guides/animation_graph_no_more_asset_ids.md
  release-content/migration-guides/bevy_render_reorganization.md
  release-content/migration-guides/bevy_ui_render_crate.md
  release-content/migration-guides/border_color_all_takes_impl_into_color.md
  release-content/migration-guides/check_change_ticks.md
  release-content/migration-guides/component_entry.md
  release-content/migration-guides/extract_fn_is_mut.md
  release-content/migration-guides/fullscreen_shader_resource.md
  release-content/migration-guides/handle_weak_replaced_with_handle_uuid.md
  release-content/migration-guides/labeled_asset_scope_errors.md
  release-content/migration-guides/map_set_apply.md
  release-content/migration-guides/non-generic-access.md
  release-content/migration-guides/reflect_asset_asset_ids.md
  release-content/migration-guides/remove_cosmic_text_reexports.md
  release-content/migration-guides/render_graph_app_to_ext.md
  release-content/migration-guides/scalar-field-on-vector-space.md
  release-content/migration-guides/scene_spawner_api.md
  release-content/migration-guides/textshadow_is_moved_to_widget_text_module.md
  release-content/migration-guides/wgpu_25.md
  release-content/release-notes/bevy_ui_render_crate.md
  release-content/release-notes/render_startup.md
  release-content/release-notes/viewport-node.md
Labels: C-Bug, D-Trivial, A-Meta, S-Ready-For-Final-Review

#20457 Solari BLAS compaction
  crates/bevy_solari/src/lib.rs
  crates/bevy_solari/src/scene/blas.rs
  crates/bevy_solari/src/scene/mod.rs
  release-content/release-notes/bevy_solari.md
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#20514 Bump crate-ci/typos from 1.34.0 to 1.35.3
  .github/workflows/ci.yml
  crates/bevy_ecs/src/system/builder.rs
Labels: C-Docs, D-Trivial, A-Build-System, S-Needs-Review

#20516 Fix latest lints for rust beta
  crates/bevy_animation/src/gltf_curves.rs
  crates/bevy_anti_aliasing/src/taa/mod.rs
  crates/bevy_image/src/basis.rs
  crates/bevy_mesh/src/mesh.rs
  crates/bevy_mesh/src/primitives/dim2.rs
  crates/bevy_pbr/src/meshlet/persistent_buffer.rs
  crates/bevy_pbr/src/render/morph.rs
  crates/bevy_render/src/render_resource/bind_group_entries.rs
  crates/bevy_tasks/src/task_pool.rs
  examples/app/headless.rs
  examples/async_tasks/async_compute.rs
  examples/ecs/nondeterministic_system_order.rs
Labels: C-Code-Quality

#20522 Fix rotation matrix construction from `Rot2`
  crates/bevy_math/src/rotation2d.rs
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, A-Math, X-Uncontroversial

#20466 Update Game of Life compute example to include a uniform buffer variable
  assets/shaders/game_of_life.wgsl
  examples/shader/compute_shader_game_of_life.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review, X-Contentious

#20525 Add migration guide for #20522
  release-content/migration-guides/rot2_matrix_construction.md
Labels: D-Trivial, S-Ready-For-Final-Review, A-Math, X-Uncontroversial

#20502 Make bevy_ui not depend on bevy_render
  crates/bevy_animation/src/lib.rs
  crates/bevy_anti_aliasing/Cargo.toml
  crates/bevy_camera/src/lib.rs
  crates/bevy_camera/src/projection.rs
  crates/bevy_core_pipeline/Cargo.toml
  crates/bevy_image/src/image.rs
  crates/bevy_image/src/lib.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_mesh/src/lib.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/mesh/mod.rs
  crates/bevy_render/src/render_resource/texture.rs
  crates/bevy_render/src/texture/mod.rs
  crates/bevy_ui/Cargo.toml
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_ui_render/src/lib.rs
  release-content/migration-guides/bevy_render_reorganization.md
  release-content/release-notes/scene-type-crates.md
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#20505 smaa: use textureSampleLevel for WebGPU support
  crates/bevy_anti_aliasing/src/smaa/smaa.wgsl
Labels: C-Bug, D-Trivial, A-Rendering, O-Web, S-Ready-For-Final-Review, O-WebGPU

#20521 Update the doc comments for `UiCameraMap` and `UiCameraMapper`.
  crates/bevy_ui_render/src/lib.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#19355 bevy_render: disable GpuPreprocessingSupport for GL backend
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/diagnostic/mod.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_resource/bind_group_layout.rs
Labels: A-Rendering, P-Crash, S-Ready-For-Final-Review, O-OpenGL

#20541 Rename the `Allows` query filter to `Allow`
  crates/bevy_ecs/src/entity_disabling.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/lib.rs
  release-content/migration-guides/deprecate_iter_entities.md
  release-content/migration-guides/internal_entities.md
Labels: D-Trivial, A-ECS, S-Ready-For-Final-Review, X-Contentious

#20520 Add documentation for `ComputedUiTargetCamera`
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, D-Trivial, A-UI, S-Ready-For-Final-Review

#20512 Simplify UI tests
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/update.rs
Labels: A-Windowing, A-UI, S-Ready-For-Final-Review, C-Testing, D-Modest, A-Camera

#20543 Add a test to ensure that state transitions happen before `PreStartup`.
  crates/bevy_state/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-States

#20250 Make math primitives runtime constructable, meshable
  crates/bevy_gizmos/src/primitives/dim2.rs
  crates/bevy_gizmos/src/primitives/dim3.rs
  crates/bevy_math/src/bounding/bounded2d/primitive_impls.rs
  crates/bevy_math/src/bounding/bounded3d/extrusion.rs
  crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_math/src/primitives/mod.rs
  crates/bevy_math/src/primitives/serde.rs
  crates/bevy_mesh/src/primitives/dim2.rs
  crates/bevy_mesh/src/primitives/dim3/mod.rs
  crates/bevy_mesh/src/primitives/dim3/polyline3d.rs
  crates/bevy_mesh/src/primitives/dim3/segment3d.rs
  examples/2d/2d_shapes.rs
  examples/3d/3d_shapes.rs
  examples/math/render_primitives.rs
  release-content/migration-guides/primitives_non_const_generic_meshable.md
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, A-Math, M-Needs-Migration-Guide

#20556 Correct documentation of Smoothstep
  crates/bevy_math/src/curve/easing.rs
Labels: C-Docs, D-Trivial, A-Math

#20484 Improve TextSpan documentation
  crates/bevy_text/src/text.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Text

#20544 Improve error message for failed entity commands
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/error.rs
Labels: C-Bug, C-Docs, A-ECS, C-Usability, S-Ready-For-Final-Review, X-Contentious, D-Straightforward

#20560 ask for features in bug report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: D-Trivial, A-Meta, S-Ready-For-Final-Review, X-Contentious

#20566 impl `Deref` for `DebugName`
  crates/bevy_utils/src/debug_info.rs
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Utils, D-Domain-Agnostic

#20548 Change cursor shape for disabled widgets
  crates/bevy_feathers/src/controls/button.rs
  crates/bevy_feathers/src/controls/checkbox.rs
  crates/bevy_feathers/src/controls/radio.rs
  crates/bevy_feathers/src/controls/slider.rs
  crates/bevy_feathers/src/controls/toggle_switch.rs
  release-content/release-notes/feathers.md
Labels: C-Feature, A-UI, S-Ready-For-Final-Review, M-Needs-Release-Note, X-Uncontroversial, D-Straightforward

#20567 Fix bevy_tasks catch_unwind compilation error with --all-features
  crates/bevy_tasks/Cargo.toml
Labels: A-ECS, S-Ready-For-Final-Review, C-Testing, A-Tasks, D-Straightforward

#20538 Only regenerate text measure funcs on changes to the scale factor, not the camera or target size
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/widget/text.rs
Labels: C-Performance, A-UI, S-Ready-For-Final-Review, A-Text, D-Straightforward

#20463 `Text2d` shadows
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/widget/text.rs
  examples/2d/text2d.rs
  release-content/release-notes/text2d_shadows.md
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, A-Text, M-Needs-Release-Note, D-Straightforward, S-Needs-Review, M-Deliberate-Rendering-Change

#20430 debounce asset events for scene reloading
  crates/bevy_scene/src/lib.rs
  crates/bevy_scene/src/scene_spawner.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review, A-Scenes, X-Contentious

#20526 Add release notes for meshlet BVH culling
  release-content/release-notes/meshlet-bvh-culling.md
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#20531 Update `morph_targets` and `many_foxes` examples to use observers
  examples/animation/morph_targets.rs
  examples/stress_tests/many_foxes.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review, A-Animation

#20577 Fix code indentation in README
  README.md
Labels: C-Docs, D-Trivial, C-Code-Quality, S-Ready-For-Final-Review

#20578 remove some new lines from ComputedStates docs
  crates/bevy_state/src/state/computed_states.rs
Labels: D-Trivial, S-Ready-For-Final-Review

#20565 Opt-in raw vulkan initialization with hooks
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/renderer/mod.rs
  crates/bevy_render/src/renderer/raw_vulkan_init.rs
  crates/bevy_render/src/settings.rs
  docs/cargo_features.md
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review

#20581 Fix typo in release-notes directory link in GitHub workflow
  .github/workflows/action-on-PR-labeled.yml
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review

#20562 Revert asset lifetime changes and preserve staticness of asset paths in AssetServer::load()
  crates/bevy_asset/src/io/source.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/path.rs
Labels: C-Bug, A-Assets, C-Performance, S-Ready-For-Final-Review, P-Regression, D-Modest

#20597 Update the list of `RenderStartup` PRs in the release notes.
  release-content/migration-guides/render_startup.md
  release-content/release-notes/render_startup.md
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#20589 Remove `scale_value`
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/widget/text.rs
  release-content/migration-guides/remove_scale_value.md
Labels: D-Trivial, C-Code-Quality, M-Needs-Migration-Guide, A-Text, S-Needs-Review

#20599 Move calculate_bounds_2d back to bevy_sprite
  crates/bevy_sprite/Cargo.toml
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite_render/src/lib.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20602 update and coalesce migration guides and release notes for crate refactors
  release-content/migration-guides/bevy_render_reorganization.md
  release-content/migration-guides/bevy_ui_render_crate.md
  release-content/release-notes/bevy_ui_render_crate.md
  release-content/release-notes/scene-type-crates.md
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#20595 Make sure we submit work even if we visited a camera.
  crates/bevy_render/src/render_graph/camera_driver_node.rs
  crates/bevy_render/src/renderer/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#20605 UI doesn't need render
  crates/bevy_ui/Cargo.toml
Labels: A-Rendering, C-Dependencies, A-UI, S-Needs-Review

#20603 Remove unnecessary sqrt ops
  crates/bevy_math/src/primitives/dim3.rs
Labels: C-Performance, A-Math

#20600 Fix internal features
  crates/bevy_internal/Cargo.toml
Labels: C-Bug, A-Rendering, C-Dependencies, S-Ready-For-Final-Review

#20596 Optional DLSS-RR support in Solari
  crates/bevy_internal/Cargo.toml
  crates/bevy_solari/Cargo.toml
  crates/bevy_solari/src/realtime/mod.rs
  crates/bevy_solari/src/realtime/node.rs
  crates/bevy_solari/src/realtime/prepare.rs
  crates/bevy_solari/src/realtime/resolve_dlss_rr_textures.wgsl
  examples/3d/solari.rs
  release-content/release-notes/bevy_solari.md
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, M-Needs-Release-Note

#20606 Fix some lints and feature gates
  crates/bevy_asset/src/io/file/sync_file_asset.rs
  crates/bevy_math/src/bounding/bounded2d/primitive_impls.rs
  crates/bevy_math/src/bounding/bounded3d/extrusion.rs
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_utils/src/debug_info.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#20604 make bevy_render not depend on bevy_light
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/decal/clustered.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/extract_impls.rs
  crates/bevy_render/src/lib.rs
Labels: A-Rendering, S-Ready-For-Final-Review, P-Regression

#20434 Add bevy_light::SunDisk
  crates/bevy_light/src/directional_light.rs
  crates/bevy_light/src/lib.rs
  crates/bevy_pbr/src/atmosphere/functions.wgsl
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh_view_types.wgsl
  crates/bevy_solari/src/scene/binder.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#20594 Move `text2d` into `bevy_sprite`
  crates/bevy_sprite/Cargo.toml
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/text2d.rs
  crates/bevy_sprite_render/Cargo.toml
  crates/bevy_sprite_render/src/lib.rs
  crates/bevy_sprite_render/src/text2d/mod.rs
  crates/bevy_text/Cargo.toml
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_text/src/text.rs
  crates/bevy_text/src/text_access.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui_render/src/lib.rs
  examples/2d/text2d.rs
  release-content/migration-guides/text2d_moved_to_bevy_sprite.md
Labels: A-Rendering, S-Ready-For-Final-Review, A-Text, M-Needs-Release-Note, X-Contentious

#20591 Gate WireframePlugin behind WgpuFeatures::POLYGON_MODE_LINE | WgpuFeatures::PUSH_CONSTANTS
  crates/bevy_pbr/src/wireframe.rs
Labels: C-Bug, D-Trivial, A-Rendering, O-Web, S-Ready-For-Final-Review, O-WebGPU

#20618 Work around ambiguous `From` error in nightly
  crates/bevy_ecs/src/entity/clone_entities.rs
Labels: C-Bug, D-Trivial, A-ECS, A-Build-System, S-Ready-For-Final-Review, P-Compile-Failure

#20617 Fix glTF coordinate conversion not converting morph targets
  crates/bevy_gltf/src/loader/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, D-Straightforward, A-glTF

#20620 Make `bevy_sprite`'s `bevy_window` dependency non-optional
  crates/bevy_sprite/Cargo.toml
Labels: C-Bug, C-Dependencies, S-Ready-For-Final-Review

#20625 bevy_reflect gating / better compile error message
  crates/bevy_reflect/src/lib.rs
  crates/bevy_window/src/cursor/custom_cursor.rs
  crates/bevy_window/src/cursor/mod.rs
Labels: C-Docs, D-Trivial, C-Code-Quality, S-Ready-For-Final-Review

#20627 Add release note for atmosphere env map
  release-content/release-notes/atmosphere_environment_map.md
Labels: C-Docs

#20657 Regression tests for observers whose Observer component is removed.
  crates/bevy_ecs/src/observer/mod.rs
Labels: A-ECS, S-Ready-For-Final-Review, C-Testing, X-Uncontroversial, D-Straightforward

#20662 Fix world_to_viewport return error codes
  crates/bevy_camera/src/camera.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#20663 Fix a comment error in example system_stepping.rs
  examples/ecs/system_stepping.rs
Labels: D-Trivial, A-ECS, C-Examples, S-Ready-For-Final-Review

#20667 Fix documentation for `Rot2`
  crates/bevy_math/src/rotation2d.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Math, D-Straightforward

#20582 Remove redundant number conversion in window resolution
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/update.rs
  crates/bevy_window/src/window.rs
  examples/shader/compute_shader_game_of_life.rs
  examples/stress_tests/bevymark.rs
  examples/stress_tests/many_animated_sprites.rs
  examples/stress_tests/many_buttons.rs
  examples/stress_tests/many_cameras_lights.rs
  examples/stress_tests/many_cubes.rs
  examples/stress_tests/many_foxes.rs
  examples/stress_tests/many_gizmos.rs
  examples/stress_tests/many_glyphs.rs
  examples/stress_tests/many_gradients.rs
  examples/stress_tests/many_lights.rs
  examples/stress_tests/many_materials.rs
  examples/stress_tests/many_sprites.rs
  examples/stress_tests/many_text2d.rs
  examples/stress_tests/text_pipeline.rs
  examples/ui/grid.rs
  examples/ui/viewport_debug.rs
  examples/window/scale_factor_override.rs
  examples/window/window_settings.rs
  release-content/migration-guides/window_resolution_constructors.md
  tests/window/resizing.rs
Labels: A-Windowing, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#20659 Prevent infinite loop during BLAS compaction
  crates/bevy_solari/src/scene/blas.rs
  release-content/release-notes/bevy_solari.md
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#20683 `Hdr` migration guide wording
  release-content/migration-guides/camera_restructure.md
  release-content/migration-guides/hdr_component.md
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#20704 invert the quaternion not the mat4 in skybox
  crates/bevy_core_pipeline/src/skybox/mod.rs
Labels: A-Rendering, C-Performance, A-Math

#20705 invert affine not mat4 in point_light
  crates/bevy_light/src/point_light.rs
Labels: A-Rendering, A-Math

#20707 use affine not inverse in rangefinder
  crates/bevy_render/src/render_phase/rangefinder.rs
  crates/bevy_render/src/view/mod.rs
  release-content/migration-guides/rangefinder.md
Labels: A-Rendering, M-Needs-Migration-Guide

#20711 affine atmosphere
  crates/bevy_pbr/src/atmosphere/resources.rs
Labels: A-Rendering

#20685 Color::srgb requires values in range 0..1 and the ui/relative_cursor_position example used misleading 0..255 range
  examples/ui/relative_cursor_position.rs
Labels: C-Bug, D-Trivial, C-Examples, A-UI, S-Ready-For-Final-Review

#20687 Don't reserve in write_buffer_range
  crates/bevy_render/src/render_resource/buffer_vec.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#20724 remove irrelevant ui dependencies
  Cargo.toml
Labels: C-Bug, S-Ready-For-Final-Review

#20677 fix(mesh2d): replace unwrap by error log in specialize system
  crates/bevy_sprite_render/src/mesh2d/material.rs
Labels: C-Bug, A-Rendering, P-Crash, S-Ready-For-Final-Review, X-Contentious, D-Straightforward

#20725 extract MeshPlugin
  crates/bevy_camera/src/visibility/mod.rs
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_light/src/lib.rs
  crates/bevy_mesh/Cargo.toml
  crates/bevy_mesh/src/lib.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_render/src/camera.rs
  crates/bevy_render/src/mesh/mod.rs
Labels: C-Bug, A-Rendering, P-Crash, S-Ready-For-Final-Review

#20721 Re-enable the workspace wide dead_code lint
  Cargo.toml
  crates/bevy_app/src/app.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/renderer/raw_vulkan_init.rs
  crates/bevy_state/src/lib.rs
  examples/ui/drag_to_scroll.rs
Labels: S-Ready-For-Final-Review

#20709 use affine in volumetric fog
  crates/bevy_pbr/src/volumetric_fog/render.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20708 use affine not mat4 inverse in light probes
  crates/bevy_pbr/src/light_probe/mod.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20751 update some stress tests to use the common setup
  examples/stress_tests/many_gradients.rs
  examples/stress_tests/many_materials.rs
  examples/stress_tests/many_text2d.rs
Labels: D-Trivial, C-Examples

#20722 add plugin tracing spans
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/sub_app.rs
  crates/bevy_ecs/src/system/function_system.rs
Labels: C-Performance, S-Ready-For-Final-Review, A-App

#20636 Disable button labels for the `many_buttons` stress text by default
  examples/stress_tests/many_buttons.rs
Labels: A-UI, S-Ready-For-Final-Review, C-Benchmarks, D-Straightforward, M-Deliberate-Rendering-Change

#20723 rename SpriteRenderingPlugin to SpriteRenderPlugin
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_sprite_render/src/lib.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20740 add clip space docs
  crates/bevy_pbr/src/render/view_transformations.wgsl
  crates/bevy_render/src/view/view.wgsl
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#20765 Fix viewport_to_world for orthographic cameras and add regression tests
  crates/bevy_camera/src/camera.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, P-Regression, D-Straightforward

#20692 Improve tracing level docs in profiling.md
  docs/profiling.md
Labels: C-Docs, S-Ready-For-Final-Review, C-Testing, D-Straightforward

#20752 Clean up root toml features
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  docs/cargo_features.md
Labels: C-Dependencies, S-Ready-For-Final-Review, A-Cross-Cutting

#19113 examples: migrate async sleep to `futures-timer`; drop `async-std`
  Cargo.toml
  examples/async_tasks/async_compute.rs
Labels: C-Bug, C-Examples, S-Ready-For-Final-Review, D-Straightforward

#20779 derive Default on ShaderRef
  crates/bevy_shader/src/shader.rs
Labels: D-Trivial, A-Rendering, C-Usability

#20628 WebAssets without filtering
  .gitignore
  Cargo.toml
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/io/mod.rs
  crates/bevy_asset/src/io/wasm.rs
  crates/bevy_asset/src/io/web.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/default_plugins.rs
  deny.toml
  docs/cargo_features.md
  examples/README.md
  examples/asset/web_asset.rs
  release-content/release-notes/web_assets.md
Labels: A-Assets, S-Ready-For-Final-Review, M-Needs-Release-Note, X-Blessed

#20789 Fix broken json documentation
  crates/bevy_remote/src/lib.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-Dev-Tools

#20795 Use web assets for meshlet example
  Cargo.toml
  examples/3d/meshlet.rs
  tools/example-showcase/src/main.rs
Labels: A-Rendering, C-Examples, S-Needs-Review

#20793 Demote OpenGL to optional feature
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/settings.rs
  crates/bevy_render/src/view/window/mod.rs
  release-content/migration-guides/gles_optional.md
Labels: A-Rendering, S-Ready-For-Final-Review, X-Contentious

#20794 Add `vulkan-portability` to fix compiling with `--all-features`
  crates/bevy_render/Cargo.toml
Labels: D-Trivial, A-Rendering, S-Needs-Review

#20806 fix atmospherics memory leak
  crates/bevy_pbr/src/atmosphere/environment.rs
  crates/bevy_pbr/src/atmosphere/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review
