Repository bevyengine/bevy, pull requests merged in 2025-02, with the labels that each got.

#17637 Run handle_lifetime only when AudioSink is added to the world
  examples/mobile/src/lib.rs
Labels: C-Bug, A-Audio, O-iOS, S-Ready-For-Final-Review

#17627 Tiny ci improvements
  .github/workflows/ci.yml
  .github/workflows/validation-jobs.yml
  .github/workflows/weekly.yml
Labels: A-Build-System, S-Ready-For-Final-Review, D-Straightforward

#17626 Add a test for direct recursion in required components.
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/lib.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#17641 Fix Maya-exported rigs by not trying to topologically sort glTF nodes.
  crates/bevy_gltf/Cargo.toml
  crates/bevy_gltf/src/loader.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-glTF

#17631 anti-alias outside the edges of UI nodes, not across them
  crates/bevy_ui/src/render/ui.wgsl
Labels: C-Bug, A-Rendering, A-UI, D-Straightforward, S-Needs-Review, D-Shaders

#17621 `queue_sprites` comment fix
  crates/bevy_sprite/src/render/mod.rs
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#17596 Fix Taffy viewport node leaks
  crates/bevy_ui/src/layout/debug.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/layout/ui_surface.rs
Labels: C-Bug, A-UI, S-Needs-Review

#17545 feat: impl `Ease` for `Isometry[2/3]d`
  crates/bevy_math/src/curve/easing.rs
Labels: C-Usability, A-Math, X-Uncontroversial, D-Straightforward, S-Needs-Review

#17597 Fixing `ValArithmeticError` typo and unused variant
  crates/bevy_ui/src/geometry.rs
Labels: A-UI, C-Code-Quality, S-Needs-Review

#17586 Use more headers in AsBindGroup docs
  crates/bevy_render/src/render_resource/bind_group.rs
Labels: C-Docs, D-Trivial, A-Rendering, S-Needs-Review

#17620 Implement `Serialize`/`Deserialize` for entity collections
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/entity/hash_map.rs
  crates/bevy_ecs/src/entity/hash_set.rs
  crates/bevy_ecs/src/entity/index_map.rs
  crates/bevy_ecs/src/entity/index_set.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#17577 Improve ergonomics of `platform_support`'s `Instant`
  crates/bevy_platform_support/src/time.rs
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Time, D-Unsafe, O-Embedded

#17571 Fix cursor hotspot out of bounds when flipping
  crates/bevy_winit/src/custom_cursor.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review, D-Straightforward

#17592 Revert "Fix rounding bug in camera projection (#16828)"
  crates/bevy_render/src/camera/projection.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#17623 Expose ObserverDescriptor fields
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/observer/runner.rs
Labels: D-Trivial, A-ECS, S-Needs-Review

#17514 Add simple Disabled marker
  crates/bevy_ecs/src/entity_disabling.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_scene/src/dynamic_scene_builder.rs
  crates/bevy_scene/src/scene.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, D-Modest

#17636 Move sprite batches to resource
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/render/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#17651 Add required serde_derive feature flag to bevy_ecs
  crates/bevy_ecs/Cargo.toml
Labels: C-Bug, D-Trivial, A-ECS, S-Ready-For-Final-Review, P-Compile-Failure

#17660 Revert #17631
  crates/bevy_ui/src/render/ui.wgsl
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#17415 Improve `TextSpan` docs
  crates/bevy_text/src/text.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/widget/text.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Text, D-Straightforward

#17393 Add basic debug checks for read-only `UnsafeWorldCell`
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: A-ECS, S-Ready-For-Final-Review, C-Testing, D-Straightforward, D-Unsafe, S-Needs-Help

#17555 Atmosphere LUT parameterization improvements
  crates/bevy_pbr/src/atmosphere/aerial_view_lut.wgsl
  crates/bevy_pbr/src/atmosphere/functions.wgsl
  crates/bevy_pbr/src/atmosphere/sky_view_lut.wgsl
  crates/bevy_pbr/src/atmosphere/transmittance_lut.wgsl
  crates/bevy_render/src/maths.wgsl
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, D-Straightforward

#17600 Implementing Reflect on *MeshBuilder types
  crates/bevy_mesh/src/primitives/dim2.rs
  crates/bevy_mesh/src/primitives/dim3/capsule.rs
  crates/bevy_mesh/src/primitives/dim3/cone.rs
  crates/bevy_mesh/src/primitives/dim3/conical_frustum.rs
  crates/bevy_mesh/src/primitives/dim3/cuboid.rs
  crates/bevy_mesh/src/primitives/dim3/cylinder.rs
  crates/bevy_mesh/src/primitives/dim3/plane.rs
  crates/bevy_mesh/src/primitives/dim3/sphere.rs
  crates/bevy_mesh/src/primitives/dim3/tetrahedron.rs
  crates/bevy_mesh/src/primitives/dim3/torus.rs
  crates/bevy_mesh/src/primitives/dim3/triangle3d.rs
  crates/bevy_render/src/mesh/mod.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection, A-Math

#17616 Fix access checks for DeferredWorld as SystemParam.
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system_param.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, P-Unsound, D-Straightforward

#17646 Warnings and docs for exponential denormalization in rotate functions (alternative to #17604)
  crates/bevy_transform/src/components/transform.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Math

#17653 Added `try_map_unchanged`.
  crates/bevy_ecs/src/change_detection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#17654 Improve docs for `WorldQuery`
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/world_query.rs
  crates/bevy_ecs/src/system/function_system.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review, D-Complex, D-Unsafe

#17680 Make `batch_and_prepare_binned_render_phase` only record information about the first batch in each batch set.
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/render_phase/mod.rs
Labels: A-Rendering, C-Performance, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#17674 Fix text-2d.
  crates/bevy_sprite/src/render/mod.rs
Labels: C-Bug, A-Rendering, P-High, S-Needs-Review

#17689 Bump to `uuid` 1.13.1 and enable `js` on `wasm` targets
  crates/bevy_animation/Cargo.toml
  crates/bevy_asset/Cargo.toml
  crates/bevy_picking/Cargo.toml
  crates/bevy_reflect/Cargo.toml
  crates/bevy_reflect/derive/Cargo.toml
  crates/bevy_scene/Cargo.toml
Labels: D-Trivial, A-Build-System, C-Dependencies, O-Web, S-Ready-For-Final-Review, P-Compile-Failure, X-Uncontroversial

#17688 Don't mark a previous mesh transform as changed if it didn't actually change.
  crates/bevy_pbr/src/prepass/mod.rs
Labels: C-Bug, A-Rendering, C-Performance, S-Ready-For-Final-Review, P-Regression

#17684 Don't reallocate work item buffers every frame.
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  examples/shader/specialized_mesh_pipeline.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#17589 implement UniqueEntitySlice
  crates/bevy_ecs/src/entity/entity_set.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/entity/unique_slice.rs
  crates/bevy_ecs/src/entity/unique_vec.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, D-Complex, D-Unsafe

#17567 Cold Specialization
  crates/bevy_animation/src/lib.rs
  crates/bevy_asset/src/asset_changed.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/mesh_material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/projection.rs
  crates/bevy_render/src/mesh/components.rs
  crates/bevy_render/src/mesh/mod.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_text/src/lib.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, D-Complex, M-Needs-Release-Note

#15858 Introduce methods on QueryState to obtain a Query
  crates/bevy_ecs/compile_fail/tests/ui/query_to_readonly.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_render/src/camera/camera.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, M-Needs-Release-Note, X-Contentious, D-Modest, D-Unsafe

#17692 Change `GhostNode` into a unit type
  crates/bevy_ui/src/experimental/ghost_hierarchy.rs
  examples/ui/ghost_nodes.rs
Labels: D-Trivial, A-UI, C-Code-Quality, S-Ready-For-Final-Review

#17679 Move `Item` and `fetch` to `QueryData` from `WorldQuery`
  crates/bevy_asset/src/asset_changed.rs
  crates/bevy_ecs/macros/src/query_data.rs
  crates/bevy_ecs/macros/src/query_filter.rs
  crates/bevy_ecs/macros/src/world_query.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/world_query.rs
  crates/bevy_ecs/src/relationship/relationship_query.rs
  crates/bevy_render/src/sync_world.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#17559 Basic UI text shadows
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/ui_node.rs
  examples/ui/button.rs
  examples/ui/text.rs
Labels: C-Feature, A-Rendering, A-UI, S-Ready-For-Final-Review, A-Text, M-Needs-Release-Note, D-Modest

#17673 Fix a couple of doc typos
  crates/bevy_picking/src/events.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-Picking

#17384 Add `weak_handle!` convenience macro
  crates/bevy_asset/src/handle.rs
  crates/bevy_asset/src/lib.rs
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#17685 Split `Component::register_component_hooks` into individual methods
  crates/bevy_core_pipeline/src/oit/mod.rs
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/observer/entity_observer.rs
  crates/bevy_ecs/src/observer/runner.rs
  examples/ecs/component_hooks.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Modest

#17671 Isolate component registration
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/storage/mod.rs
  crates/bevy_ecs/src/storage/sparse_set.rs
  crates/bevy_ecs/src/storage/table/mod.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#17676 Add a Sphere to `anisotropy` example
  examples/3d/anisotropy.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review, C-Testing

#17675 Add missing return in default `Relationship::on_insert` impl
  crates/bevy_ecs/src/relationship/mod.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#17695 Weak handle migration
  crates/bevy_asset/src/handle.rs
  crates/bevy_core_pipeline/src/auto_exposure/pipeline.rs
  crates/bevy_core_pipeline/src/blit/mod.rs
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_core_pipeline/src/deferred/copy_lighting_id.rs
  crates/bevy_core_pipeline/src/dof/mod.rs
  crates/bevy_core_pipeline/src/experimental/mip_generation/mod.rs
  crates/bevy_core_pipeline/src/fullscreen_vertex_shader/mod.rs
  crates/bevy_core_pipeline/src/fxaa/mod.rs
  crates/bevy_core_pipeline/src/motion_blur/mod.rs
  crates/bevy_core_pipeline/src/oit/mod.rs
  crates/bevy_core_pipeline/src/oit/resolve/mod.rs
  crates/bevy_core_pipeline/src/post_process/mod.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_core_pipeline/src/skybox/prepass.rs
  crates/bevy_core_pipeline/src/smaa/mod.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_pbr/src/atmosphere/mod.rs
  crates/bevy_pbr/src/decal/clustered.rs
  crates/bevy_pbr/src/decal/forward.rs
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light_probe/environment_map.rs
  crates/bevy_pbr/src/light_probe/irradiance_volume.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/lightmap/mod.rs
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/meshlet/pipelines.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/fog.rs
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_pbr/src/ssr/mod.rs
  crates/bevy_pbr/src/volumetric_fog/render.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/experimental/occlusion_culling/mod.rs
  crates/bevy_render/src/globals.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/texture/mod.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/mesh2d/color_material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/mesh2d/wireframe2d.rs
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
  examples/2d/mesh2d_manual.rs
Labels: A-Assets, C-Code-Quality, S-Ready-For-Final-Review

#17677 Add `edit_material_on_gltf` example
  Cargo.toml
  examples/3d/edit_material_on_gltf.rs
  examples/README.md
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review, A-glTF

#11094 Schedule build pass
  crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/graph/graph_map.rs
  crates/bevy_ecs/src/schedule/graph/mod.rs
  crates/bevy_ecs/src/schedule/graph/node.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/pass.rs
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: C-Feature, A-ECS, C-Code-Quality, S-Ready-For-Final-Review, D-Modest

#17687 Improved Entity Mapping and Cloning
  benches/benches/bevy_ecs/entity_cloning.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/clone_entities.rs
  crates/bevy_ecs/src/entity/map_entities.rs
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/observer/entity_observer.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/reflect/bundle.rs
  crates/bevy_ecs/src/reflect/component.rs
  crates/bevy_ecs/src/relationship/mod.rs
  crates/bevy_ecs/src/relationship/relationship_source_collection.rs
  crates/bevy_ecs/src/system/commands/entity_command.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_mesh/src/skinning.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_scene/src/scene.rs
  crates/bevy_scene/src/serde.rs
  examples/ecs/dynamic.rs
  examples/ecs/immutable_components.rs
  examples/stress_tests/many_components.rs
Labels: C-Bug, A-ECS, P-High, C-Usability, A-Scenes, M-Needs-Migration-Guide, A-Networking, S-Needs-Review

#17738 Include the material bind group in the shadow batch set key.
  crates/bevy_pbr/src/render/light.rs
Labels: C-Bug, A-Rendering, P-Regression, S-Needs-Review

#17461 EaseFunction svg graphs in doc
  crates/bevy_math/images/easefunction/BackIn.svg
  crates/bevy_math/images/easefunction/BackInOut.svg
  crates/bevy_math/images/easefunction/BackOut.svg
  crates/bevy_math/images/easefunction/BounceIn.svg
  crates/bevy_math/images/easefunction/BounceInOut.svg
  crates/bevy_math/images/easefunction/BounceOut.svg
  crates/bevy_math/images/easefunction/CircularIn.svg
  crates/bevy_math/images/easefunction/CircularInOut.svg
  crates/bevy_math/images/easefunction/CircularOut.svg
  crates/bevy_math/images/easefunction/CubicIn.svg
  crates/bevy_math/images/easefunction/CubicInOut.svg
  crates/bevy_math/images/easefunction/CubicOut.svg
  crates/bevy_math/images/easefunction/Elastic.svg
  crates/bevy_math/images/easefunction/ElasticIn.svg
  crates/bevy_math/images/easefunction/ElasticInOut.svg
  crates/bevy_math/images/easefunction/ElasticOut.svg
  crates/bevy_math/images/easefunction/ExponentialIn.svg
  crates/bevy_math/images/easefunction/ExponentialInOut.svg
  crates/bevy_math/images/easefunction/ExponentialOut.svg
  crates/bevy_math/images/easefunction/Linear.svg
  crates/bevy_math/images/easefunction/QuadraticIn.svg
  crates/bevy_math/images/easefunction/QuadraticInOut.svg
  crates/bevy_math/images/easefunction/QuadraticOut.svg
  crates/bevy_math/images/easefunction/QuarticIn.svg
  crates/bevy_math/images/easefunction/QuarticInOut.svg
  crates/bevy_math/images/easefunction/QuarticOut.svg
  crates/bevy_math/images/easefunction/QuinticIn.svg
  crates/bevy_math/images/easefunction/QuinticInOut.svg
  crates/bevy_math/images/easefunction/QuinticOut.svg
  crates/bevy_math/images/easefunction/README.md
  crates/bevy_math/images/easefunction/SineIn.svg
  crates/bevy_math/images/easefunction/SineInOut.svg
  crates/bevy_math/images/easefunction/SineOut.svg
  crates/bevy_math/images/easefunction/SmoothStep.svg
  crates/bevy_math/images/easefunction/SmoothStepIn.svg
  crates/bevy_math/images/easefunction/SmoothStepOut.svg
  crates/bevy_math/images/easefunction/SmootherStep.svg
  crates/bevy_math/images/easefunction/SmootherStepIn.svg
  crates/bevy_math/images/easefunction/SmootherStepOut.svg
  crates/bevy_math/images/easefunction/Steps.svg
  crates/bevy_math/src/curve/easing.rs
  examples/animation/easing_functions.rs
  tools/build-easefunction-graphs/Cargo.toml
  tools/build-easefunction-graphs/src/main.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Math, X-Contentious, D-Modest

#17742 Tidy up `easing_functions` example
  examples/animation/easing_functions.rs
Labels: C-Examples, C-Code-Quality, S-Ready-For-Final-Review, A-Math, D-Straightforward

#17743 Fix rounding in steps easing function
  crates/bevy_math/src/curve/easing.rs
  crates/bevy_math/src/curve/mod.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math, M-Needs-Migration-Guide

#17698 Retain bins from frame to frame.
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/batching/no_gpu_preprocessing.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_render/src/sync_world.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  examples/shader/custom_phase_item.rs
  examples/shader/specialized_mesh_pipeline.rs
Labels: A-Rendering, C-Performance, S-Needs-Review

#17749 Fix shadow retention by keying off the `RetainedViewEntity`, not the light's render world entity.
  crates/bevy_pbr/src/render/light.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#17736 Set late indirect parameter offsets every frame again.
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  examples/shader/specialized_mesh_pipeline.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, P-Regression

#17735 main_transparent_pass_2d render node command encoding parallelization
  crates/bevy_core_pipeline/src/core_2d/main_transparent_pass_2d_node.rs
Labels: A-Rendering, C-Performance, D-Straightforward, S-Needs-Review

#17719 Move specialize_* to QueueMeshes.
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_sprite/src/mesh2d/material.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#17741 deps: bump notify-debouncer-full to remove unmaintained crate
  crates/bevy_asset/Cargo.toml
  deny.toml
Labels: C-Dependencies

#17542 Upgrade to wgpu v24
  Cargo.toml
  crates/bevy_color/Cargo.toml
  crates/bevy_core_pipeline/src/experimental/mip_generation/mod.rs
  crates/bevy_image/Cargo.toml
  crates/bevy_image/src/dds.rs
  crates/bevy_image/src/image.rs
  crates/bevy_image/src/ktx2.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_mesh/Cargo.toml
  crates/bevy_mesh/src/mesh.rs
  crates/bevy_mesh/src/vertex.rs
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/meshlet/visibility_buffer_raster_node.rs
  crates/bevy_pbr/src/render/build_indirect_params.wgsl
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/shadow_sampling.wgsl
  crates/bevy_pbr/src/ssr/raymarch.wgsl
  crates/bevy_reflect/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/experimental/occlusion_culling/mesh_preprocess_types.wgsl
  crates/bevy_render/src/gpu_readback.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/mesh/mod.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/render_resource/bind_group_layout.rs
  crates/bevy_render/src/render_resource/buffer.rs
  crates/bevy_render/src/render_resource/mod.rs
  crates/bevy_render/src/render_resource/pipeline.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/render_resource/texture.rs
  crates/bevy_render/src/renderer/mod.rs
  crates/bevy_render/src/renderer/render_device.rs
  crates/bevy_render/src/settings.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_winit/Cargo.toml
  docs/cargo_features.md
  examples/app/headless_renderer.rs
Labels: A-Rendering, C-Dependencies, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Uncontroversial

#17521 Improved Spawn APIs and Bundle Effects
  benches/benches/bevy_ecs/world/world_get.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/reflect/bundle.rs
  crates/bevy_ecs/src/spawn.rs
  crates/bevy_ecs/src/system/commands/command.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/spawn_batch.rs
  crates/bevy_render/src/extract_component.rs
  crates/bevy_transform/src/systems.rs
  crates/bevy_ui/src/experimental/ghost_hierarchy.rs
  crates/bevy_ui/src/layout/mod.rs
  examples/3d/lighting.rs
  examples/3d/motion_blur.rs
  examples/games/alien_cake_addict.rs
  examples/games/breakout.rs
  examples/games/desk_toy.rs
  examples/games/game_menu.rs
  examples/ui/button.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Complex, M-Needs-Release-Note, X-Blessed

#17579 Store UI render target info locally per node
  crates/bevy_ui/src/experimental/ghost_hierarchy.rs
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/layout/debug.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/layout/ui_surface.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/picking_backend.rs
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/debug_overlay.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/update.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_ui/src/widget/text.rs
  examples/3d/split_screen.rs
Labels: C-Bug, A-Rendering, A-Windowing, C-Performance, A-UI, C-Code-Quality, C-Usability, S-Ready-For-Final-Review

#17770 Fix meshlets when bindless disabled.
  crates/bevy_pbr/src/render/pbr_fragment.wgsl
Labels: C-Bug, A-Rendering, S-Needs-Review

#15481 Remove `labeled_assets` from `LoadedAsset` and `ErasedLoadedAsset`
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/loader.rs
  crates/bevy_asset/src/loader_builders.rs
  crates/bevy_asset/src/processor/process.rs
  crates/bevy_asset/src/saver.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_asset/src/transformer.rs
  examples/asset/asset_decompression.rs
  examples/asset/processing/asset_processing.rs
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Straightforward

#16913 many_components stress test improvements
  Cargo.toml
  examples/stress_tests/many_components.rs
Labels: A-ECS, S-Ready-For-Final-Review, C-Benchmarks, D-Straightforward, D-Unsafe

#17602 Encapsulate `cfg(feature = "track_location")` in a type.
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/event/base.rs
  crates/bevy_ecs/src/event/collections.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/storage/resource.rs
  crates/bevy_ecs/src/storage/sparse_set.rs
  crates/bevy_ecs/src/storage/table/column.rs
  crates/bevy_ecs/src/storage/table/mod.rs
  crates/bevy_ecs/src/system/commands/command.rs
  crates/bevy_ecs/src/system/commands/entity_command.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/filtered_resource.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/spawn_batch.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Blessed

#17605 Support decibels in bevy_audio::Volume
  crates/bevy_audio/src/audio.rs
  crates/bevy_audio/src/audio_output.rs
  crates/bevy_audio/src/sinks.rs
  crates/bevy_audio/src/volume.rs
  examples/audio/audio_control.rs
  examples/audio/decodable.rs
  examples/audio/soundtrack.rs
Labels: A-Audio, C-Usability, S-Ready-For-Final-Review, X-Contentious, D-Straightforward

#17704 Add scroll functionality to bevy_picking
  crates/bevy_picking/src/events.rs
  crates/bevy_picking/src/input.rs
  crates/bevy_picking/src/lib.rs
  crates/bevy_picking/src/pointer.rs
Labels: C-Feature, S-Ready-For-Final-Review, D-Modest, A-Picking

#17724 `Query::get_many` should not check for duplicates
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/system/query.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#17727 make bevy math publishable
  crates/bevy_math/Cargo.toml
  crates/bevy_math/src/curve/easing.rs
  crates/bevy_math/src/curve/sample_curves.rs
  crates/bevy_math/src/direction.rs
  crates/bevy_math/src/isometry.rs
  crates/bevy_math/src/rotation2d.rs
  deny.toml
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Math

#17748 CosmicBuffer is a public type but not not used or accessible in any public API
  crates/bevy_text/src/text.rs
Labels: C-Feature, S-Ready-For-Final-Review, A-Text, D-Straightforward

#17781 Derive Reflect on Skybox
  crates/bevy_core_pipeline/src/skybox/mod.rs
Labels: D-Trivial, A-Rendering, C-Usability, S-Ready-For-Final-Review, A-Reflection

#17785 UI clipping update function comments fix
  crates/bevy_ui/src/update.rs
Labels: C-Docs, D-Trivial, A-UI, S-Ready-For-Final-Review

#17783 run example in CI on windows using static dxc
  .github/workflows/validation-jobs.yml
  examples/testbed/3d.rs
Labels: C-Bug, A-Build-System, O-Windows, S-Ready-For-Final-Review

#17778 Expand `EasingCurve` documentation
  crates/bevy_math/src/curve/easing.rs
Labels: C-Docs, C-Usability, S-Ready-For-Final-Review, A-Animation, A-Math

#17787 Sweep bins after queuing so as to only sweep them once.
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_sprite/src/mesh2d/material.rs
Labels: C-Bug, A-Rendering, P-High, S-Needs-Review

#17672 Use dual-source blending for rendering the sky
  crates/bevy_pbr/src/atmosphere/aerial_view_lut.wgsl
  crates/bevy_pbr/src/atmosphere/functions.wgsl
  crates/bevy_pbr/src/atmosphere/mod.rs
  crates/bevy_pbr/src/atmosphere/render_sky.wgsl
  crates/bevy_pbr/src/atmosphere/resources.rs
Labels: A-Rendering, S-Ready-For-Final-Review, D-Modest

#17790 Silence deprecation warning in `Bundle` derive macro (#17369)
  crates/bevy_ecs/macros/src/lib.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review

#17791 Add links to the types on the documentation of `GltfAssetLabel`
  crates/bevy_gltf/src/lib.rs
Labels: C-Docs, D-Trivial, A-Assets, S-Ready-For-Final-Review, A-glTF

#17768 Allow users to register their own disabling components / default query filters
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/entity_disabling.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_scene/src/dynamic_scene_builder.rs
Labels: A-ECS, C-Usability, X-Contentious, D-Straightforward, S-Needs-Review

#17795 Fix failing proc macros when depending on bevy through dev and normal dependencies.
  crates/bevy_macro_utils/Cargo.toml
  crates/bevy_macro_utils/src/bevy_manifest.rs
  tests-integration/simple-ecs-test/Cargo.toml
Labels: P-High, S-Ready-For-Final-Review, A-Cross-Cutting, D-Macros

#17802 Split the labels in many_buttons
  examples/stress_tests/many_buttons.rs
Labels: D-Trivial, A-UI, S-Ready-For-Final-Review, A-Text, C-Benchmarks

#17681 Add relative position reporting to UI picking
  crates/bevy_ui/src/picking_backend.rs
Labels: C-Feature, A-UI, S-Ready-For-Final-Review, D-Straightforward, A-Picking

#17716 Expose method to update the internal ticks of Ref and Mut
  crates/bevy_ecs/src/change_detection.rs
Labels: A-ECS, X-Controversial, A-Networking, D-Modest, S-Needs-Review

#17758 Trait tags on docs.rs
  .github/workflows/docs.yml
  Cargo.toml
  docs-rs/README.md
  docs-rs/trait-tags.html
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review, M-Needs-Release-Note

#17731 feat(ecs): implement fallible observer systems
  Cargo.toml
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/system/observer_system.rs
  examples/ecs/fallible_systems.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, X-Uncontroversial, D-Modest

#17805 UI text extraction refactor
  crates/bevy_ui/src/render/mod.rs
Labels: A-Rendering, C-Performance, A-UI, C-Code-Quality, S-Ready-For-Final-Review, A-Text, D-Straightforward

#17752 Add ways to configure `EasingFunction::Steps` via new `StepConfig`
  crates/bevy_math/images/easefunction/BothSteps.svg
  crates/bevy_math/images/easefunction/EndSteps.svg
  crates/bevy_math/images/easefunction/NoneSteps.svg
  crates/bevy_math/images/easefunction/StartSteps.svg
  crates/bevy_math/images/easefunction/Steps.svg
  crates/bevy_math/src/curve/easing.rs
  crates/bevy_math/src/curve/mod.rs
  examples/animation/easing_functions.rs
  tools/build-easefunction-graphs/src/main.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Animation, A-Math, M-Needs-Migration-Guide, D-Straightforward

#17801 Fix validation errors in `Fox.glb`
  CREDITS.md
  assets/models/animated/Fox.glb
  examples/testbed/3d.rs
Labels: C-Bug, C-Examples, S-Ready-For-Final-Review, A-glTF

#17799 Fix error in scene example
  assets/scenes/load_scene_example.scn.ron
Labels: C-Bug, D-Trivial, C-Examples, S-Ready-For-Final-Review, A-Scenes

#17789 Add tonemapping switch to bloom 2d example
  examples/2d/bloom_2d.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review, C-Testing, D-Straightforward

#17809 gate get_tag behind ndef MESHLET_MESH_MATERIAL_PASS
  crates/bevy_pbr/src/render/mesh_functions.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#17793 Don't relocate the meshes when mesh slabs grow.
  crates/bevy_render/src/mesh/allocator.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, P-Regression

#17772 Cache `MeshInputUniform` indices in each `RenderBin`.
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/batching/no_gpu_preprocessing.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  examples/shader/custom_phase_item.rs
  examples/shader/custom_render_phase.rs
  examples/shader/specialized_mesh_pipeline.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#17702 Use `target_abi = "sim"` instead of `ios_simulator` feature
  Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/render_resource/uniform_buffer.rs
  docs/cargo_features.md
  examples/mobile/Cargo.toml
  examples/mobile/android_basic/Cargo.toml
Labels: O-iOS, C-Usability, S-Ready-For-Final-Review, C-Testing, M-Needs-Migration-Guide

#17812 Panic on failure in `scene` example
  examples/scene/scene.rs
Labels: C-Examples, S-Ready-For-Final-Review, C-Testing, A-Scenes

#17813 Deterministic fallible_systems example
  Cargo.toml
  examples/ecs/fallible_systems.rs
Labels: C-Examples, S-Ready-For-Final-Review, C-Testing

#17796 implement iterators that yield UniqueEntitySlice
  crates/bevy_ecs/src/entity/unique_slice.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, X-Uncontroversial, D-Modest

#17767 Use unchecked shaders for better performance
  crates/bevy_render/src/renderer/render_device.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, X-Blessed

#17823 Add separate option to control font size behavior in `many_text2d`
  examples/stress_tests/many_text2d.rs
Labels: D-Trivial, A-UI, C-Testing, A-Text

#17825 Minor tidying in `font_atlas_debug`
  examples/ui/font_atlas_debug.rs
Labels: D-Trivial, C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#17765 Meshlet texture atomics
  crates/bevy_core_pipeline/src/experimental/mip_generation/downsample_depth.wgsl
  crates/bevy_core_pipeline/src/experimental/mip_generation/mod.rs
  crates/bevy_pbr/src/meshlet/clear_visibility_buffer.wgsl
  crates/bevy_pbr/src/meshlet/meshlet_bindings.wgsl
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/meshlet/pipelines.rs
  crates/bevy_pbr/src/meshlet/resolve_render_targets.wgsl
  crates/bevy_pbr/src/meshlet/resource_manager.rs
  crates/bevy_pbr/src/meshlet/visibility_buffer_hardware_raster.wgsl
  crates/bevy_pbr/src/meshlet/visibility_buffer_raster_node.rs
  crates/bevy_pbr/src/meshlet/visibility_buffer_resolve.wgsl
  crates/bevy_pbr/src/meshlet/visibility_buffer_software_raster.wgsl
Labels: A-Rendering, C-Performance, D-Straightforward, S-Waiting-on-Author

#17800 Add ComponentId-taking functions to Entity{Ref,Mut}Except to mirror FilteredEntity{Ref,Mut}
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#17819 Switch bins from parallel key/value arrays to `IndexMap`s.
  crates/bevy_core_pipeline/src/deferred/node.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/batching/no_gpu_preprocessing.rs
  crates/bevy_render/src/render_phase/mod.rs
Labels: A-Rendering, C-Performance, C-Code-Quality, S-Ready-For-Final-Review

#17694 Shorten the 'world lifetime returned from `QueryLens::query()`.
  crates/bevy_ecs/compile_fail/tests/ui/query_lens_lifetime_safety.rs
  crates/bevy_ecs/compile_fail/tests/ui/query_lens_lifetime_safety.stderr
  crates/bevy_ecs/src/system/query.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, M-Needs-Migration-Guide, P-Unsound, D-Modest

#17764 Build batches across phases in parallel.
  crates/bevy_pbr/src/decal/forward.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  examples/3d/occlusion_culling.rs
  examples/shader/custom_render_phase.rs
  examples/shader/specialized_mesh_pipeline.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#17833 Update `HitData` position docs
  crates/bevy_picking/src/backend.rs
Labels: C-Docs, S-Ready-For-Final-Review, D-Straightforward, A-Picking

#17850 Update `typos` to 1.29.6
  .github/workflows/ci.yml
  crates/bevy_ecs/src/entity/entity_set.rs
  crates/bevy_mikktspace/src/generated.rs
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  crates/bevy_pbr/src/ssr/raymarch.wgsl
  crates/bevy_picking/src/lib.rs
  crates/bevy_reflect/src/func/args/count.rs
  crates/bevy_reflect/src/func/dynamic_function_internal.rs
  typos.toml
Labels: C-Code-Quality, S-Ready-For-Final-Review

#17848 Add `NodeImageMode` to the UI prelude
  crates/bevy_ui/src/lib.rs
Labels: D-Trivial, A-UI, C-Usability, S-Ready-For-Final-Review

#17815 implement par_iter_many and par_iter_many_unique
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, D-Complex, D-Unsafe

#17830 Improve clarity of existing bevy_assets documentation
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/direct_access_ext.rs
  crates/bevy_asset/src/folder.rs
  crates/bevy_asset/src/handle.rs
Labels: C-Docs, A-Assets, S-Ready-For-Final-Review

#17853 Combine `output_index` and `indirect_parameters_index` into one field in `PreprocessWorkItem`.
  crates/bevy_pbr/src/render/mesh_preprocess.wgsl
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  examples/shader/specialized_mesh_pipeline.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#17852 `ui_material` example webgl2 fix
  assets/shaders/custom_ui_material.wgsl
  examples/ui/ui_material.rs
Labels: C-Bug, A-Rendering, C-Examples, A-UI, S-Ready-For-Final-Review, O-WebGL2

#17829 Fill out some missing docs for bevy_assets
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/event.rs
  crates/bevy_asset/src/folder.rs
  crates/bevy_asset/src/handle.rs
  crates/bevy_asset/src/id.rs
  crates/bevy_asset/src/io/embedded/embedded_watcher.rs
  crates/bevy_asset/src/io/embedded/mod.rs
  crates/bevy_asset/src/io/file/file_watcher.rs
  crates/bevy_asset/src/io/file/mod.rs
  crates/bevy_asset/src/io/source.rs
  crates/bevy_asset/src/processor/log.rs
  crates/bevy_asset/src/render_asset.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_asset/src/transformer.rs
Labels: C-Docs, A-Assets, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#17565 Remove prepasses from the render world when they're removed from the main world.
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_pbr/src/deferred/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, P-Regression

#17849 Actually add objects to the scene buffers in sorted render phases.
  crates/bevy_render/src/batching/gpu_preprocessing.rs
Labels: C-Bug, A-Rendering, P-High, S-Ready-For-Final-Review, P-Regression

#17817 Add `TypeRegistry::register_by_val`
  crates/bevy_reflect/src/type_registry.rs
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Reflection

#17859 Update picking docs to include position space
  crates/bevy_picking/src/mesh_picking/mod.rs
  crates/bevy_picking/src/window.rs
  crates/bevy_sprite/src/picking_backend.rs
  crates/bevy_ui/src/picking_backend.rs
Labels: C-Docs, S-Ready-For-Final-Review, D-Straightforward, A-Picking

#15624 Support using FilteredResources with ReflectResource.
  crates/bevy_ecs/src/reflect/resource.rs
  crates/bevy_ecs/src/system/builder.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Straightforward

#17822 Move implementations of `Query` methods from `QueryState` to `Query`.
  crates/bevy_ecs/src/query/error.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system_param.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#17841 Don't delete the buffers that batch building writes into every frame.
  crates/bevy_render/src/batching/gpu_preprocessing.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, D-Modest

#17862 Replace `BufferVec<PreprocessWorkItem>` with `RawBufferVec<PreprocessWorkItem>`.
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, D-Modest

#17866 Fix panic in `custom_render_phase` example
  examples/shader/custom_render_phase.rs
Labels: C-Bug, A-Rendering, C-Examples, P-Crash, S-Ready-For-Final-Review, D-Straightforward

#17855 Add `EntityDoesNotExistError`, replace cases of `Entity` as an error, do some easy Resultification
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/query/error.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/relationship/mod.rs
  crates/bevy_ecs/src/system/commands/entity_command.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/entity_fetch.rs
  crates/bevy_ecs/src/world/error.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_render/src/render_phase/draw.rs
  crates/bevy_transform/src/helper.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#17886 Improve the docs for ChildOf and Children
  crates/bevy_ecs/src/hierarchy.rs
Labels: C-Docs, A-ECS, X-Uncontroversial, D-Straightforward, S-Needs-Review

#17888 Fix `dds` feature enabling `bevy_gltf`
  crates/bevy_internal/Cargo.toml
Labels: C-Bug, S-Ready-For-Final-Review, P-Compile-Failure, A-glTF

#17887 Fixed `bevy_image` and `bevy_gltf` failing to compile with some features.
  crates/bevy_gltf/Cargo.toml
  crates/bevy_image/Cargo.toml
Labels: C-Bug, D-Trivial, A-Rendering, S-Ready-For-Final-Review, P-Compile-Failure

#17899 Fix typos CREDITS.md
  CREDITS.md
Labels: C-Examples, S-Ready-For-Final-Review

#17903 Sweep old entities from 2D binned render phases
  crates/bevy_sprite/src/mesh2d/mesh.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#17902 Bump `typos` to 1.29.7
  .github/workflows/ci.yml
  typos.toml
Labels: D-Trivial, A-Build-System, C-Dependencies, S-Ready-For-Final-Review

#17863 Split out the `IndirectParametersMetadata` into CPU-populated and GPU-populated buffers.
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/render/build_indirect_params.wgsl
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_preprocess.wgsl
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/experimental/occlusion_culling/mesh_preprocess_types.wgsl
  crates/bevy_render/src/render_resource/buffer_vec.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  examples/3d/occlusion_culling.rs
  examples/shader/custom_render_phase.rs
Labels: A-Rendering, C-Performance, C-Code-Quality, S-Needs-Review

#17818 Retain skins from frame to frame.
  crates/bevy_mesh/src/skinning.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/meshlet/instance_manager.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_preprocess.wgsl
  crates/bevy_pbr/src/render/mesh_types.wgsl
  crates/bevy_pbr/src/render/mod.rs
  crates/bevy_pbr/src/render/skin.rs
  crates/bevy_pbr/src/render/skinning.wgsl
  crates/bevy_render/src/experimental/occlusion_culling/mesh_preprocess_types.wgsl
  examples/shader/custom_render_phase.rs
Labels: C-Bug, A-Rendering, C-Performance, S-Ready-For-Final-Review, A-Animation

#17915 Make the specialized pipeline cache two-level.
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_sprite/src/mesh2d/material.rs
Labels: C-Bug, A-Rendering, C-Performance, S-Ready-For-Final-Review

#17717 Fix motion vector computation after #17688.
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_preprocess.wgsl
  crates/bevy_pbr/src/render/skinning.wgsl
  crates/bevy_render/src/experimental/occlusion_culling/mesh_preprocess_types.wgsl
  crates/bevy_render/src/render_resource/buffer_vec.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/view.wgsl
Labels: C-Bug, A-Rendering, S-Blocked, P-Regression, S-Needs-Review

#17922 Don't mark newly-hidden meshes invisible until all visibility-determining systems run.
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_render/src/view/visibility/mod.rs
Labels: C-Bug, A-Rendering, C-Performance, S-Ready-For-Final-Review

#17927 Add option to animate materials in many_cubes
  examples/stress_tests/many_cubes.rs
Labels: A-Rendering, C-Performance, S-Needs-Review

#17824 Shader validation enum
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/render_resource/shader.rs
  crates/bevy_render/src/renderer/render_device.rs
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review

#17939 Fix false positive GPU frustum culling
  crates/bevy_pbr/src/render/mesh_preprocess.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#17923 Rewrite the multidrawable batch set builder for performance.
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#17934 Implement occlusion culling for the deferred rendering pipeline.
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/deferred/node.rs
  crates/bevy_core_pipeline/src/experimental/mip_generation/mod.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  examples/tools/scene_viewer/main.rs
Labels: A-Rendering, C-Performance, S-Needs-Review

#17959 Remove unused `#[must_used]`
  crates/bevy_app/src/app.rs
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, A-App, P-Compile-Failure, X-Uncontroversial

#17898 Use global binding arrays for bindless resources.
  assets/shaders/bindless_material.wgsl
  crates/bevy_pbr/src/extended_material.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/material_bind_groups.rs
  crates/bevy_pbr/src/meshlet/material_pipeline_prepare.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/parallax_mapping.wgsl
  crates/bevy_pbr/src/render/pbr_bindings.wgsl
  crates/bevy_pbr/src/render/pbr_fragment.wgsl
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
  crates/bevy_pbr/src/render/pbr_prepass_functions.wgsl
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/src/bindless.wgsl
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/render_resource/bindless.rs
  crates/bevy_render/src/render_resource/mod.rs
  examples/shader/shader_material_bindless.rs
Labels: C-Bug, A-Rendering, P-Crash, C-Performance, S-Needs-Review

#17951 Implement occlusion culling for directional light shadow maps.
  crates/bevy_core_pipeline/src/experimental/mip_generation/mod.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_render/src/experimental/occlusion_culling/mod.rs
  examples/tools/scene_viewer/main.rs
Labels: A-Rendering, C-Performance, S-Needs-Review

#17958 Fix issue with `define_label!` instantiation in a 3rd party crate
  crates/bevy_ecs/src/label.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review, D-Macros

#17938 Only despawn scene entities still in the hierarchy
  crates/bevy_scene/src/lib.rs
  crates/bevy_scene/src/scene_spawner.rs
Labels: S-Ready-For-Final-Review, A-Scenes, D-Straightforward

#17974 Enable `nonstandard_macro_braces` and enforce `[]` for `children!`
  Cargo.toml
  benches/Cargo.toml
  clippy.toml
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Cross-Cutting

#17936 Use fully qualified syntax in assertions.
  crates/bevy_ecs/src/storage/blob_array.rs
  crates/bevy_ecs/src/storage/thin_array_ptr.rs
Labels: C-Bug, D-Trivial, A-ECS, S-Ready-For-Final-Review

#17890 Fix 1x1 dds textures being interpreted as 1-dimensional
  crates/bevy_image/src/dds.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, D-Straightforward

#17980 Fix bugs in the new non-bindless mesh material allocator.
  crates/bevy_pbr/src/material_bind_groups.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, P-Regression

#17963 Reextract a mesh on the next frame if its material couldn't be prepared on the frame we first encountered it.
  crates/bevy_pbr/src/render/mesh.rs
Labels: C-Bug, A-Rendering, P-Regression, S-Needs-Review

#17979 Reallocate materials when they change.
  crates/bevy_pbr/src/material.rs
Labels: C-Bug, A-Rendering, P-Regression, S-Needs-Review
