Repository bevyengine/bevy, pull requests merged in 2025-07, with the labels that each got.

#19885 Use RenderStartup in MaterialPlugin
  crates/bevy_pbr/src/material.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#19886 Use RenderStartup in custom_post_processing example
  examples/shader/custom_post_processing.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#17373 Composable Pipeline Specialization
  crates/bevy_render/macros/src/lib.rs
  crates/bevy_render/macros/src/specialize.rs
  crates/bevy_render/src/render_resource/mod.rs
  crates/bevy_render/src/render_resource/pipeline.rs
  crates/bevy_render/src/render_resource/specialize.rs
  examples/shader/custom_phase_item.rs
  release-content/migration-guides/composable_specialization.md
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Modest, D-Macros

#19894 EntityEvent derive: Fix silent error
  crates/bevy_ecs/macros/src/component.rs
Labels: A-ECS, S-Ready-For-Final-Review, D-Macros

#19855 Change core widgets to use callback enum instead of option
  crates/bevy_core_widgets/src/callback.rs
  crates/bevy_core_widgets/src/core_button.rs
  crates/bevy_core_widgets/src/core_checkbox.rs
  crates/bevy_core_widgets/src/core_radio.rs
  crates/bevy_core_widgets/src/core_slider.rs
  crates/bevy_core_widgets/src/lib.rs
  crates/bevy_feathers/src/controls/button.rs
  crates/bevy_feathers/src/controls/slider.rs
  examples/ui/core_widgets.rs
  examples/ui/core_widgets_observers.rs
  examples/ui/feathers.rs
  release-content/release-notes/headless-widgets.md
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#19867 Move `ExtractInstancesPlugin<EnvironmentMapIds>` init to app.
  crates/bevy_pbr/src/light_probe/mod.rs
Labels: C-Bug, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#19890 Correctly disable prepass/shadows when configured on MaterialPlugin<M>
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, P-Regression

#19895 Solari: Merge reservoir file, reformulate confidence weight
  crates/bevy_solari/src/realtime/mod.rs
  crates/bevy_solari/src/realtime/reservoir.wgsl
  crates/bevy_solari/src/realtime/restir_di.wgsl
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review

#19881 Newtyped `ScrollPosition`
  crates/bevy_core_widgets/src/core_scrollbar.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/ui_node.rs
  examples/testbed/full_ui.rs
  examples/ui/scroll.rs
  examples/ui/scrollbars.rs
  release-content/migration-guides/Newtype_ScrollPosition.md
Labels: C-Docs, D-Trivial, A-UI, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#19691 UI z-ordering fix
  crates/bevy_ui/src/render/debug_overlay.rs
  crates/bevy_ui/src/render/gradient.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
  examples/testbed/ui.rs
  release-content/migration-guides/stack_z_offsets_changes.md
Labels: C-Bug, A-Rendering, A-UI, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Straightforward, M-Deliberate-Rendering-Change

#19909 Flatten `PrepassPipelineInternal` into `PrepassPipeline`.
  crates/bevy_pbr/src/meshlet/material_pipeline_prepare.rs
  crates/bevy_pbr/src/prepass/mod.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#19896 Replace `Handle::Weak` with `Handle::Uuid`.
  crates/bevy_anti_aliasing/src/smaa/mod.rs
  crates/bevy_asset/src/handle.rs
  crates/bevy_core_pipeline/src/experimental/mip_generation/mod.rs
  crates/bevy_core_pipeline/src/post_process/mod.rs
  crates/bevy_gizmos/src/retained.rs
  crates/bevy_pbr/src/decal/forward.rs
  crates/bevy_pbr/src/volumetric_fog/render.rs
  crates/bevy_render/src/texture/mod.rs
  crates/bevy_text/src/font_atlas_set.rs
  crates/bevy_text/src/glyph.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/render/mod.rs
  examples/2d/mesh2d_manual.rs
  examples/shader/compute_shader_game_of_life.rs
  examples/tools/scene_viewer/scene_viewer_plugin.rs
  release-content/migration-guides/handle_weak_replaced_with_handle_uuid.md
Labels: A-Assets, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Blessed, D-Straightforward

#19908 Implement `MapEntities` for arrays, `HashMap`, `BTreeMap`, `IndexMap`
  crates/bevy_ecs/src/entity/map_entities.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Scenes, A-Networking, X-Uncontroversial, D-Straightforward

#19888 fix skin uniform buffer size
  crates/bevy_pbr/src/render/skin.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, O-WebGPU, X-Uncontroversial, D-Straightforward

#19094 Add test that repros #11111 (different loader settings produce same asset)
  crates/bevy_asset/src/lib.rs
Labels: A-Assets, S-Ready-For-Final-Review, C-Testing, X-Contentious, D-Straightforward

#19897 Use `RenderStartup` in `bevy_anti_aliasing`.
  crates/bevy_anti_aliasing/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_anti_aliasing/src/fxaa/mod.rs
  crates/bevy_anti_aliasing/src/smaa/mod.rs
  crates/bevy_anti_aliasing/src/taa/mod.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#19792 Set checkbox and radio fill color to gray when disabled in core widgets example
  examples/ui/core_widgets.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Art

#19928 Feathers toggle switches.
  crates/bevy_feathers/Cargo.toml
  crates/bevy_feathers/src/constants.rs
  crates/bevy_feathers/src/controls/checkbox.rs
  crates/bevy_feathers/src/controls/mod.rs
  crates/bevy_feathers/src/controls/toggle_switch.rs
  crates/bevy_feathers/src/dark_theme.rs
  crates/bevy_feathers/src/tokens.rs
  examples/ui/feathers.rs
  release-content/release-notes/feathers.md
Labels: C-Feature, A-UI, S-Ready-For-Final-Review, M-Needs-Release-Note, A-Art

#19923 spec_v2: minor revisions
  crates/bevy_render/macros/src/lib.rs
  crates/bevy_render/macros/src/specializer.rs
  crates/bevy_render/src/render_resource/mod.rs
  crates/bevy_render/src/render_resource/specializer.rs
Labels: C-Docs, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#19352 Use `SlotMap`s to store systems and system sets in `Schedule`s
  Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/graph/graph_map.rs
  crates/bevy_ecs/src/schedule/graph/node.rs
  crates/bevy_ecs/src/schedule/pass.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/stepping.rs
  examples/games/stepping.rs
  release-content/migration-guides/schedule_slotmaps.md
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Modest

#19857 Add support for returning all `Component` and values to query method in the Bevy Remote Protocol
  crates/bevy_remote/Cargo.toml
  crates/bevy_remote/src/builtin_methods.rs
  crates/bevy_remote/src/lib.rs
  examples/remote/client.rs
  examples/remote/server.rs
Labels: C-Feature, S-Ready-For-Final-Review, A-Editor, A-Dev-Tools

#19936 improved the entity_index_map unit test
  crates/bevy_ecs/src/relationship/relationship_source_collection.rs
Labels: A-ECS, S-Ready-For-Final-Review, C-Testing, D-Straightforward

#19939 Remove leftover apply deferred example metadata from Cargo.toml
  Cargo.toml
Labels: C-Examples, S-Ready-For-Final-Review

#19145 Have `System::run_unsafe` return `Result`.
  benches/benches/bevy_ecs/iteration/iter_simple_system.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/event/mod.rs
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/builder.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/commands/command.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/input.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/observer_system.rs
  crates/bevy_ecs/src/system/schedule_system.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/system/system_registry.rs
  crates/bevy_utils/src/debug_info.rs
  release-content/migration-guides/system_run_returns_result.md
Labels: C-Feature, A-ECS, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Uncontroversial, D-Modest, D-Unsafe

#19921 Add options for selecting adapter by name and forcing fallback
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/renderer/mod.rs
  crates/bevy_render/src/settings.rs
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review

#19930 bevy_reflect: Remove unnecessary `allow(unused_mut)`.
  crates/bevy_reflect/derive/src/registration.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Reflection, D-Macros

#19933 fix panic looking for extension in multibyte unicode paths
  crates/bevy_asset/src/path.rs
Labels: C-Bug, D-Trivial, A-Assets, P-Crash, S-Ready-For-Final-Review

#19945 add must_use to register_component_hooks
  crates/bevy_ecs/src/world/mod.rs
Labels: C-Bug, D-Trivial, A-ECS, S-Ready-For-Final-Review

#19901 Use `RenderStartup` in `bevy_ui`.
  crates/bevy_ui_render/src/box_shadow.rs
  crates/bevy_ui_render/src/gradient.rs
  crates/bevy_ui_render/src/lib.rs
  crates/bevy_ui_render/src/pipeline.rs
  crates/bevy_ui_render/src/ui_material_pipeline.rs
  crates/bevy_ui_render/src/ui_texture_slice_pipeline.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#19953 Move Camera3d/2d to bevy_camera
  crates/bevy_camera/src/components.rs
  crates/bevy_camera/src/lib.rs
  crates/bevy_core_pipeline/Cargo.toml
  crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_render/src/camera.rs
Labels: A-Rendering, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, A-Camera

#19954 move some Visibility stuff to bevy_camera::visibility
  crates/bevy_camera/src/visibility/mod.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/components.rs
  crates/bevy_pbr/src/lib.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#19956 move spot light function into spot light file
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/light/spot_light.rs
  crates/bevy_pbr/src/render/light.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#19957 make cluster assign not depend on RenderAdapter/RenderDevice
  crates/bevy_pbr/src/cluster/assign.rs
  crates/bevy_pbr/src/cluster/mod.rs
  crates/bevy_pbr/src/lib.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#19960 Move CubemapLayout out of decal code
  crates/bevy_camera/src/primitives.rs
  crates/bevy_pbr/src/decal/clustered.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#19961 Minor code readability improvement in enum_utility.access_field
  crates/bevy_reflect/derive/src/enum_utility.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Reflection

#19958 move calculate_cluster_factors to cluster assign
  crates/bevy_pbr/src/cluster/assign.rs
  crates/bevy_pbr/src/render/light.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#19962 move light stuff out of decal cluster
  crates/bevy_pbr/src/decal/clustered.rs
  crates/bevy_pbr/src/light/directional_light.rs
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/light/point_light.rs
  crates/bevy_pbr/src/light/spot_light.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#19963 move ShadowsEnabled to material
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/material.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#19964 fix a couple typos in CubemapLayout
  crates/bevy_camera/src/primitives.rs
Labels: A-Rendering, S-Needs-Review

#19959 move ClusteredDecal to cluster module
  crates/bevy_pbr/src/cluster/assign.rs
  crates/bevy_pbr/src/cluster/mod.rs
  crates/bevy_pbr/src/decal/clustered.rs
Labels: A-Rendering, S-Needs-Review

#19972 consistently dont use smallvec default features
  crates/bevy_animation/Cargo.toml
  crates/bevy_camera/Cargo.toml
  crates/bevy_core_pipeline/Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_gltf/Cargo.toml
  crates/bevy_math/Cargo.toml
  crates/bevy_pbr/Cargo.toml
  crates/bevy_reflect/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_text/Cargo.toml
  crates/bevy_ui/Cargo.toml
  crates/bevy_ui_render/Cargo.toml
Labels: D-Trivial, C-Dependencies, S-Ready-For-Final-Review, A-Cross-Cutting

#19973 extract cluster extract to a separate module
  crates/bevy_pbr/src/cluster/extract_and_prepare.rs
  crates/bevy_pbr/src/cluster/mod.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#19967 Remove `Bundle::register_required_components`
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/spawn.rs
  release-content/migration-guides/remove_bundle_register_required_components.md
Labels: D-Trivial, A-ECS, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#19985 dont hard code clustering limits on cpu side so they can be informed by Limits later
  crates/bevy_pbr/src/cluster/assign.rs
  crates/bevy_pbr/src/cluster/extract_and_prepare.rs
  crates/bevy_pbr/src/cluster/mod.rs
Labels: A-Rendering, C-Code-Quality, C-Usability, D-Straightforward, S-Needs-Review

#19991 bevy_light
  crates/bevy_light/Cargo.toml
  crates/bevy_light/LICENSE-APACHE
  crates/bevy_light/LICENSE-MIT
  crates/bevy_light/src/ambient_light.rs
  crates/bevy_light/src/cascade.rs
  crates/bevy_light/src/cluster/assign.rs
  crates/bevy_light/src/cluster/mod.rs
  crates/bevy_light/src/cluster/test.rs
  crates/bevy_light/src/directional_light.rs
  crates/bevy_light/src/lib.rs
  crates/bevy_light/src/point_light.rs
  crates/bevy_light/src/probe.rs
  crates/bevy_light/src/spot_light.rs
  crates/bevy_light/src/volumetric.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/cluster.rs
  crates/bevy_pbr/src/decal/clustered.rs
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light_probe/environment_map.rs
  crates/bevy_pbr/src/light_probe/irradiance_volume.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/meshlet/material_pipeline_prepare.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_pbr/src/volumetric_fog/mod.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/extract_impls.rs
  crates/bevy_render/src/lib.rs
  examples/3d/light_textures.rs
  tools/example-showcase/reduce-light-cluster-config.patch
Labels: A-Rendering, S-Ready-For-Final-Review, X-Controversial

#19995 remove fast_sqrt in favor of sqrt
  crates/bevy_render/src/maths.wgsl
Labels: A-Rendering, C-Performance, C-Code-Quality, S-Ready-For-Final-Review

#19926 Run `RenderStartup` in/before extract instead of after it.
  crates/bevy_app/src/sub_app.rs
  crates/bevy_render/src/lib.rs
  release-content/migration-guides/extract_fn_is_mut.md
Labels: C-Bug, A-Rendering, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#19996 fix meshlets with charlotte
  crates/bevy_pbr/src/meshlet/meshlet_mesh_material.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#19997 make optional crates for mesh, camera, and light
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/lib.rs
  crates/bevy_pbr/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/lib.rs
Labels: A-Rendering, C-Usability, S-Needs-Review

#18763 Add test for invalid skinned meshes
  Cargo.toml
  tests/3d/test_invalid_skinned_mesh.rs
Labels: A-Rendering, S-Ready-For-Final-Review, A-Animation, C-Testing, X-Uncontroversial, D-Straightforward

#18812 Fix the extended_material example on WebGL2
  assets/shaders/extended_material.wgsl
  examples/shader/extended_material.rs
Labels: C-Bug, A-Rendering, C-Examples, S-Ready-For-Final-Review, O-WebGL2, D-Straightforward

#19295 Explanation for the '3d shapes' example
  examples/3d/3d_shapes.rs
Labels: C-Docs, A-Rendering, C-Examples, S-Ready-For-Final-Review, D-Straightforward

#19357 SpatialListener now requires a Transform
  crates/bevy_audio/src/audio.rs
  crates/bevy_audio/src/audio_output.rs
Labels: A-ECS, A-Audio, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#19929 bevy_reflect: Avoid trait bounds on non-generic types
  crates/bevy_reflect/derive/src/lib.rs
  crates/bevy_reflect/derive/src/where_clause_options.rs
  crates/bevy_reflect/src/impls/core/sync.rs
  crates/bevy_reflect/src/lib.rs
Labels: C-Performance, C-Code-Quality, S-Ready-For-Final-Review, A-Reflection, X-Uncontroversial, D-Macros

#19942 Implement display for direction
  crates/bevy_math/src/direction.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math, D-Straightforward

#19980 Add parent ID to the `B0004` log message
  crates/bevy_ecs/src/hierarchy.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#20000 Move IrradianceVolume to bevy_light
  crates/bevy_light/src/lib.rs
  crates/bevy_light/src/probe.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light_probe/irradiance_volume.rs
  crates/bevy_pbr/src/light_probe/mod.rs
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review

#20017 Rename `send_event` and similar methods to `write_event`
  benches/benches/bevy_ecs/events/iter.rs
  benches/benches/bevy_ecs/events/mod.rs
  benches/benches/bevy_ecs/events/write.rs
  crates/bevy_app/src/app.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_dev_tools/src/ci_testing/systems.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/event/collections.rs
  crates/bevy_ecs/src/event/event_cursor.rs
  crates/bevy_ecs/src/event/mod.rs
  crates/bevy_ecs/src/event/mutator.rs
  crates/bevy_ecs/src/event/reader.rs
  crates/bevy_ecs/src/event/writer.rs
  crates/bevy_ecs/src/lifecycle.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/system/commands/command.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input_focus/src/lib.rs
  crates/bevy_render/src/pipelined_rendering.rs
  crates/bevy_state/src/app.rs
  crates/bevy_state/src/state_scoped_events.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_ui/src/widget/viewport.rs
  crates/bevy_winit/src/state.rs
  examples/3d/clustered_decals.rs
  examples/3d/light_textures.rs
  examples/ecs/component_hooks.rs
  examples/ecs/send_and_receive_events.rs
  release-content/migration-guides/send_event_rename.md
  tests/how_to_test_systems.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Contentious, D-Straightforward

#20010 UI gradients long hue paths fix
  crates/bevy_ui_render/src/gradient.wgsl
  examples/testbed/ui.rs
Labels: C-Bug, A-Rendering, A-UI, S-Ready-For-Final-Review, D-Straightforward, D-Shaders, A-Color, M-Deliberate-Rendering-Change

#19408 Clean up several miscellaneous uses of `weak_handle`.
  crates/bevy_anti_aliasing/src/smaa/mod.rs
  crates/bevy_asset/src/handle.rs
  crates/bevy_core_pipeline/src/experimental/mip_generation/mod.rs
  crates/bevy_core_pipeline/src/post_process/mod.rs
  crates/bevy_pbr/src/meshlet/pipelines.rs
  crates/bevy_pbr/src/volumetric_fog/mod.rs
  crates/bevy_pbr/src/volumetric_fog/render.rs
  examples/2d/mesh2d_manual.rs
  release-content/migration-guides/chromatic_aberration_option.md
Labels: A-Rendering, A-Assets, S-Ready-For-Final-Review, D-Modest

#20034 enable syn/full in bevy_render_macros
  crates/bevy_render/macros/Cargo.toml
Labels: D-Trivial, C-Dependencies, S-Ready-For-Final-Review

#20015 Simplify self-edge checking in schedule building
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: C-Bug, A-ECS, C-Code-Quality, S-Ready-For-Final-Review, X-Uncontroversial, D-Modest

#20036 Change CoreWidgets plugin to plugin group.
  crates/bevy_core_widgets/src/lib.rs
  examples/ui/core_widgets.rs
  examples/ui/core_widgets_observers.rs
  examples/ui/feathers.rs
  release-content/release-notes/headless-widgets.md
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#17976 Material, mesh, skin extraction optimization
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/skin.rs
  crates/bevy_sprite/src/mesh2d/material.rs
Labels: A-Rendering, C-Performance, S-Needs-Review

#19277 Add frame_time graph to fps_overlay v2
  crates/bevy_dev_tools/Cargo.toml
  crates/bevy_dev_tools/src/fps_overlay.rs
  crates/bevy_dev_tools/src/frame_time_graph/frame_time_graph.wgsl
  crates/bevy_dev_tools/src/frame_time_graph/mod.rs
  crates/bevy_dev_tools/src/lib.rs
  examples/dev_tools/fps_overlay.rs
  release-content/release-notes/frame_time_graph.md
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, A-Diagnostics, M-Needs-Release-Note, A-Dev-Tools, D-Modest

#20044 Use PluginGroup for SolariPlugins
  crates/bevy_solari/src/lib.rs
  crates/bevy_solari/src/pathtracer/mod.rs
  crates/bevy_solari/src/realtime/mod.rs
  crates/bevy_solari/src/scene/mod.rs
  examples/3d/solari.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#20063 Split `component.rs`
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/component/clone.rs
  crates/bevy_ecs/src/component/info.rs
  crates/bevy_ecs/src/component/mod.rs
  crates/bevy_ecs/src/component/register.rs
  crates/bevy_ecs/src/component/required.rs
  crates/bevy_ecs/src/component/tick.rs
Labels: A-ECS, C-Code-Quality, P-High, S-Ready-For-Final-Review, X-Uncontroversial

#20024 Add release notes and a migration guide for `RenderStartup`.
  release-content/migration-guides/render_startup.md
  release-content/release-notes/render_startup.md
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review, M-Needs-Migration-Guide, M-Needs-Release-Note

#20071 Refactor `3d_viewport_to_world` example with let chains
  examples/3d/3d_viewport_to_world.rs
Labels: D-Trivial, C-Examples, C-Code-Quality, S-Ready-For-Final-Review

#20068 Adjust specular_multiscatter to not take LightingInput
  crates/bevy_pbr/src/render/pbr_lighting.wgsl
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#20076 Fix crash on meshes with morphs + skins + motion blur when not using storage buffers
  crates/bevy_pbr/src/render/mesh.rs
Labels: C-Bug, A-Rendering, P-Crash, S-Ready-For-Final-Review, A-Animation, D-Straightforward

#20066 `ColorStop` constructor functions
  crates/bevy_ui/src/gradients.rs
Labels: D-Trivial, A-UI, C-Usability, S-Ready-For-Final-Review

#20067 Fix SSAO specular occlusion roughness bug
  crates/bevy_pbr/src/render/pbr_fragment.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#20064 `OverrideClip` interaction fix
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/picking_backend.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review, D-Straightforward, A-Picking

#20052 Factor out up-choice in shadow cubemap sampling orthonormalize
  crates/bevy_pbr/src/render/shadow_sampling.wgsl
  crates/bevy_render/src/maths.wgsl
Labels: C-Bug, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#20054 Fix adapter forcing breaking wasm builds
  crates/bevy_render/src/renderer/mod.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20080 Thoroughly document `UninitializedId` semantics
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: C-Docs, A-ECS, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#20084 Update `sysinfo` version to `0.36.0`
  crates/bevy_diagnostic/Cargo.toml
Labels: D-Trivial, C-Dependencies, S-Ready-For-Final-Review, A-Diagnostics

#20113 Fix visibility (re)use in Solari DI
  crates/bevy_solari/src/realtime/restir_di.wgsl
  crates/bevy_solari/src/realtime/restir_gi.wgsl
  release-content/release-notes/bevy_solari.md
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review

#20102 FIX - RelativeCursorPosition Changed<> query filter
  crates/bevy_ui/src/focus.rs
Labels: A-UI, S-Ready-For-Final-Review, D-Straightforward, A-Picking

#19902 bevy_reflect: remove unnecessary `const _` around `TypePath` impl
  crates/bevy_reflect/derive/src/impls/typed.rs
Labels: C-Performance, S-Ready-For-Final-Review, A-Reflection, D-Straightforward, D-Macros

#20088 Split `bundle.rs`
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/bundle/impls.rs
  crates/bevy_ecs/src/bundle/info.rs
  crates/bevy_ecs/src/bundle/insert.rs
  crates/bevy_ecs/src/bundle/mod.rs
  crates/bevy_ecs/src/bundle/remove.rs
  crates/bevy_ecs/src/bundle/spawner.rs
  crates/bevy_ecs/src/bundle/tests.rs
Labels: A-ECS, C-Code-Quality, P-High, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#18916 Fixing a crash when minimizing a window with custom viewport. (#16704)
  crates/bevy_render/src/camera.rs
Labels: C-Bug, A-Rendering, A-Windowing, S-Ready-For-Final-Review, D-Straightforward

#19117 Fix a `NestedLoader` code path that failed to use its meta transform
  crates/bevy_asset/src/loader_builders.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review, D-Straightforward

#19922 bevy_reflect: Use `active_types` instead of `active_fields` where appropriate
  crates/bevy_reflect/derive/src/derive_data.rs
  crates/bevy_reflect/derive/src/where_clause_options.rs
Labels: C-Performance, C-Code-Quality, S-Ready-For-Final-Review, A-Reflection

#19999 Use `RenderStartup` for `bevy_pbr` for some basic cases.
  crates/bevy_pbr/src/deferred/mod.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/lightmap/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/volumetric_fog/mod.rs
  crates/bevy_pbr/src/volumetric_fog/render.rs
  crates/bevy_pbr/src/wireframe.rs
  release-content/migration-guides/render_startup.md
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#20016 Prevent TOCTOU bugs in ComponentsQueuedRegistrator
  crates/bevy_ecs/src/component/register.rs
  crates/bevy_ecs/src/lib.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#20053 Add zstd release note
  crates/bevy_image/src/ktx2.rs
  release-content/release-notes/faster-zstd-option.md
Labels: A-Rendering, S-Ready-For-Final-Review

#20109 Mitigate Tracy dep version woes
  docs/profiling.md
Labels: C-Docs, C-Performance, S-Ready-For-Final-Review, A-Diagnostics

#20133 `GpuReadbackPlugin`: Allow reading only a part of a buffer
  crates/bevy_render/src/gpu_readback.rs
  examples/shader/gpu_readback.rs
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review

#20077 Fix anisotropy not working when material is lit by environment map light
  crates/bevy_pbr/src/render/pbr_functions.wgsl
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward, M-Deliberate-Rendering-Change

#20082 Rhombus sampling
  crates/bevy_math/src/sampling/shape_sampling.rs
Labels: C-Feature, S-Ready-For-Final-Review, A-Math, D-Straightforward

#20083 Fix AmbientLight::affects_lightmapped_meshes not working
  crates/bevy_pbr/src/render/mesh_view_types.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
Labels: A-Rendering, S-Ready-For-Final-Review, D-Straightforward

#20089 Port the physics in fixed timestep example to 3D
  examples/movement/physics_in_fixed_timestep.rs
Labels: A-ECS, C-Examples, S-Ready-For-Final-Review, A-Physics, A-Time, D-Straightforward, M-Deliberate-Rendering-Change

#20097 Fix link to `bevy_solari` logo
  crates/bevy_solari/src/lib.rs
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review, X-Uncontroversial, D-Domain-Agnostic

#20098 Constify `gradients` helper functions
  crates/bevy_ui/src/gradients.rs
Labels: D-Trivial, A-UI, C-Code-Quality, S-Ready-For-Final-Review

#20101 Split `BufferedEvent` from `Event`
  benches/benches/bevy_ecs/events/iter.rs
  benches/benches/bevy_ecs/events/write.rs
  crates/bevy_a11y/src/lib.rs
  crates/bevy_app/src/app.rs
  crates/bevy_asset/src/event.rs
  crates/bevy_dev_tools/src/ci_testing/config.rs
  crates/bevy_ecs/README.md
  crates/bevy_ecs/examples/events.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/event/base.rs
  crates/bevy_ecs/src/event/collections.rs
  crates/bevy_ecs/src/event/event_cursor.rs
  crates/bevy_ecs/src/event/mod.rs
  crates/bevy_ecs/src/event/mutator.rs
  crates/bevy_ecs/src/event/reader.rs
  crates/bevy_ecs/src/event/writer.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/lifecycle.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input/src/gestures.rs
  crates/bevy_input/src/keyboard.rs
  crates/bevy_input/src/mouse.rs
  crates/bevy_input/src/touch.rs
  crates/bevy_picking/src/backend.rs
  crates/bevy_picking/src/lib.rs
  crates/bevy_picking/src/pointer.rs
  crates/bevy_state/src/state/transitions.rs
  crates/bevy_state/src/state_scoped_events.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_time/src/time.rs
  crates/bevy_window/src/event.rs
  crates/bevy_winit/src/lib.rs
  examples/3d/mixed_lighting.rs
  examples/app/log_layers_ecs.rs
  examples/async_tasks/external_source_external_thread.rs
  examples/audio/pitch.rs
  examples/ecs/component_hooks.rs
  examples/ecs/event.rs
  examples/ecs/send_and_receive_events.rs
  examples/games/breakout.rs
  examples/helpers/widgets.rs
  examples/ui/size_constraints.rs
  examples/window/custom_user_event.rs
  release-content/migration-guides/pointer_target.md
  release-content/release-notes/event_split.md
  tests/how_to_test_systems.rs
Labels: A-ECS, S-Ready-For-Final-Review, X-Blessed, D-Straightforward

#20108 feat: implement clone for IntoPipeSystem
  crates/bevy_ecs/src/system/combinator.rs
Labels: A-ECS, S-Ready-For-Final-Review, D-Straightforward

#20118 Mini Blit refactor
  crates/bevy_core_pipeline/src/blit/mod.rs
  crates/bevy_core_pipeline/src/msaa_writeback.rs
  crates/bevy_core_pipeline/src/upscaling/node.rs
Labels: D-Trivial, A-Rendering, C-Usability, S-Ready-For-Final-Review

#20120 Allow NotShadowCaster to be used with HierarchyPropagatePlugin.
  crates/bevy_light/src/lib.rs
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review

#20124 Switch most examples to use `RenderStartup` instead of `finish` and `FromWorld`.
  examples/2d/mesh2d_manual.rs
  examples/3d/manual_material.rs
  examples/shader/compute_shader_game_of_life.rs
  examples/shader/custom_render_phase.rs
  examples/shader/custom_shader_instancing.rs
  examples/shader/gpu_readback.rs
  examples/shader/specialized_mesh_pipeline.rs
  examples/shader/texture_binding_array.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review, D-Straightforward

#20126 Streamline `GetOwnership`/`FromArg`/`IntoReturn`
  crates/bevy_reflect/derive/src/impls/func/from_arg.rs
  crates/bevy_reflect/derive/src/impls/func/get_ownership.rs
  crates/bevy_reflect/derive/src/impls/func/into_return.rs
  crates/bevy_reflect/src/func/args/from_arg.rs
  crates/bevy_reflect/src/func/args/ownership.rs
  crates/bevy_reflect/src/func/macros.rs
  crates/bevy_reflect/src/func/return_type.rs
  crates/bevy_reflect/src/impls/core/panic.rs
  crates/bevy_reflect/src/impls/core/primitives.rs
  crates/bevy_reflect/src/impls/std/path.rs
Labels: C-Performance, C-Code-Quality, S-Ready-For-Final-Review, A-Reflection

#20127 Link `ComponentIdFor` in the `ComponentId` related docs
  crates/bevy_ecs/src/component/info.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#20142 Rename the `InterpolationColorSpace` variants to match `Color`.
  crates/bevy_feathers/src/controls/slider.rs
  crates/bevy_ui/src/gradients.rs
  crates/bevy_ui_render/src/gradient.rs
  examples/testbed/ui.rs
  examples/ui/gradients.rs
Labels: D-Trivial, A-UI, C-Code-Quality, S-Ready-For-Final-Review, M-Deliberate-Rendering-Change

#20119 Improve node encapsulation in `ScheduleGraph`
  crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/node.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  release-content/migration-guides/schedule_cleanup.md
  release-content/migration-guides/schedule_slotmaps.md
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Modest

#20002 Use `RenderStartup` for all basic cases in `bevy_core_pipeline`.
  crates/bevy_core_pipeline/src/auto_exposure/mod.rs
  crates/bevy_core_pipeline/src/auto_exposure/pipeline.rs
  crates/bevy_core_pipeline/src/blit/mod.rs
  crates/bevy_core_pipeline/src/bloom/downsampling_pipeline.rs
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/bloom/upsampling_pipeline.rs
  crates/bevy_core_pipeline/src/dof/mod.rs
  crates/bevy_core_pipeline/src/experimental/mip_generation/mod.rs
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_core_pipeline/src/motion_blur/mod.rs
  crates/bevy_core_pipeline/src/motion_blur/pipeline.rs
  crates/bevy_core_pipeline/src/oit/mod.rs
  crates/bevy_core_pipeline/src/post_process/mod.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_core_pipeline/src/skybox/prepass.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  release-content/migration-guides/render_startup.md
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#20104 Remove the need to derive `Event` when deriving `EntityEvent`
  benches/benches/bevy_ecs/observers/propagation.rs
  benches/benches/bevy_ecs/observers/simple.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_app/src/app.rs
  crates/bevy_core_widgets/src/core_checkbox.rs
  crates/bevy_core_widgets/src/core_slider.rs
  crates/bevy_ecs/README.md
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/event/base.rs
  crates/bevy_ecs/src/lifecycle.rs
  crates/bevy_ecs/src/observer/distributed_storage.rs
  crates/bevy_ecs/src/observer/entity_cloning.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/observer/system_param.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_input_focus/src/lib.rs
  crates/bevy_picking/src/events.rs
  crates/bevy_render/src/gpu_readback.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_scene/src/scene_spawner.rs
  examples/animation/animated_mesh_events.rs
  examples/animation/animation_events.rs
  examples/ecs/observer_propagation.rs
  examples/ecs/observers.rs
  examples/no_std/library/src/lib.rs
  examples/ui/scroll.rs
  release-content/release-notes/event_split.md
Labels: A-ECS, S-Ready-For-Final-Review, X-Blessed, D-Straightforward

#20154 Added finish method for timer
  crates/bevy_time/src/timer.rs
Labels: D-Trivial, S-Ready-For-Final-Review, A-Time

#20074 Preconvert colors before sending to shader
  Cargo.toml
  crates/bevy_ui_render/src/gradient.rs
  crates/bevy_ui_render/src/gradient.wgsl
  examples/README.md
  examples/stress_tests/many_gradients.rs
Labels: A-Rendering, C-Performance, A-UI, C-Code-Quality, S-Ready-For-Final-Review, M-Deliberate-Rendering-Change

#20161 fix crash in light textures example
  examples/3d/light_textures.rs
Labels: C-Bug, D-Trivial, A-Rendering, C-Examples, S-Ready-For-Final-Review

#20162 Add `EntityWorldMut::(try_)resource_scope`
  crates/bevy_ecs/src/event/update.rs
  crates/bevy_ecs/src/reflect/entity_commands.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_transform/src/commands.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#19924 TilemapChunk single quad; TileData (color/visibility)
  crates/bevy_sprite/src/tilemap_chunk/mod.rs
  crates/bevy_sprite/src/tilemap_chunk/tilemap_chunk_material.rs
  crates/bevy_sprite/src/tilemap_chunk/tilemap_chunk_material.wgsl
  examples/2d/tilemap_chunk.rs
  release-content/release-notes/tilemap-chunk-rendering.md
Labels: C-Feature, A-Rendering, M-Needs-Release-Note, S-Needs-Review

#20180 Remove unnecessary + `use<>`
  crates/bevy_ecs/src/entity_disabling.rs
  examples/asset/multi_asset_sync.rs
  examples/ui/button.rs
  examples/usage/context_menu.rs
Labels: D-Trivial, C-Code-Quality, P-High, S-Ready-For-Final-Review, X-Uncontroversial

#20190 dont normalize twice for no reason in octahedral_decode
  crates/bevy_pbr/src/render/utils.wgsl
Labels: D-Trivial, A-Rendering, C-Performance, C-Code-Quality, S-Ready-For-Final-Review, P-Critical, A-Math, A-Utils, X-Uncontroversial, X-Blessed, D-Shaders

#20199 Remove extraneous h parameter for D_GGX
  crates/bevy_pbr/src/render/pbr_lighting.wgsl
Labels: D-Trivial, A-Rendering, C-Code-Quality

#20209 Use `RenderStartup` for screenshot plugin.
  crates/bevy_render/src/view/window/screenshot.rs
  release-content/migration-guides/render_startup.md
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#20210 Use `RenderStartup` for meshlets.
  crates/bevy_pbr/src/meshlet/meshlet_mesh_manager.rs
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/meshlet/pipelines.rs
  release-content/migration-guides/render_startup.md
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#20218 Fix relationship method names in comments
  examples/ecs/relationships.rs
Labels: C-Docs, D-Trivial, A-ECS, S-Ready-For-Final-Review

#18983 UI render graph setup refactor
  crates/bevy_ui_render/src/lib.rs
Labels: D-Trivial, A-Rendering, A-UI, C-Code-Quality, S-Ready-For-Final-Review

#19046 Allow entities to be added to a relationship using the new spawn api (remade)
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/spawn.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, X-Contentious

#20095 Implement `ShapeSample for CircularSector`
  crates/bevy_math/src/sampling/shape_sampling.rs
Labels: C-Feature, S-Ready-For-Final-Review, A-Math, D-Straightforward

#20111 Faster `FilteredEntity(Ref|Mut)` and `Entity(Ref|Mut)Except` by borrowing `Access`
  crates/bevy_animation/src/animation_curves.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/reflect/component.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_remote/src/builtin_methods.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review

#20130 Implement closest_point for Segment[23]d.
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
Labels: C-Feature, S-Ready-For-Final-Review, A-Math, D-Straightforward

#20144 Refactor actions cache to be build on main
  .github/workflows/ci.yml
  .github/workflows/example-run.yml
  .github/workflows/update-caches.yml
  .github/workflows/validation-jobs.yml
Labels: A-Build-System, C-Performance, S-Ready-For-Final-Review

#20184 Use `RenderStartup` for `occlusion_culling` example.
  examples/3d/occlusion_culling.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#20187 Fix `ComponentsRegistrator` unsoundness
  crates/bevy_ecs/src/component/register.rs
  crates/bevy_ecs/src/component/required.rs
  release-content/migration-guides/components-registrator-derefmut.md
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, P-Unsound

#20195 Use `RenderStartup` for `CopyDeferredLightingIdPipeline`.
  crates/bevy_core_pipeline/src/deferred/copy_lighting_id.rs
  release-content/migration-guides/render_startup.md
  tests/ecs/ambiguity_detection.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#20196 Clean up `NodeId` kind fetching
  crates/bevy_ecs/src/schedule/graph/graph_map.rs
  crates/bevy_ecs/src/schedule/graph/mod.rs
  crates/bevy_ecs/src/schedule/graph/node.rs
  crates/bevy_ecs/src/schedule/graph/tarjan_scc.rs
  crates/bevy_ecs/src/schedule/node.rs
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: D-Trivial, A-ECS, C-Code-Quality, S-Ready-For-Final-Review, D-Domain-Agnostic

#20204 Internal Entities
  crates/bevy_ecs/src/entity_disabling.rs
  crates/bevy_ecs/src/observer/distributed_storage.rs
  crates/bevy_ecs/src/system/system_registry.rs
  release-content/migration-guides/internal_entities.md
Labels: C-Usability, S-Ready-For-Final-Review, A-Dev-Tools, A-Cross-Cutting

#20213 Solari light tiles
  crates/bevy_solari/src/realtime/mod.rs
  crates/bevy_solari/src/realtime/node.rs
  crates/bevy_solari/src/realtime/prepare.rs
  crates/bevy_solari/src/realtime/presample_light_tiles.wgsl
  crates/bevy_solari/src/realtime/restir_di.wgsl
  crates/bevy_solari/src/realtime/restir_gi.wgsl
  crates/bevy_solari/src/scene/binder.rs
  crates/bevy_solari/src/scene/sampling.wgsl
  release-content/release-notes/bevy_solari.md
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, D-Complex

#20214 Make line segments meshable
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_mesh/src/primitives/dim2.rs
  crates/bevy_mesh/src/primitives/dim3/mod.rs
  crates/bevy_mesh/src/primitives/dim3/segment3d.rs
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review

#20227 Fix panic when focused entity is despawned
  crates/bevy_input_focus/src/lib.rs
Labels: C-Bug, P-Crash, A-UI, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#20230 Add a `Query::count()` method.
  crates/bevy_ecs/src/system/query.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#20239 fix branch name when installing rust in cache update action
  .github/workflows/update-caches.yml
Labels: C-Bug, A-Build-System, S-Ready-For-Final-Review

#20232 Rework one-to-one relationships to remove existing instead of panicking
  crates/bevy_ecs/src/relationship/mod.rs
  crates/bevy_ecs/src/relationship/relationship_source_collection.rs
Labels: C-Bug, A-ECS, P-Crash, S-Ready-For-Final-Review, X-Uncontroversial

#19428 Replace the `FORWARD_DECAL_MESH_HANDLE` with a resource that gets cloned out in a hook.
  crates/bevy_pbr/src/decal/forward.rs
Labels: A-Rendering, A-Assets, S-Ready-For-Final-Review, X-Contentious, D-Straightforward

#20153 enable codeql analysis
  .github/workflows/codeql.yml
Labels: C-Feature, A-Build-System, S-Ready-For-Final-Review, X-Blessed

#20255 Remove default implementation of `extend_from_iter` from RelationshipSourceCollection
  crates/bevy_ecs/src/relationship/relationship_source_collection.rs
  release-content/migration-guides/remove_default_extend_from_iter.md
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#20248 Improve test robustness
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/entity_disabling.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/world/command_queue.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Testing

#20263 Derive Copy and Clone for `NavAction`
  crates/bevy_input_focus/src/tab_navigation.rs
Labels: D-Trivial, S-Ready-For-Final-Review

#19076 Environment Map Filtering GPU pipeline
  crates/bevy_light/src/lib.rs
  crates/bevy_light/src/probe.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light_probe/copy.wgsl
  crates/bevy_pbr/src/light_probe/downsample.wgsl
  crates/bevy_pbr/src/light_probe/environment_filter.wgsl
  crates/bevy_pbr/src/light_probe/generate.rs
  crates/bevy_pbr/src/light_probe/irradiance_volume.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/render/pbr_lighting.wgsl
  crates/bevy_pbr/src/render/utils.wgsl
  crates/bevy_pbr/src/stbn.ktx2
  crates/bevy_solari/src/pathtracer/pathtracer.wgsl
  crates/bevy_solari/src/realtime/restir_di.wgsl
  crates/bevy_solari/src/realtime/restir_gi.wgsl
  crates/bevy_solari/src/scene/sampling.wgsl
  examples/3d/reflection_probes.rs
  release-content/release-notes/realtime-environment-map-filtering.md
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, D-Complex, M-Needs-Release-Note, M-Deliberate-Rendering-Change

#20260 Deprecate `iter_entities` and `iter_entities_mut`
  benches/benches/bevy_ecs/world/despawn.rs
  crates/bevy_ecs/src/entity_disabling.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/lib.rs
  release-content/migration-guides/deprecate_iter_entities.md
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, D-Modest

#20256 Better `ScheduleBuildError` introspection and handling
  crates/bevy_ecs/src/schedule/error.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  release-content/migration-guides/schedule_cleanup.md
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, D-Modest

#20293 Updated Material Reference link as the old link was returning a 404
  crates/bevy_pbr/src/pbr_material.rs
Labels: C-Docs, D-Trivial, A-Rendering

#20278 Delete `ui_material.rs`
  crates/bevy_ui/src/ui_material.rs
Labels: D-Trivial, A-UI, S-Ready-For-Final-Review

#20270 UI layout taffy sync fix
  crates/bevy_ui/src/layout/mod.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#20325 Rename `When` system param to `If`
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/system/builder.rs
  crates/bevy_ecs/src/system/system_param.rs
  release-content/migration-guides/system_run_returns_result.md
Labels: D-Trivial, A-ECS, S-Ready-For-Final-Review

#19697 Bug fix in Gizmo grid
  crates/bevy_gizmos/src/grid.rs
  examples/testbed/2d.rs
  examples/testbed/3d.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Gizmos, M-Deliberate-Rendering-Change

#20261 Support multiple unnamed fields in relationship derive
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/src/relationship/mod.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#19772 Fix intermittent drag-and-drop freezing on Windows
  crates/bevy_winit/src/state.rs
Labels: C-Bug, A-Windowing, O-Windows, S-Ready-For-Final-Review, P-Regression
