Repository bevyengine/bevy, pull requests merged in 2025-09, with the labels that each got.

#20811 fix reflect feature gate
  crates/bevy_window/src/cursor/mod.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review, A-Reflection, D-Straightforward

#20245 Extract text colors per glyph
  crates/bevy_ui_render/src/debug_overlay.rs
  crates/bevy_ui_render/src/gradient.rs
  crates/bevy_ui_render/src/lib.rs
  release-content/migration-guides/extract_ui_text_colors_per_glyph.md
Labels: A-Rendering, C-Performance, A-UI, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Text, D-Modest

#20689 Ensure systems passed to `Combine` cannot be called re-entrantly either
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/system/combinator.rs
  release-content/migration-guides/combine_soundness_fix.md
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, D-Complex, P-Unsound, D-Unsafe

#20744 Cleanup bevy_tasks::future module
  crates/bevy_tasks/src/futures.rs
  crates/bevy_tasks/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Tasks

#20807 Bump hashbrown to 0.16.0
  crates/bevy_platform/Cargo.toml
  crates/bevy_platform/src/hash.rs
  crates/bevy_reflect/Cargo.toml
  crates/bevy_reflect/src/impls/foldhash.rs
  crates/bevy_reflect/src/utility.rs
  tools/build-templated-pages/Cargo.toml
Labels: C-Dependencies, A-Cross-Cutting, X-Uncontroversial, D-Straightforward, S-Needs-Review

#20836 Add coloured text to the ui testbed example's text module
  examples/testbed/ui.rs
Labels: D-Trivial, C-Examples, A-UI, S-Ready-For-Final-Review, C-Testing, A-Text, M-Deliberate-Rendering-Change

#20837 Fix text span colors
  crates/bevy_ui_render/src/lib.rs
Labels: C-Bug, D-Trivial, A-UI, S-Ready-For-Final-Review, A-Text, M-Deliberate-Rendering-Change

#20827 `ui_target_camera` example
  Cargo.toml
  examples/README.md
  examples/ui/ui_target_camera.rs
Labels: C-Examples, A-UI, S-Ready-For-Final-Review, D-Straightforward

#20658 Solari PicaPica scene
  Cargo.toml
  crates/bevy_asset/src/io/web.rs
  crates/bevy_solari/src/realtime/world_cache_compact.wgsl
  examples/3d/solari.rs
  examples/helpers/camera_controller.rs
  release-content/release-notes/bevy_solari.md
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review

#20841 Impl ```AsAssetId``` for ```Sprite``` and ```ImageNode```
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_ui/src/widget/image.rs
Labels: C-Bug, D-Trivial, A-Rendering, A-Assets, S-Ready-For-Final-Review

#20830 Don't require cameras to have color render targets.
  Cargo.toml
  assets/shaders/show_depth_texture_material.wgsl
  crates/bevy_camera/src/camera.rs
  crates/bevy_render/src/camera.rs
  crates/bevy_render/src/view/window/screenshot.rs
  examples/README.md
  examples/shader_advanced/render_depth_to_texture.rs
Labels: C-Feature, A-Rendering, C-Examples, S-Ready-For-Final-Review, D-Straightforward

#20840 Add init_state to State example docs
  crates/bevy_state/src/state/states.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-States

#20850 rename variable
  crates/bevy_ui_render/src/lib.rs
Labels: D-Trivial, A-UI, C-Code-Quality, S-Ready-For-Final-Review

#20847 Add `#[doc(fake_variadic)]` to some places where it's missing
  crates/bevy_ecs/src/bundle/impls.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/spawn.rs
  crates/bevy_render/src/render_resource/specializer.rs
Labels: C-Docs, A-Rendering, A-ECS, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#20863 `prepare_uinodes` refactor
  crates/bevy_ui_render/src/lib.rs
Labels: D-Trivial, A-Rendering, A-UI, C-Code-Quality, S-Ready-For-Final-Review

#20450 Replace `from_` constructors on `TextFont` with `From` impls
  crates/bevy_text/src/text.rs
  examples/testbed/2d.rs
  release-content/migration-guides/remove_text_font_from_constructor_methods.md
Labels: D-Trivial, A-UI, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Text

#20857 rename bevy_anti_aliasing to bevy_anti_alias
  Cargo.toml
  crates/bevy_anti_alias/Cargo.toml
  crates/bevy_anti_alias/LICENSE-APACHE
  crates/bevy_anti_alias/LICENSE-MIT
  crates/bevy_anti_alias/README.md
  crates/bevy_anti_alias/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_anti_alias/src/contrast_adaptive_sharpening/node.rs
  crates/bevy_anti_alias/src/contrast_adaptive_sharpening/robust_contrast_adaptive_sharpening.wgsl
  crates/bevy_anti_alias/src/dlss/extract.rs
  crates/bevy_anti_alias/src/dlss/mod.rs
  crates/bevy_anti_alias/src/dlss/node.rs
  crates/bevy_anti_alias/src/dlss/prepare.rs
  crates/bevy_anti_alias/src/fxaa/fxaa.wgsl
  crates/bevy_anti_alias/src/fxaa/mod.rs
  crates/bevy_anti_alias/src/fxaa/node.rs
  crates/bevy_anti_alias/src/lib.rs
  crates/bevy_anti_alias/src/smaa/SMAAAreaLUT.ktx2
  crates/bevy_anti_alias/src/smaa/SMAASearchLUT.ktx2
  crates/bevy_anti_alias/src/smaa/mod.rs
  crates/bevy_anti_alias/src/smaa/smaa.wgsl
  crates/bevy_anti_alias/src/taa/mod.rs
  crates/bevy_anti_alias/src/taa/taa.wgsl
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_internal/src/lib.rs
  crates/bevy_solari/Cargo.toml
  crates/bevy_solari/src/realtime/node.rs
  crates/bevy_solari/src/realtime/prepare.rs
  docs/cargo_features.md
  examples/3d/anti_aliasing.rs
  examples/3d/deferred_rendering.rs
  examples/3d/pcss.rs
  examples/3d/scrolling_fog.rs
  examples/3d/skybox.rs
  examples/3d/solari.rs
  examples/3d/ssao.rs
  examples/3d/ssr.rs
  examples/3d/transmission.rs
  release-content/migration-guides/taa_non_experimental.md
Labels: A-Rendering, S-Ready-For-Final-Review

#20855 added anti-aliasing support for Custom Projection
  crates/bevy_anti_alias/src/dlss/extract.rs
  crates/bevy_anti_alias/src/taa/mod.rs
  crates/bevy_camera/src/projection.rs
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, D-Straightforward

#20879 Fix plugin_group macro with multiple nested plugin groups
  crates/bevy_app/src/plugin_group.rs
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, A-App, D-Macros

#20881 Note some features requiring WebGPU on Wasm builds
  crates/bevy_light/src/volumetric.rs
  crates/bevy_pbr/src/decal/forward.rs
  examples/3d/decal.rs
  examples/3d/volumetric_fog.rs
Labels: C-Docs, A-Rendering, C-Examples, O-Web, S-Ready-For-Final-Review, O-WebGPU, O-WebGL2, D-Straightforward

#20889 Move WgpuWrapper back to where it was
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/diagnostic/internal.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/render_resource/bind_group_layout.rs
  crates/bevy_render/src/render_resource/buffer.rs
  crates/bevy_render/src/render_resource/pipeline.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/render_resource/texture.rs
  crates/bevy_render/src/renderer/mod.rs
  crates/bevy_render/src/renderer/render_device.rs
  crates/bevy_render/src/renderer/wgpu_wrapper.rs
  crates/bevy_render/src/view/window/mod.rs
Labels: A-Rendering, S-Ready-For-Final-Review

#20893 Add `register_type` for `MaterialNode`
  crates/bevy_ui_render/src/ui_material_pipeline.rs
Labels: D-Trivial, A-UI, S-Ready-For-Final-Review

#20897 Limit bloom_3d float output to two decimal places.
  examples/3d/bloom_3d.rs
Labels: D-Trivial, A-Rendering, C-Examples, S-Ready-For-Final-Review, M-Deliberate-Rendering-Change

#20876 convert more examples to new spawn api
  examples/2d/sprite_scale.rs
  examples/2d/text2d.rs
  examples/animation/animated_transform.rs
  examples/animation/animated_ui.rs
  examples/animation/animation_masks.rs
  examples/animation/easing_functions.rs
  examples/ecs/one_shot_systems.rs
  examples/window/low_power.rs
  examples/window/scale_factor_override.rs
  examples/window/window_drag_move.rs
Labels: A-ECS, C-Examples, S-Ready-For-Final-Review, D-Straightforward

#20902 Constify math
  crates/bevy_math/src/aspect_ratio.rs
  crates/bevy_math/src/curve/interval.rs
  crates/bevy_math/src/isometry.rs
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_math/src/primitives/polygon.rs
  crates/bevy_math/src/rotation2d.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Math, D-Straightforward

#20903 Constify ui
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/ui_transform.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_ui/src/widget/text.rs
  crates/bevy_ui/src/widget/viewport.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#20910 Hide `super` in `ComputedNode`'s doclinks
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, D-Trivial, A-UI

#20892 Put order parameter back in render_to_texture example's camera
  examples/3d/render_to_texture.rs
  examples/ui/render_ui_to_texture.rs
Labels: A-Rendering, C-Examples, A-UI, S-Ready-For-Final-Review, D-Straightforward, A-Camera, C-Refinement

#20915 Limit float output in some examples to two decimal places.
  examples/3d/depth_of_field.rs
  examples/3d/post_processing.rs
  examples/3d/tonemapping.rs
Labels: D-Trivial, C-Examples, S-Ready-For-Final-Review

#20624 Fix missed RedrawRequested and WindowCloseRequested events with UpdateMode::Reactive (part 2) [ADOPTED]
  Cargo.toml
  crates/bevy_winit/src/state.rs
  tests/window/desktop_request_redraw.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review, D-Complex

#20906 Update the 3D examples to use `children!`
  examples/3d/blend_modes.rs
  examples/3d/clustered_decals.rs
  examples/3d/color_grading.rs
  examples/3d/light_textures.rs
  examples/3d/mixed_lighting.rs
  examples/3d/motion_blur.rs
  examples/3d/order_independent_transparency.rs
  examples/3d/parallax_mapping.rs
  examples/3d/parenting.rs
  examples/3d/pcss.rs
  examples/3d/shadow_biases.rs
  examples/3d/split_screen.rs
  examples/3d/spotlight.rs
  examples/helpers/widgets.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review, D-Straightforward

#20916 Use DespawnOnExit instead of generic cleanup system
  examples/games/game_menu.rs
Labels: C-Examples, S-Ready-For-Final-Review

#20920 feathers: ensure buttons can change variant dynamically
  crates/bevy_feathers/src/controls/button.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#20877 Introduce MovingPtr as a safer alternative to moving typed values by raw pointer
  crates/bevy_ptr/README.md
  crates/bevy_ptr/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Pointers, D-Unsafe

#20883 Always enable state scoped entities
  crates/bevy_state/macros/src/states.rs
  crates/bevy_state/src/app.rs
  crates/bevy_state/src/state/computed_states.rs
  crates/bevy_state/src/state/states.rs
  crates/bevy_state/src/state_scoped.rs
  release-content/migration-guides/state_scoped_entities_by_default.md
Labels: S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Straightforward, A-States

#20932 add helper functions for registering bundles to world
  crates/bevy_ecs/src/bundle/insert.rs
  crates/bevy_ecs/src/bundle/remove.rs
  crates/bevy_ecs/src/bundle/spawner.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward, D-Unsafe

#20940 add reflection serialization example
  Cargo.toml
  examples/README.md
  examples/reflection/serialization.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Reflection

#20937 Add `UiRect` constructor functions to `Val`
  crates/bevy_ui/src/geometry.rs
  release-content/release-notes/constructor_functions_for_val_variants.md
Labels: A-UI, C-Usability, S-Ready-For-Final-Review, X-Contentious

#20954 Fix `MeshTag` changes having no effect
  crates/bevy_pbr/src/render/mesh.rs
Labels: C-Bug, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#20956 Constify `Val` functions
  crates/bevy_ui/src/geometry.rs
Labels: D-Trivial, A-UI, C-Usability, S-Ready-For-Final-Review

#20944 Renamed `bevy_core_widgets` to `bevy_ui_widgets`.
  Cargo.toml
  crates/bevy_feathers/Cargo.toml
  crates/bevy_feathers/src/controls/button.rs
  crates/bevy_feathers/src/controls/checkbox.rs
  crates/bevy_feathers/src/controls/color_slider.rs
  crates/bevy_feathers/src/controls/radio.rs
  crates/bevy_feathers/src/controls/slider.rs
  crates/bevy_feathers/src/controls/toggle_switch.rs
  crates/bevy_feathers/src/controls/virtual_keyboard.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/lib.rs
  crates/bevy_ui_widgets/Cargo.toml
  crates/bevy_ui_widgets/src/button.rs
  crates/bevy_ui_widgets/src/callback.rs
  crates/bevy_ui_widgets/src/checkbox.rs
  crates/bevy_ui_widgets/src/lib.rs
  crates/bevy_ui_widgets/src/radio.rs
  crates/bevy_ui_widgets/src/scrollbar.rs
  crates/bevy_ui_widgets/src/slider.rs
  docs/cargo_features.md
  examples/README.md
  examples/testbed/full_ui.rs
  examples/ui/feathers.rs
  examples/ui/scrollbars.rs
  examples/ui/standard_widgets.rs
  examples/ui/standard_widgets_observers.rs
  examples/ui/virtual_keyboard.rs
  release-content/release-notes/headless-widgets.md
Labels: D-Trivial, A-UI, S-Ready-For-Final-Review, X-Blessed

#20996 Automatically add Send + Sync + 'static bounds to Event / EntityEvent derives
  crates/bevy_ecs/macros/src/event.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#20993 Make specialization cache cleanup respect material swaps
  crates/bevy_pbr/src/material.rs
Labels: C-Bug, A-Rendering, S-Needs-Review

#21000 Fix links in observer_overhaul.md
  release-content/release-notes/observer_overhaul.md
Labels: S-Ready-For-Final-Review

#21002 Mark meshes as changed *after* AssetEvents are processed.
  crates/bevy_mesh/src/lib.rs
Labels: C-Bug, A-Rendering, A-Assets

#21010 Fix typo in specialized_ui_transform.md
  release-content/migration-guides/specialized_ui_transform.md
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-Transform, X-Uncontroversial

#21009 Make `On` documentation more friendly
  crates/bevy_ecs/src/observer/system_param.rs
Labels: C-Docs, A-ECS

#20995 Gave bevy::app::App the must_use attribute
  crates/bevy_app/src/app.rs
Labels: C-Usability, A-App, D-Straightforward, S-Needs-Review

#21029 Add `$crate` in weak_handle macro
  crates/bevy_asset/src/handle.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review, D-Macros

#21018 fix sprite gizmo feature
  crates/bevy_gizmos/Cargo.toml
  crates/bevy_gizmos/src/config.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gizmos/src/retained.rs
  crates/bevy_internal/Cargo.toml
Labels: A-Rendering, S-Ready-For-Final-Review, A-Gizmos

#21019 Improve render migration guide
  release-content/migration-guides/bevy_render_reorganization.md
Labels: A-Rendering, S-Ready-For-Final-Review

#20822 Impl ```AsAssetId``` for ```SceneRoot``` and ```DynamicSceneRoot```
  crates/bevy_scene/src/components.rs
Labels: C-Feature, A-Assets, S-Ready-For-Final-Review, A-Scenes, D-Straightforward

#21023 More doc link tidy up
  crates/bevy_camera/src/projection.rs
  crates/bevy_pbr/src/meshlet/asset.rs
  crates/bevy_pbr/src/meshlet/material_pipeline_prepare.rs
  crates/bevy_pbr/src/meshlet/resource_manager.rs
  crates/bevy_state/src/lib.rs
  crates/bevy_text/src/glyph.rs
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/monitor.rs
  crates/bevy_window/src/window.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#21040 fix(bevy_ptr): correct Debug impl for MovingPtr
  crates/bevy_ptr/src/lib.rs
Labels: C-Bug, D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Pointers

#21045 Impl Debug for triggers
  crates/bevy_ecs/src/event/trigger.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#21055 `directional_navigation` example tweak
  examples/ui/directional_navigation.rs
Labels: D-Trivial, C-Examples, A-UI, S-Ready-For-Final-Review

#21056 Improve suggestion when old name for `Justify` is used
  crates/bevy_text/src/text.rs
Labels: A-UI, C-Usability, S-Ready-For-Final-Review

#21057 Add note about `z` translation value which is no longer present
  release-content/migration-guides/specialized_ui_transform.md
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#21049 Fix `On::target` not being implemented for an `EntityEvent` without propagation
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/observer/system_param.rs
Labels: C-Bug, D-Trivial, A-ECS, S-Ready-For-Final-Review, P-Regression

#21061 mention import paths in TAA migration guide
  release-content/migration-guides/taa_non_experimental.md
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#21062 migration guide for #20427 (cursor)
  release-content/migration-guides/cursor-android.md
Labels: C-Docs, A-Windowing, S-Ready-For-Final-Review

#21063 mention `Hdr` import path (#21026)
  release-content/migration-guides/hdr_component.md
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#21064 remove publish script
  tools/publish.sh
Labels: A-Meta, S-Ready-For-Final-Review

#21065 fix: migration guide starting with backtick
  release-content/migration-guides/remove_text_font_from_constructor_methods.md
Labels: C-Docs, S-Ready-For-Final-Review

#21066 readme: use a logo url available from everywhere
  README.md
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review

#21015 fps overlay: text node display none if disable
  crates/bevy_dev_tools/src/fps_overlay.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#21067 Run release exporter in ci
  .github/workflows/ci.yml
  tools/export-content/src/app.rs
  tools/export-content/src/main.rs
Labels: C-Feature, A-Build-System, S-Ready-For-Final-Review, D-Straightforward

#21068 Add `YAxisOrientation` migration guide.
  release-content/migration-guides/The_YAxisOrientation_component_has_been_removed
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#21077 Remove unneeded migration guide
  release-content/migration-guides/border_color_all_takes_impl_into_color.md
Labels: C-Docs, D-Trivial, A-UI, S-Needs-Review

#21082 Change the default for `RenderTargetInfo::scale_factor` to `1.`
  crates/bevy_camera/src/camera.rs
  release-content/migration-guides/RenderTargetInfo_default.md
Labels: C-Bug, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#21084 Commandqueue uses source tracing.
  crates/bevy_ecs/src/world/command_queue.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#21096 Fix tasks on wasm
  crates/bevy_tasks/src/task.rs
Labels: C-Bug, D-Trivial, P-Crash, O-Web, S-Ready-For-Final-Review, A-Tasks, D-Async

#21098 improve render reorg guide
  release-content/migration-guides/bevy_render_reorganization.md
Labels: A-Rendering, S-Ready-For-Final-Review

#21099 Fix empty children regression
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/spawn.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, P-Regression

#21100 Rename `bevy_sprite::sprite::ScalingMode` to `SpriteScalingMode`
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_sprite_render/src/render/mod.rs
  examples/2d/sprite_scale.rs
  release-content/migration-guides/rename_bevy_sprite_ScalingMode_to_SpriteScalingMode.md
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#21112 Improve error message for warn_on_no_render_graph
  crates/bevy_render/src/camera.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#21113 Use `$crate` instead of `bevy_ptr` in `move_as_ptr` macro
  crates/bevy_ptr/src/lib.rs
Labels: C-Bug, A-ECS, D-Macros

#21102 Combine added and existing `ComponentId`s in a single allocation
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/bundle/insert.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review

#21143 Fix typo
  .github/workflows/ci.yml
  README.md
  crates/bevy_camera/src/camera.rs
  crates/bevy_camera/src/visibility/mod.rs
  crates/bevy_dev_tools/src/fps_overlay.rs
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/bundle/insert.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/event/trigger.rs
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/observer/system_param.rs
  crates/bevy_ecs/src/relationship/mod.rs
  crates/bevy_ecs/src/spawn.rs
  crates/bevy_ecs/src/storage/table/mod.rs
  crates/bevy_ecs/src/world/command_queue.rs
  crates/bevy_ptr/src/lib.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_remote/src/lib.rs
  crates/bevy_render/src/camera.rs
  crates/bevy_render/src/texture/manual_texture_view.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_sprite_render/src/lib.rs
  crates/bevy_sprite_render/src/render/mod.rs
  crates/bevy_state/src/lib.rs
  crates/bevy_state/src/state_scoped.rs
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/src/task.rs
  crates/bevy_text/src/text.rs
  crates/bevy_ui_render/Cargo.toml
  examples/2d/sprite_scale.rs
  examples/reflection/auto_register_static/src/lib.rs
  examples/reflection/reflection_types.rs
  examples/ui/directional_navigation.rs
  release-content/migration-guides/RenderTargetInfo_default.md
  release-content/migration-guides/The_YAxisOrientation_component_has_been_removed
  release-content/migration-guides/bevy_render_reorganization.md
  release-content/migration-guides/border_color_all_takes_impl_into_color.md
  release-content/migration-guides/cursor-android.md
  release-content/migration-guides/hdr_component.md
  release-content/migration-guides/per-world-error-handler.md
  release-content/migration-guides/remove_text_font_from_constructor_methods.md
  release-content/migration-guides/rename_bevy_sprite_ScalingMode_to_SpriteScalingMode.md
  release-content/migration-guides/specialized_ui_transform.md
  release-content/migration-guides/taa_non_experimental.md
  release-content/migration-guides/ui-debug-overlay.md
  release-content/migration-guides/wayland.md
  release-content/release-notes/infinite-children.md
  tools/export-content/src/app.rs
  tools/export-content/src/main.rs
  tools/publish.sh
Labels: C-Docs, D-Trivial, A-ECS, S-Ready-For-Final-Review, X-Uncontroversial

#21130 `JustifySelf` doc comment edit
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, A-UI, S-Needs-Review

#20981 BRP allow spawning/inserting Components with only `Reflect`
  crates/bevy_remote/src/builtin_methods.rs
Labels: S-Ready-For-Final-Review, A-Reflection, A-Editor, A-Dev-Tools, D-Straightforward

#21148 add helper to get tile_data_from_tile_pos from tilemapchunktiledata
  crates/bevy_sprite_render/src/tilemap_chunk/mod.rs
  examples/2d/tilemap_chunk.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#21085 `UiGlobalTransform` helper methods
  crates/bevy_ui/src/ui_transform.rs
Labels: C-Feature, A-UI, S-Ready-For-Final-Review, A-Math, D-Straightforward

#21141 move gltf examples to gltf category
  Cargo.toml
  examples/README.md
  examples/gltf/custom_gltf_vertex_attribute.rs
  examples/gltf/edit_material_on_gltf.rs
  examples/gltf/gltf_skinned_mesh.rs
  examples/gltf/load_gltf.rs
  examples/gltf/load_gltf_extras.rs
  examples/gltf/query_gltf_primitives.rs
  examples/gltf/update_gltf_scene.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-glTF

#21151 enable required transitive features on docs.rs
  crates/bevy_anti_alias/Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_core_pipeline/Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_pbr/Cargo.toml
Labels: C-Docs, A-Build-System, S-Ready-For-Final-Review

#21128 Borders example cleanup
  examples/ui/borders.rs
Labels: D-Trivial, C-Examples, A-UI, S-Ready-For-Final-Review

#21142 Add data-driven rendering release note.
  release-content/release-notes/data-driven-materials.md
Labels: A-Rendering, S-Ready-For-Final-Review

#21153 Add release notes for new Sun Disk feature
  crates/bevy_light/src/directional_light.rs
  release-content/release-notes/sun_disk.md
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#21137 `TypedReflectDeserializer`: return a concrete value when possible
  crates/bevy_reflect/src/serde/de/deserializer.rs
  examples/reflection/serialization.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Reflection

#21109 Detailed migration guide for automatic reflection registration
  release-content/migration-guides/reflect_registration_changes.md
Labels: C-Docs, S-Ready-For-Final-Review, A-Reflection, D-Modest

#21161 Adds migration instructions for old zstd feature.
  release-content/migration-guides/zstd.md
Labels: C-Docs, S-Ready-For-Final-Review

#21163 Improve searchability of wgpu 25 migration
  release-content/migration-guides/wgpu_25.md
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#21166 Migration guide for the `stack_index` to `z_order` change.
  release-content/migration-guides/extracted_uinodes_z_order.md
Labels: C-Docs, A-Rendering, A-UI, S-Ready-For-Final-Review

#21172 Added required components to InheritableFont and ThemeFontColor
  crates/bevy_feathers/src/font_styles.rs
  crates/bevy_feathers/src/theme.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#21054 Change `ImageRenderTarget`'s `scale_factor` to an `f32`
  crates/bevy_camera/src/camera.rs
  crates/bevy_render/src/camera.rs
  release-content/migration-guides/image_render_target_scale_factor_is_now_f32.md
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Camera

#21176 Revived #18741, Remove `SimpleExecutor`.
  benches/benches/bevy_ecs/scheduling/schedule.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  release-content/migration-guides/removed_simple_executor.md
Labels: D-Trivial, A-ECS, S-Ready-For-Final-Review, X-Blessed

#21177 get_random migration guide polish: round two
  release-content/migration-guides/glam-rand-upgrades.md
Labels: C-Docs, D-Trivial, A-Math, S-Needs-Review

#21186 `NonSendMut` alias
  crates/bevy_ecs/src/system/system_param.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, P-Unsound

#21188 Fix animation crate typo from resume to pause
  crates/bevy_animation/src/lib.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-Animation

#21189 Print `Name` in `validate_parent_has_component`
  crates/bevy_ecs/src/hierarchy.rs
Labels: A-ECS, S-Ready-For-Final-Review, D-Straightforward

#21203 Add two basic tests for asset hot reloading.
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/server/mod.rs
Labels: A-Assets, S-Ready-For-Final-Review, C-Testing, D-Straightforward

#21202 Fix chrome rendering bug
  crates/bevy_pbr/src/render/view_transformations.wgsl
Labels: C-Bug, S-Ready-For-Final-Review, P-Regression

#21227 Fix typo in gradient types link
  crates/bevy_ui/src/gradients.rs
Labels: C-Docs, D-Trivial, A-UI, S-Ready-For-Final-Review

#21234 add methods to *EntityMut to UnsafeEntityCell as an escape hatch
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#21255 Re-export disqualified::ShortName from bevy_utils
  crates/bevy_utils/src/lib.rs
Labels: D-Trivial, A-Utils, S-Needs-Review

#21257 Add conversion from DebugName to Cow<'static, str>
  crates/bevy_utils/src/debug_info.rs
Labels: D-Trivial, S-Ready-For-Final-Review, A-Utils

#21266 Add additional FixedHasher details in HashSet and HashMap docs
  crates/bevy_platform/src/collections/hash_map.rs
  crates/bevy_platform/src/collections/hash_set.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-Utils

#21286 Delete animation graph migration code.
  crates/bevy_animation/src/graph.rs
Labels: D-Trivial, C-Code-Quality, A-Animation, S-Needs-Review

#21289 BufferSlice cleanup
  crates/bevy_render/src/render_phase/draw_state.rs
  crates/bevy_render/src/render_resource/buffer.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality

#21247 Delete `Callback` and use observers to control widgets for 0.17
  crates/bevy_feathers/src/controls/button.rs
  crates/bevy_feathers/src/controls/checkbox.rs
  crates/bevy_feathers/src/controls/color_slider.rs
  crates/bevy_feathers/src/controls/mod.rs
  crates/bevy_feathers/src/controls/slider.rs
  crates/bevy_feathers/src/controls/toggle_switch.rs
  crates/bevy_feathers/src/controls/virtual_keyboard.rs
  crates/bevy_ui_widgets/src/button.rs
  crates/bevy_ui_widgets/src/callback.rs
  crates/bevy_ui_widgets/src/checkbox.rs
  crates/bevy_ui_widgets/src/lib.rs
  crates/bevy_ui_widgets/src/observe.rs
  crates/bevy_ui_widgets/src/radio.rs
  crates/bevy_ui_widgets/src/slider.rs
  examples/ui/feathers.rs
  examples/ui/standard_widgets.rs
  examples/ui/standard_widgets_observers.rs
  examples/ui/virtual_keyboard.rs
Labels: C-Feature, A-UI, X-Blessed, S-Needs-SME

#20468 Remove `offset` argument from `TrackedRenderPass::set_index_buffer`
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/render_phase/draw_state.rs
  crates/bevy_sprite_render/src/mesh2d/mesh.rs
  crates/bevy_sprite_render/src/render/mod.rs
  crates/bevy_ui_render/src/box_shadow.rs
  crates/bevy_ui_render/src/gradient.rs
  crates/bevy_ui_render/src/render_pass.rs
  crates/bevy_ui_render/src/ui_texture_slice_pipeline.rs
  examples/shader_advanced/custom_phase_item.rs
  examples/shader_advanced/custom_shader_instancing.rs
  release-content/migration-guides/set_index_buffer.md
Labels: D-Trivial, A-Rendering, C-Code-Quality, C-Usability, M-Needs-Migration-Guide

#21284 Add closure-based EntityEvent triggers
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#20630 Remove parking_lot dependency
  crates/bevy_animation/macros/src/animation_event.rs
  crates/bevy_asset/Cargo.toml
  crates/bevy_asset/macros/src/lib.rs
  crates/bevy_asset/src/assets.rs
  crates/bevy_asset/src/io/embedded/embedded_watcher.rs
  crates/bevy_asset/src/io/embedded/mod.rs
  crates/bevy_asset/src/io/gated.rs
  crates/bevy_asset/src/io/memory.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_derive/src/lib.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_encase_derive/src/lib.rs
  crates/bevy_gizmos/macros/src/lib.rs
  crates/bevy_macro_utils/Cargo.toml
  crates/bevy_macro_utils/src/bevy_manifest.rs
  crates/bevy_reflect/derive/src/meta.rs
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/macros/src/extract_component.rs
  crates/bevy_render/macros/src/lib.rs
  crates/bevy_state/macros/src/lib.rs
  release-content/migration-guides/bevy_manifest_scope_api.md
Labels: A-Assets, C-Dependencies, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Uncontroversial, D-Straightforward, D-Macros

#21304 Replace `feature(doc_auto_cfg)` with `feature(doc_cfg)`.
  crates/bevy_a11y/src/lib.rs
  crates/bevy_animation/macros/src/lib.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_anti_alias/src/lib.rs
  crates/bevy_asset/macros/src/lib.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_audio/src/lib.rs
  crates/bevy_color/src/lib.rs
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_derive/src/lib.rs
  crates/bevy_dev_tools/src/lib.rs
  crates/bevy_diagnostic/src/lib.rs
  crates/bevy_dylib/src/lib.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_encase_derive/src/lib.rs
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_gizmos/macros/src/lib.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gltf/src/lib.rs
  crates/bevy_input/src/lib.rs
  crates/bevy_input_focus/src/lib.rs
  crates/bevy_internal/src/lib.rs
  crates/bevy_log/src/lib.rs
  crates/bevy_macro_utils/src/lib.rs
  crates/bevy_math/src/lib.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_platform/src/lib.rs
  crates/bevy_post_process/src/lib.rs
  crates/bevy_ptr/src/lib.rs
  crates/bevy_reflect/derive/src/lib.rs
  crates/bevy_render/macros/src/lib.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite_render/src/lib.rs
  crates/bevy_state/macros/src/lib.rs
  crates/bevy_tasks/src/lib.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_transform/src/lib.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui_render/src/lib.rs
  crates/bevy_utils/src/lib.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/src/lib.rs
  src/lib.rs
Labels: C-Docs, A-Build-System

#21306 Replace `feature(doc_auto_cfg)` with `feature(doc_cfg)`, part 2
  crates/bevy_app/src/lib.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_render/src/lib.rs
Labels: C-Docs, A-Build-System
