Repository bevyengine/bevy, pull requests merged in 2025-01, with the labels that each got.

#17065 Do not lowercase asset file extensions
  crates/bevy_asset/src/path.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review, D-Straightforward

#17073 Replace `map_or(true, _)` with `is_none_or(_)`
  crates/bevy_ecs/src/world/mod.rs
Labels: D-Trivial, A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#17071 Return `Result` from tab navigation API
  crates/bevy_input_focus/Cargo.toml
  crates/bevy_input_focus/src/tab_navigation.rs
Labels: A-Input, A-UI, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#17047 Remove the `atlas_scaling` field from `ExtractedUiItem::Gylphs`.
  crates/bevy_ui/src/render/mod.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Text

#17078 Fix sprite performance regression since retained render world
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_sprite/src/texture_slice/computed_slices.rs
  crates/bevy_text/src/text2d.rs
  examples/stress_tests/bevymark.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review

#17075 Rename `track_change_detection` flag to `track_location`
  Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/event/base.rs
  crates/bevy_ecs/src/event/collections.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/storage/resource.rs
  crates/bevy_ecs/src/storage/sparse_set.rs
  crates/bevy_ecs/src/storage/table/column.rs
  crates/bevy_ecs/src/storage/table/mod.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/filtered_resource.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/spawn_batch.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_internal/Cargo.toml
  docs/cargo_features.md
  examples/ecs/change_detection.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Dev-Tools

#17063 Refactor and simplify custom projections
  Cargo.toml
  crates/bevy_animation/src/animation_curves.rs
  crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/meshlet/material_pipeline_prepare.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/mod.rs
  crates/bevy_render/src/camera/projection.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_sprite/src/picking_backend.rs
  crates/bevy_ui/src/layout/mod.rs
  examples/2d/pixel_grid_snap.rs
  examples/README.md
  examples/camera/custom_projection.rs
  examples/camera/projection_zoom.rs
Labels: A-Rendering, C-Usability, M-Needs-Migration-Guide, D-Modest, S-Needs-Review

#17080 Fix `clippy::precedence`
  crates/bevy_color/src/srgba.rs
  crates/bevy_pbr/src/cluster/mod.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review

#17031 Add `no_std` support to `bevy_window`
  crates/bevy_window/Cargo.toml
  crates/bevy_window/src/event.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_window/src/monitor.rs
  crates/bevy_window/src/raw_handle.rs
  crates/bevy_window/src/system.rs
  crates/bevy_window/src/system_cursor.rs
  crates/bevy_window/src/window.rs
  tools/ci/src/commands/compile_check_no_std.rs
Labels: C-Feature, A-Windowing, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward, O-Embedded

#17054 small documentation update and issue template fix
  .github/ISSUE_TEMPLATE/docs_improvement.md
  crates/bevy_state/src/condition.rs
Labels: C-Docs, D-Trivial, A-Meta, S-Ready-For-Final-Review, A-States

#17066 reduce nesting in the `sparse_set` module
  crates/bevy_ecs/src/storage/sparse_set.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#17095 bevy_app: Apply `#[deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_app/src/lib.rs
  crates/bevy_app/src/plugin.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-App

#17097 UI Debug Overlay `show_hidden` and `show_clipped` options
  crates/bevy_ui/src/render/debug_overlay.rs
  examples/testbed/ui.rs
Labels: C-Feature, C-Examples, A-UI, S-Ready-For-Final-Review, A-Dev-Tools, D-Straightforward

#17094 bevy_animation: Apply `#[deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_animation/src/lib.rs
Labels: D-Trivial, C-Code-Quality, A-Animation, S-Needs-Review

#17093 bevy_a11y: Apply `#[deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_a11y/src/lib.rs
Labels: D-Trivial, A-Accessibility, C-Code-Quality, S-Needs-Review

#17091 bevy_math: Apply `#[deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_math/src/bounding/bounded2d/primitive_impls.rs
  crates/bevy_math/src/cubic_splines/mod.rs
  crates/bevy_math/src/curve/easing.rs
  crates/bevy_math/src/float_ord.rs
  crates/bevy_math/src/lib.rs
  crates/bevy_math/src/ops.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Math, D-Straightforward

#17084 Update entity cloning benchmarks
  benches/Cargo.toml
  benches/benches/bevy_ecs/entity_cloning.rs
  benches/benches/bevy_ecs/main.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, C-Benchmarks, D-Modest

#17106 Fix documentation for system set method
  crates/bevy_ecs/src/schedule/config.rs
Labels: C-Docs, D-Trivial, A-ECS, S-Ready-For-Final-Review

#17089 bevy_tasks: Apply `#[deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_tasks/src/executor.rs
  crates/bevy_tasks/src/lib.rs
  crates/bevy_tasks/src/task_pool.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Tasks, D-Straightforward

#17109 Truncate the floats in `bevy_color::oklaba`
  crates/bevy_color/src/oklaba.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Color

#17015 Scale input to account for deadzones
  crates/bevy_input/src/gamepad.rs
Labels: A-Input, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Modest

#17081 Add `-D warnings` in a few steps
  .github/workflows/ci.yml
Labels: A-Build-System, S-Ready-For-Final-Review, D-Straightforward

#17092 bevy_reflect: Apply `#[deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_reflect/src/attributes.rs
  crates/bevy_reflect/src/from_reflect.rs
  crates/bevy_reflect/src/func/info.rs
  crates/bevy_reflect/src/func/reflect_fn.rs
  crates/bevy_reflect/src/func/reflect_fn_mut.rs
  crates/bevy_reflect/src/impls/glam.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/path/mod.rs
  crates/bevy_reflect/src/path/parse.rs
  crates/bevy_reflect/src/serde/mod.rs
  crates/bevy_reflect/src/type_registry.rs
Labels: C-Code-Quality, A-Reflection, D-Straightforward, S-Needs-Help

#17123 Revert "Fix sprite performance regression since retained render world (#17078)"
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_sprite/src/texture_slice/computed_slices.rs
  crates/bevy_text/src/text2d.rs
  examples/stress_tests/bevymark.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, P-Regression, D-Straightforward

#17115 Optimize `Entities::entity_does_not_exist_error_details_message`, remove `UnsafeWorldCell` from error
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/query/error.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/entity_fetch.rs
  crates/bevy_ecs/src/world/error.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Modest

#17090 bevy_color: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_color/src/lib.rs
  crates/bevy_color/src/palettes/css.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward, A-Color

#16947 METIS-based meshlet generation
  Cargo.toml
  crates/bevy_pbr/Cargo.toml
  crates/bevy_pbr/src/meshlet/from_mesh.rs
  examples/3d/meshlet.rs
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, D-Modest

#17085 Fix 2D Gizmos not always drawn on top
  crates/bevy_gizmos/src/pipeline_2d.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, P-Regression, A-Gizmos, D-Straightforward

#17146 Updated nixos link in `linux_dependencies.md`.
  docs/linux_dependencies.md
Labels: C-Docs, D-Trivial, A-Meta, S-Ready-For-Final-Review

#17148 More combinator cleanup
  crates/bevy_diagnostic/src/diagnostic.rs
  tools/build-templated-pages/src/examples.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review

#17139 Derived `Default` for all public unit components.
  crates/bevy_audio/src/audio_output.rs
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_window/src/window.rs
Labels: C-Feature, D-Trivial, S-Ready-For-Final-Review, A-Cross-Cutting

#17150 Update GetPath unit test and documentation for empty path usecase
  crates/bevy_reflect/src/path/mod.rs
Labels: C-Docs, C-Code-Quality, S-Ready-For-Final-Review, A-Reflection, D-Straightforward

#17175 Allow users to easily use `bevy_sprite` and `bevy_ui` without picking
  Cargo.toml
Labels: C-Bug, S-Ready-For-Final-Review, A-Picking

#17162 Fix workflows for version bump
  .github/workflows/post-release.yml
  .github/workflows/release.yml
Labels: A-Build-System, S-Ready-For-Final-Review

#17163 remove daily mobile jobs
  .github/workflows/daily.yml
Labels: A-Build-System, O-Android, O-iOS, S-Ready-For-Final-Review, D-Straightforward

#17171 Change `bevy_reflect::RegisterForReflection::__register()` to expect unused variables, rather than putting underscores on the parameter names
  crates/bevy_reflect/src/lib.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection

#17174 Use `radsort` for sprite picking
  crates/bevy_sprite/src/picking_backend.rs
Labels: C-Performance, S-Ready-For-Final-Review, D-Straightforward, A-Picking

#17159 bevy_dev_tools: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_dev_tools/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Dev-Tools

#16338 Remove all `deprecated` code
  crates/bevy_animation/src/lib.rs
  crates/bevy_asset/src/processor/process.rs
  crates/bevy_audio/src/audio.rs
  crates/bevy_audio/src/lib.rs
  crates/bevy_audio/src/pitch.rs
  crates/bevy_color/src/color.rs
  crates/bevy_core_pipeline/src/auto_exposure/mod.rs
  crates/bevy_core_pipeline/src/auto_exposure/settings.rs
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/bloom/settings.rs
  crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
  crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
  crates/bevy_core_pipeline/src/dof/mod.rs
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_core_pipeline/src/motion_blur/mod.rs
  crates/bevy_core_pipeline/src/smaa/mod.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_ecs/src/query/builder.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/entity_fetch.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_math/src/direction.rs
  crates/bevy_math/src/rotation2d.rs
  crates/bevy_pbr/src/bundle.rs
  crates/bevy_pbr/src/components.rs
  crates/bevy_pbr/src/fog.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light_probe/environment_map.rs
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_pbr/src/ssr/mod.rs
  crates/bevy_pbr/src/volumetric_fog/mod.rs
  crates/bevy_reflect/src/array.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/spatial_bundle.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_scene/src/bundle.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_sprite/src/bundle.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/mesh2d/color_material.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/texture_atlas_builder.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_transform/src/bundles.rs
  crates/bevy_transform/src/components/global_transform.rs
  crates/bevy_transform/src/components/transform.rs
  crates/bevy_transform/src/lib.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/node_bundles.rs
  crates/bevy_ui/src/widget/text.rs
  errors/B0004.md
  examples/ecs/dynamic.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Cross-Cutting, D-Straightforward

#17142 unmut extracted view queries
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#17155 Disable bindless on a per-material basis if the specific material uses more samplers than are available on the device.
  crates/bevy_pbr/src/material_bind_groups.rs
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/src/render_resource/bind_group.rs
Labels: C-Bug, A-Rendering, P-Crash, S-Ready-For-Final-Review, D-Straightforward

#17158 Remove everything except `Instant` from `bevy_utils::time`
  crates/bevy_animation/src/transition.rs
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_asset/src/io/embedded/embedded_watcher.rs
  crates/bevy_asset/src/io/file/file_watcher.rs
  crates/bevy_asset/src/io/source.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_diagnostic/src/diagnostic.rs
  crates/bevy_diagnostic/src/log_diagnostics_plugin.rs
  crates/bevy_gilrs/src/rumble.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_picking/src/events.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_time/src/common_conditions.rs
  crates/bevy_time/src/fixed.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_time/src/real.rs
  crates/bevy_time/src/stopwatch.rs
  crates/bevy_time/src/time.rs
  crates/bevy_time/src/timer.rs
  crates/bevy_time/src/virt.rs
  crates/bevy_utils/src/lib.rs
  crates/bevy_utils/src/time.rs
  crates/bevy_winit/src/winit_config.rs
  examples/app/headless.rs
  examples/app/plugin.rs
  examples/audio/decodable.rs
  examples/ecs/ecs_guide.rs
  examples/input/gamepad_rumble.rs
  examples/scene/scene.rs
  examples/stress_tests/bevymark.rs
  examples/ui/ui_scaling.rs
  examples/window/low_power.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Utils, X-Contentious

#17182 Add diagnostic logging to `many_gizmos`
  examples/stress_tests/many_gizmos.rs
Labels: D-Trivial, C-Examples, S-Ready-For-Final-Review, A-Gizmos

#17136 Update all previously-merged `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]` attributes to include a reason field pointing to the tracking issue
  crates/bevy_a11y/src/lib.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_app/src/lib.rs
  crates/bevy_math/src/lib.rs
  crates/bevy_tasks/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Cross-Cutting, D-Straightforward

#16898 Introduce two-level bins for multidrawable meshes.
  assets/shaders/storage_buffer.wgsl
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/deferred/mod.rs
  crates/bevy_core_pipeline/src/deferred/node.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/batching/no_gpu_preprocessing.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  examples/shader/custom_phase_item.rs
  examples/shader/specialized_mesh_pipeline.rs
  examples/shader/storage_buffer.rs
Labels: A-Rendering, C-Performance, C-Code-Quality, S-Ready-For-Final-Review

#17079 Fix depth_bias and build errors on less capable platforms
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/lib.rs
  crates/bevy_dev_tools/src/ci_testing/mod.rs
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_reflect/src/impls/std.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, D-Straightforward, O-Embedded

#17096 Anamorphic Bloom
  crates/bevy_core_pipeline/src/bloom/bloom.wgsl
  crates/bevy_core_pipeline/src/bloom/downsampling_pipeline.rs
  crates/bevy_core_pipeline/src/bloom/settings.rs
  examples/2d/bloom_2d.rs
  examples/3d/bloom_3d.rs
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, M-Needs-Release-Note, D-Modest, D-Shaders

#17100 default UI camera extraction fix
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/debug_overlay.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
Labels: A-Rendering, C-Performance, A-UI, S-Ready-For-Final-Review, D-Straightforward

#17102 Add basic directional (gamepad) navigation for UI (and non-UI)
  crates/bevy_input_focus/Cargo.toml
  crates/bevy_input_focus/src/directional_navigation.rs
  crates/bevy_input_focus/src/lib.rs
  crates/bevy_math/src/compass.rs
Labels: C-Feature, A-Input, A-UI, S-Ready-For-Final-Review, X-Contentious, D-Modest

#17116 Disallow requesting write resource access in Queries
  crates/bevy_asset/src/asset_changed.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/query/world_query.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Unsafe

#17119 bevy_audio: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_audio/src/lib.rs
Labels: D-Trivial, A-Audio, C-Code-Quality, S-Ready-For-Final-Review

#17120 More DefaultUiCamera fixes
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/picking_backend.rs
  crates/bevy_ui/src/widget/text.rs
Labels: D-Trivial, C-Performance, A-UI, S-Ready-For-Final-Review

#17131 Make the `get` function on `InstanceInputUniformBuffer` less error prone
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Straightforward

#17179 can hide status bar on iOS
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/mobile/src/lib.rs
Labels: A-Windowing, O-iOS, S-Ready-For-Final-Review, D-Straightforward

#17143 Simplified UI tree navigation without `ghost_nodes`
  crates/bevy_ui/src/experimental/ghost_hierarchy.rs
Labels: C-Performance, A-UI, S-Ready-For-Final-Review, D-Straightforward

#17113 bevy_asset: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_asset/src/asset_changed.rs
  crates/bevy_asset/src/handle.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/server/loaders.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#17149 Cleanup entity reference types
  crates/bevy_ecs/src/world/entity_ref.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward, D-Unsafe

#17185 Remove `bevy_core_pipeline::core_2d::Camera2dBundle`
  crates/bevy_core_pipeline/src/core_2d/camera_2d.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#17186 bevy_diagnostic: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_diagnostic/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Diagnostics

#17191 Split up `animated_fox` example
  Cargo.toml
  examples/README.md
  examples/animation/animated_fox.rs
  examples/animation/animated_fox_control.rs
  examples/animation/animated_fox_events.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Animation

#16614 add line height to `TextFont`
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_text/src/text.rs
  examples/dev_tools/fps_overlay.rs
Labels: C-Feature, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Text, D-Straightforward

#17194 bevy_render: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/mod.rs
  crates/bevy_render/src/diagnostic/mod.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/mesh/allocator.rs
  crates/bevy_render/src/render_asset.rs
  crates/bevy_render/src/render_phase/draw.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/render_resource/resource_macros.rs
  crates/bevy_render/src/settings.rs
  crates/bevy_render/src/view/window/mod.rs
  crates/bevy_render/src/view/window/screenshot.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#16630 Update winit_runner to use spawn_app for wasm32 target
  crates/bevy_winit/src/state.rs
Labels: O-Web, S-Ready-For-Final-Review, A-App, D-Straightforward

#17203 Add builder method for `TextFont::line_height`
  crates/bevy_text/src/text.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Text

#17199 Add the original source for Oklab conversions
  crates/bevy_color/src/oklaba.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Color

#17195 Remove references to old sample_texture function
  crates/bevy_pbr/src/meshlet/asset.rs
  crates/bevy_pbr/src/render/pbr_functions.wgsl
Labels: C-Docs, A-Rendering, S-Ready-For-Final-Review

#17205 Added docs on how `Parent` component is affected by `BuildChildren` methods.
  crates/bevy_hierarchy/src/child_builder.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-Hierarchy

#17204 iOS: can change home indicator / status bar during runtime
  crates/bevy_winit/src/system.rs
Labels: C-Feature, A-Windowing, O-iOS, S-Ready-For-Final-Review, D-Straightforward

#17202 Make typos config stricter
  typos.toml
Labels: A-Build-System, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#17206 Replace unsafe blocks in `World` and `DeferredWorld` with safe equivalents
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Code-Quality, X-Uncontroversial, D-Straightforward, D-Unsafe

#17177 Upstream `DebugPickingPlugin` from `bevy_mod_picking`
  Cargo.toml
  crates/bevy_dev_tools/Cargo.toml
  crates/bevy_dev_tools/src/lib.rs
  crates/bevy_dev_tools/src/picking_debug.rs
  examples/README.md
  examples/picking/debug_picking.rs
Labels: C-Feature, S-Ready-For-Final-Review, A-Dev-Tools, D-Modest, A-Picking

#17043 Add `Result` handling to `Commands` and `EntityCommands`
  benches/benches/bevy_ecs/world/commands.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/system/commands/command.rs
  crates/bevy_ecs/src/system/commands/entity_command.rs
  crates/bevy_ecs/src/system/commands/error.rs
  crates/bevy_ecs/src/system/commands/error_handler.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/command_queue.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_hierarchy/src/hierarchy.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Complex, M-Needs-Release-Note, X-Contentious

#17219 Move `TextureAtlas` and friends into `bevy_image`
  crates/bevy_image/Cargo.toml
  crates/bevy_image/src/dynamic_texture_atlas_builder.rs
  crates/bevy_image/src/lib.rs
  crates/bevy_image/src/texture_atlas.rs
  crates/bevy_image/src/texture_atlas_builder.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_sprite/Cargo.toml
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/picking_backend.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_text/src/font_atlas.rs
  crates/bevy_text/src/font_atlas_set.rs
  crates/bevy_text/src/glyph.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
  crates/bevy_ui/src/widget/image.rs
  crates/bevy_ui/src/widget/text.rs
Labels: A-Rendering, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Straightforward

#17213 bevy_window: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_window/src/lib.rs
  crates/bevy_window/src/raw_handle.rs
Labels: A-Windowing, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#17214 bevy_ptr: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_ptr/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Pointers

#17222 Fix "Unrecognized Option" error when using Criterion-specific arguments in benchmarks
  benches/Cargo.toml
  crates/bevy_render/src/extract_resource.rs
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, C-Benchmarks, A-Cross-Cutting

#17235 Rename `DefaultCameraView`
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/render_pass.rs
Labels: C-Docs, A-Rendering, A-UI, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Straightforward

#17234 Allow tuple structs in animated_field! macro
  crates/bevy_animation/src/animation_curves.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Animation, D-Straightforward, D-Macros

#17251 Fix up the reason given for a couple of `too_many_arguments` lints
  crates/bevy_render/src/mesh/allocator.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_ui/src/widget/text.rs
Labels: D-Trivial, A-Rendering, A-UI, S-Ready-For-Final-Review

#17248 Cleanup instances of `#[allow(clippy::type_complexity)]`
  benches/benches/bevy_ecs/main.rs
  benches/benches/bevy_reflect/main.rs
  crates/bevy_core_pipeline/src/oit/mod.rs
  crates/bevy_input_focus/src/tab_navigation.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_sprite/src/mesh2d/wireframe2d.rs
  crates/bevy_text/src/lib.rs
  examples/3d/split_screen.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review

#17245 bevy_gilrs: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_gilrs/src/rumble.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#17241 Added docs about `MinimalPlugins` looping as fast as possible.
  crates/bevy_internal/src/default_plugins.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-App, D-Straightforward

#17236 `extract_shadows` responsive coords fix
  crates/bevy_ui/src/render/box_shadow.rs
Labels: C-Bug, A-Rendering, A-UI, S-Ready-For-Final-Review, D-Straightforward

#17232 bevy_winit: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: D-Trivial, A-Windowing, C-Code-Quality, S-Needs-Review

#17210 bevy_time: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_time/src/lib.rs
  crates/bevy_time/src/timer.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Time

#17218 bevy_mesh: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_mesh/src/lib.rs
  crates/bevy_mesh/src/mesh.rs
  crates/bevy_mesh/src/vertex.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#17254 Add compile-time dyn compatible checks for `DynEq`, `DynHash`
  crates/bevy_ecs/src/label.rs
  crates/bevy_utils/src/lib.rs
  crates/bevy_utils/src/object_safe.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, A-Utils

#17225 Make sprite picking opt-in
  crates/bevy_picking/src/lib.rs
  crates/bevy_sprite/src/picking_backend.rs
  examples/picking/sprite_picking.rs
Labels: C-Performance, C-Usability, M-Needs-Migration-Guide, X-Contentious, S-Needs-Review, A-Picking

#17224 Add a simple directional UI navigation example
  Cargo.toml
  crates/bevy_input_focus/src/lib.rs
  crates/bevy_winit/src/accessibility.rs
  examples/README.md
  examples/ui/directional_navigation.rs
Labels: C-Bug, C-Examples, A-Input, A-Accessibility, A-UI, S-Ready-For-Final-Review

#17215 Improved Command Errors
  benches/benches/bevy_ecs/world/commands.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/reflect/entity_commands.rs
  crates/bevy_ecs/src/system/commands/command.rs
  crates/bevy_ecs/src/system/commands/entity_command.rs
  crates/bevy_ecs/src/system/commands/error.rs
  crates/bevy_ecs/src/system/commands/error_handler.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/command_queue.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_hierarchy/src/hierarchy.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_transform/src/commands.rs
Labels: A-ECS, C-Usability, M-Needs-Migration-Guide, D-Complex, S-Needs-Review

#17274 Minor `TextPipeline` cleanup
  crates/bevy_text/src/pipeline.rs
Labels: C-Performance, C-Code-Quality, S-Ready-For-Final-Review, A-Text

#17281 bevy_gizmos: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_gizmos/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Gizmos

#17284 bevy_transform: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_transform/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Transform

#17285 bevy_text: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_text/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Text

#17286 bevy_hierarchy: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_hierarchy/src/child_builder.rs
  crates/bevy_hierarchy/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Hierarchy

#17280 bevy_gltf: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_gltf/src/lib.rs
  crates/bevy_gltf/src/loader.rs
Labels: D-Trivial, C-Code-Quality, S-Needs-Review, A-glTF

#17277 bevy_pbr: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_pbr/src/extended_material.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/ssao/mod.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#17228 Add documentation to `DynamicStorageBuffer` to clarify purpose
  crates/bevy_render/src/render_resource/storage_buffer.rs
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#17278 bevy_scene: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_scene/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Scenes

#17260 Make `bevy_remote` feature enable `serialize` feature
  crates/bevy_internal/Cargo.toml
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Reflection, M-Needs-Migration-Guide, X-Contentious

#17292 Fix a few typos
  crates/bevy_animation/src/animatable.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_app/src/app.rs
  crates/bevy_asset/src/asset_changed.rs
  crates/bevy_core_pipeline/src/smaa/smaa.wgsl
  crates/bevy_core_pipeline/src/upscaling/mod.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/world_query.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/graph/graph_map.rs
  crates/bevy_ecs/src/storage/table/mod.rs
  crates/bevy_ecs/src/system/builder.rs
  crates/bevy_gizmos/src/primitives/dim3.rs
  crates/bevy_gizmos/src/primitives/helpers.rs
  crates/bevy_gltf/src/loader.rs
  crates/bevy_input/src/common_conditions.rs
  crates/bevy_math/src/bounding/bounded2d/primitive_impls.rs
  crates/bevy_math/src/curve/cores.rs
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_reflect/src/reflect.rs
  crates/bevy_render/src/mesh/allocator.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_sprite/src/texture_slice/mod.rs
  crates/bevy_tasks/src/task_pool.rs
  crates/bevy_utils/src/syncunsafecell.rs
  crates/bevy_window/src/event.rs
  docs-template/EXAMPLE_README.md.tpl
  docs/linux_dependencies.md
  examples/README.md
  examples/animation/custom_skinned_mesh.rs
  examples/ecs/system_piping.rs
  examples/ui/directional_navigation.rs
  examples/window/window_drag_move.rs
Labels: C-Docs, C-Code-Quality, S-Ready-For-Final-Review, A-Cross-Cutting

#17293 `bevy_image` now enables reflection on `bevy_math`
  crates/bevy_image/Cargo.toml
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, A-Reflection, P-Compile-Failure

#17296 Improve Compiler Errors for `bevy_tasks`
  crates/bevy_tasks/src/lib.rs
  crates/bevy_tasks/src/single_threaded_task_pool.rs
Labels: C-Bug, S-Ready-For-Final-Review, A-Tasks, P-Compile-Failure, D-Straightforward

#17289 bevy_image: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_image/src/compressed_image_saver.rs
  crates/bevy_image/src/image.rs
  crates/bevy_image/src/lib.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#17282 `custom_ui_material` border fix
  assets/shaders/custom_ui_material.wgsl
Labels: C-Bug, D-Trivial, A-Rendering, A-UI, S-Ready-For-Final-Review, D-Shaders

#17270 Fix text alignment for unbounded text
  crates/bevy_text/src/pipeline.rs
  examples/2d/text2d.rs
  examples/stress_tests/many_text2d.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review, A-Text

#17313 Feature gate `bevy_reflect` in `bevy_image`.
  crates/bevy_image/Cargo.toml
  crates/bevy_image/src/image.rs
  crates/bevy_image/src/texture_atlas.rs
Labels: A-Rendering, C-Code-Quality, C-Usability, S-Ready-For-Final-Review

#17302 bevy_picking: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_picking/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Picking

#17303 bevy_remote: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_remote/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Dev-Tools

#17305 bevy_utils: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_utils/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Utils

#17306 bevy_internal: Apply `#![deny(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_internal/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#17320 Downgrade `clippy::allow_attributes` and `clippy::allow_attributes_without_reason` to `warn`
  crates/bevy_a11y/src/lib.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_app/src/lib.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_audio/src/lib.rs
  crates/bevy_color/src/lib.rs
  crates/bevy_dev_tools/src/lib.rs
  crates/bevy_diagnostic/src/lib.rs
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gltf/src/lib.rs
  crates/bevy_hierarchy/src/lib.rs
  crates/bevy_image/src/lib.rs
  crates/bevy_input/src/lib.rs
  crates/bevy_internal/src/lib.rs
  crates/bevy_log/src/lib.rs
  crates/bevy_math/src/lib.rs
  crates/bevy_mesh/src/lib.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_picking/src/lib.rs
  crates/bevy_ptr/src/lib.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_remote/src/lib.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_state/src/lib.rs
  crates/bevy_tasks/src/lib.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_transform/src/lib.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_utils/src/lib.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Cross-Cutting

#17243 Rename UI `camera_entity` fields
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/debug_overlay.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
Labels: D-Trivial, A-Rendering, A-UI, C-Code-Quality, S-Ready-For-Final-Review

#17266 Rename `PickingBehavior` to `Pickable`
  crates/bevy_dev_tools/src/picking_debug.rs
  crates/bevy_picking/src/backend.rs
  crates/bevy_picking/src/hover.rs
  crates/bevy_picking/src/lib.rs
  crates/bevy_picking/src/mesh_picking/mod.rs
  crates/bevy_sprite/src/picking_backend.rs
  crates/bevy_ui/src/picking_backend.rs
  examples/3d/mixed_lighting.rs
  examples/picking/mesh_picking.rs
  examples/testbed/ui.rs
  examples/ui/scroll.rs
Labels: C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Contentious, D-Straightforward, A-Picking

#17264 Fix entity does not exist message on index reuse
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/reflect/entity_commands.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/entity_fetch.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#17311 Renamed members of `ParamWarnPolicy` to reflect new behaviour.
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_registry.rs
  examples/ecs/fallible_params.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#16740 Higher quality bicubic lightmap sampling
  crates/bevy_pbr/src/lightmap/lightmap.wgsl
  crates/bevy_pbr/src/lightmap/mod.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/mesh.rs
  examples/3d/lightmaps.rs
  examples/3d/mixed_lighting.rs
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review

#17259 Allow users to customize history length in `FrameTimeDiagnosticsPlugin`
  crates/bevy_dev_tools/src/fps_overlay.rs
  crates/bevy_diagnostic/src/frame_time_diagnostics_plugin.rs
  examples/diagnostics/enabling_disabling_diagnostic.rs
  examples/diagnostics/log_diagnostics.rs
  examples/stress_tests/bevymark.rs
  examples/stress_tests/many_animated_sprites.rs
  examples/stress_tests/many_buttons.rs
  examples/stress_tests/many_components.rs
  examples/stress_tests/many_cubes.rs
  examples/stress_tests/many_foxes.rs
  examples/stress_tests/many_gizmos.rs
  examples/stress_tests/many_glyphs.rs
  examples/stress_tests/many_lights.rs
  examples/stress_tests/many_sprites.rs
  examples/stress_tests/many_text2d.rs
  examples/stress_tests/text_pipeline.rs
  examples/stress_tests/transform_hierarchy.rs
  examples/ui/text.rs
  examples/ui/text_debug.rs
  examples/window/window_settings.rs
Labels: C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Diagnostics, X-Uncontroversial, D-Straightforward

#16942 Key render phases off the main world view entity, not the render world view entity.
  crates/bevy_core_pipeline/src/core_2d/main_opaque_pass_2d_node.rs
  crates/bevy_core_pipeline/src/core_2d/main_transparent_pass_2d_node.rs
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transmissive_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transparent_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/deferred/node.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/render_pass.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
  examples/2d/mesh2d_manual.rs
  examples/shader/custom_phase_item.rs
  examples/shader/custom_shader_instancing.rs
  examples/shader/specialized_mesh_pipeline.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#17349 Fix `bevy_time` tests occasionally failing on optimised Windows builds
  crates/bevy_time/src/real.rs
Labels: A-Build-System, S-Ready-For-Final-Review, C-Testing, A-Time

#16785 Add std derives to SystemParam types
  crates/bevy_ecs/src/system/builder.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#7849 `update_text2d_layout` creates new font atlases when the primary window is closed
  crates/bevy_text/src/text2d.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review, D-Straightforward

#17354 Diagnostics smoothing factor fix
  crates/bevy_diagnostic/src/frame_time_diagnostics_plugin.rs
Labels: C-Bug, A-Diagnostics, D-Straightforward, S-Needs-Review

#17358 Make InputFocus optional in bevy_winit
  crates/bevy_winit/src/accessibility.rs
Labels: A-Input, A-Windowing, P-Crash, S-Ready-For-Final-Review, D-Straightforward

#16940 Add BRP method to mutate a component
  crates/bevy_remote/src/builtin_methods.rs
  crates/bevy_remote/src/lib.rs
Labels: C-Feature, S-Ready-For-Final-Review, A-Dev-Tools, D-Straightforward

#17308 Add some multi-span text to the `text2d` example
  examples/2d/text2d.rs
Labels: D-Trivial, C-Examples, S-Ready-For-Final-Review, A-Text

#17343 Ambient component
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light/ambient_light.rs
  crates/bevy_pbr/src/render/light.rs
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review

#17364 Refactor event system documentation in `system_param.rs`
  crates/bevy_ecs/src/system/system_param.rs
Labels: C-Docs, D-Trivial, A-ECS, C-Examples, S-Ready-For-Final-Review

#17291 Create missing constructors for 2D primitive mesh builders
  crates/bevy_mesh/src/primitives/dim2.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, A-Math, D-Straightforward

#17211 Use `multi_draw_indirect_count` where available, in preparation for two-phase occlusion culling.
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/build_indirect_params.wgsl
  crates/bevy_pbr/src/render/gpu_preprocess.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/render/mesh_preprocess.wgsl
  crates/bevy_pbr/src/render/mesh_preprocess_types.wgsl
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/batching/mod.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/mesh/components.rs
  crates/bevy_render/src/mesh/mod.rs
  crates/bevy_render/src/render_phase/mod.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/render_pass.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
  examples/2d/mesh2d_manual.rs
  examples/shader/custom_shader_instancing.rs
  examples/shader/specialized_mesh_pipeline.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Complex

#17137 bevy_core_pipeline: Apply `#![warn(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_core_pipeline/src/auto_exposure/compensation_curve.rs
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#17323 bevy_input_focus: Apply `#![warn(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_input_focus/src/lib.rs
Labels: D-Trivial, A-Input, C-Code-Quality, S-Ready-For-Final-Review

#17332 bevy_dylib: Apply `#![warn(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_dylib/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review

#17304 bevy_macro_utils: Apply `#![warn(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_macro_utils/src/lib.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Utils

#17335 bevy_ecs: Apply `#![warn(clippy::allow_attributes, clippy::allow_attributes_without_reason)]`
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/entity/entity_set.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/entity/visit_entities.rs
  crates/bevy_ecs/src/event/event_cursor.rs
  crates/bevy_ecs/src/event/mod.rs
  crates/bevy_ecs/src/identifier/mod.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/world_query.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/graph/mod.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/stepping.rs
  crates/bevy_ecs/src/system/builder.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/exclusive_system_param.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/input.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/command_queue.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#17368 Fix some punctuation
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_render/src/render_resource/bind_group.rs
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#17363 Fix a missing `.entity() -> .target()` conversion in observers example
  examples/ecs/observers.rs
Labels: C-Docs, D-Trivial, A-ECS, C-Examples, S-Ready-For-Final-Review

#17327 added `any_match_filter` common condition
  crates/bevy_ecs/src/schedule/condition.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#17366 fix typo query.rs
  crates/bevy_ecs/src/system/query.rs
Labels: C-Docs, D-Trivial, A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#17297 Make `ObservedBy` public
  crates/bevy_ecs/src/observer/entity_observer.rs
  crates/bevy_ecs/src/observer/mod.rs
Labels: C-Feature, D-Trivial, A-ECS, S-Ready-For-Final-Review, X-Contentious

#16545 feat: support for clip children on windows
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Feature, A-Windowing, S-Ready-For-Final-Review, D-Straightforward

#17121 Support texture atlases in CustomCursor::Image
  Cargo.toml
  assets/cursors/kenney_crosshairPack/License.txt
  assets/cursors/kenney_crosshairPack/Tilesheet/crosshairs_tilesheet_white.png
  crates/bevy_image/src/texture_atlas.rs
  crates/bevy_winit/src/cursor.rs
  crates/bevy_winit/src/custom_cursor.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/state.rs
  examples/README.md
  examples/window/custom_cursor_image.rs
  examples/window/window_settings.rs
Labels: A-Windowing, C-Usability, S-Ready-For-Final-Review, X-Contentious, D-Modest

#17374 Move `#![warn(clippy::allow_attributes, clippy::allow_attributes_without_reason)]` to the workspace `Cargo.toml`
  Cargo.toml
  benches/Cargo.toml
  benches/benches/bevy_ecs/components/add_remove_very_big_table.rs
  crates/bevy_a11y/src/lib.rs
  crates/bevy_animation/src/lib.rs
  crates/bevy_app/src/lib.rs
  crates/bevy_asset/src/lib.rs
  crates/bevy_audio/src/lib.rs
  crates/bevy_color/src/lib.rs
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_dev_tools/src/lib.rs
  crates/bevy_diagnostic/src/lib.rs
  crates/bevy_dylib/src/lib.rs
  crates/bevy_ecs/examples/change_detection.rs
  crates/bevy_ecs/examples/resources.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gltf/src/lib.rs
  crates/bevy_hierarchy/src/lib.rs
  crates/bevy_image/src/lib.rs
  crates/bevy_input/src/lib.rs
  crates/bevy_input_focus/src/lib.rs
  crates/bevy_internal/src/lib.rs
  crates/bevy_log/src/lib.rs
  crates/bevy_macro_utils/src/lib.rs
  crates/bevy_math/src/lib.rs
  crates/bevy_mesh/src/lib.rs
  crates/bevy_mikktspace/src/lib.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_picking/src/lib.rs
  crates/bevy_ptr/src/lib.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_remote/src/lib.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_state/src/lib.rs
  crates/bevy_tasks/src/lib.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_transform/src/lib.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_utils/src/lib.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_winit/src/lib.rs
  examples/asset/custom_asset.rs
  examples/asset/processing/asset_processing.rs
  examples/ecs/dynamic.rs
  examples/ecs/immutable_components.rs
  examples/math/render_primitives.rs
  examples/reflection/reflection_types.rs
  examples/stress_tests/many_components.rs
  examples/stress_tests/transform_hierarchy.rs
  src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Cross-Cutting, D-Straightforward

#16600 Forward decals (port of bevy_contact_projective_decals)
  Cargo.toml
  crates/bevy_pbr/src/decal/forward.rs
  crates/bevy_pbr/src/decal/forward_decal.wgsl
  crates/bevy_pbr/src/decal/mod.rs
  crates/bevy_pbr/src/extended_material.rs
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/render/pbr.wgsl
  crates/bevy_render/src/maths.wgsl
  examples/3d/decal.rs
  examples/README.md
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, M-Needs-Release-Note

#17381 Move CustomCursor to bevy_winit/src/custom_cursor.rs
  crates/bevy_winit/src/cursor.rs
  crates/bevy_winit/src/custom_cursor.rs
Labels: D-Trivial, A-Windowing, C-Code-Quality, S-Ready-For-Final-Review

#17372 Add type registration for PickingInteraction
  crates/bevy_picking/src/lib.rs
Labels: C-Feature, D-Trivial, S-Ready-For-Final-Review, A-Reflection, A-Picking

#17385 Clip outlines using the local clipping rect.
  crates/bevy_ui/src/render/mod.rs
Labels: C-Bug, D-Trivial, A-UI, S-Ready-For-Final-Review

#17380 Remove Event: Component trait bound using a wrapper type which impls Component
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/src/event/base.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Contentious, D-Straightforward

#17387 Use chain() for system dependency
  crates/bevy_render/src/lib.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#17391 Implement `Clone` for `QueryIter` over read-only data
  crates/bevy_ecs/src/query/iter.rs
Labels: C-Feature, D-Trivial, A-ECS, S-Ready-For-Final-Review, X-Uncontroversial
