Repository bevyengine/bevy, pull requests merged in 2025-06, with the labels that each got.

#18513 add 2d_on_ui example
  Cargo.toml
  examples/README.md
  examples/camera/2d_on_ui.rs
Labels: A-Rendering, C-Examples, A-UI, S-Ready-For-Final-Review

#19250 Clarify PartialReflect::apply docs
  crates/bevy_reflect/src/reflect.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Reflection, D-Straightforward

#19478 Use BevyError for AssetLoader::Error
  crates/bevy_asset/src/loader.rs
  crates/bevy_asset/src/server/mod.rs
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#19449 Allow returning an error from `labeled_asset_scope`.
  crates/bevy_asset/src/loader.rs
  crates/bevy_gltf/src/loader/mod.rs
  release-content/migration-guides/labeled_asset_scope_errors.md
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Uncontroversial, D-Straightforward

#19483 deny(missing_docs) for bevy_derive
  crates/bevy_derive/src/lib.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#19490 Mention `Option` and `When` in the error message for a failing system parameter
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/system/system_registry.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial

#19492 deny(missing_docs) for bevy_state
  crates/bevy_state/macros/src/lib.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#19493 Add a few missing doc comments in bevy_image
  crates/bevy_image/src/dynamic_texture_atlas_builder.rs
  crates/bevy_image/src/image.rs
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#19423 fix: Ensure linear volume subtraction does not go below zero
  crates/bevy_audio/src/volume.rs
  examples/audio/audio_control.rs
  examples/audio/soundtrack.rs
  release-content/migration-guides/remove_the_add_sub_impls_on_volume.md
Labels: D-Trivial, A-Audio, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#17575 generic component propagation
  crates/bevy_app/src/lib.rs
  crates/bevy_app/src/propagate.rs
Labels: C-Feature, A-ECS, C-Usability, S-Ready-For-Final-Review

#19515 Allow new mismatched_lifetime_syntaxes lint
  Cargo.toml
Labels: D-Trivial, A-Build-System, S-Ready-For-Final-Review, P-Critical, X-Contentious

#19510 Only get valid component ids
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/clone_entities.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/filtered_resource.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/reflect.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_remote/src/builtin_methods.rs
  crates/bevy_scene/src/dynamic_scene_builder.rs
Labels: C-Bug, A-ECS, C-Performance, P-High, S-Ready-For-Final-Review

#19516 Remove re-exports of cosmic_text types
  crates/bevy_text/src/text.rs
  release-content/migration-guides/remove_cosmic_text_reexports.md
Labels: C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Text, X-Contentious, D-Straightforward

#19518 Mention in the docs for pointer events that these are in screen-space.
  crates/bevy_picking/src/events.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review, A-Picking

#19432 Replace (`Partial`)`Ord` for `EntityGeneration` with corrected standalone method
  crates/bevy_ecs/src/entity/map_entities.rs
  crates/bevy_ecs/src/entity/mod.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review

#19194 Improve Bevy's double-precision story for third-party crates
  benches/benches/bevy_math/bezier.rs
  crates/bevy_animation/src/gltf_curves.rs
  crates/bevy_color/src/lib.rs
  crates/bevy_math/src/common_traits.rs
  crates/bevy_math/src/cubic_splines/curve_impls.rs
  crates/bevy_math/src/cubic_splines/mod.rs
  crates/bevy_math/src/curve/derivatives/adaptor_impls.rs
  crates/bevy_math/src/curve/easing.rs
  crates/bevy_math/src/sampling/shape_sampling.rs
  examples/animation/color_animation.rs
  release-content/migration-guides/scalar-field-on-vector-space.md
Labels: S-Ready-For-Final-Review, A-Math, M-Needs-Migration-Guide, D-Modest

#19321 Update add flake.nix example
  docs/linux_dependencies.md
Labels: C-Docs, O-Linux, S-Ready-For-Final-Review

#19488 Fix PickingInteraction change detection
  crates/bevy_picking/src/hover.rs
Labels: C-Bug, S-Ready-For-Final-Review, D-Straightforward, A-Picking

#19520 Gradients example: Fit in initial window
  examples/ui/gradients.rs
Labels: D-Trivial, C-Examples, A-UI, S-Ready-For-Final-Review

#19548 Add more wgpu helpers/types
  crates/bevy_render/src/render_resource/bind_group_entries.rs
  crates/bevy_render/src/render_resource/bind_group_layout_entries.rs
  crates/bevy_render/src/render_resource/mod.rs
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review

#19549 Add CameraMainTextureUsages helper method
  crates/bevy_render/src/camera/camera.rs
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review

#19550 Require naga_oil 0.17.1
  crates/bevy_render/Cargo.toml
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review

#19233 Clarify docs for transmute_lens functions
  crates/bevy_ecs/src/system/query.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#19397 Remove workaround for image resize warning
  crates/bevy_ui/src/widget/viewport.rs
Labels: D-Trivial, A-UI, C-Code-Quality, S-Ready-For-Final-Review

#19495 Use component_access_set to determine the set of conflicting accesses between two systems.
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#19499 Add missing docs for ImageLoader
  crates/bevy_image/src/image_loader.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#19522 Rename `JustifyText` to `Justify`
  crates/bevy_text/src/bounds.rs
  crates/bevy_text/src/lib.rs
  crates/bevy_text/src/pipeline.rs
  crates/bevy_text/src/text.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/widget/text.rs
  examples/2d/sprite_scale.rs
  examples/2d/sprite_slice.rs
  examples/2d/text2d.rs
  examples/2d/texture_atlas.rs
  examples/3d/tonemapping.rs
  examples/animation/animated_ui.rs
  examples/animation/animation_graph.rs
  examples/animation/animation_masks.rs
  examples/async_tasks/external_source_external_thread.rs
  examples/ecs/one_shot_systems.rs
  examples/math/render_primitives.rs
  examples/mobile/src/lib.rs
  examples/stress_tests/many_glyphs.rs
  examples/stress_tests/many_text2d.rs
  examples/stress_tests/text_pipeline.rs
  examples/testbed/2d.rs
  examples/testbed/ui.rs
  examples/time/virtual_time.rs
  examples/ui/directional_navigation.rs
  examples/ui/display_and_visibility.rs
  examples/ui/size_constraints.rs
  examples/ui/text.rs
  examples/ui/text_background_colors.rs
  examples/ui/text_debug.rs
  examples/ui/text_wrap_debug.rs
  release-content/migration-guides/rename-justifytext.md
Labels: C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Text

#19538 Write real docs for `SystemSet`
  crates/bevy_ecs/src/schedule/set.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review, X-Uncontroversial, D-Modest

#19546 Add extra buffer usages field to MeshAllocator
  crates/bevy_render/src/mesh/allocator.rs
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review

#19547 Make camera controller not trigger change detection every frame
  examples/helpers/camera_controller.rs
Labels: D-Trivial, C-Examples, S-Ready-For-Final-Review

#19249 Allow not emitting `BundleFromComponents` with `Bundle` derive macro
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/bundle.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, D-Modest, D-Macros

#19274 Introduce `CheckChangeTicks` event that is triggered by `World::check_change_ticks`
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, S-Ready-For-Final-Review, A-Time, A-Networking, D-Straightforward

#19561 Fix uninlined format argument lint
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/stepping.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review

#19496 Delete `System::component_access()`.
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/observer_system.rs
  crates/bevy_ecs/src/system/schedule_system.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  release-content/migration-guides/delete_component_access.md
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Straightforward

#19543 Component lifecycle reorganization and documentation
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/propagate.rs
  crates/bevy_core_pipeline/src/oit/mod.rs
  crates/bevy_ecs/compile_fail/tests/ui/component_hook_relationship.rs
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/event/base.rs
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/lifecycle.rs
  crates/bevy_ecs/src/observer/entity_observer.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/relationship/mod.rs
  crates/bevy_ecs/src/removal_detection.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/world/component_constants.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_input_focus/src/autofocus.rs
  crates/bevy_input_focus/src/lib.rs
  crates/bevy_pbr/src/lightmap/mod.rs
  crates/bevy_remote/src/builtin_methods.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/sync_world.rs
  crates/bevy_render/src/view/visibility/mod.rs
  crates/bevy_render/src/view/visibility/range.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_winit/src/cursor.rs
  crates/bevy_winit/src/system.rs
  examples/ecs/component_hooks.rs
  examples/ecs/immutable_components.rs
  release-content/migration-guides/component-lifecycle-module.md
Labels: C-Docs, A-ECS, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Uncontroversial, D-Straightforward

#19517 Rename bevy_ecs::world::Entry to ComponentEntry
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_render/src/sync_world.rs
  release-content/migration-guides/component_entry.md
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#19571 Fix `pbr` example text rotation
  examples/3d/pbr.rs
Labels: D-Trivial, A-Rendering, C-Examples, S-Ready-For-Final-Review

#19574 Rename some pointer events and components
  crates/bevy_core_widgets/src/core_button.rs
  crates/bevy_dev_tools/src/picking_debug.rs
  crates/bevy_picking/src/events.rs
  crates/bevy_picking/src/hover.rs
  crates/bevy_picking/src/lib.rs
  crates/bevy_ui/src/interaction_states.rs
  crates/bevy_ui/src/lib.rs
  examples/picking/mesh_picking.rs
  examples/picking/sprite_picking.rs
  examples/ui/core_widgets.rs
  examples/ui/core_widgets_observers.rs
  examples/ui/scroll.rs
  examples/usages/context_menu.rs
  release-content/migration-guides/rename_pointer_events.md
  release-content/release-notes/headless-widgets.md
Labels: D-Trivial, A-UI, C-Code-Quality, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Picking

#19590 Thoroughly document the current state of observers
  crates/bevy_ecs/src/observer/mod.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review, X-Uncontroversial, D-Modest

#19578 Fix `bevy_core_widgets` crate description typo
  crates/bevy_core_widgets/Cargo.toml
Labels: C-Docs, D-Trivial, A-UI, S-Ready-For-Final-Review

#19565 Update example doc link for `ImageLoaderSettings`.
  examples/asset/asset_settings.rs
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#19592 Modified the "scroll.rs" example to use the new spawning API.
  examples/ui/scroll.rs
Labels: D-Trivial, C-Examples, A-UI, S-Ready-For-Final-Review, X-Uncontroversial

#19575 Make `GILRS` and `WINIT_WINDOWS` public
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_winit/src/lib.rs
  release-content/migration-guides/replace_non_send_resources.md
Labels: A-ECS, A-Windowing, C-Usability, S-Ready-For-Final-Review, P-Regression

#19604 don't deny warnings on wasm-atomics CI job
  .github/workflows/ci.yml
Labels: D-Trivial, A-Build-System, P-High, C-Usability, S-Ready-For-Final-Review

#19621 Make `IrradianceVolume` require `LightProbe` (and document this).
  crates/bevy_pbr/src/light_probe/irradiance_volume.rs
  examples/3d/irradiance_volumes.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#19618 Fixing `AutoFocus` not working if it's spawn before Startup
  crates/bevy_input_focus/Cargo.toml
  crates/bevy_input_focus/src/lib.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#19477 Stop storing access for all systems
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/lifecycle.rs
  crates/bevy_ecs/src/schedule/auto_insert_apply_deferred.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/builder.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/observer_system.rs
  crates/bevy_ecs/src/system/schedule_system.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_name.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/identifier.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_gizmos/src/gizmos.rs
  crates/bevy_render/src/extract_param.rs
  release-content/migration-guides/delete_component_access.md
  release-content/migration-guides/stop_storing_system_access.md
Labels: A-ECS, C-Performance, C-Code-Quality, S-Ready-For-Final-Review

#19584 Core slider
  crates/bevy_core_widgets/Cargo.toml
  crates/bevy_core_widgets/src/core_slider.rs
  crates/bevy_core_widgets/src/lib.rs
  examples/ui/core_widgets.rs
  examples/ui/core_widgets_observers.rs
  release-content/release-notes/headless-widgets.md
Labels: C-Feature, A-UI, S-Ready-For-Final-Review, M-Needs-Release-Note, X-Contentious

#19651 Fix typos
  crates/bevy_ecs/src/relationship/relationship_source_collection.rs
Labels: D-Trivial, S-Ready-For-Final-Review

#19588 Preserve extra data in `RelationshipTarget` with `replace_related`(`_with_difference`)
  crates/bevy_ecs/src/relationship/related_methods.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#19606 Replace `UntypedHandle` from ReflectAsset with `impl Into<UntypedAssetId>`.
  crates/bevy_asset/src/reflect.rs
  release-content/migration-guides/reflect_asset_asset_ids.md
Labels: A-Assets, C-Usability, S-Ready-For-Final-Review, A-Reflection, M-Needs-Migration-Guide, X-Uncontroversial, D-Straightforward

#19654 deny(missing_docs) for bevy_mikktspace
  crates/bevy_mikktspace/src/lib.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#19658 lighting.rs example: Improved ambient light showcase
  examples/3d/lighting.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review, M-Deliberate-Rendering-Change

#19622 Add insert_child and remove_child methods
  crates/bevy_ecs/src/hierarchy.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial

#19659 Make sequential_dispersed fn constant
  crates/bevy_color/src/hsla.rs
  crates/bevy_color/src/lcha.rs
  crates/bevy_color/src/oklcha.rs
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Color

#19663 Provide access to the original target of entity-events in observers
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_picking/src/events.rs
  examples/ecs/error_handling.rs
  examples/ui/directional_navigation.rs
  examples/usages/context_menu.rs
  release-content/migration-guides/pointer_target.md
  release-content/release-notes/observer_overhaul.md
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, M-Needs-Migration-Guide, M-Needs-Release-Note, X-Contentious, D-Modest, A-Picking

#19605 Add more PreviousViewData
  crates/bevy_core_pipeline/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/prepass/prepass_bindings.wgsl
Labels: A-Rendering, C-Usability, X-Uncontroversial, D-Straightforward, S-Needs-Review

#15396 Let query items borrow from query state to avoid needing to clone
  crates/bevy_anti_aliasing/src/smaa/mod.rs
  crates/bevy_asset/src/asset_changed.rs
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/bloom/settings.rs
  crates/bevy_core_pipeline/src/core_2d/main_opaque_pass_2d_node.rs
  crates/bevy_core_pipeline/src/core_2d/main_transparent_pass_2d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/deferred/node.rs
  crates/bevy_core_pipeline/src/dof/mod.rs
  crates/bevy_core_pipeline/src/msaa_writeback.rs
  crates/bevy_core_pipeline/src/post_process/mod.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_ecs/macros/src/query_data.rs
  crates/bevy_ecs/macros/src/query_filter.rs
  crates/bevy_ecs/macros/src/world_query.rs
  crates/bevy_ecs/src/name.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/query/world_query.rs
  crates/bevy_ecs/src/relationship/relationship_query.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/traversal.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_input_focus/src/lib.rs
  crates/bevy_pbr/src/atmosphere/mod.rs
  crates/bevy_pbr/src/atmosphere/node.rs
  crates/bevy_pbr/src/light_probe/environment_map.rs
  crates/bevy_pbr/src/render/mesh.rs
  crates/bevy_pbr/src/ssr/mod.rs
  crates/bevy_pbr/src/volumetric_fog/render.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_picking/src/events.rs
  crates/bevy_render/macros/src/extract_component.rs
  crates/bevy_render/src/extract_component.rs
  crates/bevy_render/src/extract_instances.rs
  crates/bevy_render/src/render_graph/node.rs
  crates/bevy_render/src/render_phase/draw.rs
  crates/bevy_render/src/sync_world.rs
  crates/bevy_sprite/src/mesh2d/mesh.rs
  crates/bevy_sprite/src/mesh2d/wireframe2d.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  examples/ecs/custom_query_param.rs
  examples/shader/custom_phase_item.rs
  examples/shader/custom_render_phase.rs
  examples/shader/custom_shader_instancing.rs
  release-content/migration-guides/query_items_borrow_from_query_state.md
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Complex, X-Contentious

#19359 Allow passing number of thread for building and testing to CI
  tools/ci/Cargo.toml
  tools/ci/src/args.rs
  tools/ci/src/ci.rs
  tools/ci/src/commands/bench_check.rs
  tools/ci/src/commands/clippy.rs
  tools/ci/src/commands/compile.rs
  tools/ci/src/commands/compile_check.rs
  tools/ci/src/commands/compile_fail.rs
  tools/ci/src/commands/doc.rs
  tools/ci/src/commands/doc_check.rs
  tools/ci/src/commands/doc_test.rs
  tools/ci/src/commands/example_check.rs
  tools/ci/src/commands/format.rs
  tools/ci/src/commands/integration_test.rs
  tools/ci/src/commands/integration_test_check.rs
  tools/ci/src/commands/integration_test_clean.rs
  tools/ci/src/commands/lints.rs
  tools/ci/src/commands/test.rs
  tools/ci/src/commands/test_check.rs
  tools/ci/src/main.rs
  tools/ci/src/prepare.rs
Labels: C-Feature, A-Build-System, S-Ready-For-Final-Review, D-Straightforward

#19481 deny(missing_docs) for bevy_reflect
  crates/bevy_reflect/src/array.rs
  crates/bevy_reflect/src/attributes.rs
  crates/bevy_reflect/src/enums/dynamic_enum.rs
  crates/bevy_reflect/src/enums/enum_trait.rs
  crates/bevy_reflect/src/enums/variants.rs
  crates/bevy_reflect/src/error.rs
  crates/bevy_reflect/src/fields.rs
  crates/bevy_reflect/src/func/args/arg.rs
  crates/bevy_reflect/src/func/args/error.rs
  crates/bevy_reflect/src/func/error.rs
  crates/bevy_reflect/src/func/info.rs
  crates/bevy_reflect/src/func/mod.rs
  crates/bevy_reflect/src/func/registry.rs
  crates/bevy_reflect/src/kind.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/map.rs
  crates/bevy_reflect/src/reflect.rs
  crates/bevy_reflect/src/serde/de/deserialize_with_registry.rs
  crates/bevy_reflect/src/serde/de/registrations.rs
  crates/bevy_reflect/src/serde/mod.rs
  crates/bevy_reflect/src/serde/ser/serializable.rs
  crates/bevy_reflect/src/serde/ser/serialize_with_registry.rs
  crates/bevy_reflect/src/std_traits.rs
  crates/bevy_reflect/src/struct_trait.rs
  crates/bevy_reflect/src/tuple.rs
  crates/bevy_reflect/src/tuple_struct.rs
  crates/bevy_reflect/src/type_info.rs
  crates/bevy_reflect/src/type_registry.rs
  crates/bevy_reflect/src/utility.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#19595 Fix SubStates with multiple source states not reacting to all source changes
  crates/bevy_state/src/state/mod.rs
  crates/bevy_state/src/state/state_set.rs
Labels: C-Bug, S-Ready-For-Final-Review, D-Straightforward, A-States

#19633 Allow users to fix glTF coordinate system imports
  crates/bevy_gltf/src/convert_coordinates.rs
  crates/bevy_gltf/src/lib.rs
  crates/bevy_gltf/src/loader/gltf_ext/scene.rs
  crates/bevy_gltf/src/loader/mod.rs
  crates/bevy_gltf/src/vertex_attributes.rs
  release-content/release-notes/convert-coordinates.md
Labels: S-Ready-For-Final-Review, M-Needs-Release-Note, X-Uncontroversial, D-Modest, A-glTF

#19661 Fix Keyboard observer not updating SliderValue
  crates/bevy_core_widgets/src/core_slider.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review, D-Straightforward

#19676 slider widget track click position `UiScale` fix
  crates/bevy_core_widgets/src/core_slider.rs
Labels: C-Bug, D-Trivial, A-UI, S-Ready-For-Final-Review

#19643 rename GlobalTransform::compute_matrix to to_matrix
  crates/bevy_pbr/src/atmosphere/resources.rs
  crates/bevy_pbr/src/cluster/assign.rs
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/volumetric_fog/render.rs
  crates/bevy_picking/src/mesh_picking/ray_cast/intersections.rs
  crates/bevy_picking/src/mesh_picking/ray_cast/mod.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/projection.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_solari/src/scene/binder.rs
  crates/bevy_transform/src/components/global_transform.rs
  release-content/migration-guides/rename_global_transform_compute_matrix.md
Labels: S-Ready-For-Final-Review, A-Math, M-Needs-Migration-Guide, D-Straightforward

#19668 Split CursorOptions off of Window
  crates/bevy_window/src/lib.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/state.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/games/desk_toy.rs
  examples/helpers/camera_controller.rs
  examples/input/mouse_grab.rs
  examples/ui/window_fallthrough.rs
  examples/window/window_settings.rs
  release-content/migration-guides/split-window.md
  tools/example-showcase/fixed-window-position.patch
Labels: A-Input, A-Windowing, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Straightforward

#19705 Revert "bevy_log: refactor how log layers are wired together (#19248)"
  crates/bevy_log/src/lib.rs
  examples/app/log_layers.rs
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, P-Critical, A-Diagnostics

#19683 Add TypeIdMapExt trait to make TypeIdMap operations more ergonomic
  crates/bevy_utils/src/map.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#19708 Added clone bounds to EntityEvents that were missing them.
  crates/bevy_core_widgets/src/core_slider.rs
  crates/bevy_ecs/src/lifecycle.rs
Labels: D-Trivial, A-ECS, A-UI, C-Usability, S-Ready-For-Final-Review

#19611 Exposes `Observer`'s system's name
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/system/schedule_system.rs
  release-content/release-notes/observer_overhaul.md
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Release-Note, X-Contentious, D-Straightforward

#19646 rename Transform::compute_matrix to to_matrix
  crates/bevy_core_pipeline/src/skybox/mod.rs
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_transform/src/components/transform.rs
  release-content/migration-guides/rename_global_transform_compute_matrix.md
  release-content/migration-guides/rename_transform_compute_matrix.md
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Math, M-Needs-Migration-Guide

#19558 ECS: put strings only used for debug behind a feature
  .github/workflows/ci.yml
  Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/clone_entities.rs
  crates/bevy_ecs/src/error/command_handling.rs
  crates/bevy_ecs/src/error/handler.rs
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/query/error.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/reflect/bundle.rs
  crates/bevy_ecs/src/reflect/component.rs
  crates/bevy_ecs/src/reflect/mod.rs
  crates/bevy_ecs/src/relationship/mod.rs
  crates/bevy_ecs/src/schedule/condition.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/schedule/set.rs
  crates/bevy_ecs/src/schedule/stepping.rs
  crates/bevy_ecs/src/storage/resource.rs
  crates/bevy_ecs/src/system/adapter_system.rs
  crates/bevy_ecs/src/system/combinator.rs
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/function_system.rs
  crates/bevy_ecs/src/system/observer_system.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/schedule_system.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_name.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/error.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_ecs/src/world/reflect.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_remote/Cargo.toml
  crates/bevy_remote/src/builtin_methods.rs
  crates/bevy_scene/src/scene.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_utils/Cargo.toml
  crates/bevy_utils/src/debug_info.rs
  crates/bevy_utils/src/lib.rs
  docs/cargo_features.md
  examples/games/stepping.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review, X-Contentious

#19684 Add support for ButtonInput<Key>
  crates/bevy_input/src/button_input.rs
  crates/bevy_input/src/keyboard.rs
  crates/bevy_input/src/lib.rs
  examples/input/keyboard_input.rs
  release-content/release-notes/key_buttoninput.md
Labels: A-Input, S-Ready-For-Final-Review, M-Needs-Release-Note, X-Contentious

#19720 Remove `'s` lifetime from `WorldQuery::Fetch`
  crates/bevy_asset/src/asset_changed.rs
  crates/bevy_ecs/macros/src/query_data.rs
  crates/bevy_ecs/macros/src/query_filter.rs
  crates/bevy_ecs/macros/src/world_query.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/world_query.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
  crates/bevy_render/src/sync_world.rs
  release-content/migration-guides/query_items_borrow_from_query_state.md
Labels: A-ECS, S-Ready-For-Final-Review

#19719 deny(missing_docs) for bevy_asset_macros
  crates/bevy_asset/macros/src/lib.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#19655 deny(missing_docs) for bevy_window
  crates/bevy_window/src/event.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#19724 Rewrite camera shake example
  examples/camera/2d_screen_shake.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review, D-Modest, M-Deliberate-Rendering-Change, A-Camera

#19756 don't allow nightly lints
  Cargo.toml
Labels: A-Build-System, S-Ready-For-Final-Review, X-Blessed

#19757 Move `usages` folder to `usage`
  Cargo.toml
  examples/README.md
  examples/usage/context_menu.rs
Labels: D-Trivial, C-Examples, S-Ready-For-Final-Review

#19738 Fix issue 19734: add dependency on bevy_utils for the bevy_ecs test.
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/schedule/mod.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_name.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/system/system_registry.rs
Labels: C-Bug, A-ECS, A-Build-System, S-Ready-For-Final-Review

#19736 New simplified "click to focus" logic for core widgets.
  crates/bevy_core_widgets/src/core_button.rs
  crates/bevy_core_widgets/src/core_slider.rs
  crates/bevy_input_focus/Cargo.toml
  crates/bevy_input_focus/src/lib.rs
  crates/bevy_input_focus/src/tab_navigation.rs
  examples/ui/core_widgets.rs
  examples/ui/core_widgets_observers.rs
Labels: A-UI, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#19601 `EntityWorldMut` methods do not automatically overwrite `Relationship` components
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/src/relationship/mod.rs
  crates/bevy_ecs/src/relationship/related_methods.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/mod.rs
  release-content/migration-guides/relationship_set_risky.md
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#19780 Add `num_entities()` to World
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/command_queue.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: D-Trivial, A-ECS, S-Ready-For-Final-Review

#19746 Add newlines before impl blocks
  benches/benches/bevy_ecs/change_detection.rs
  crates/bevy_app/src/propagate.rs
  crates/bevy_asset/src/direct_access_ext.rs
  crates/bevy_asset/src/io/embedded/embedded_watcher.rs
  crates/bevy_asset/src/io/embedded/mod.rs
  crates/bevy_asset/src/reflect.rs
  crates/bevy_audio/src/audio_output.rs
  crates/bevy_core_pipeline/src/core_3d/camera_3d.rs
  crates/bevy_diagnostic/src/frame_time_diagnostics_plugin.rs
  crates/bevy_ecs/src/archetype.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/entity/unique_array.rs
  crates/bevy_ecs/src/name.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/filter.rs
  crates/bevy_ecs/src/schedule/pass.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/spawn.rs
  crates/bevy_ecs/src/system/observer_system.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_gizmos/src/grid.rs
  crates/bevy_image/src/texture_atlas.rs
  crates/bevy_math/src/cubic_splines/mod.rs
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
  crates/bevy_math/src/primitives/polygon.rs
  crates/bevy_mesh/src/index.rs
  crates/bevy_mesh/src/morph.rs
  crates/bevy_pbr/src/light/ambient_light.rs
  crates/bevy_pbr/src/parallax.rs
  crates/bevy_ptr/src/lib.rs
  crates/bevy_reflect/src/func/dynamic_function.rs
  crates/bevy_reflect/src/func/signature.rs
  crates/bevy_reflect/src/impls/smallvec.rs
  crates/bevy_reflect/src/kind.rs
  crates/bevy_reflect/src/path/error.rs
  crates/bevy_reflect/src/path/mod.rs
  crates/bevy_reflect/src/path/parse.rs
  crates/bevy_reflect/src/tuple.rs
  crates/bevy_reflect/src/type_registry.rs
  crates/bevy_render/src/render_resource/gpu_array_buffer.rs
  crates/bevy_tasks/src/executor.rs
  crates/bevy_tasks/src/lib.rs
  crates/bevy_tasks/src/thread_executor.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_window/src/event.rs
  examples/3d/meshlet.rs
  examples/3d/parallax_mapping.rs
  examples/animation/color_animation.rs
  examples/app/log_layers_ecs.rs
  examples/shader/custom_render_phase.rs
  examples/shader/gpu_readback.rs
  examples/shader/specialized_mesh_pipeline.rs
  examples/tools/gamepad_viewer.rs
  examples/tools/scene_viewer/animation_plugin.rs
  examples/tools/scene_viewer/morph_viewer_plugin.rs
  examples/ui/box_shadow.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Cross-Cutting

#19779 Improve module structure of observers code
  crates/bevy_ecs/src/observer/centralized_storage.rs
  crates/bevy_ecs/src/observer/distributed_storage.rs
  crates/bevy_ecs/src/observer/entity_cloning.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/observer/system_param.rs
  crates/bevy_ecs/src/observer/trigger_targets.rs
Labels: A-ECS, C-Code-Quality, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#19620 bevy_solari: RIS for Direct Lighting
  Cargo.toml
  crates/bevy_render/src/diagnostic/mod.rs
  crates/bevy_solari/Cargo.toml
  crates/bevy_solari/src/lib.rs
  crates/bevy_solari/src/realtime/extract.rs
  crates/bevy_solari/src/realtime/mod.rs
  crates/bevy_solari/src/realtime/node.rs
  crates/bevy_solari/src/realtime/prepare.rs
  crates/bevy_solari/src/realtime/reservoir.wgsl
  crates/bevy_solari/src/realtime/restir_di.wgsl
  crates/bevy_solari/src/scene/raytracing_scene_bindings.wgsl
  crates/bevy_solari/src/scene/sampling.wgsl
  examples/3d/solari.rs
  examples/README.md
  typos.toml
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, M-Needs-Release-Note

#19781 Rename num_entities to entity_count
  crates/bevy_app/src/app.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/observer/mod.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/command_queue.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_pbr/src/cluster/mod.rs
Labels: D-Trivial, A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#19196 Explanation for the 'classic' fog example
  examples/3d/fog.rs
Labels: A-Rendering, C-Examples, S-Ready-For-Final-Review, D-Straightforward

#19192 Update doc about Windows CursorGrabMode support
  crates/bevy_window/src/window.rs
Labels: C-Docs, A-Windowing, S-Ready-For-Final-Review

#19426 Replace `FULLSCREEN_SHADER_HANDLE` with a `FullscreenShader` resource.
  crates/bevy_anti_aliasing/src/contrast_adaptive_sharpening/mod.rs
  crates/bevy_anti_aliasing/src/fxaa/mod.rs
  crates/bevy_anti_aliasing/src/taa/mod.rs
  crates/bevy_core_pipeline/src/blit/mod.rs
  crates/bevy_core_pipeline/src/bloom/downsampling_pipeline.rs
  crates/bevy_core_pipeline/src/bloom/upsampling_pipeline.rs
  crates/bevy_core_pipeline/src/deferred/copy_lighting_id.rs
  crates/bevy_core_pipeline/src/dof/mod.rs
  crates/bevy_core_pipeline/src/fullscreen_vertex_shader/mod.rs
  crates/bevy_core_pipeline/src/lib.rs
  crates/bevy_core_pipeline/src/motion_blur/pipeline.rs
  crates/bevy_core_pipeline/src/oit/resolve/mod.rs
  crates/bevy_core_pipeline/src/post_process/mod.rs
  crates/bevy_core_pipeline/src/skybox/prepass.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_pbr/src/atmosphere/resources.rs
  crates/bevy_pbr/src/meshlet/pipelines.rs
  crates/bevy_pbr/src/ssr/mod.rs
  examples/shader/custom_post_processing.rs
  release-content/migration-guides/fullscreen_shader_resource.md
Labels: A-Rendering, A-Assets, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Modest

#19649 Split `EntityClonerBuilder` in `OptOut` and `OptIn` variants
  benches/benches/bevy_ecs/entity_cloning.rs
  crates/bevy_ecs/src/entity/clone_entities.rs
  crates/bevy_ecs/src/observer/entity_cloning.rs
  crates/bevy_ecs/src/system/commands/entity_command.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  release-content/migration-guides/entity_cloner_builder_split.md
Labels: C-Bug, C-Feature, A-ECS, C-Code-Quality, S-Ready-For-Final-Review

#19743 Implement serializable mesh
  crates/bevy_internal/Cargo.toml
  crates/bevy_mesh/Cargo.toml
  crates/bevy_mesh/src/index.rs
  crates/bevy_mesh/src/mesh.rs
  crates/bevy_mesh/src/vertex.rs
  crates/bevy_render/Cargo.toml
  crates/bevy_scene/Cargo.toml
  crates/bevy_ui/Cargo.toml
Labels: A-Rendering, A-Assets, S-Ready-For-Final-Review, A-Editor, X-Contentious, D-Straightforward

#19775 Add write_buffer_range to RawBufferVec and BufferVec
  crates/bevy_render/src/render_resource/buffer_vec.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#19789 Split overloaded basis-universal feature into compressed_image_saver
  Cargo.toml
  crates/bevy_image/Cargo.toml
  crates/bevy_image/src/lib.rs
  crates/bevy_internal/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/texture/mod.rs
  docs/cargo_features.md
Labels: A-Rendering, D-Straightforward, S-Needs-Review

#18458 `Projection` Improvements
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/projection.rs
  crates/bevy_render/src/view/visibility/mod.rs
Labels: A-Rendering, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#19794 remove unneeded dependency from bevy_render
  crates/bevy_render/Cargo.toml
Labels: D-Trivial, A-Rendering, S-Ready-For-Final-Review

#19462 Allow images to be resized on the GPU without losing data
  crates/bevy_core_pipeline/src/auto_exposure/compensation_curve.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_image/src/image.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/mesh/mod.rs
  crates/bevy_render/src/render_asset.rs
  crates/bevy_render/src/storage.rs
  crates/bevy_render/src/texture/gpu_image.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/mesh2d/wireframe2d.rs
  crates/bevy_sprite/src/tilemap_chunk/mod.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
Labels: C-Bug, C-Feature, A-Rendering, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#19795 TilemapChunk cleanup
  crates/bevy_sprite/src/tilemap_chunk/mod.rs
  crates/bevy_sprite/src/tilemap_chunk/tilemap_chunk_material.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#19806 CI tests can exit directly after taking a screenshot
  crates/bevy_dev_tools/src/ci_testing/config.rs
  crates/bevy_dev_tools/src/ci_testing/systems.rs
  tools/example-showcase/src/main.rs
Labels: A-Rendering, A-Build-System, S-Ready-For-Final-Review, C-Testing

#19825 Upgrade to Rust 1.88
  benches/benches/bevy_ecs/events/mod.rs
  benches/benches/bevy_ecs/iteration/mod.rs
  benches/benches/bevy_ecs/scheduling/run_condition.rs
  benches/benches/bevy_ecs/scheduling/running_systems.rs
  benches/benches/bevy_ecs/world/commands.rs
  benches/benches/bevy_ecs/world/despawn.rs
  benches/benches/bevy_ecs/world/despawn_recursive.rs
  benches/benches/bevy_ecs/world/spawn.rs
  benches/benches/bevy_ecs/world/world_get.rs
  benches/benches/bevy_reflect/map.rs
  benches/benches/bevy_reflect/struct.rs
  crates/bevy_app/src/task_pool_plugin.rs
  crates/bevy_asset/src/server/mod.rs
  crates/bevy_audio/src/volume.rs
  crates/bevy_dev_tools/src/ci_testing/systems.rs
  crates/bevy_diagnostic/src/log_diagnostics_plugin.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_gltf/src/loader/gltf_ext/mesh.rs
  crates/bevy_image/src/image.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_input_focus/src/tab_navigation.rs
  crates/bevy_log/src/lib.rs
  crates/bevy_math/src/curve/mod.rs
  crates/bevy_pbr/src/decal/forward.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
  crates/bevy_remote/src/builtin_methods.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_scene/src/serde.rs
  crates/bevy_state/src/app.rs
  crates/bevy_state/src/commands.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/2d/bloom_2d.rs
  examples/3d/anisotropy.rs
  examples/3d/lighting.rs
  examples/3d/occlusion_culling.rs
  examples/3d/ssao.rs
  examples/animation/animation_masks.rs
  examples/animation/easing_functions.rs
  examples/ecs/entity_disabling.rs
  examples/ecs/relationships.rs
  examples/remote/client.rs
  examples/scene/scene.rs
  examples/stress_tests/many_components.rs
  examples/tools/gamepad_viewer.rs
  examples/ui/box_shadow.rs
  examples/ui/directional_navigation.rs
  examples/ui/gradients.rs
  examples/ui/tab_navigation.rs
  examples/usage/context_menu.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, P-Critical, A-Cross-Cutting

#19807 Add UVec to_extents helper method
  crates/bevy_anti_aliasing/src/smaa/mod.rs
  crates/bevy_anti_aliasing/src/taa/mod.rs
  crates/bevy_core_pipeline/src/bloom/mod.rs
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_core_pipeline/src/core_3d/main_transmissive_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/deferred/copy_lighting_id.rs
  crates/bevy_core_pipeline/src/experimental/mip_generation/mod.rs
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_image/src/image.rs
  crates/bevy_pbr/src/atmosphere/resources.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_render/src/view/mod.rs
  crates/bevy_render/src/view/window/screenshot.rs
  crates/bevy_solari/Cargo.toml
  crates/bevy_solari/src/pathtracer/prepare.rs
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_sprite/src/tilemap_chunk/mod.rs
  crates/bevy_text/src/font_atlas.rs
  crates/bevy_ui/src/widget/viewport.rs
  examples/stress_tests/many_cubes.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review

#19793 add native zstd support
  Cargo.toml
  crates/bevy_image/Cargo.toml
  crates/bevy_image/src/ktx2.rs
  crates/bevy_image/src/lib.rs
  crates/bevy_internal/Cargo.toml
  docs/cargo_features.md
  release-content/migration-guides/zstd.md
Labels: A-Rendering, S-Ready-For-Final-Review, D-Straightforward

#19827 updating: very very minorly
  crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review

#19829 use wgpu TextureDataOrder
  crates/bevy_core_pipeline/src/tonemapping/mod.rs
  crates/bevy_image/src/image.rs
  crates/bevy_image/src/ktx2.rs
  crates/bevy_render/src/texture/gpu_image.rs
  crates/bevy_sprite/src/tilemap_chunk/mod.rs
Labels: A-Rendering, S-Ready-For-Final-Review, D-Straightforward

#19817 Resolution override
  crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transmissive_pass_3d_node.rs
  crates/bevy_core_pipeline/src/core_3d/main_transparent_pass_3d_node.rs
  crates/bevy_core_pipeline/src/deferred/node.rs
  crates/bevy_core_pipeline/src/oit/resolve/node.rs
  crates/bevy_core_pipeline/src/prepass/node.rs
  crates/bevy_pbr/src/meshlet/material_shade_nodes.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/camera/mod.rs
  examples/shader/custom_render_phase.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#19826 Opt-out for UI clipping
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/update.rs
Labels: C-Feature, A-Rendering, A-UI, S-Ready-For-Final-Review, D-Straightforward

#19846 Use SmallVec instead of HashMap in MaterialProperties
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
Labels: A-Rendering, C-Performance, S-Needs-Benchmarking, S-Needs-Review

#19811 Doc for X11 CursorGrabMode support
  crates/bevy_window/src/window.rs
Labels: D-Trivial, A-Input, O-Linux, S-Ready-For-Final-Review

#19318 Meshlet BVH Culling
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/meshlet/asset.rs
  crates/bevy_pbr/src/meshlet/cull_bvh.wgsl
  crates/bevy_pbr/src/meshlet/cull_clusters.wgsl
  crates/bevy_pbr/src/meshlet/cull_instances.wgsl
  crates/bevy_pbr/src/meshlet/fill_cluster_buffers.wgsl
  crates/bevy_pbr/src/meshlet/fill_counts.wgsl
  crates/bevy_pbr/src/meshlet/from_mesh.rs
  crates/bevy_pbr/src/meshlet/instance_manager.rs
  crates/bevy_pbr/src/meshlet/material_pipeline_prepare.rs
  crates/bevy_pbr/src/meshlet/material_shade_nodes.rs
  crates/bevy_pbr/src/meshlet/meshlet_bindings.wgsl
  crates/bevy_pbr/src/meshlet/meshlet_cull_shared.wgsl
  crates/bevy_pbr/src/meshlet/meshlet_mesh_manager.rs
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/meshlet/persistent_buffer.rs
  crates/bevy_pbr/src/meshlet/persistent_buffer_impls.rs
  crates/bevy_pbr/src/meshlet/pipelines.rs
  crates/bevy_pbr/src/meshlet/remap_1d_to_2d_dispatch.wgsl
  crates/bevy_pbr/src/meshlet/resolve_render_targets.wgsl
  crates/bevy_pbr/src/meshlet/resource_manager.rs
  crates/bevy_pbr/src/meshlet/visibility_buffer_hardware_raster.wgsl
  crates/bevy_pbr/src/meshlet/visibility_buffer_raster_node.rs
  crates/bevy_pbr/src/meshlet/visibility_buffer_resolve.wgsl
  crates/bevy_pbr/src/meshlet/visibility_buffer_software_raster.wgsl
  examples/3d/meshlet.rs
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, D-Shaders

#19718 Don't create errors for ignored failed commands
  crates/bevy_ecs/src/error/command_handling.rs
  crates/bevy_ecs/src/relationship/mod.rs
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: A-ECS, C-Performance, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#19858 bevy_ui compilation
  crates/bevy_ui/src/focus.rs
  crates/bevy_ui/src/picking_backend.rs
  crates/bevy_ui/src/widget/viewport.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#19859 bevy_ecs: remove use of needless_return
  crates/bevy_ecs/src/storage/resource.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#19860 bevy_platform: clippy without default features
  crates/bevy_platform/src/thread.rs
  crates/bevy_platform/src/time/fallback.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#19861 bevy_utils: clippy without debug feature enabled
  crates/bevy_utils/src/debug_info.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#19862 bevy_input: build warnings without bevy_reflect
  crates/bevy_input/src/lib.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#19579 Move `TextShadow` to `text` widget module
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_ui/src/widget/text.rs
  release-content/migration-guides/textshadow_is_moved_to_widget_text_module.md
Labels: D-Trivial, A-UI, C-Code-Quality, S-Ready-For-Final-Review, A-Text

#19849 Dds transcode channel order fix
  crates/bevy_image/src/dds.rs
  crates/bevy_image/src/image.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#19790 bevy_solari ReSTIR DI
  crates/bevy_core_pipeline/src/core_3d/mod.rs
  crates/bevy_core_pipeline/src/skybox/skybox_prepass.wgsl
  crates/bevy_solari/src/realtime/node.rs
  crates/bevy_solari/src/realtime/prepare.rs
  crates/bevy_solari/src/realtime/reservoir.wgsl
  crates/bevy_solari/src/realtime/restir_di.wgsl
  crates/bevy_solari/src/scene/binder.rs
  crates/bevy_solari/src/scene/raytracing_scene_bindings.wgsl
  crates/bevy_solari/src/scene/sampling.wgsl
  release-content/release-notes/bevy_solari.md
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, M-Needs-Release-Note

#19865 bevy_asset: fix clippy in wasm
  crates/bevy_asset/src/io/wasm.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#19869 bevy_winit: fix compile and clippy on wasm
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#19845 optimize ktx2 level data concatenation
  crates/bevy_image/src/ktx2.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, D-Straightforward

#19872 bevy_render: fix clippy on wasm
  crates/bevy_render/src/batching/gpu_preprocessing.rs
  crates/bevy_render/src/render_resource/pipeline_cache.rs
Labels: C-Code-Quality

#19799 Update ui_test requirement from 0.29.1 to 0.30.1
  tools/compile_fail_utils/Cargo.toml
  tools/compile_fail_utils/src/lib.rs
Labels: C-Dependencies, S-Ready-For-Final-Review, D-Straightforward

#19870 bevy_window: fix compilation without default features
  crates/bevy_window/src/window.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review

#19615 Prevent `AnimationGraph` from serializing `AssetId`s.
  assets/animation_graphs/Fox.animgraph.ron
  crates/bevy_animation/src/graph.rs
  examples/animation/animation_graph.rs
  release-content/migration-guides/animation_graph_no_more_asset_ids.md
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review, A-Animation, M-Needs-Migration-Guide, D-Modest

#19634 Restructure the logic in `AssetServer::load_internal` to avoid using weak handles.
  crates/bevy_asset/src/server/mod.rs
Labels: A-Assets, C-Code-Quality, S-Ready-For-Final-Review, D-Modest

#18293 Update log_layers_ecs example for children macro
  examples/app/log_layers_ecs.rs
Labels: A-ECS, C-Examples, A-UI, S-Ready-For-Final-Review, D-Straightforward

#19803 CoreScrollbar widget.
  Cargo.toml
  crates/bevy_core_widgets/src/core_scrollbar.rs
  crates/bevy_core_widgets/src/lib.rs
  examples/README.md
  examples/ui/scrollbars.rs
  release-content/release-notes/headless-widgets.md
Labels: C-Feature, A-UI, S-Ready-For-Final-Review, M-Needs-Release-Note

#19840 Split LatePrepassNode query in a few groups
  crates/bevy_core_pipeline/src/prepass/node.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review

#19874 Update bevy website link in newer code
  crates/bevy_core_widgets/Cargo.toml
  crates/bevy_feathers/Cargo.toml
  crates/bevy_solari/Cargo.toml
  examples/3d/fog.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#19875 bevy_reflect: avoid useless `with_{custom_attributes,docs}` calls
  crates/bevy_reflect/derive/src/custom_attributes.rs
  crates/bevy_reflect/derive/src/derive_data.rs
  crates/bevy_reflect/derive/src/documentation.rs
Labels: C-Performance, S-Ready-For-Final-Review, A-Reflection, D-Macros

#19876 bevy_reflect: avoid duplicate type bounds in derived methods
  crates/bevy_reflect/derive/Cargo.toml
  crates/bevy_reflect/derive/src/derive_data.rs
Labels: C-Performance, S-Ready-For-Final-Review, A-Reflection, D-Macros
