Repository bevyengine/bevy, pull requests merged in 2025-03, with the labels that each got.

#18071 Update `EntityCommands::trigger` to check for the entity's existence
  crates/bevy_ecs/src/system/commands/entity_command.rs
  crates/bevy_ecs/src/system/commands/mod.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#18056 chore: update compile fail test stderr files
  crates/bevy_ecs/compile_fail/tests/ui/query_exact_sized_iterator_safety.stderr
  crates/bevy_ecs/compile_fail/tests/ui/query_iter_combinations_mut_iterator_safety.stderr
  crates/bevy_ecs/compile_fail/tests/ui/query_iter_many_mut_iterator_safety.stderr
  crates/bevy_ecs/compile_fail/tests/ui/query_lens_lifetime_safety.stderr
  crates/bevy_ecs/compile_fail/tests/ui/query_to_readonly.stderr
  crates/bevy_ecs/compile_fail/tests/ui/system_param_derive_readonly.stderr
  crates/bevy_ecs/compile_fail/tests/ui/system_query_iter_sort_lifetime_safety.stderr
  crates/bevy_ecs/compile_fail/tests/ui/world_query_derive.stderr
Labels: C-Bug, S-Ready-For-Final-Review, C-Testing, A-Cross-Cutting

#18110 Add missing bindless imports in `pbr_prepass.wgsl`.
  crates/bevy_pbr/src/render/pbr_prepass.wgsl
Labels: C-Bug, D-Trivial, A-Rendering, P-Regression, S-Needs-Review

#18105 Fix invisible window creation on Windows
  crates/bevy_winit/src/state.rs
Labels: C-Bug, A-Windowing, S-Ready-For-Final-Review

#18023 Make asset watcher work when path contains "../"
  crates/bevy_asset/src/io/file/file_watcher.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review, X-Contentious, D-Straightforward

#18097 Bump `typos` to 1.30.0
  .github/workflows/ci.yml
  crates/bevy_image/src/dynamic_texture_atlas_builder.rs
  crates/bevy_image/src/texture_atlas_builder.rs
  examples/ecs/fallible_systems.rs
Labels: D-Trivial, A-Build-System, C-Code-Quality, S-Ready-For-Final-Review

#18114 Fix incorrect doc about `GamepadAxis::RightZ`/`LeftZ`
  crates/bevy_input/src/gamepad.rs
Labels: C-Docs, A-Input, S-Ready-For-Final-Review, D-Straightforward

#18082 Make Query::single (and friends) return a Result
  crates/bevy_core_pipeline/src/oit/mod.rs
  crates/bevy_dev_tools/src/picking_debug.rs
  crates/bevy_ecs/compile_fail/tests/ui/query_lifetime_safety.rs
  crates/bevy_ecs/compile_fail/tests/ui/query_lifetime_safety.stderr
  crates/bevy_ecs/compile_fail/tests/ui/query_to_readonly.rs
  crates/bevy_ecs/compile_fail/tests/ui/query_transmute_safety.rs
  crates/bevy_ecs/src/change_detection.rs
  crates/bevy_ecs/src/query/builder.rs
  crates/bevy_ecs/src/query/error.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_input_focus/src/lib.rs
  crates/bevy_pbr/src/light_probe/irradiance_volume.rs
  crates/bevy_picking/src/input.rs
  crates/bevy_picking/src/pointer.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/sync_world.rs
  crates/bevy_scene/src/scene_spawner.rs
  crates/bevy_scene/src/serde.rs
  crates/bevy_sprite/src/picking_backend.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_ui/src/accessibility.rs
  crates/bevy_ui/src/layout/mod.rs
  crates/bevy_ui/src/picking_backend.rs
  crates/bevy_ui/src/ui_node.rs
  crates/bevy_winit/src/accessibility.rs
  crates/bevy_winit/src/state.rs
  examples/2d/2d_viewport_to_world.rs
  examples/3d/3d_viewport_to_world.rs
  examples/3d/generate_custom_mesh.rs
  examples/3d/tonemapping.rs
  examples/asset/multi_asset_sync.rs
  examples/audio/audio_control.rs
  examples/camera/2d_screen_shake.rs
  examples/ecs/entity_disabling.rs
  examples/ecs/observers.rs
  examples/ecs/parallel_query.rs
  examples/games/contributors.rs
  examples/helpers/camera_controller.rs
  examples/mobile/src/lib.rs
  examples/stress_tests/bevymark.rs
  examples/stress_tests/many_cameras_lights.rs
  examples/stress_tests/many_text2d.rs
  examples/tools/scene_viewer/morph_viewer_plugin.rs
  examples/window/window_drag_move.rs
  tests/how_to_test_apps.rs
  tests/window/change_window_mode.rs
Labels: A-ECS, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Blessed, D-Straightforward

#18118 Fix label name for Deliberate-Rendering-Change CI
  .github/workflows/example-run-report.yml
Labels: C-Bug, D-Trivial, A-Build-System, S-Ready-For-Final-Review, X-Contentious

#18115 Fix `webgl2` feature gating affecting webgpu in `transmission` example
  examples/3d/transmission.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, O-WebGL2

#18119 Fix panic with multiple fog volumes
  crates/bevy_pbr/src/volumetric_fog/render.rs
Labels: C-Bug, A-Rendering, P-Crash, S-Ready-For-Final-Review, D-Straightforward

#18127 fix test for .iter().sort() to include data to sort
  crates/bevy_ecs/src/query/iter.rs
Labels: D-Trivial, S-Ready-For-Final-Review, C-Testing

#18123 Reextract meshes when their material assets change.
  crates/bevy_pbr/src/material.rs
Labels: C-Bug, D-Trivial, A-Rendering, S-Ready-For-Final-Review, P-Regression

#18136 fix generics for relationships
  crates/bevy_ecs/macros/src/component.rs
Labels: C-Bug, D-Trivial, A-ECS, S-Ready-For-Final-Review

#18145 Update ruzstd requirement from 0.7.0 to 0.8.0
  crates/bevy_image/Cargo.toml
  crates/bevy_image/src/ktx2.rs
Labels: D-Trivial, C-Dependencies, S-Needs-Review

#18146 Update ureq requirement from 2.10.1 to 3.0.8
  Cargo.toml
  examples/remote/client.rs
Labels: C-Examples, C-Dependencies, S-Ready-For-Final-Review, A-Dev-Tools

#16694 Cache systems by `S` instead of `S::System`
  crates/bevy_ecs/src/system/system_registry.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#17482 Replace Ambient Lights with Environment Map Lights
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/light/ambient_light.rs
  crates/bevy_pbr/src/light/mod.rs
  crates/bevy_pbr/src/light_probe/environment_map.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/render/mesh_view_types.wgsl
  crates/bevy_pbr/src/render/pbr_ambient.wgsl
  crates/bevy_pbr/src/render/pbr_functions.wgsl
  examples/2d/custom_gltf_vertex_attribute.rs
  examples/3d/auto_exposure.rs
  examples/3d/fog.rs
  examples/3d/fog_volumes.rs
  examples/3d/irradiance_volumes.rs
  examples/3d/lighting.rs
  examples/3d/lightmaps.rs
  examples/3d/mixed_lighting.rs
  examples/3d/motion_blur.rs
  examples/3d/skybox.rs
  examples/3d/specular_tint.rs
  examples/3d/spherical_area_lights.rs
  examples/3d/spotlight.rs
  examples/3d/ssao.rs
  examples/3d/transmission.rs
  examples/3d/volumetric_fog.rs
  examples/animation/animated_mesh.rs
  examples/animation/animated_mesh_control.rs
  examples/animation/animated_mesh_events.rs
  examples/animation/animated_transform.rs
  examples/animation/animation_graph.rs
  examples/animation/animation_masks.rs
  examples/animation/custom_skinned_mesh.rs
  examples/animation/gltf_skinned_mesh.rs
  examples/animation/morph_targets.rs
  examples/asset/multi_asset_sync.rs
  examples/math/render_primitives.rs
Labels: A-Rendering, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, M-Needs-Release-Note, D-Straightforward, D-Shaders

#17730 Replace some `!Send` resources with `thread_local!`
  crates/bevy_gilrs/src/gilrs_system.rs
  crates/bevy_gilrs/src/lib.rs
  crates/bevy_gilrs/src/rumble.rs
  crates/bevy_winit/src/lib.rs
  crates/bevy_winit/src/state.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review

#18087 One-to-One Relationships
  crates/bevy_ecs/src/relationship/relationship_source_collection.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#18140 Relationship(…Target) html trait tag
  docs-rs/trait-tags.html
Labels: C-Docs, C-Feature, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#18141 `BorderRadius` comment fix
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, A-UI, S-Ready-For-Final-Review

#16348 Remove deprecated `component_reads_and_writes`
  crates/bevy_ecs/src/query/access.rs
  crates/bevy_ecs/src/query/builder.rs
  crates/bevy_ecs/src/query/state.rs
  examples/ecs/dynamic.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, X-Contentious, D-Modest

#18091 testbed for UI
  .github/example-run/testbed_ui.ron
  Cargo.toml
  examples/testbed/full_ui.rs
  examples/testbed/ui.rs
  examples/testbed/ui_layout_rounding.rs
Labels: A-Build-System, A-UI, S-Ready-For-Final-Review, C-Testing, M-Deliberate-Rendering-Change

#17996 Emphasize no structural changes in SystemParam::get_param
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/unsafe_world_cell.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review, P-Unsound, D-Unsafe

#17973 Fix unsound query transmutes on queries obtained from `Query::as_readonly()`
  crates/bevy_ecs/macros/src/query_data.rs
  crates/bevy_ecs/src/query/fetch.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
  crates/bevy_render/src/sync_world.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, P-Unsound

#18165 Fix Component require() IDE integration
  crates/bevy_core_pipeline/src/motion_blur/mod.rs
  crates/bevy_core_pipeline/src/taa/mod.rs
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/clone_entities.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/system_registry.rs
  crates/bevy_gizmos/src/retained.rs
  crates/bevy_input/src/gamepad.rs
  crates/bevy_pbr/src/atmosphere/mod.rs
  crates/bevy_pbr/src/decal/clustered.rs
  crates/bevy_pbr/src/decal/forward.rs
  crates/bevy_pbr/src/light_probe/mod.rs
  crates/bevy_pbr/src/meshlet/mod.rs
  crates/bevy_pbr/src/ssao/mod.rs
  crates/bevy_pbr/src/ssr/mod.rs
  crates/bevy_pbr/src/volumetric_fog/mod.rs
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_render/src/mesh/components.rs
  crates/bevy_scene/src/components.rs
  crates/bevy_sprite/src/sprite.rs
  crates/bevy_text/src/text2d.rs
  crates/bevy_transform/src/components/transform.rs
  crates/bevy_ui/src/ui_material.rs
  crates/bevy_ui/src/widget/button.rs
  crates/bevy_ui/src/widget/text.rs
Labels: C-Bug, A-ECS, C-Usability, S-Needs-Review

#18035 Replace internal uses of `insert_or_spawn_batch`
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_pbr/src/wireframe.rs
  crates/bevy_render/src/extract_component.rs
  crates/bevy_render/src/gpu_component_array_buffer.rs
  crates/bevy_sprite/src/mesh2d/wireframe2d.rs
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
  examples/2d/mesh2d_manual.rs
Labels: A-Rendering, A-ECS, C-Performance, C-Code-Quality, S-Ready-For-Final-Review

#18017 allow `Call` and `Closure` expressions in hook macro attributes
  crates/bevy_derive/compile_fail/tests/deref_mut_derive/missing_deref_fail.stderr
  crates/bevy_ecs/compile_fail/tests/ui/component_hook_call_signature_mismatch.rs
  crates/bevy_ecs/compile_fail/tests/ui/component_hook_call_signature_mismatch.stderr
  crates/bevy_ecs/compile_fail/tests/ui/component_hook_relationship.rs
  crates/bevy_ecs/compile_fail/tests/ui/component_hook_relationship.stderr
  crates/bevy_ecs/compile_fail/tests/ui/component_hook_struct_path.rs
  crates/bevy_ecs/compile_fail/tests/ui/component_hook_struct_path.stderr
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/src/component.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Release-Note, X-Uncontroversial

#10462 Helper function for getting inverse model matrix in WGSL shaders
  crates/bevy_pbr/src/render/mesh_functions.wgsl
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#18147 Deprecate `insert_or_spawn` function family
  benches/benches/bevy_ecs/world/commands.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Performance, C-Usability, S-Ready-For-Final-Review

#17216 Stop automatically generating meta files for assets while using asset processing.
  crates/bevy_asset/src/processor/mod.rs
  crates/bevy_asset/src/server/mod.rs
  examples/asset/processing/assets/d.cool.ron.meta
  examples/asset/processing/assets/foo/b.cool.ron.meta
  examples/asset/processing/assets/foo/c.cool.ron.meta
Labels: A-Assets, C-Usability, M-Needs-Release-Note, D-Straightforward, S-Needs-Review

#18153 rendering regression: mention in pr comment that the solution could be to update the pr
  .github/workflows/example-run-report.yml
Labels: D-Trivial, A-Build-System, S-Ready-For-Final-Review

#18144 BevyError: Bevy's new catch-all error type
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/panic_handler.rs
  crates/bevy_app/src/sub_app.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/error/bevy_error.rs
  crates/bevy_ecs/src/error/handler.rs
  crates/bevy_ecs/src/error/mod.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/schedule/config.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/commands/command.rs
  crates/bevy_ecs/src/system/commands/entity_command.rs
  crates/bevy_ecs/src/system/commands/error_handler.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/system/observer_system.rs
  crates/bevy_ecs/src/system/schedule_system.rs
  crates/bevy_ecs/src/system/system_registry.rs
  examples/ecs/fallible_systems.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Modest

#18178 Add `TextureAtlasSources::uv_rect` to get `Rect` in UV coords
  crates/bevy_image/src/texture_atlas.rs
Labels: A-Rendering, C-Usability, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#18083 Improve derive(Event) and simplify macro code
  crates/bevy_ecs/macros/Cargo.toml
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/event/base.rs
  crates/bevy_ecs/src/observer/mod.rs
  examples/ecs/observer_propagation.rs
Labels: A-ECS, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, D-Macros

#18183 Deprecated Query::many and many_mut
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/system/query.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Contentious

#17955 Add `no_std` support to `bevy`
  .github/workflows/ci.yml
  Cargo.toml
  crates/bevy_animation/Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/lib.rs
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_audio/Cargo.toml
  crates/bevy_diagnostic/Cargo.toml
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/entity/unique_array.rs
  crates/bevy_ecs/src/entity/unique_slice.rs
  crates/bevy_ecs/src/entity/unique_vec.rs
  crates/bevy_gltf/Cargo.toml
  crates/bevy_image/Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_internal/src/default_plugins.rs
  crates/bevy_internal/src/lib.rs
  crates/bevy_internal/src/prelude.rs
  crates/bevy_mesh/Cargo.toml
  crates/bevy_pbr/Cargo.toml
  crates/bevy_platform_support/README.md
  crates/bevy_reflect/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_scene/Cargo.toml
  crates/bevy_sprite/Cargo.toml
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/README.md
  crates/bevy_tasks/src/edge_executor.rs
  crates/bevy_tasks/src/executor.rs
  crates/bevy_tasks/src/lib.rs
  crates/bevy_tasks/src/single_threaded_task_pool.rs
  crates/bevy_text/Cargo.toml
  crates/bevy_time/Cargo.toml
  crates/bevy_transform/Cargo.toml
  crates/bevy_ui/Cargo.toml
  docs/cargo_features.md
  src/lib.rs
  tools/ci/src/ci.rs
  tools/ci/src/commands/compile_check_no_std.rs
  tools/ci/src/commands/mod.rs
Labels: C-Feature, S-Ready-For-Final-Review, M-Needs-Migration-Guide, M-Needs-Release-Note, A-Cross-Cutting, X-Blessed, D-Modest, O-Embedded

#17992 Fix mesh tangent attribute matching in mesh transform operations
  crates/bevy_mesh/src/mesh.rs
Labels: C-Bug, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward, A-glTF

#17499 Support for non-browser `wasm`
  Cargo.toml
  crates/bevy_animation/Cargo.toml
  crates/bevy_app/Cargo.toml
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/panic_handler.rs
  crates/bevy_app/src/schedule_runner.rs
  crates/bevy_app/src/task_pool_plugin.rs
  crates/bevy_asset/Cargo.toml
  crates/bevy_audio/Cargo.toml
  crates/bevy_internal/Cargo.toml
  crates/bevy_log/Cargo.toml
  crates/bevy_picking/Cargo.toml
  crates/bevy_platform_support/Cargo.toml
  crates/bevy_platform_support/src/time.rs
  crates/bevy_platform_support/src/time/fallback.rs
  crates/bevy_platform_support/src/time/mod.rs
  crates/bevy_reflect/Cargo.toml
  crates/bevy_reflect/derive/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_scene/Cargo.toml
  crates/bevy_tasks/Cargo.toml
  crates/bevy_tasks/examples/busy_behavior.rs
  crates/bevy_tasks/examples/idle_behavior.rs
  crates/bevy_tasks/src/executor.rs
  crates/bevy_tasks/src/lib.rs
  crates/bevy_tasks/src/single_threaded_task_pool.rs
  crates/bevy_tasks/src/usages.rs
  crates/bevy_winit/Cargo.toml
  docs/cargo_features.md
Labels: C-Feature, O-Web, S-Ready-For-Final-Review, A-Cross-Cutting, X-Contentious, D-Modest, O-Embedded

#18179 Update Component docs to point to Relationship trait
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/relationship/mod.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#17900 Add byte information to `PositionedGlyph`
  crates/bevy_text/src/glyph.rs
  crates/bevy_text/src/pipeline.rs
Labels: C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, A-Text, X-Uncontroversial

#18201 Ensure `bevy_utils` is included with `std` feature
  crates/bevy_internal/Cargo.toml
  crates/bevy_transform/Cargo.toml
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, A-Transform, P-Compile-Failure, X-Uncontroversial

#17953 Add support for experimental WESL shader source
  Cargo.toml
  assets/shaders/custom_material.wesl
  assets/shaders/util.wesl
  crates/bevy_internal/Cargo.toml
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/render_resource/pipeline_cache.rs
  crates/bevy_render/src/render_resource/shader.rs
  docs/cargo_features.md
  examples/README.md
  examples/shader/shader_material_wesl.rs
Labels: C-Feature, A-Rendering, S-Ready-For-Final-Review, O-WebGPU, M-Needs-Release-Note

#18093 Transform Propagation Optimization: Static Subtree Marking
  crates/bevy_transform/src/components/transform.rs
  crates/bevy_transform/src/plugins.rs
  crates/bevy_transform/src/systems.rs
  crates/bevy_ui/src/layout/mod.rs
Labels: C-Performance, S-Ready-For-Final-Review, A-Transform, M-Needs-Release-Note

#18157 Remove lifetime from `QueryEntityError`
  crates/bevy_ecs/src/query/error.rs
  crates/bevy_ecs/src/query/state.rs
  crates/bevy_ecs/src/system/query.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Blessed

#18113 Partially fix panics when setting `WGPU_SETTINGS_PRIO=webgl2`
  crates/bevy_core_pipeline/src/experimental/mip_generation/mod.rs
  crates/bevy_core_pipeline/src/oit/resolve/mod.rs
  crates/bevy_pbr/src/render/mesh_view_bindings.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, O-WebGL2

#18209 Ignore unmaintained security advisory about paste for now
  deny.toml
Labels: D-Trivial, A-Build-System, X-Contentious, S-Needs-Review

#18206 Improve `Segment2d`/`Segment3d` API and docs
  crates/bevy_gizmos/src/primitives/dim2.rs
  crates/bevy_gizmos/src/primitives/dim3.rs
  crates/bevy_math/src/bounding/bounded2d/primitive_impls.rs
  crates/bevy_math/src/bounding/bounded3d/extrusion.rs
  crates/bevy_math/src/bounding/bounded3d/primitive_impls.rs
  crates/bevy_math/src/primitives/dim2.rs
  crates/bevy_math/src/primitives/dim3.rs
Labels: C-Docs, C-Usability, S-Ready-For-Final-Review, A-Math, X-Uncontroversial, D-Straightforward

#18196 action shouldn't comment on a pr if last comment is from action
  .github/workflows/ci-comment-failures.yml
  .github/workflows/example-run-report.yml
Labels: A-Build-System, S-Ready-For-Final-Review, D-Straightforward

#18099 Decoupled naga for wgpu testing
  crates/bevy_render/Cargo.toml
  crates/bevy_render/src/render_resource/pipeline_cache.rs
Labels: A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, C-Testing

#18216 `UiTargetCamera` doc comment correction
  crates/bevy_ui/src/ui_node.rs
Labels: C-Docs, D-Trivial, A-Rendering, A-UI, S-Ready-For-Final-Review

#18217 Fix CI comment workflow after 18196
  .github/workflows/ci-comment-failures.yml
Labels: A-Build-System, S-Ready-For-Final-Review

#17914 Parallelize prepare_assets::<T> systems
  crates/bevy_pbr/src/volumetric_fog/render.rs
  crates/bevy_render/src/lib.rs
  crates/bevy_render/src/render_asset.rs
Labels: A-Rendering, C-Performance, D-Modest, S-Needs-Review

#14379 Replace winit's synthetic events by our own key tracking
  crates/bevy_winit/src/state.rs
  crates/bevy_winit/src/system.rs
Labels: C-Bug, A-Input, A-Windowing, S-Ready-For-Final-Review, D-Straightforward

#17581 don't use bevy_pbr for base bevy_gizmos plugin
  crates/bevy_gizmos/Cargo.toml
  crates/bevy_gizmos/src/config.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_gizmos/src/retained.rs
  crates/bevy_gizmos/src/view.rs
  crates/bevy_internal/Cargo.toml
Labels: A-Rendering, C-Code-Quality, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#18235 Backtrace: std and threadsafe bevy_error_panic_hook
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/error/bevy_error.rs
Labels: C-Bug, S-Ready-For-Final-Review, O-Embedded

#17633 Respect viewport position in coordinate conversion functions
  Cargo.toml
  crates/bevy_render/src/camera/camera.rs
  examples/2d/2d_viewport_to_world.rs
  examples/README.md
Labels: C-Bug, S-Ready-For-Final-Review, A-Math, D-Straightforward

#17930 `extract_text_shadows` camera query fix
  crates/bevy_ui/src/render/mod.rs
  examples/window/multiple_windows.rs
Labels: C-Bug, A-Rendering, A-UI, S-Ready-For-Final-Review, A-Text, D-Straightforward

#17935 `many-cameras` option for `many_buttons`
  examples/stress_tests/many_buttons.rs
Labels: A-UI, S-Ready-For-Final-Review, C-Benchmarks, D-Straightforward

#17972 Fix unsound lifetimes in `Query::join` and `Query::join_filtered`
  crates/bevy_ecs/compile_fail/tests/ui/query_lens_lifetime_safety.rs
  crates/bevy_ecs/compile_fail/tests/ui/query_lens_lifetime_safety.stderr
  crates/bevy_ecs/src/system/query.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, P-Unsound

#17994 Reimplement bindless storage buffers.
  assets/shaders/bindless_material.wgsl
  crates/bevy_pbr/src/material_bind_groups.rs
  crates/bevy_render/macros/src/as_bind_group.rs
  crates/bevy_render/src/render_resource/bind_group.rs
  crates/bevy_render/src/render_resource/bindless.rs
Labels: A-Rendering, S-Ready-For-Final-Review, P-Regression

#18028 Use register_dynamic for merging
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/lib.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Straightforward

#18076 Recursive run_system
  crates/bevy_ecs/src/system/exclusive_function_system.rs
  crates/bevy_ecs/src/system/system.rs
  crates/bevy_ecs/src/system/system_registry.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review

#18125 Make buffer binding arrays emit bind group layout entries and bindless resource descriptors again.
  crates/bevy_render/macros/src/as_bind_group.rs
Labels: C-Bug, A-Rendering, P-Crash, S-Ready-For-Final-Review, P-Regression, D-Modest

#18173 Queued component registration
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/spawn.rs
  crates/bevy_ecs/src/storage/table/mod.rs
  crates/bevy_ecs/src/system/system_param.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/filtered_resource.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#18180 Improve component registration performance
  crates/bevy_ecs/src/component.rs
Labels: A-ECS, C-Performance, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward

#18190 Address `Entities::len` inconsistency
  crates/bevy_ecs/src/entity/mod.rs
Labels: C-Docs, A-ECS, C-Code-Quality, S-Ready-For-Final-Review, D-Straightforward

#18202 Add Saturation trait to bevy_color
  crates/bevy_color/src/color.rs
  crates/bevy_color/src/color_ops.rs
  crates/bevy_color/src/hsla.rs
  crates/bevy_color/src/hsva.rs
Labels: C-Feature, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward, A-Color

#18218 Fix mikkitspace typos
  crates/bevy_mikktspace/README.md
  crates/bevy_mikktspace/src/generated.rs
Labels: C-Docs, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#18232 (Adoped) Remove panics and optimise mesh picking
  crates/bevy_picking/src/mesh_picking/ray_cast/intersections.rs
Labels: C-Usability, S-Ready-For-Final-Review, D-Straightforward, A-Picking

#18237 docs: Fix incorrect cycle_modes function documentation
  examples/window/low_power.rs
Labels: D-Trivial, C-Examples, A-Windowing, S-Ready-For-Final-Review

#18241 Expand the `RelationshipSourceCollection` to return more information
  crates/bevy_ecs/src/relationship/relationship_source_collection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#18240 Add more to the 2d testbed for text
  examples/testbed/2d.rs
Labels: A-Rendering, S-Ready-For-Final-Review, C-Testing, A-Text, D-Straightforward, M-Deliberate-Rendering-Change

#17525 Rework WindowMode::Fullscreen API
  crates/bevy_render/src/camera/camera.rs
  crates/bevy_window/src/lib.rs
  crates/bevy_window/src/monitor.rs
  crates/bevy_window/src/window.rs
  crates/bevy_winit/src/system.rs
  crates/bevy_winit/src/winit_windows.rs
  examples/window/monitor_info.rs
  tests/window/change_window_mode.rs
Labels: A-Windowing, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, D-Modest

#18250 Update state/states example to use children! macro
  examples/state/states.rs
Labels: D-Trivial, A-ECS, C-Examples, S-Ready-For-Final-Review

#18248 make various entity wrapper type modules public
  crates/bevy_ecs/src/entity/entity_set.rs
  crates/bevy_ecs/src/entity/index_map.rs
  crates/bevy_ecs/src/entity/index_set.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/entity/unique_array.rs
  crates/bevy_ecs/src/entity/unique_slice.rs
  crates/bevy_ecs/src/entity/unique_vec.rs
  crates/bevy_ecs/src/query/par_iter.rs
  crates/bevy_ecs/src/query/state.rs
Labels: D-Trivial, A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide

#13432 bevy_reflect: Reflection-based cloning
  crates/bevy_reflect/compile_fail/tests/reflect_remote/nested_fail.rs
  crates/bevy_reflect/derive/src/container_attributes.rs
  crates/bevy_reflect/derive/src/derive_data.rs
  crates/bevy_reflect/derive/src/enum_utility.rs
  crates/bevy_reflect/derive/src/field_attributes.rs
  crates/bevy_reflect/derive/src/impls/enums.rs
  crates/bevy_reflect/derive/src/impls/opaque.rs
  crates/bevy_reflect/derive/src/impls/structs.rs
  crates/bevy_reflect/derive/src/impls/tuple_structs.rs
  crates/bevy_reflect/derive/src/lib.rs
  crates/bevy_reflect/derive/src/struct_utility.rs
  crates/bevy_reflect/src/error.rs
  crates/bevy_reflect/src/fields.rs
  crates/bevy_reflect/src/impls/glam.rs
  crates/bevy_reflect/src/impls/petgraph.rs
  crates/bevy_reflect/src/impls/smallvec.rs
  crates/bevy_reflect/src/impls/smol_str.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/impls/uuid.rs
  crates/bevy_reflect/src/impls/wgpu_types.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/reflect.rs
  crates/bevy_reflect/src/tuple.rs
Labels: C-Feature, S-Ready-For-Final-Review, A-Reflection, D-Modest

#18219 Fix non-crate typos
  Cargo.toml
  assets/shaders/specialized_mesh_pipeline.wgsl
  assets/shaders/tonemapping_test_patterns.wgsl
  benches/benches/bevy_ecs/scheduling/schedule.rs
  examples/README.md
  examples/games/alien_cake_addict.rs
  examples/games/stepping.rs
  examples/math/custom_primitives.rs
  examples/ui/scroll.rs
  examples/ui/text_debug.rs
  examples/ui/viewport_debug.rs
  examples/ui/window_fallthrough.rs
  examples/window/low_power.rs
  tests/window/change_window_mode.rs
  tools/compile_fail_utils/tests/example.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#18244 Remove superfluous spaces in `Transform` documentation
  crates/bevy_transform/src/components/transform.rs
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#18233 Add `print_stdout` and `print_stderr` lints (#17446)
  Cargo.toml
  crates/bevy_asset/src/asset_changed.rs
  crates/bevy_ecs/examples/change_detection.rs
  crates/bevy_ecs/examples/events.rs
  crates/bevy_ecs/examples/resources.rs
  crates/bevy_ecs/src/error/bevy_error.rs
  crates/bevy_ecs/src/query/iter.rs
  crates/bevy_ecs/src/query/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/stepping.rs
  crates/bevy_ecs/src/system/mod.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_log/src/lib.rs
  crates/bevy_math/src/bounding/bounded2d/primitive_impls.rs
  crates/bevy_math/src/direction.rs
  crates/bevy_mikktspace/examples/generate.rs
  crates/bevy_reflect/examples/reflect_docs.rs
  crates/bevy_remote/src/builtin_methods.rs
  crates/bevy_tasks/examples/busy_behavior.rs
  crates/bevy_tasks/examples/idle_behavior.rs
  crates/bevy_time/src/lib.rs
  crates/bevy_transform/src/components/transform.rs
  tools/build-easefunction-graphs/src/main.rs
  tools/example-showcase/src/main.rs
Labels: C-Code-Quality, S-Ready-For-Final-Review, A-Cross-Cutting, D-Straightforward, O-Embedded

#18220 Sync up the Derive of DragEntry to match the other events
  crates/bevy_picking/src/events.rs
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Picking

#18263 Internalize BevyManifest logic. Switch to RwLock
  crates/bevy_encase_derive/src/lib.rs
  crates/bevy_macro_utils/Cargo.toml
  crates/bevy_macro_utils/src/bevy_manifest.rs
  crates/bevy_macro_utils/src/lib.rs
  tests-integration/remapped-test/Cargo.toml
  tests-integration/remapped-test/src/lib.rs
Labels: C-Performance, C-Usability, S-Ready-For-Final-Review

#18268 Update render_primitives example for children! macro
  examples/math/render_primitives.rs
Labels: D-Trivial, A-ECS, C-Examples, S-Ready-For-Final-Review

#18271 Update breakout example's stepping plugin to use children
  examples/games/stepping.rs
Labels: D-Trivial, A-ECS, C-Examples, S-Ready-For-Final-Review

#18273 Remove the entity index from the UI phase's sort key
  crates/bevy_ui/src/render/box_shadow.rs
  crates/bevy_ui/src/render/mod.rs
  crates/bevy_ui/src/render/render_pass.rs
  crates/bevy_ui/src/render/ui_material_pipeline.rs
  crates/bevy_ui/src/render/ui_texture_slice_pipeline.rs
Labels: C-Bug, A-UI, S-Ready-For-Final-Review

#18275 Add derive Default to Disabled
  crates/bevy_ecs/src/entity_disabling.rs
Labels: D-Trivial, A-ECS, S-Ready-For-Final-Review

#18239 Upgrade to cosmic-text 0.13
  crates/bevy_text/Cargo.toml
  crates/bevy_text/src/pipeline.rs
Labels: C-Dependencies, S-Ready-For-Final-Review, A-Text, X-Uncontroversial, D-Straightforward, M-Deliberate-Rendering-Change

#18272 Switch to `ImDocument` in `BevyManifest`
  crates/bevy_macro_utils/src/bevy_manifest.rs
Labels: D-Trivial, C-Code-Quality, S-Ready-For-Final-Review, A-Utils, X-Uncontroversial

#18281 Implement Serialize/Deserialize/PartialEq for bounding primitives
  crates/bevy_math/src/bounding/bounded2d/mod.rs
  crates/bevy_math/src/bounding/bounded3d/mod.rs
Labels: D-Trivial, C-Usability, S-Ready-For-Final-Review, A-Math

#18068 RPC Discover endpoint with basic informations
  crates/bevy_remote/src/builtin_methods.rs
  crates/bevy_remote/src/lib.rs
  crates/bevy_remote/src/schemas/json_schema.rs
  crates/bevy_remote/src/schemas/mod.rs
  crates/bevy_remote/src/schemas/open_rpc.rs
Labels: C-Feature, S-Ready-For-Final-Review, A-Dev-Tools

#18282 Update gamepad_viewer to use children macro
  examples/tools/gamepad_viewer.rs
Labels: D-Trivial, A-ECS, C-Examples, S-Ready-For-Final-Review

#18280 Small cleanup for ECS error handling
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/sub_app.rs
  crates/bevy_ecs/src/error/mod.rs
Labels: C-Docs, D-Trivial, A-ECS, C-Code-Quality, X-Uncontroversial, S-Needs-Review

#18292 Update custom_transitions and sub_states examples to use children macro
  examples/state/custom_transitions.rs
  examples/state/sub_states.rs
Labels: A-ECS, C-Examples, S-Ready-For-Final-Review

#18288 Add `examples/helpers/*` as library examples
  Cargo.toml
  examples/README.md
  examples/helpers/camera_controller.rs
  examples/helpers/widgets.rs
Labels: D-Trivial, C-Examples, S-Ready-For-Final-Review, A-Utils, X-Uncontroversial

#18289 Update ui_test requirement from 0.23.0 to 0.29.1
  tools/compile_fail_utils/Cargo.toml
  tools/compile_fail_utils/src/lib.rs
Labels: A-Build-System, C-Dependencies, S-Ready-For-Final-Review, D-Straightforward

#18213 Return an error when direct-nested-loading a subasset
  crates/bevy_asset/src/lib.rs
  crates/bevy_asset/src/loader.rs
  crates/bevy_asset/src/loader_builders.rs
Labels: C-Bug, A-Assets, S-Ready-For-Final-Review

#18286 implement `Bounded2d` for `ConvexPolygon`
  crates/bevy_math/src/bounding/bounded2d/primitive_impls.rs
Labels: C-Feature, D-Trivial, S-Ready-For-Final-Review, A-Math, X-Uncontroversial

#18290 Update computed_states example to use children macro
  examples/state/computed_states.rs
Labels: A-ECS, C-Examples, S-Ready-For-Final-Review

#18284 bevy_reflect: Deprecate `PartialReflect::clone_value`
  benches/benches/bevy_reflect/list.rs
  benches/benches/bevy_reflect/map.rs
  benches/benches/bevy_reflect/struct.rs
  crates/bevy_asset/src/handle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/clone_entities.rs
  crates/bevy_ecs/src/reflect/entity_commands.rs
  crates/bevy_reflect/derive/src/impls/enums.rs
  crates/bevy_reflect/derive/src/impls/opaque.rs
  crates/bevy_reflect/derive/src/impls/structs.rs
  crates/bevy_reflect/derive/src/impls/tuple_structs.rs
  crates/bevy_reflect/src/array.rs
  crates/bevy_reflect/src/enums/dynamic_enum.rs
  crates/bevy_reflect/src/enums/enum_trait.rs
  crates/bevy_reflect/src/func/dynamic_function.rs
  crates/bevy_reflect/src/func/function.rs
  crates/bevy_reflect/src/impls/smallvec.rs
  crates/bevy_reflect/src/impls/std.rs
  crates/bevy_reflect/src/lib.rs
  crates/bevy_reflect/src/list.rs
  crates/bevy_reflect/src/map.rs
  crates/bevy_reflect/src/reflect.rs
  crates/bevy_reflect/src/serde/mod.rs
  crates/bevy_reflect/src/serde/ser/mod.rs
  crates/bevy_reflect/src/set.rs
  crates/bevy_reflect/src/struct_trait.rs
  crates/bevy_reflect/src/tuple.rs
  crates/bevy_reflect/src/tuple_struct.rs
  crates/bevy_reflect/src/type_info.rs
  crates/bevy_reflect/src/utility.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/dynamic_scene_builder.rs
  crates/bevy_scene/src/lib.rs
  crates/bevy_scene/src/reflect_utils.rs
  crates/bevy_scene/src/scene.rs
  examples/reflection/dynamic_types.rs
Labels: C-Usability, S-Ready-For-Final-Review, A-Reflection, M-Needs-Migration-Guide, D-Straightforward

#18303 Fix shadow_biases example
  examples/3d/shadow_biases.rs
Labels: D-Trivial, A-Rendering, C-Examples, S-Ready-For-Final-Review, M-Deliberate-Rendering-Change

#18306 Fix MainTransparentPass2dNode attachment ordering
  crates/bevy_core_pipeline/src/core_2d/main_transparent_pass_2d_node.rs
Labels: C-Bug, A-Rendering, D-Straightforward, S-Needs-Review

#18308 Add missing system ordering constraint to prepare_lights
  crates/bevy_pbr/src/lib.rs
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/pbr_material.rs
  crates/bevy_pbr/src/render/mesh.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#18126 Pad out binding arrays to their full length if partially bound binding arrays aren't supported.
  crates/bevy_pbr/src/material_bind_groups.rs
Labels: C-Bug, A-Rendering, S-Needs-Review

#18335 Derive Clone for `ImageLoaderSettings` and `ImageFormatSetting`
  crates/bevy_image/src/image_loader.rs
Labels: D-Trivial, A-Assets, C-Usability, S-Ready-For-Final-Review

#18198 Introduce public `World::register_dynamic_bundle` method
  crates/bevy_ecs/src/world/mod.rs
Labels: C-Feature, A-ECS, S-Ready-For-Final-Review, D-Straightforward, D-Unsafe

#18336 bevy_render: Derive `Error` on `ViewportConversionError`
  crates/bevy_render/src/camera/camera.rs
Labels: D-Trivial, A-Rendering, C-Usability, S-Ready-For-Final-Review

#18320 update superlinter
  .github/workflows/ci.yml
Labels: A-Build-System, S-Ready-For-Final-Review, D-Straightforward

#18345 Canonicalize the root path to match the canonicalized asset path.
  crates/bevy_asset/src/io/file/file_watcher.rs
Labels: C-Bug, D-Trivial, A-Assets, O-Windows, S-Ready-For-Final-Review

#18279 Add process cpu/memory usage to SystemInformationDiagnosticsPlugin
  crates/bevy_diagnostic/src/system_information_diagnostics_plugin.rs
Labels: S-Ready-For-Final-Review, A-Diagnostics, D-Modest

#18346 bevy_winit: Create the window initially invisible as required by AccessKit
  crates/bevy_winit/src/winit_windows.rs
Labels: C-Bug, A-Windowing, A-Accessibility, S-Needs-Review

#18347 Make prepare_view_targets() caching account for CameraMainTextureUsages
  crates/bevy_render/src/view/mod.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review, D-Straightforward

#18361 Fix clippy lints on Rust beta
  crates/bevy_pbr/src/material_bind_groups.rs
Labels: D-Trivial, A-Rendering, C-Code-Quality, S-Ready-For-Final-Review, X-Uncontroversial

#18215 Provide a safe abstraction for split access to entities and commands
  crates/bevy_ecs/src/relationship/mod.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/entity_fetch.rs
  crates/bevy_ecs/src/world/mod.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Modest, D-Unsafe

#18242 Incorporate viewport position into clamping in `camera_system`
  crates/bevy_render/src/camera/camera.rs
Labels: C-Bug, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#18298 Fixed Reflect derive macro on empty enums (#18277)
  crates/bevy_reflect/derive/src/derive_data.rs
  crates/bevy_reflect/src/lib.rs
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, A-Reflection

#18134 wrap EntityIndexMap/Set slices as well
  crates/bevy_ecs/src/entity/index_map.rs
  crates/bevy_ecs/src/entity/index_set.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, D-Modest, D-Unsafe

#18265 FilteredResource returns a Result instead of a simple Option
  crates/bevy_ecs/src/reflect/resource.rs
  crates/bevy_ecs/src/world/error.rs
  crates/bevy_ecs/src/world/filtered_resource.rs
  crates/bevy_remote/src/builtin_methods.rs
  crates/bevy_scene/src/dynamic_scene_builder.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, A-Reflection, M-Needs-Migration-Guide, D-Straightforward

#18369 bevy: Replace unnecessary tuple type registrations
  crates/bevy_picking/src/mesh_picking/mod.rs
  crates/bevy_sprite/src/picking_backend.rs
Labels: D-Trivial, A-Rendering, C-Performance, S-Ready-For-Final-Review, A-Reflection, A-Picking

#14780 Link iOS example with `rustc`, and avoid C trampoline
  .github/workflows/ci.yml
  crates/bevy_derive/src/bevy_main.rs
  examples/mobile/Cargo.toml
  examples/mobile/bevy_mobile_example.xcodeproj/project.pbxproj
  examples/mobile/build_rust_deps.sh
  examples/mobile/ios-src/bindings.h
  examples/mobile/ios-src/main.m
  examples/mobile/src/lib.rs
  examples/mobile/src/main.rs
Labels: C-Examples, O-iOS, M-Needs-Release-Note, D-Modest, S-Waiting-on-Author

#18372 Use `UiRect::all` to build the `UiRect` constants
  crates/bevy_ui/src/geometry.rs
Labels: D-Trivial, A-UI, C-Code-Quality, S-Ready-For-Final-Review

#18327 Revert "don't use bevy_pbr for base bevy_gizmos plugin"
  crates/bevy_gizmos/Cargo.toml
  crates/bevy_gizmos/src/config.rs
  crates/bevy_gizmos/src/lib.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_gizmos/src/pipeline_3d.rs
  crates/bevy_gizmos/src/retained.rs
  crates/bevy_gizmos/src/view.rs
  crates/bevy_internal/Cargo.toml
  examples/testbed/2d.rs
  examples/testbed/3d.rs
Labels: C-Bug, A-Gizmos, S-Needs-Review, M-Deliberate-Rendering-Change

#18350 Update docs to explain default Hasher issue
  crates/bevy_platform_support/Cargo.toml
  crates/bevy_platform_support/src/collections.rs
Labels: C-Docs, S-Ready-For-Final-Review, A-Utils

#18375 Fix Formatting of Optimisation Table
  docs-template/EXAMPLE_README.md.tpl
  examples/README.md
Labels: C-Bug, D-Trivial, A-Build-System, S-Ready-For-Final-Review

#18333 Add `no_std` Library Example
  .github/workflows/ci.yml
  Cargo.toml
  crates/bevy_internal/src/prelude.rs
  examples/README.md
  examples/no_std/README.md
  examples/no_std/library/Cargo.toml
  examples/no_std/library/README.md
  examples/no_std/library/src/lib.rs
Labels: C-Examples, A-Meta, S-Ready-For-Final-Review, X-Uncontroversial, D-Straightforward, O-Embedded

#17619 Extract sprites into a `Vec`
  crates/bevy_core_pipeline/src/core_2d/mod.rs
  crates/bevy_gizmos/src/pipeline_2d.rs
  crates/bevy_sprite/src/mesh2d/material.rs
  crates/bevy_sprite/src/render/mod.rs
  crates/bevy_sprite/src/texture_slice/computed_slices.rs
  crates/bevy_text/src/text2d.rs
  examples/2d/mesh2d_manual.rs
Labels: A-Rendering, C-Performance, S-Ready-For-Final-Review, D-Straightforward

#18377 remove circular dependency between bevy_image and bevy_core_pipeline
  crates/bevy_image/Cargo.toml
Labels: C-Bug, D-Trivial, A-Rendering, P-High, S-Ready-For-Final-Review, X-Contentious

#18374 only handle bin examples in showcase
  tools/example-showcase/src/main.rs
Labels: A-Build-System, S-Ready-For-Final-Review

#18378 Support skipping Relationship on_replace hooks
  crates/bevy_ecs/src/bundle.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/clone_entities.rs
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/reflect/bundle.rs
  crates/bevy_ecs/src/reflect/component.rs
  crates/bevy_ecs/src/relationship/mod.rs
  crates/bevy_ecs/src/system/commands/entity_command.rs
  crates/bevy_ecs/src/world/deferred_world.rs
  crates/bevy_ecs/src/world/entity_ref.rs
  crates/bevy_ecs/src/world/mod.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_scene/src/scene.rs
Labels: C-Bug, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#18379 remove circular dependency between bevy_sprite and bevy_image
  crates/bevy_image/Cargo.toml
  crates/bevy_image/src/texture_atlas_builder.rs
Labels: C-Bug, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#18392 Remove commented-out code
  crates/bevy_sprite/src/render/mod.rs
Labels: C-Docs, D-Trivial, S-Needs-Review

#17348 Unify picking backends
  crates/bevy_picking/src/lib.rs
  crates/bevy_picking/src/mesh_picking/mod.rs
  crates/bevy_sprite/src/lib.rs
  crates/bevy_sprite/src/picking_backend.rs
  crates/bevy_ui/src/lib.rs
  crates/bevy_ui/src/picking_backend.rs
  examples/picking/debug_picking.rs
  examples/picking/mesh_picking.rs
  examples/picking/simple_picking.rs
  examples/picking/sprite_picking.rs
  examples/ui/directional_navigation.rs
  examples/ui/scroll.rs
  examples/ui/tab_navigation.rs
Labels: M-Needs-Migration-Guide, X-Contentious, D-Modest, S-Needs-Review, A-Picking

#18351 Unify and simplify command and system error handling
  Cargo.toml
  crates/bevy_app/src/app.rs
  crates/bevy_app/src/sub_app.rs
  crates/bevy_ecs/Cargo.toml
  crates/bevy_ecs/src/error/command_handling.rs
  crates/bevy_ecs/src/error/handler.rs
  crates/bevy_ecs/src/error/mod.rs
  crates/bevy_ecs/src/observer/runner.rs
  crates/bevy_ecs/src/relationship/mod.rs
  crates/bevy_ecs/src/schedule/executor/mod.rs
  crates/bevy_ecs/src/schedule/executor/multi_threaded.rs
  crates/bevy_ecs/src/schedule/executor/simple.rs
  crates/bevy_ecs/src/schedule/executor/single_threaded.rs
  crates/bevy_ecs/src/schedule/schedule.rs
  crates/bevy_ecs/src/system/commands/command.rs
  crates/bevy_ecs/src/system/commands/entity_command.rs
  crates/bevy_ecs/src/system/commands/error_handler.rs
  crates/bevy_ecs/src/system/commands/mod.rs
  crates/bevy_internal/Cargo.toml
  docs/cargo_features.md
  examples/README.md
  examples/ecs/error_handling.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, X-Contentious, D-Modest

#18395 Fix dynamic scene resources not being entity mapped
  crates/bevy_scene/src/dynamic_scene.rs
Labels: C-Bug, D-Trivial, S-Ready-For-Final-Review, A-Scenes

#18401 Unified picking cleanup
  crates/bevy_ui/src/lib.rs
  examples/picking/debug_picking.rs
  examples/picking/simple_picking.rs
  examples/picking/sprite_picking.rs
  examples/ui/directional_navigation.rs
  examples/ui/scroll.rs
  examples/ui/tab_navigation.rs
Labels: C-Bug, S-Ready-For-Final-Review, D-Straightforward, A-Picking

#18384 Small Docs PR for Deferred Worlds
  crates/bevy_ecs/src/world/deferred_world.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review, D-Straightforward

#18405 enable std when building bevy_dylib
  crates/bevy_dylib/Cargo.toml
Labels: C-Bug, S-Ready-For-Final-Review, O-Embedded

#18410 Fix unecessary specialization checks for apps with many materials
  crates/bevy_pbr/src/material.rs
  crates/bevy_pbr/src/prepass/mod.rs
  crates/bevy_pbr/src/render/light.rs
  crates/bevy_sprite/src/mesh2d/material.rs
Labels: C-Bug, A-Rendering, S-Needs-Review

#18412 Fix specialize_shadows system ordering
  crates/bevy_pbr/src/material.rs
Labels: C-Bug, A-Rendering, S-Ready-For-Final-Review

#18191 Split example file docblock and code when generating web examples markdown
  tools/example-showcase/src/main.rs
Labels: C-Examples, S-Ready-For-Final-Review, A-Cross-Cutting, X-Uncontroversial, D-Straightforward

#18424 Fix `bevy_ecs` doc tests with `--all-features`
  crates/bevy_ecs/src/error/handler.rs
Labels: C-Docs, A-ECS, S-Ready-For-Final-Review

#18058 Add methods to bulk replace relationships on a entity
  crates/bevy_ecs/src/hierarchy.rs
  crates/bevy_ecs/src/relationship/related_methods.rs
  crates/bevy_ecs/src/relationship/relationship_source_collection.rs
Labels: A-ECS, C-Performance, C-Usability, S-Ready-For-Final-Review, D-Straightforward

#18419 Gltf handle missing bindposes
  crates/bevy_gltf/src/loader/mod.rs
Labels: C-Bug, D-Straightforward, S-Needs-Review, A-glTF

#18421 Add more methods to `RelationshipSourceCollection`
  crates/bevy_ecs/src/relationship/relationship_source_collection.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review, M-Needs-Migration-Guide, X-Uncontroversial, D-Straightforward

#18427 Establish structure and process for in-repo release notes
  working-migration-guides/README.md
  working-migration-guides/template.md
  working-release-notes/README.md
  working-release-notes/template.md
Labels: C-Docs, A-Meta, S-Ready-For-Final-Review, X-Blessed

#18431 Fix incorrect command given by the benchmarking README
  benches/README.md
Labels: C-Docs, D-Trivial, S-Ready-For-Final-Review

#18433 Fix warning spam on `mesh2d_manual` example
  examples/2d/mesh2d_manual.rs
Labels: C-Bug, D-Trivial, A-Rendering, S-Ready-For-Final-Review

#18318 Update sprite_slice, spatial_audio_3d, spatial_audio_2d examples to use children macro
  examples/2d/sprite_slice.rs
  examples/audio/spatial_audio_2d.rs
  examples/audio/spatial_audio_3d.rs
Labels: C-Examples, S-Ready-For-Final-Review

#18309 Required components accept const values (#16720)
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/src/component.rs
Labels: A-ECS, C-Usability, S-Ready-For-Final-Review

#18432 Replace VisitEntities with MapEntities
  crates/bevy_ecs/macros/src/component.rs
  crates/bevy_ecs/macros/src/lib.rs
  crates/bevy_ecs/src/component.rs
  crates/bevy_ecs/src/entity/clone_entities.rs
  crates/bevy_ecs/src/entity/map_entities.rs
  crates/bevy_ecs/src/entity/mod.rs
  crates/bevy_ecs/src/entity/visit_entities.rs
  crates/bevy_ecs/src/lib.rs
  crates/bevy_ecs/src/observer/entity_observer.rs
  crates/bevy_ecs/src/reflect/component.rs
  crates/bevy_ecs/src/reflect/mod.rs
  crates/bevy_ecs/src/reflect/visit_entities.rs
  crates/bevy_ecs/src/relationship/mod.rs
  crates/bevy_scene/src/dynamic_scene.rs
  crates/bevy_window/src/window.rs
Labels: A-ECS, C-Usability, M-Needs-Migration-Guide, S-Needs-Review
